# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMainDesigner.ui'
#
# Created: Mon Dec 12 16:21:43 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(832, 646)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icon_swmm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        frmMain.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(frmMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.map = QtGui.QMdiArea(self.centralwidget)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName(_fromUtf8("map"))
        self.gridLayout.addWidget(self.map, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbAutoLength = QtGui.QComboBox(self.centralwidget)
        self.cbAutoLength.setObjectName(_fromUtf8("cbAutoLength"))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbAutoLength)
        self.cbOffset = QtGui.QComboBox(self.centralwidget)
        self.cbOffset.setObjectName(_fromUtf8("cbOffset"))
        self.cbOffset.addItem(_fromUtf8(""))
        self.cbOffset.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbOffset)
        self.cbFlowUnits = QtGui.QComboBox(self.centralwidget)
        self.cbFlowUnits.setObjectName(_fromUtf8("cbFlowUnits"))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbFlowUnits)
        self.btnZoom100 = QtGui.QPushButton(self.centralwidget)
        self.btnZoom100.setObjectName(_fromUtf8("btnZoom100"))
        self.horizontalLayout.addWidget(self.btnZoom100)
        self.btnCoord = QtGui.QPushButton(self.centralwidget)
        self.btnCoord.setObjectName(_fromUtf8("btnCoord"))
        self.horizontalLayout.addWidget(self.btnCoord)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        frmMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(frmMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuImport = QtGui.QMenu(self.menuFile)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuRecent = QtGui.QMenu(self.menuFile)
        self.menuRecent.setObjectName(_fromUtf8("menuRecent"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuBackdrop = QtGui.QMenu(self.menuView)
        self.menuBackdrop.setObjectName(_fromUtf8("menuBackdrop"))
        self.menuObjects = QtGui.QMenu(self.menuView)
        self.menuObjects.setObjectName(_fromUtf8("menuObjects"))
        self.menuLegends = QtGui.QMenu(self.menuView)
        self.menuLegends.setObjectName(_fromUtf8("menuLegends"))
        self.menuModifyLeg = QtGui.QMenu(self.menuLegends)
        self.menuModifyLeg.setObjectName(_fromUtf8("menuModifyLeg"))
        self.menuToolbars = QtGui.QMenu(self.menuView)
        self.menuToolbars.setObjectName(_fromUtf8("menuToolbars"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuScripting = QtGui.QMenu(self.menubar)
        self.menuScripting.setObjectName(_fromUtf8("menuScripting"))
        frmMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frmMain.setStatusBar(self.statusbar)
        self.toolBar_Standard = QtGui.QToolBar(frmMain)
        self.toolBar_Standard.setObjectName(_fromUtf8("toolBar_Standard"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Standard)
        self.toolBar_Map = QtGui.QToolBar(frmMain)
        self.toolBar_Map.setObjectName(_fromUtf8("toolBar_Map"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Map)
        frmMain.insertToolBarBreak(self.toolBar_Map)
        self.toolBar_Object = QtGui.QToolBar(frmMain)
        self.toolBar_Object.setObjectName(_fromUtf8("toolBar_Object"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Object)
        frmMain.insertToolBarBreak(self.toolBar_Object)
        self.dockw_tab = QtGui.QDockWidget(frmMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockw_tab.sizePolicy().hasHeightForWidth())
        self.dockw_tab.setSizePolicy(sizePolicy)
        self.dockw_tab.setMinimumSize(QtCore.QSize(212, 270))
        self.dockw_tab.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockw_tab.setObjectName(_fromUtf8("dockw_tab"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabProjMap = QtGui.QTabWidget(self.dockWidgetContents_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProjMap.sizePolicy().hasHeightForWidth())
        self.tabProjMap.setSizePolicy(sizePolicy)
        self.tabProjMap.setObjectName(_fromUtf8("tabProjMap"))
        self.tabProject = QtGui.QWidget()
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.tabProjMap.addTab(self.tabProject, _fromUtf8(""))
        self.tabMap = QtGui.QWidget()
        self.tabMap.setObjectName(_fromUtf8("tabMap"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabMap)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblMapSubcatchments = QtGui.QLabel(self.tabMap)
        self.lblMapSubcatchments.setObjectName(_fromUtf8("lblMapSubcatchments"))
        self.verticalLayout_2.addWidget(self.lblMapSubcatchments)
        self.cboMapSubcatchments = QtGui.QComboBox(self.tabMap)
        self.cboMapSubcatchments.setObjectName(_fromUtf8("cboMapSubcatchments"))
        self.verticalLayout_2.addWidget(self.cboMapSubcatchments)
        self.lblMapNodes = QtGui.QLabel(self.tabMap)
        self.lblMapNodes.setObjectName(_fromUtf8("lblMapNodes"))
        self.verticalLayout_2.addWidget(self.lblMapNodes)
        self.cboMapNodes = QtGui.QComboBox(self.tabMap)
        self.cboMapNodes.setObjectName(_fromUtf8("cboMapNodes"))
        self.verticalLayout_2.addWidget(self.cboMapNodes)
        self.lblMapLinks = QtGui.QLabel(self.tabMap)
        self.lblMapLinks.setObjectName(_fromUtf8("lblMapLinks"))
        self.verticalLayout_2.addWidget(self.lblMapLinks)
        self.cboMapLinks = QtGui.QComboBox(self.tabMap)
        self.cboMapLinks.setObjectName(_fromUtf8("cboMapLinks"))
        self.verticalLayout_2.addWidget(self.cboMapLinks)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabProjMap.addTab(self.tabMap, _fromUtf8(""))
        self.tabGIS = QtGui.QWidget()
        self.tabGIS.setObjectName(_fromUtf8("tabGIS"))
        self.tabProjMap.addTab(self.tabGIS, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabProjMap, 0, 0, 1, 1)
        self.dockw_tab.setWidget(self.dockWidgetContents_6)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_tab)
        self.dockw_more = QtGui.QDockWidget(frmMain)
        self.dockw_more.setObjectName(_fromUtf8("dockw_more"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hlayout_obj = QtGui.QHBoxLayout()
        self.hlayout_obj.setSpacing(0)
        self.hlayout_obj.setObjectName(_fromUtf8("hlayout_obj"))
        self.btnObjAdd = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjAdd.sizePolicy().hasHeightForWidth())
        self.btnObjAdd.setSizePolicy(sizePolicy)
        self.btnObjAdd.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjAdd.setIcon(icon1)
        self.btnObjAdd.setIconSize(QtCore.QSize(20, 20))
        self.btnObjAdd.setFlat(True)
        self.btnObjAdd.setObjectName(_fromUtf8("btnObjAdd"))
        self.hlayout_obj.addWidget(self.btnObjAdd)
        self.btnObjDelete = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjDelete.sizePolicy().hasHeightForWidth())
        self.btnObjDelete.setSizePolicy(sizePolicy)
        self.btnObjDelete.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjDelete.setIcon(icon2)
        self.btnObjDelete.setIconSize(QtCore.QSize(20, 20))
        self.btnObjDelete.setFlat(True)
        self.btnObjDelete.setObjectName(_fromUtf8("btnObjDelete"))
        self.hlayout_obj.addWidget(self.btnObjDelete)
        self.btnObjProperty = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjProperty.sizePolicy().hasHeightForWidth())
        self.btnObjProperty.setSizePolicy(sizePolicy)
        self.btnObjProperty.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_property.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjProperty.setIcon(icon3)
        self.btnObjProperty.setIconSize(QtCore.QSize(20, 20))
        self.btnObjProperty.setFlat(True)
        self.btnObjProperty.setObjectName(_fromUtf8("btnObjProperty"))
        self.hlayout_obj.addWidget(self.btnObjProperty)
        self.btnObjMoveUp = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjMoveUp.sizePolicy().hasHeightForWidth())
        self.btnObjMoveUp.setSizePolicy(sizePolicy)
        self.btnObjMoveUp.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_moveup.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjMoveUp.setIcon(icon4)
        self.btnObjMoveUp.setIconSize(QtCore.QSize(20, 20))
        self.btnObjMoveUp.setFlat(True)
        self.btnObjMoveUp.setObjectName(_fromUtf8("btnObjMoveUp"))
        self.hlayout_obj.addWidget(self.btnObjMoveUp)
        self.btnObjMoveDown = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjMoveDown.sizePolicy().hasHeightForWidth())
        self.btnObjMoveDown.setSizePolicy(sizePolicy)
        self.btnObjMoveDown.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_movedown.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjMoveDown.setIcon(icon5)
        self.btnObjMoveDown.setIconSize(QtCore.QSize(20, 20))
        self.btnObjMoveDown.setFlat(True)
        self.btnObjMoveDown.setObjectName(_fromUtf8("btnObjMoveDown"))
        self.hlayout_obj.addWidget(self.btnObjMoveDown)
        self.btnObjSort = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjSort.sizePolicy().hasHeightForWidth())
        self.btnObjSort.setSizePolicy(sizePolicy)
        self.btnObjSort.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_sort.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjSort.setIcon(icon6)
        self.btnObjSort.setIconSize(QtCore.QSize(20, 20))
        self.btnObjSort.setFlat(True)
        self.btnObjSort.setObjectName(_fromUtf8("btnObjSort"))
        self.hlayout_obj.addWidget(self.btnObjSort)
        self.gridLayout_3.addLayout(self.hlayout_obj, 0, 0, 1, 1)
        self.listViewObjects = QtGui.QListWidget(self.dockWidgetContents_4)
        self.listViewObjects.setObjectName(_fromUtf8("listViewObjects"))
        self.gridLayout_3.addWidget(self.listViewObjects, 1, 0, 1, 1)
        self.dockw_more.setWidget(self.dockWidgetContents_4)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_more)
        self.time_widget = QtGui.QDockWidget(frmMain)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_widget.sizePolicy().hasHeightForWidth())
        self.time_widget.setSizePolicy(sizePolicy)
        self.time_widget.setMinimumSize(QtCore.QSize(200, 78))
        self.time_widget.setObjectName(_fromUtf8("time_widget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButtonBack = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon7)
        self.pushButtonBack.setIconSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName(_fromUtf8("pushButtonBack"))
        self.gridLayout_4.addWidget(self.pushButtonBack, 0, 0, 1, 1)
        self.horizontalTimeSlider = QtGui.QSlider(self.dockWidgetContents_2)
        self.horizontalTimeSlider.setMinimumSize(QtCore.QSize(0, 12))
        self.horizontalTimeSlider.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalTimeSlider.setObjectName(_fromUtf8("horizontalTimeSlider"))
        self.gridLayout_4.addWidget(self.horizontalTimeSlider, 0, 1, 1, 3)
        self.pushButtonForward = QtGui.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.pushButtonForward.sizePolicy().hasHeightForWidth())
        self.pushButtonForward.setSizePolicy(sizePolicy)
        self.pushButtonForward.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonForward.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForward.setIcon(icon8)
        self.pushButtonForward.setFlat(True)
        self.pushButtonForward.setObjectName(_fromUtf8("pushButtonForward"))
        self.gridLayout_4.addWidget(self.pushButtonForward, 0, 4, 1, 1)
        self.pushButtonPlay = QtGui.QPushButton(self.dockWidgetContents_2)
        self.pushButtonPlay.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlay.sizePolicy().hasHeightForWidth())
        self.pushButtonPlay.setSizePolicy(sizePolicy)
        self.pushButtonPlay.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonPlay.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPlay.setIcon(icon9)
        self.pushButtonPlay.setCheckable(True)
        self.pushButtonPlay.setChecked(False)
        self.pushButtonPlay.setFlat(True)
        self.pushButtonPlay.setObjectName(_fromUtf8("pushButtonPlay"))
        self.gridLayout_4.addWidget(self.pushButtonPlay, 1, 0, 1, 1)
        self.labelStartTime = QtGui.QLabel(self.dockWidgetContents_2)
        self.labelStartTime.setMaximumSize(QtCore.QSize(16777215, 18))
        self.labelStartTime.setObjectName(_fromUtf8("labelStartTime"))
        self.gridLayout_4.addWidget(self.labelStartTime, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(689, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 2, 1, 1)
        self.labelEndTime = QtGui.QLabel(self.dockWidgetContents_2)
        self.labelEndTime.setMaximumSize(QtCore.QSize(16777215, 18))
        self.labelEndTime.setObjectName(_fromUtf8("labelEndTime"))
        self.gridLayout_4.addWidget(self.labelEndTime, 1, 3, 1, 1)
        self.time_widget.setWidget(self.dockWidgetContents_2)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.time_widget)
        self.actionStdNewProject = QtGui.QAction(frmMain)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_new.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdNewProject.setIcon(icon10)
        self.actionStdNewProject.setObjectName(_fromUtf8("actionStdNewProject"))
        self.actionMapSelectObj = QtGui.QAction(frmMain)
        self.actionMapSelectObj.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_pointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectObj.setIcon(icon11)
        self.actionMapSelectObj.setObjectName(_fromUtf8("actionMapSelectObj"))
        self.actionObjAddGage = QtGui.QAction(frmMain)
        self.actionObjAddGage.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_gage.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddGage.setIcon(icon12)
        self.actionObjAddGage.setObjectName(_fromUtf8("actionObjAddGage"))
        self.actionScriptEditor = QtGui.QAction(frmMain)
        self.actionScriptEditor.setObjectName(_fromUtf8("actionScriptEditor"))
        self.actionExec = QtGui.QAction(frmMain)
        self.actionExec.setObjectName(_fromUtf8("actionExec"))
        self.actionAdd_Vector = QtGui.QAction(frmMain)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_add_v.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Vector.setIcon(icon13)
        self.actionAdd_Vector.setObjectName(_fromUtf8("actionAdd_Vector"))
        self.actionAdd_Raster = QtGui.QAction(frmMain)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_add_r.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Raster.setIcon(icon14)
        self.actionAdd_Raster.setObjectName(_fromUtf8("actionAdd_Raster"))
        self.actionPan = QtGui.QAction(frmMain)
        self.actionPan.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPan.setIcon(icon15)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionShow_coordinates = QtGui.QAction(frmMain)
        self.actionShow_coordinates.setObjectName(_fromUtf8("actionShow_coordinates"))
        self.actionZoom_in = QtGui.QAction(frmMain)
        self.actionZoom_in.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomin.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_in.setIcon(icon16)
        self.actionZoom_in.setObjectName(_fromUtf8("actionZoom_in"))
        self.actionZoom_out = QtGui.QAction(frmMain)
        self.actionZoom_out.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomout.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_out.setIcon(icon17)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionZoom_full = QtGui.QAction(frmMain)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomfull.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_full.setIcon(icon18)
        self.actionZoom_full.setObjectName(_fromUtf8("actionZoom_full"))
        self.actionStdOpenProjMenu = QtGui.QAction(frmMain)
        self.actionStdOpenProjMenu.setObjectName(_fromUtf8("actionStdOpenProjMenu"))
        self.actionStdOpenProj = QtGui.QAction(frmMain)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdOpenProj.setIcon(icon19)
        self.actionStdOpenProj.setObjectName(_fromUtf8("actionStdOpenProj"))
        self.actionStdNewProjectMenu = QtGui.QAction(frmMain)
        self.actionStdNewProjectMenu.setObjectName(_fromUtf8("actionStdNewProjectMenu"))
        self.actionAdd_Feature = QtGui.QAction(frmMain)
        self.actionAdd_Feature.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_edit_addfeature.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_edit_addfeature0.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.actionAdd_Feature.setIcon(icon20)
        self.actionAdd_Feature.setObjectName(_fromUtf8("actionAdd_Feature"))
        self.actionStdSaveMenu = QtGui.QAction(frmMain)
        self.actionStdSaveMenu.setObjectName(_fromUtf8("actionStdSaveMenu"))
        self.actionStdSave = QtGui.QAction(frmMain)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_save.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdSave.setIcon(icon21)
        self.actionStdSave.setObjectName(_fromUtf8("actionStdSave"))
        self.actionStdSave_As = QtGui.QAction(frmMain)
        self.actionStdSave_As.setObjectName(_fromUtf8("actionStdSave_As"))
        self.actionStdImportMap = QtGui.QAction(frmMain)
        self.actionStdImportMap.setObjectName(_fromUtf8("actionStdImportMap"))
        self.actionStdImportScenario = QtGui.QAction(frmMain)
        self.actionStdImportScenario.setObjectName(_fromUtf8("actionStdImportScenario"))
        self.actionStdImportNetwork = QtGui.QAction(frmMain)
        self.actionStdImportNetwork.setObjectName(_fromUtf8("actionStdImportNetwork"))
        self.actionStdExportMap = QtGui.QAction(frmMain)
        self.actionStdExportMap.setObjectName(_fromUtf8("actionStdExportMap"))
        self.actionStdPage_Setup = QtGui.QAction(frmMain)
        self.actionStdPage_Setup.setObjectName(_fromUtf8("actionStdPage_Setup"))
        self.actionStdPrint_Preview = QtGui.QAction(frmMain)
        self.actionStdPrint_Preview.setObjectName(_fromUtf8("actionStdPrint_Preview"))
        self.actionStdPrint = QtGui.QAction(frmMain)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_printwindow.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdPrint.setIcon(icon22)
        self.actionStdPrint.setObjectName(_fromUtf8("actionStdPrint"))
        self.actionStdExit = QtGui.QAction(frmMain)
        self.actionStdExit.setObjectName(_fromUtf8("actionStdExit"))
        self.actionStdCopy_To = QtGui.QAction(frmMain)
        self.actionStdCopy_To.setObjectName(_fromUtf8("actionStdCopy_To"))
        self.actionStdSelect_Object = QtGui.QAction(frmMain)
        self.actionStdSelect_Object.setObjectName(_fromUtf8("actionStdSelect_Object"))
        self.actionStdSelect_Vertex = QtGui.QAction(frmMain)
        self.actionStdSelect_Vertex.setObjectName(_fromUtf8("actionStdSelect_Vertex"))
        self.actionStdSelect_Region = QtGui.QAction(frmMain)
        self.actionStdSelect_Region.setObjectName(_fromUtf8("actionStdSelect_Region"))
        self.actionStdSelect_All = QtGui.QAction(frmMain)
        self.actionStdSelect_All.setObjectName(_fromUtf8("actionStdSelect_All"))
        self.actionStdGroup_Edit = QtGui.QAction(frmMain)
        self.actionStdGroup_Edit.setObjectName(_fromUtf8("actionStdGroup_Edit"))
        self.actionStdProjSummary = QtGui.QAction(frmMain)
        self.actionStdProjSummary.setObjectName(_fromUtf8("actionStdProjSummary"))
        self.actionStdProjDefault = QtGui.QAction(frmMain)
        self.actionStdProjDefault.setObjectName(_fromUtf8("actionStdProjDefault"))
        self.actionStdProjCalibration_Data = QtGui.QAction(frmMain)
        self.actionStdProjCalibration_Data.setObjectName(_fromUtf8("actionStdProjCalibration_Data"))
        self.actionStdProjSimulation_Options = QtGui.QAction(frmMain)
        self.actionStdProjSimulation_Options.setObjectName(_fromUtf8("actionStdProjSimulation_Options"))
        self.actionRun_SimulationMenu = QtGui.QAction(frmMain)
        self.actionRun_SimulationMenu.setObjectName(_fromUtf8("actionRun_SimulationMenu"))
        self.actionStdRun_Simulation = QtGui.QAction(frmMain)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_runswmm.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdRun_Simulation.setIcon(icon23)
        self.actionStdRun_Simulation.setObjectName(_fromUtf8("actionStdRun_Simulation"))
        self.actionStdProjDetails = QtGui.QAction(frmMain)
        self.actionStdProjDetails.setObjectName(_fromUtf8("actionStdProjDetails"))
        self.actionSave_Map_As_Image = QtGui.QAction(frmMain)
        self.actionSave_Map_As_Image.setObjectName(_fromUtf8("actionSave_Map_As_Image"))
        self.actionObjAddSub = QtGui.QAction(frmMain)
        self.actionObjAddSub.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_subcatchment.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddSub.setIcon(icon24)
        self.actionObjAddSub.setObjectName(_fromUtf8("actionObjAddSub"))
        self.actionObjAddJunc = QtGui.QAction(frmMain)
        self.actionObjAddJunc.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_node_junction.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddJunc.setIcon(icon25)
        self.actionObjAddJunc.setObjectName(_fromUtf8("actionObjAddJunc"))
        self.actionObjAddOutfall = QtGui.QAction(frmMain)
        self.actionObjAddOutfall.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_node_outfall.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOutfall.setIcon(icon26)
        self.actionObjAddOutfall.setObjectName(_fromUtf8("actionObjAddOutfall"))
        self.actionObjAddDivider = QtGui.QAction(frmMain)
        self.actionObjAddDivider.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_node_divider.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddDivider.setIcon(icon27)
        self.actionObjAddDivider.setObjectName(_fromUtf8("actionObjAddDivider"))
        self.actionObjAddStorage = QtGui.QAction(frmMain)
        self.actionObjAddStorage.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_node_storage.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddStorage.setIcon(icon28)
        self.actionObjAddStorage.setObjectName(_fromUtf8("actionObjAddStorage"))
        self.actionObjAddConduit = QtGui.QAction(frmMain)
        self.actionObjAddConduit.setCheckable(True)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_conduit.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddConduit.setIcon(icon29)
        self.actionObjAddConduit.setObjectName(_fromUtf8("actionObjAddConduit"))
        self.actionObjAddPump = QtGui.QAction(frmMain)
        self.actionObjAddPump.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_pump.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddPump.setIcon(icon30)
        self.actionObjAddPump.setObjectName(_fromUtf8("actionObjAddPump"))
        self.actionObjAddOrifice = QtGui.QAction(frmMain)
        self.actionObjAddOrifice.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_orifice.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOrifice.setIcon(icon31)
        self.actionObjAddOrifice.setObjectName(_fromUtf8("actionObjAddOrifice"))
        self.actionObjAddWeir = QtGui.QAction(frmMain)
        self.actionObjAddWeir.setCheckable(True)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_weir.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddWeir.setIcon(icon32)
        self.actionObjAddWeir.setObjectName(_fromUtf8("actionObjAddWeir"))
        self.actionObjAddOutlet = QtGui.QAction(frmMain)
        self.actionObjAddOutlet.setCheckable(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_outlet.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOutlet.setIcon(icon33)
        self.actionObjAddOutlet.setObjectName(_fromUtf8("actionObjAddOutlet"))
        self.actionObjAddLabel = QtGui.QAction(frmMain)
        self.actionObjAddLabel.setCheckable(True)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_maplabel.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddLabel.setIcon(icon34)
        self.actionObjAddLabel.setObjectName(_fromUtf8("actionObjAddLabel"))
        self.actionObjAddTank = QtGui.QAction(frmMain)
        self.actionObjAddTank.setCheckable(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_node_tank.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddTank.setIcon(icon35)
        self.actionObjAddTank.setObjectName(_fromUtf8("actionObjAddTank"))
        self.actionObjAddValve = QtGui.QAction(frmMain)
        self.actionObjAddValve.setCheckable(True)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_link_valve.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddValve.setIcon(icon36)
        self.actionObjAddValve.setObjectName(_fromUtf8("actionObjAddValve"))
        self.actionMapSelectRegion = QtGui.QAction(frmMain)
        self.actionMapSelectRegion.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_selectregion.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectRegion.setIcon(icon37)
        self.actionMapSelectRegion.setObjectName(_fromUtf8("actionMapSelectRegion"))
        self.actionMapFindObj = QtGui.QAction(frmMain)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_findobjectinmap.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapFindObj.setIcon(icon38)
        self.actionMapFindObj.setObjectName(_fromUtf8("actionMapFindObj"))
        self.actionMapQuery = QtGui.QAction(frmMain)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_findobjectbyrules.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapQuery.setIcon(icon39)
        self.actionMapQuery.setObjectName(_fromUtf8("actionMapQuery"))
        self.actionProjPlotProfile = QtGui.QAction(frmMain)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_profileplot.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotProfile.setIcon(icon40)
        self.actionProjPlotProfile.setObjectName(_fromUtf8("actionProjPlotProfile"))
        self.actionProjPlotTimeseries = QtGui.QAction(frmMain)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_tsplot.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotTimeseries.setIcon(icon41)
        self.actionProjPlotTimeseries.setObjectName(_fromUtf8("actionProjPlotTimeseries"))
        self.actionProjPlotScatter = QtGui.QAction(frmMain)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_scatterplot.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotScatter.setIcon(icon42)
        self.actionProjPlotScatter.setObjectName(_fromUtf8("actionProjPlotScatter"))
        self.actionProjTableTimeseries = QtGui.QAction(frmMain)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_tstable.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjTableTimeseries.setIcon(icon43)
        self.actionProjTableTimeseries.setObjectName(_fromUtf8("actionProjTableTimeseries"))
        self.actionProjTableStatistics = QtGui.QAction(frmMain)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_statisticreport.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjTableStatistics.setIcon(icon44)
        self.actionProjTableStatistics.setObjectName(_fromUtf8("actionProjTableStatistics"))
        self.actionMapOption = QtGui.QAction(frmMain)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_viewoption.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapOption.setIcon(icon45)
        self.actionMapOption.setObjectName(_fromUtf8("actionMapOption"))
        self.actionProjStatus = QtGui.QAction(frmMain)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_statusreport.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjStatus.setIcon(icon46)
        self.actionProjStatus.setObjectName(_fromUtf8("actionProjStatus"))
        self.actionMapMeasure = QtGui.QAction(frmMain)
        self.actionMapMeasure.setCheckable(True)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapMeasure.setIcon(icon47)
        self.actionMapMeasure.setObjectName(_fromUtf8("actionMapMeasure"))
        self.actionMapSelectVertices = QtGui.QAction(frmMain)
        self.actionMapSelectVertices.setCheckable(True)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_selectvertices.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectVertices.setIcon(icon48)
        self.actionMapSelectVertices.setObjectName(_fromUtf8("actionMapSelectVertices"))
        self.actionStdEditObject = QtGui.QAction(frmMain)
        self.actionStdEditObject.setObjectName(_fromUtf8("actionStdEditObject"))
        self.actionStdDeleteObject = QtGui.QAction(frmMain)
        self.actionStdDeleteObject.setObjectName(_fromUtf8("actionStdDeleteObject"))
        self.actionStdMapDimensions = QtGui.QAction(frmMain)
        self.actionStdMapDimensions.setObjectName(_fromUtf8("actionStdMapDimensions"))
        self.actionLoad = QtGui.QAction(frmMain)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionStdMapBackLoad = QtGui.QAction(frmMain)
        self.actionStdMapBackLoad.setObjectName(_fromUtf8("actionStdMapBackLoad"))
        self.actionStdMapBackUnload = QtGui.QAction(frmMain)
        self.actionStdMapBackUnload.setObjectName(_fromUtf8("actionStdMapBackUnload"))
        self.actionStdMapBackAlign = QtGui.QAction(frmMain)
        self.actionStdMapBackAlign.setObjectName(_fromUtf8("actionStdMapBackAlign"))
        self.actionStdMapBackResize = QtGui.QAction(frmMain)
        self.actionStdMapBackResize.setObjectName(_fromUtf8("actionStdMapBackResize"))
        self.actionStdMapBackWatermark = QtGui.QAction(frmMain)
        self.actionStdMapBackWatermark.setObjectName(_fromUtf8("actionStdMapBackWatermark"))
        self.actionStdMapPan = QtGui.QAction(frmMain)
        self.actionStdMapPan.setObjectName(_fromUtf8("actionStdMapPan"))
        self.actionStdMapZoomIn = QtGui.QAction(frmMain)
        self.actionStdMapZoomIn.setObjectName(_fromUtf8("actionStdMapZoomIn"))
        self.actionStdMapZoomOut = QtGui.QAction(frmMain)
        self.actionStdMapZoomOut.setObjectName(_fromUtf8("actionStdMapZoomOut"))
        self.actionStdMapFullExtent = QtGui.QAction(frmMain)
        self.actionStdMapFullExtent.setObjectName(_fromUtf8("actionStdMapFullExtent"))
        self.actionStdMapQuery = QtGui.QAction(frmMain)
        self.actionStdMapQuery.setObjectName(_fromUtf8("actionStdMapQuery"))
        self.actionStdMapOverview = QtGui.QAction(frmMain)
        self.actionStdMapOverview.setObjectName(_fromUtf8("actionStdMapOverview"))
        self.actionStdMapOptions = QtGui.QAction(frmMain)
        self.actionStdMapOptions.setObjectName(_fromUtf8("actionStdMapOptions"))
        self.actionStdProgPrefer = QtGui.QAction(frmMain)
        self.actionStdProgPrefer.setObjectName(_fromUtf8("actionStdProgPrefer"))
        self.actionStdConfigTools = QtGui.QAction(frmMain)
        self.actionStdConfigTools.setObjectName(_fromUtf8("actionStdConfigTools"))
        self.actionStdWinCascade = QtGui.QAction(frmMain)
        self.actionStdWinCascade.setObjectName(_fromUtf8("actionStdWinCascade"))
        self.actionStdWinTile = QtGui.QAction(frmMain)
        self.actionStdWinTile.setObjectName(_fromUtf8("actionStdWinTile"))
        self.actionStdWinCloseAll = QtGui.QAction(frmMain)
        self.actionStdWinCloseAll.setObjectName(_fromUtf8("actionStdWinCloseAll"))
        self.actionStdMapToggle = QtGui.QAction(frmMain)
        self.actionStdMapToggle.setCheckable(True)
        self.actionStdMapToggle.setChecked(True)
        self.actionStdMapToggle.setObjectName(_fromUtf8("actionStdMapToggle"))
        self.actionStdMapShowRainGages = QtGui.QAction(frmMain)
        self.actionStdMapShowRainGages.setCheckable(True)
        self.actionStdMapShowRainGages.setObjectName(_fromUtf8("actionStdMapShowRainGages"))
        self.actionStdMapShowSubcatchments = QtGui.QAction(frmMain)
        self.actionStdMapShowSubcatchments.setCheckable(True)
        self.actionStdMapShowSubcatchments.setObjectName(_fromUtf8("actionStdMapShowSubcatchments"))
        self.actionStdMapShowNodes = QtGui.QAction(frmMain)
        self.actionStdMapShowNodes.setCheckable(True)
        self.actionStdMapShowNodes.setObjectName(_fromUtf8("actionStdMapShowNodes"))
        self.actionStdMapShowLinks = QtGui.QAction(frmMain)
        self.actionStdMapShowLinks.setCheckable(True)
        self.actionStdMapShowLinks.setObjectName(_fromUtf8("actionStdMapShowLinks"))
        self.actionStdMapShowLabels = QtGui.QAction(frmMain)
        self.actionStdMapShowLabels.setCheckable(True)
        self.actionStdMapShowLabels.setObjectName(_fromUtf8("actionStdMapShowLabels"))
        self.actionStdMapShowBackdrop = QtGui.QAction(frmMain)
        self.actionStdMapShowBackdrop.setCheckable(True)
        self.actionStdMapShowBackdrop.setObjectName(_fromUtf8("actionStdMapShowBackdrop"))
        self.actionStdLegSubcatchment = QtGui.QAction(frmMain)
        self.actionStdLegSubcatchment.setCheckable(True)
        self.actionStdLegSubcatchment.setObjectName(_fromUtf8("actionStdLegSubcatchment"))
        self.actionStdLegNode = QtGui.QAction(frmMain)
        self.actionStdLegNode.setCheckable(True)
        self.actionStdLegNode.setObjectName(_fromUtf8("actionStdLegNode"))
        self.actionStdLegLink = QtGui.QAction(frmMain)
        self.actionStdLegLink.setCheckable(True)
        self.actionStdLegLink.setObjectName(_fromUtf8("actionStdLegLink"))
        self.actionStdLegTime = QtGui.QAction(frmMain)
        self.actionStdLegTime.setCheckable(True)
        self.actionStdLegTime.setObjectName(_fromUtf8("actionStdLegTime"))
        self.actionStdLegModSubcatchment = QtGui.QAction(frmMain)
        self.actionStdLegModSubcatchment.setObjectName(_fromUtf8("actionStdLegModSubcatchment"))
        self.actionStdLegModNode = QtGui.QAction(frmMain)
        self.actionStdLegModNode.setObjectName(_fromUtf8("actionStdLegModNode"))
        self.actionStdLegModLink = QtGui.QAction(frmMain)
        self.actionStdLegModLink.setObjectName(_fromUtf8("actionStdLegModLink"))
        self.actionToolbarShowStandard = QtGui.QAction(frmMain)
        self.actionToolbarShowStandard.setCheckable(True)
        self.actionToolbarShowStandard.setChecked(True)
        self.actionToolbarShowStandard.setObjectName(_fromUtf8("actionToolbarShowStandard"))
        self.actionToolbarShowMap = QtGui.QAction(frmMain)
        self.actionToolbarShowMap.setCheckable(True)
        self.actionToolbarShowMap.setChecked(True)
        self.actionToolbarShowMap.setObjectName(_fromUtf8("actionToolbarShowMap"))
        self.actionToolbarShowObject = QtGui.QAction(frmMain)
        self.actionToolbarShowObject.setCheckable(True)
        self.actionToolbarShowObject.setChecked(True)
        self.actionToolbarShowObject.setObjectName(_fromUtf8("actionToolbarShowObject"))
        self.actionEditScript = QtGui.QAction(frmMain)
        self.actionEditScript.setObjectName(_fromUtf8("actionEditScript"))
        self.actionRun_Script = QtGui.QAction(frmMain)
        self.actionRun_Script.setObjectName(_fromUtf8("actionRun_Script"))
        self.actionOpen = QtGui.QAction(frmMain)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuImport.addAction(self.actionStdImportMap)
        self.menuImport.addAction(self.actionStdImportScenario)
        self.menuImport.addAction(self.actionStdImportNetwork)
        self.menuExport.addAction(self.actionStdExportMap)
        self.menuRecent.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionStdNewProjectMenu)
        self.menuFile.addAction(self.actionStdOpenProjMenu)
        self.menuFile.addAction(self.menuRecent.menuAction())
        self.menuFile.addAction(self.actionStdSaveMenu)
        self.menuFile.addAction(self.actionStdSave_As)
        self.menuFile.addAction(self.actionSave_Map_As_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStdPage_Setup)
        self.menuFile.addAction(self.actionStdPrint_Preview)
        self.menuFile.addAction(self.actionStdPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStdExit)
        self.menuEdit.addAction(self.actionStdCopy_To)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdSelect_Object)
        self.menuEdit.addAction(self.actionStdSelect_Vertex)
        self.menuEdit.addAction(self.actionStdSelect_Region)
        self.menuEdit.addAction(self.actionStdSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdEditObject)
        self.menuEdit.addAction(self.actionStdDeleteObject)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdGroup_Edit)
        self.menuEdit.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackLoad)
        self.menuBackdrop.addAction(self.actionStdMapBackUnload)
        self.menuBackdrop.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackAlign)
        self.menuBackdrop.addAction(self.actionStdMapBackResize)
        self.menuBackdrop.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackWatermark)
        self.menuObjects.addAction(self.actionStdMapShowRainGages)
        self.menuObjects.addAction(self.actionStdMapShowSubcatchments)
        self.menuObjects.addAction(self.actionStdMapShowNodes)
        self.menuObjects.addAction(self.actionStdMapShowLinks)
        self.menuObjects.addAction(self.actionStdMapShowLabels)
        self.menuObjects.addAction(self.actionStdMapShowBackdrop)
        self.menuModifyLeg.addAction(self.actionStdLegModSubcatchment)
        self.menuModifyLeg.addAction(self.actionStdLegModNode)
        self.menuModifyLeg.addAction(self.actionStdLegModLink)
        self.menuLegends.addAction(self.actionStdLegSubcatchment)
        self.menuLegends.addAction(self.actionStdLegNode)
        self.menuLegends.addAction(self.actionStdLegLink)
        self.menuLegends.addAction(self.actionStdLegTime)
        self.menuLegends.addSeparator()
        self.menuLegends.addAction(self.menuModifyLeg.menuAction())
        self.menuToolbars.addAction(self.actionToolbarShowStandard)
        self.menuToolbars.addAction(self.actionToolbarShowMap)
        self.menuToolbars.addAction(self.actionToolbarShowObject)
        self.menuView.addAction(self.actionStdMapDimensions)
        self.menuView.addAction(self.menuBackdrop.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapPan)
        self.menuView.addAction(self.actionStdMapZoomIn)
        self.menuView.addAction(self.actionStdMapZoomOut)
        self.menuView.addAction(self.actionStdMapFullExtent)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapQuery)
        self.menuView.addAction(self.actionStdMapOverview)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuObjects.menuAction())
        self.menuView.addAction(self.menuLegends.menuAction())
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapOptions)
        self.menuProject.addAction(self.actionStdProjSummary)
        self.menuProject.addAction(self.actionStdProjDetails)
        self.menuProject.addAction(self.actionStdProjDefault)
        self.menuProject.addAction(self.actionStdProjCalibration_Data)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionStdProjSimulation_Options)
        self.menuProject.addAction(self.actionRun_SimulationMenu)
        self.menuTools.addAction(self.actionStdProgPrefer)
        self.menuTools.addAction(self.actionStdConfigTools)
        self.menuWindow.addAction(self.actionStdWinCascade)
        self.menuWindow.addAction(self.actionStdWinTile)
        self.menuWindow.addAction(self.actionStdWinCloseAll)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionStdMapToggle)
        self.menuPlugins.addSeparator()
        self.menuScripting.addAction(self.actionEditScript)
        self.menuScripting.addAction(self.actionRun_Script)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuScripting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_Standard.addAction(self.actionStdNewProject)
        self.toolBar_Standard.addAction(self.actionStdOpenProj)
        self.toolBar_Standard.addAction(self.actionStdSave)
        self.toolBar_Standard.addAction(self.actionStdPrint)
        self.toolBar_Standard.addSeparator()
        self.toolBar_Standard.addAction(self.actionStdRun_Simulation)
        self.toolBar_Standard.addSeparator()
        self.toolBar_Standard.addAction(self.actionProjStatus)
        self.toolBar_Standard.addAction(self.actionProjPlotProfile)
        self.toolBar_Standard.addAction(self.actionProjPlotTimeseries)
        self.toolBar_Standard.addAction(self.actionProjPlotScatter)
        self.toolBar_Standard.addAction(self.actionProjTableTimeseries)
        self.toolBar_Standard.addAction(self.actionProjTableStatistics)
        self.toolBar_Map.addAction(self.actionAdd_Vector)
        self.toolBar_Map.addAction(self.actionAdd_Raster)
        self.toolBar_Map.addAction(self.actionZoom_in)
        self.toolBar_Map.addAction(self.actionZoom_out)
        self.toolBar_Map.addAction(self.actionZoom_full)
        self.toolBar_Map.addAction(self.actionPan)
        self.toolBar_Map.addAction(self.actionAdd_Feature)
        self.toolBar_Map.addAction(self.actionMapSelectObj)
        self.toolBar_Map.addAction(self.actionMapSelectVertices)
        self.toolBar_Map.addAction(self.actionMapSelectRegion)
        self.toolBar_Map.addAction(self.actionMapMeasure)
        self.toolBar_Map.addAction(self.actionMapFindObj)
        self.toolBar_Map.addAction(self.actionMapQuery)
        self.toolBar_Map.addSeparator()
        self.toolBar_Map.addAction(self.actionMapOption)
        self.toolBar_Object.addAction(self.actionObjAddGage)
        self.toolBar_Object.addAction(self.actionObjAddSub)
        self.toolBar_Object.addAction(self.actionObjAddJunc)
        self.toolBar_Object.addAction(self.actionObjAddOutfall)
        self.toolBar_Object.addAction(self.actionObjAddDivider)
        self.toolBar_Object.addAction(self.actionObjAddStorage)
        self.toolBar_Object.addAction(self.actionObjAddTank)
        self.toolBar_Object.addAction(self.actionObjAddConduit)
        self.toolBar_Object.addAction(self.actionObjAddPump)
        self.toolBar_Object.addAction(self.actionObjAddOrifice)
        self.toolBar_Object.addAction(self.actionObjAddWeir)
        self.toolBar_Object.addAction(self.actionObjAddOutlet)
        self.toolBar_Object.addAction(self.actionObjAddValve)
        self.toolBar_Object.addAction(self.actionObjAddLabel)

        self.retranslateUi(frmMain)
        self.tabProjMap.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "SWMM 5.1", None))
        self.cbAutoLength.setItemText(0, _translate("frmMain", "Auto-Length: Off", None))
        self.cbAutoLength.setItemText(1, _translate("frmMain", "Auto-Length: On", None))
        self.cbOffset.setItemText(0, _translate("frmMain", "Offsets: Elevation", None))
        self.cbOffset.setItemText(1, _translate("frmMain", "Offsets: Depth", None))
        self.cbFlowUnits.setItemText(0, _translate("frmMain", "Flow Units: CFS", None))
        self.cbFlowUnits.setItemText(1, _translate("frmMain", "Flow Units: GPM", None))
        self.cbFlowUnits.setItemText(2, _translate("frmMain", "Flow Units: MGD", None))
        self.cbFlowUnits.setItemText(3, _translate("frmMain", "Flow Units: CMS", None))
        self.cbFlowUnits.setItemText(4, _translate("frmMain", "Flow Units:  LPS", None))
        self.cbFlowUnits.setItemText(5, _translate("frmMain", "Flow Units: MLD", None))
        self.btnZoom100.setText(_translate("frmMain", "Zoom Level: 100%", None))
        self.btnCoord.setText(_translate("frmMain", "x,y", None))
        self.menuFile.setTitle(_translate("frmMain", "File", None))
        self.menuImport.setTitle(_translate("frmMain", "Import", None))
        self.menuExport.setTitle(_translate("frmMain", "Export", None))
        self.menuRecent.setTitle(_translate("frmMain", "Recent", None))
        self.menuEdit.setTitle(_translate("frmMain", "Edit", None))
        self.menuView.setTitle(_translate("frmMain", "View", None))
        self.menuBackdrop.setTitle(_translate("frmMain", "Backdrop", None))
        self.menuObjects.setTitle(_translate("frmMain", "Objects", None))
        self.menuLegends.setTitle(_translate("frmMain", "Legends", None))
        self.menuModifyLeg.setTitle(_translate("frmMain", "Modify", None))
        self.menuToolbars.setTitle(_translate("frmMain", "Toolbars", None))
        self.menuProject.setTitle(_translate("frmMain", "Project", None))
        self.menuReport.setTitle(_translate("frmMain", "Report", None))
        self.menuTools.setTitle(_translate("frmMain", "Tools", None))
        self.menuWindow.setTitle(_translate("frmMain", "Window", None))
        self.menuPlugins.setTitle(_translate("frmMain", "Plugins", None))
        self.menuHelp.setTitle(_translate("frmMain", "Help", None))
        self.menuScripting.setTitle(_translate("frmMain", "Scripting", None))
        self.toolBar_Standard.setWindowTitle(_translate("frmMain", "Standard", None))
        self.toolBar_Map.setWindowTitle(_translate("frmMain", "Map", None))
        self.toolBar_Object.setWindowTitle(_translate("frmMain", "Object", None))
        self.dockw_tab.setWindowTitle(_translate("frmMain", "Project Explorer", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabProject), _translate("frmMain", "Project", None))
        self.lblMapSubcatchments.setText(_translate("frmMain", "Subcatchments", None))
        self.lblMapNodes.setText(_translate("frmMain", "Nodes", None))
        self.lblMapLinks.setText(_translate("frmMain", "Links", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabMap), _translate("frmMain", "Map", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabGIS), _translate("frmMain", "Layers", None))
        self.dockw_more.setWindowTitle(_translate("frmMain", "Object Explorer", None))
        self.time_widget.setWindowTitle(_translate("frmMain", "Time", None))
        self.labelStartTime.setText(_translate("frmMain", "not set", None))
        self.labelEndTime.setText(_translate("frmMain", "not set", None))
        self.actionStdNewProject.setText(_translate("frmMain", "New", None))
        self.actionStdNewProject.setToolTip(_translate("frmMain", "Start a new project", None))
        self.actionMapSelectObj.setText(_translate("frmMain", "Select an object", None))
        self.actionMapSelectObj.setToolTip(_translate("frmMain", "Select an object from a map", None))
        self.actionObjAddGage.setText(_translate("frmMain", "Add Gage", None))
        self.actionObjAddGage.setToolTip(_translate("frmMain", "Add a rain gage", None))
        self.actionScriptEditor.setText(_translate("frmMain", "Script Editor", None))
        self.actionScriptEditor.setToolTip(_translate("frmMain", "ScriptEditor", None))
        self.actionExec.setText(_translate("frmMain", "exec", None))
        self.actionAdd_Vector.setText(_translate("frmMain", "Add Vector", None))
        self.actionAdd_Vector.setToolTip(_translate("frmMain", "Add a vector layer", None))
        self.actionAdd_Raster.setText(_translate("frmMain", "Add Raster", None))
        self.actionAdd_Raster.setToolTip(_translate("frmMain", "Add a raster layer", None))
        self.actionPan.setText(_translate("frmMain", "Pan", None))
        self.actionPan.setToolTip(_translate("frmMain", "Pan", None))
        self.actionShow_coordinates.setText(_translate("frmMain", "show coordinates", None))
        self.actionZoom_in.setText(_translate("frmMain", "zoom in", None))
        self.actionZoom_in.setToolTip(_translate("frmMain", "zoom in", None))
        self.actionZoom_out.setText(_translate("frmMain", "zoom out", None))
        self.actionZoom_out.setToolTip(_translate("frmMain", "zoom out", None))
        self.actionZoom_full.setText(_translate("frmMain", "zoom full", None))
        self.actionZoom_full.setToolTip(_translate("frmMain", "zoom full extent", None))
        self.actionStdOpenProjMenu.setText(_translate("frmMain", "Open...", None))
        self.actionStdOpenProjMenu.setToolTip(_translate("frmMain", "Open existing project", None))
        self.actionStdOpenProj.setText(_translate("frmMain", "Open...", None))
        self.actionStdOpenProj.setToolTip(_translate("frmMain", "Open existing project", None))
        self.actionStdNewProjectMenu.setText(_translate("frmMain", "New", None))
        self.actionStdNewProjectMenu.setToolTip(_translate("frmMain", "Create a new project", None))
        self.actionAdd_Feature.setText(_translate("frmMain", "Add Feature", None))
        self.actionAdd_Feature.setToolTip(_translate("frmMain", "Add Feature", None))
        self.actionStdSaveMenu.setText(_translate("frmMain", "Save", None))
        self.actionStdSaveMenu.setToolTip(_translate("frmMain", "Save Project", None))
        self.actionStdSave.setText(_translate("frmMain", "Save", None))
        self.actionStdSave.setToolTip(_translate("frmMain", "Save project", None))
        self.actionStdSave_As.setText(_translate("frmMain", "Save As...", None))
        self.actionStdSave_As.setToolTip(_translate("frmMain", "Save project as", None))
        self.actionStdImportMap.setText(_translate("frmMain", "Map...", None))
        self.actionStdImportMap.setToolTip(_translate("frmMain", "Import a map", None))
        self.actionStdImportScenario.setText(_translate("frmMain", "Scenario...", None))
        self.actionStdImportScenario.setToolTip(_translate("frmMain", "Import a scenario file", None))
        self.actionStdImportNetwork.setText(_translate("frmMain", "Network...", None))
        self.actionStdImportNetwork.setToolTip(_translate("frmMain", "Import an existing input file", None))
        self.actionStdExportMap.setText(_translate("frmMain", "Map...", None))
        self.actionStdExportMap.setToolTip(_translate("frmMain", "Export current schematic", None))
        self.actionStdPage_Setup.setText(_translate("frmMain", "Page Setup...", None))
        self.actionStdPage_Setup.setToolTip(_translate("frmMain", "Page setup", None))
        self.actionStdPrint_Preview.setText(_translate("frmMain", "Print Preview", None))
        self.actionStdPrint_Preview.setToolTip(_translate("frmMain", "Print preview", None))
        self.actionStdPrint.setText(_translate("frmMain", "Print", None))
        self.actionStdPrint.setToolTip(_translate("frmMain", "Print", None))
        self.actionStdExit.setText(_translate("frmMain", "Exit", None))
        self.actionStdExit.setToolTip(_translate("frmMain", "Quit program", None))
        self.actionStdCopy_To.setText(_translate("frmMain", "Copy To...", None))
        self.actionStdCopy_To.setToolTip(_translate("frmMain", "Copy map at current extent", None))
        self.actionStdSelect_Object.setText(_translate("frmMain", "Select Object", None))
        self.actionStdSelect_Object.setToolTip(_translate("frmMain", "Select object", None))
        self.actionStdSelect_Vertex.setText(_translate("frmMain", "Select Vertex", None))
        self.actionStdSelect_Vertex.setToolTip(_translate("frmMain", "Select vertex of object geometry", None))
        self.actionStdSelect_Region.setText(_translate("frmMain", "Select Region", None))
        self.actionStdSelect_Region.setToolTip(_translate("frmMain", "Select a region on the map", None))
        self.actionStdSelect_All.setText(_translate("frmMain", "Select All", None))
        self.actionStdSelect_All.setToolTip(_translate("frmMain", "Select all objects on the map", None))
        self.actionStdGroup_Edit.setText(_translate("frmMain", "Group Edit...", None))
        self.actionStdGroup_Edit.setToolTip(_translate("frmMain", "Edit a selected group of objects", None))
        self.actionStdProjSummary.setText(_translate("frmMain", "Summary...", None))
        self.actionStdProjSummary.setToolTip(_translate("frmMain", "Project summary", None))
        self.actionStdProjDefault.setText(_translate("frmMain", "Default...", None))
        self.actionStdProjDefault.setToolTip(_translate("frmMain", "Project defaults", None))
        self.actionStdProjCalibration_Data.setText(_translate("frmMain", "Calibration Data...", None))
        self.actionStdProjCalibration_Data.setToolTip(_translate("frmMain", "Set project calibration data", None))
        self.actionStdProjSimulation_Options.setText(_translate("frmMain", "Simulation Options...", None))
        self.actionStdProjSimulation_Options.setToolTip(_translate("frmMain", "Set Simulation Options", None))
        self.actionRun_SimulationMenu.setText(_translate("frmMain", "Run Simulation", None))
        self.actionRun_SimulationMenu.setToolTip(_translate("frmMain", "Start running simulation", None))
        self.actionStdRun_Simulation.setText(_translate("frmMain", "Run Simulation", None))
        self.actionStdRun_Simulation.setToolTip(_translate("frmMain", "Run Simulation", None))
        self.actionStdProjDetails.setText(_translate("frmMain", "Details...", None))
        self.actionStdProjDetails.setToolTip(_translate("frmMain", "Show properties", None))
        self.actionSave_Map_As_Image.setText(_translate("frmMain", "Save Map As Image...", None))
        self.actionObjAddSub.setText(_translate("frmMain", "ObjAddSub", None))
        self.actionObjAddSub.setToolTip(_translate("frmMain", "Add a subcatchment", None))
        self.actionObjAddJunc.setText(_translate("frmMain", "ObjAddJunc", None))
        self.actionObjAddJunc.setToolTip(_translate("frmMain", "Add a junction node", None))
        self.actionObjAddOutfall.setText(_translate("frmMain", "ObjAddOutfall", None))
        self.actionObjAddOutfall.setToolTip(_translate("frmMain", "Add an outfall node", None))
        self.actionObjAddDivider.setText(_translate("frmMain", "ObjAddDivider", None))
        self.actionObjAddDivider.setToolTip(_translate("frmMain", "Add a flow divider node", None))
        self.actionObjAddStorage.setText(_translate("frmMain", "ObjAddStorage", None))
        self.actionObjAddStorage.setToolTip(_translate("frmMain", "Add a storage node", None))
        self.actionObjAddConduit.setText(_translate("frmMain", "ObjAddConduit", None))
        self.actionObjAddConduit.setToolTip(_translate("frmMain", "Add a conduit link", None))
        self.actionObjAddPump.setText(_translate("frmMain", "ObjAddPump", None))
        self.actionObjAddPump.setToolTip(_translate("frmMain", "Add a pump link", None))
        self.actionObjAddOrifice.setText(_translate("frmMain", "ObjAddOrifice", None))
        self.actionObjAddOrifice.setToolTip(_translate("frmMain", "Add an orifice link", None))
        self.actionObjAddWeir.setText(_translate("frmMain", "ObjAddWeir", None))
        self.actionObjAddWeir.setToolTip(_translate("frmMain", "Add a weir link", None))
        self.actionObjAddOutlet.setText(_translate("frmMain", "ObjAddOutlet", None))
        self.actionObjAddOutlet.setToolTip(_translate("frmMain", "Add an outlet link", None))
        self.actionObjAddLabel.setText(_translate("frmMain", "ObjAddLabel", None))
        self.actionObjAddLabel.setToolTip(_translate("frmMain", "Add a map label", None))
        self.actionObjAddTank.setText(_translate("frmMain", "ObjAddTank", None))
        self.actionObjAddTank.setToolTip(_translate("frmMain", "Add a tank node", None))
        self.actionObjAddValve.setText(_translate("frmMain", "ObjAddValve", None))
        self.actionObjAddValve.setToolTip(_translate("frmMain", "Add a valve link", None))
        self.actionMapSelectRegion.setText(_translate("frmMain", "MapSelectRegion", None))
        self.actionMapSelectRegion.setToolTip(_translate("frmMain", "Select region", None))
        self.actionMapFindObj.setText(_translate("frmMain", "MapFindObj", None))
        self.actionMapFindObj.setToolTip(_translate("frmMain", "Find an object on map", None))
        self.actionMapQuery.setText(_translate("frmMain", "MapQuery", None))
        self.actionMapQuery.setToolTip(_translate("frmMain", "Find object via query", None))
        self.actionProjPlotProfile.setText(_translate("frmMain", "ProjPlotProfile", None))
        self.actionProjPlotProfile.setToolTip(_translate("frmMain", "Plot profile", None))
        self.actionProjPlotTimeseries.setText(_translate("frmMain", "ProjPlotTimeseries", None))
        self.actionProjPlotTimeseries.setToolTip(_translate("frmMain", "Plot time series", None))
        self.actionProjPlotScatter.setText(_translate("frmMain", "ProjPlotScatter", None))
        self.actionProjPlotScatter.setToolTip(_translate("frmMain", "Scatter plot", None))
        self.actionProjTableTimeseries.setText(_translate("frmMain", "ProjTableTimeseries", None))
        self.actionProjTableTimeseries.setToolTip(_translate("frmMain", "Create time series table", None))
        self.actionProjTableStatistics.setText(_translate("frmMain", "ProjTableStatistics", None))
        self.actionProjTableStatistics.setToolTip(_translate("frmMain", "Create statistic report", None))
        self.actionMapOption.setText(_translate("frmMain", "MapOption", None))
        self.actionMapOption.setToolTip(_translate("frmMain", "Map options", None))
        self.actionProjStatus.setText(_translate("frmMain", "ProjStatus", None))
        self.actionProjStatus.setToolTip(_translate("frmMain", "Project status report", None))
        self.actionMapMeasure.setText(_translate("frmMain", "MapMeasure", None))
        self.actionMapMeasure.setToolTip(_translate("frmMain", "Measure distance or area", None))
        self.actionMapSelectVertices.setText(_translate("frmMain", "MapSelectVertices", None))
        self.actionMapSelectVertices.setToolTip(_translate("frmMain", "Select vertex", None))
        self.actionStdEditObject.setText(_translate("frmMain", "Edit Object...", None))
        self.actionStdDeleteObject.setText(_translate("frmMain", "Delete Object", None))
        self.actionStdMapDimensions.setText(_translate("frmMain", "Dimensions...", None))
        self.actionLoad.setText(_translate("frmMain", "Load", None))
        self.actionStdMapBackLoad.setText(_translate("frmMain", "Load...", None))
        self.actionStdMapBackUnload.setText(_translate("frmMain", "Unload", None))
        self.actionStdMapBackAlign.setText(_translate("frmMain", "Align", None))
        self.actionStdMapBackResize.setText(_translate("frmMain", "Resize...", None))
        self.actionStdMapBackWatermark.setText(_translate("frmMain", "Watermark", None))
        self.actionStdMapPan.setText(_translate("frmMain", "Pan", None))
        self.actionStdMapZoomIn.setText(_translate("frmMain", "Zoom In", None))
        self.actionStdMapZoomOut.setText(_translate("frmMain", "Zoom Out", None))
        self.actionStdMapFullExtent.setText(_translate("frmMain", "Full Extent", None))
        self.actionStdMapQuery.setText(_translate("frmMain", "Query...", None))
        self.actionStdMapOverview.setText(_translate("frmMain", "Overview", None))
        self.actionStdMapOptions.setText(_translate("frmMain", "Map Options...", None))
        self.actionStdProgPrefer.setText(_translate("frmMain", "Program Preferences...", None))
        self.actionStdConfigTools.setText(_translate("frmMain", "Configure Tools", None))
        self.actionStdWinCascade.setText(_translate("frmMain", "Cascade", None))
        self.actionStdWinTile.setText(_translate("frmMain", "Tile", None))
        self.actionStdWinCloseAll.setText(_translate("frmMain", "Close All", None))
        self.actionStdMapToggle.setText(_translate("frmMain", "Study Area Map", None))
        self.actionStdMapShowRainGages.setText(_translate("frmMain", "Rain Gages", None))
        self.actionStdMapShowSubcatchments.setText(_translate("frmMain", "Subcatchments", None))
        self.actionStdMapShowNodes.setText(_translate("frmMain", "Nodes", None))
        self.actionStdMapShowLinks.setText(_translate("frmMain", "Links", None))
        self.actionStdMapShowLabels.setText(_translate("frmMain", "Labels", None))
        self.actionStdMapShowBackdrop.setText(_translate("frmMain", "Backdrop", None))
        self.actionStdLegSubcatchment.setText(_translate("frmMain", "Subcatchment", None))
        self.actionStdLegNode.setText(_translate("frmMain", "Node", None))
        self.actionStdLegLink.setText(_translate("frmMain", "Link", None))
        self.actionStdLegTime.setText(_translate("frmMain", "Time", None))
        self.actionStdLegModSubcatchment.setText(_translate("frmMain", "Subcatchment", None))
        self.actionStdLegModNode.setText(_translate("frmMain", "Node", None))
        self.actionStdLegModLink.setText(_translate("frmMain", "Link", None))
        self.actionToolbarShowStandard.setText(_translate("frmMain", "Standard", None))
        self.actionToolbarShowMap.setText(_translate("frmMain", "Map", None))
        self.actionToolbarShowObject.setText(_translate("frmMain", "Object", None))
        self.actionEditScript.setText(_translate("frmMain", "Script Editor", None))
        self.actionRun_Script.setText(_translate("frmMain", "Run Script", None))
        self.actionOpen.setText(_translate("frmMain", "File0", None))

import swmm_rc
