# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\frmMainDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(832, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon_swmm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        frmMain.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(frmMain)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.map = QtWidgets.QMdiArea(self.centralwidget)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName("map")
        self.gridLayout.addWidget(self.map, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbAutoLength = QtWidgets.QComboBox(self.centralwidget)
        self.cbAutoLength.setObjectName("cbAutoLength")
        self.cbAutoLength.addItem("")
        self.cbAutoLength.addItem("")
        self.horizontalLayout.addWidget(self.cbAutoLength)
        self.cbOffset = QtWidgets.QComboBox(self.centralwidget)
        self.cbOffset.setObjectName("cbOffset")
        self.cbOffset.addItem("")
        self.cbOffset.addItem("")
        self.horizontalLayout.addWidget(self.cbOffset)
        self.cbFlowUnits = QtWidgets.QComboBox(self.centralwidget)
        self.cbFlowUnits.setObjectName("cbFlowUnits")
        self.cbFlowUnits.addItem("")
        self.cbFlowUnits.addItem("")
        self.cbFlowUnits.addItem("")
        self.cbFlowUnits.addItem("")
        self.cbFlowUnits.addItem("")
        self.cbFlowUnits.addItem("")
        self.horizontalLayout.addWidget(self.cbFlowUnits)
        self.btnCoord = QtWidgets.QPushButton(self.centralwidget)
        self.btnCoord.setObjectName("btnCoord")
        self.horizontalLayout.addWidget(self.btnCoord)
        self.txtCrs = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCrs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtCrs.setReadOnly(True)
        self.txtCrs.setObjectName("txtCrs")
        self.horizontalLayout.addWidget(self.txtCrs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        frmMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(frmMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuImport = QtWidgets.QMenu(self.menuFile)
        self.menuImport.setObjectName("menuImport")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuBackdrop = QtWidgets.QMenu(self.menuView)
        self.menuBackdrop.setObjectName("menuBackdrop")
        self.menuObjects = QtWidgets.QMenu(self.menuView)
        self.menuObjects.setObjectName("menuObjects")
        self.menuToolbars = QtWidgets.QMenu(self.menuView)
        self.menuToolbars.setObjectName("menuToolbars")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        self.menuPlugins = QtWidgets.QMenu(self.menubar)
        self.menuPlugins.setObjectName("menuPlugins")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuScripting = QtWidgets.QMenu(self.menubar)
        self.menuScripting.setObjectName("menuScripting")
        frmMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(frmMain)
        self.statusbar.setObjectName("statusbar")
        frmMain.setStatusBar(self.statusbar)
        self.toolBar_Standard = QtWidgets.QToolBar(frmMain)
        self.toolBar_Standard.setObjectName("toolBar_Standard")
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Standard)
        self.toolBar_Map = QtWidgets.QToolBar(frmMain)
        self.toolBar_Map.setObjectName("toolBar_Map")
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Map)
        frmMain.insertToolBarBreak(self.toolBar_Map)
        self.toolBar_Object = QtWidgets.QToolBar(frmMain)
        self.toolBar_Object.setObjectName("toolBar_Object")
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Object)
        frmMain.insertToolBarBreak(self.toolBar_Object)
        self.dockw_tab = QtWidgets.QDockWidget(frmMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockw_tab.sizePolicy().hasHeightForWidth())
        self.dockw_tab.setSizePolicy(sizePolicy)
        self.dockw_tab.setMinimumSize(QtCore.QSize(212, 270))
        self.dockw_tab.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockw_tab.setObjectName("dockw_tab")
        self.dockWidgetContents_6 = QtWidgets.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabProjMap = QtWidgets.QTabWidget(self.dockWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabProjMap.sizePolicy().hasHeightForWidth())
        self.tabProjMap.setSizePolicy(sizePolicy)
        self.tabProjMap.setObjectName("tabProjMap")
        self.tabProject = QtWidgets.QWidget()
        self.tabProject.setObjectName("tabProject")
        self.tabProjMap.addTab(self.tabProject, "")
        self.tabMap = QtWidgets.QWidget()
        self.tabMap.setObjectName("tabMap")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabMap)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblMapSubcatchments = QtWidgets.QLabel(self.tabMap)
        self.lblMapSubcatchments.setObjectName("lblMapSubcatchments")
        self.verticalLayout_2.addWidget(self.lblMapSubcatchments)
        self.cboMapSubcatchments = QtWidgets.QComboBox(self.tabMap)
        self.cboMapSubcatchments.setObjectName("cboMapSubcatchments")
        self.verticalLayout_2.addWidget(self.cboMapSubcatchments)
        self.lblMapNodes = QtWidgets.QLabel(self.tabMap)
        self.lblMapNodes.setObjectName("lblMapNodes")
        self.verticalLayout_2.addWidget(self.lblMapNodes)
        self.cboMapNodes = QtWidgets.QComboBox(self.tabMap)
        self.cboMapNodes.setObjectName("cboMapNodes")
        self.verticalLayout_2.addWidget(self.cboMapNodes)
        self.lblMapLinks = QtWidgets.QLabel(self.tabMap)
        self.lblMapLinks.setObjectName("lblMapLinks")
        self.verticalLayout_2.addWidget(self.lblMapLinks)
        self.cboMapLinks = QtWidgets.QComboBox(self.tabMap)
        self.cboMapLinks.setObjectName("cboMapLinks")
        self.verticalLayout_2.addWidget(self.cboMapLinks)
        self.chkDisplayFlowDir = QtWidgets.QCheckBox(self.tabMap)
        self.chkDisplayFlowDir.setObjectName("chkDisplayFlowDir")
        self.verticalLayout_2.addWidget(self.chkDisplayFlowDir)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabProjMap.addTab(self.tabMap, "")
        self.tabGIS = QtWidgets.QWidget()
        self.tabGIS.setObjectName("tabGIS")
        self.tabProjMap.addTab(self.tabGIS, "")
        self.gridLayout_2.addWidget(self.tabProjMap, 0, 0, 1, 1)
        self.dockw_tab.setWidget(self.dockWidgetContents_6)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_tab)
        self.dockw_more = QtWidgets.QDockWidget(frmMain)
        self.dockw_more.setObjectName("dockw_more")
        self.dockWidgetContents_4 = QtWidgets.QWidget()
        self.dockWidgetContents_4.setObjectName("dockWidgetContents_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hlayout_obj = QtWidgets.QHBoxLayout()
        self.hlayout_obj.setSpacing(0)
        self.hlayout_obj.setObjectName("hlayout_obj")
        self.btnObjAdd = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjAdd.sizePolicy().hasHeightForWidth())
        self.btnObjAdd.setSizePolicy(sizePolicy)
        self.btnObjAdd.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/obj_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjAdd.setIcon(icon1)
        self.btnObjAdd.setIconSize(QtCore.QSize(20, 20))
        self.btnObjAdd.setFlat(True)
        self.btnObjAdd.setObjectName("btnObjAdd")
        self.hlayout_obj.addWidget(self.btnObjAdd)
        self.btnObjDelete = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjDelete.sizePolicy().hasHeightForWidth())
        self.btnObjDelete.setSizePolicy(sizePolicy)
        self.btnObjDelete.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/obj_delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjDelete.setIcon(icon2)
        self.btnObjDelete.setIconSize(QtCore.QSize(20, 20))
        self.btnObjDelete.setFlat(True)
        self.btnObjDelete.setObjectName("btnObjDelete")
        self.hlayout_obj.addWidget(self.btnObjDelete)
        self.btnObjProperty = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjProperty.sizePolicy().hasHeightForWidth())
        self.btnObjProperty.setSizePolicy(sizePolicy)
        self.btnObjProperty.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/obj_property.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjProperty.setIcon(icon3)
        self.btnObjProperty.setIconSize(QtCore.QSize(20, 20))
        self.btnObjProperty.setFlat(True)
        self.btnObjProperty.setObjectName("btnObjProperty")
        self.hlayout_obj.addWidget(self.btnObjProperty)
        self.btnObjMoveUp = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjMoveUp.sizePolicy().hasHeightForWidth())
        self.btnObjMoveUp.setSizePolicy(sizePolicy)
        self.btnObjMoveUp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/obj_moveup.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjMoveUp.setIcon(icon4)
        self.btnObjMoveUp.setIconSize(QtCore.QSize(20, 20))
        self.btnObjMoveUp.setFlat(True)
        self.btnObjMoveUp.setObjectName("btnObjMoveUp")
        self.hlayout_obj.addWidget(self.btnObjMoveUp)
        self.btnObjMoveDown = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjMoveDown.sizePolicy().hasHeightForWidth())
        self.btnObjMoveDown.setSizePolicy(sizePolicy)
        self.btnObjMoveDown.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/obj_movedown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjMoveDown.setIcon(icon5)
        self.btnObjMoveDown.setIconSize(QtCore.QSize(20, 20))
        self.btnObjMoveDown.setFlat(True)
        self.btnObjMoveDown.setObjectName("btnObjMoveDown")
        self.hlayout_obj.addWidget(self.btnObjMoveDown)
        self.btnObjSort = QtWidgets.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnObjSort.sizePolicy().hasHeightForWidth())
        self.btnObjSort.setSizePolicy(sizePolicy)
        self.btnObjSort.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/obj_sort.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnObjSort.setIcon(icon6)
        self.btnObjSort.setIconSize(QtCore.QSize(20, 20))
        self.btnObjSort.setFlat(True)
        self.btnObjSort.setObjectName("btnObjSort")
        self.hlayout_obj.addWidget(self.btnObjSort)
        self.gridLayout_3.addLayout(self.hlayout_obj, 0, 0, 1, 1)
        self.listViewObjects = QtWidgets.QListWidget(self.dockWidgetContents_4)
        self.listViewObjects.setObjectName("listViewObjects")
        self.gridLayout_3.addWidget(self.listViewObjects, 1, 0, 1, 1)
        self.dockw_more.setWidget(self.dockWidgetContents_4)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_more)
        self.time_widget = QtWidgets.QDockWidget(frmMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_widget.sizePolicy().hasHeightForWidth())
        self.time_widget.setSizePolicy(sizePolicy)
        self.time_widget.setMinimumSize(QtCore.QSize(658, 82))
        self.time_widget.setObjectName("time_widget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelStartTime = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.labelStartTime.setMaximumSize(QtCore.QSize(16777215, 18))
        self.labelStartTime.setObjectName("labelStartTime")
        self.gridLayout_4.addWidget(self.labelStartTime, 0, 0, 1, 1)
        self.horizontalTimeSlider = QtWidgets.QSlider(self.dockWidgetContents_2)
        self.horizontalTimeSlider.setMinimumSize(QtCore.QSize(0, 12))
        self.horizontalTimeSlider.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalTimeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalTimeSlider.setObjectName("horizontalTimeSlider")
        self.gridLayout_4.addWidget(self.horizontalTimeSlider, 0, 1, 1, 14)
        self.labelEndTime = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.labelEndTime.setMaximumSize(QtCore.QSize(16777215, 18))
        self.labelEndTime.setObjectName("labelEndTime")
        self.gridLayout_4.addWidget(self.labelEndTime, 0, 15, 1, 1)
        self.pushButtonBack = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.pushButtonBack.sizePolicy().hasHeightForWidth())
        self.pushButtonBack.setSizePolicy(sizePolicy)
        self.pushButtonBack.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBack.setIcon(icon7)
        self.pushButtonBack.setIconSize(QtCore.QSize(12, 12))
        self.pushButtonBack.setFlat(True)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.gridLayout_4.addWidget(self.pushButtonBack, 1, 0, 1, 1)
        self.pushButtonPlay = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.pushButtonPlay.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPlay.sizePolicy().hasHeightForWidth())
        self.pushButtonPlay.setSizePolicy(sizePolicy)
        self.pushButtonPlay.setMaximumSize(QtCore.QSize(18, 18))
        self.pushButtonPlay.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButtonPlay.setIcon(icon8)
        self.pushButtonPlay.setCheckable(True)
        self.pushButtonPlay.setChecked(False)
        self.pushButtonPlay.setFlat(True)
        self.pushButtonPlay.setObjectName("pushButtonPlay")
        self.gridLayout_4.addWidget(self.pushButtonPlay, 1, 1, 1, 1)
        self.pushButtonForward = QtWidgets.QPushButton(self.dockWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.pushButtonForward.sizePolicy().hasHeightForWidth())
        self.pushButtonForward.setSizePolicy(sizePolicy)
        self.pushButtonForward.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButtonForward.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonForward.setIcon(icon9)
        self.pushButtonForward.setFlat(True)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.gridLayout_4.addWidget(self.pushButtonForward, 1, 2, 1, 1)
        self.dsbPlaySpeed = QtWidgets.QDoubleSpinBox(self.dockWidgetContents_2)
        self.dsbPlaySpeed.setObjectName("dsbPlaySpeed")
        self.gridLayout_4.addWidget(self.dsbPlaySpeed, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(266, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 4, 1, 1)
        self.lblDate = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.lblDate.setObjectName("lblDate")
        self.gridLayout_4.addWidget(self.lblDate, 1, 5, 1, 1)
        self.cboDate = QtWidgets.QComboBox(self.dockWidgetContents_2)
        self.cboDate.setObjectName("cboDate")
        self.gridLayout_4.addWidget(self.cboDate, 1, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 7, 1, 1)
        self.lblAnimateTime = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.lblAnimateTime.setObjectName("lblAnimateTime")
        self.gridLayout_4.addWidget(self.lblAnimateTime, 1, 8, 1, 1)
        self.cboTime = QtWidgets.QComboBox(self.dockWidgetContents_2)
        self.cboTime.setObjectName("cboTime")
        self.gridLayout_4.addWidget(self.cboTime, 1, 9, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 1, 10, 1, 1)
        self.lblETime = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.lblETime.setObjectName("lblETime")
        self.gridLayout_4.addWidget(self.lblETime, 1, 11, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 1, 14, 1, 2)
        self.txtETime = QtWidgets.QLineEdit(self.dockWidgetContents_2)
        self.txtETime.setObjectName("txtETime")
        self.gridLayout_4.addWidget(self.txtETime, 1, 12, 1, 1)
        self.sbETime = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.sbETime.setWrapping(False)
        self.sbETime.setFrame(False)
        self.sbETime.setObjectName("sbETime")
        self.gridLayout_4.addWidget(self.sbETime, 1, 13, 1, 1)
        self.time_widget.setWidget(self.dockWidgetContents_2)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.time_widget)
        self.actionStdNewProject = QtWidgets.QAction(frmMain)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/std_project_new.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdNewProject.setIcon(icon10)
        self.actionStdNewProject.setObjectName("actionStdNewProject")
        self.actionMapSelectObj = QtWidgets.QAction(frmMain)
        self.actionMapSelectObj.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/map_pointer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectObj.setIcon(icon11)
        self.actionMapSelectObj.setObjectName("actionMapSelectObj")
        self.actionObjAddGage = QtWidgets.QAction(frmMain)
        self.actionObjAddGage.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/obj_gage.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddGage.setIcon(icon12)
        self.actionObjAddGage.setObjectName("actionObjAddGage")
        self.actionScriptEditor = QtWidgets.QAction(frmMain)
        self.actionScriptEditor.setObjectName("actionScriptEditor")
        self.actionExec = QtWidgets.QAction(frmMain)
        self.actionExec.setObjectName("actionExec")
        self.actionAdd_Vector = QtWidgets.QAction(frmMain)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/map_add_v.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Vector.setIcon(icon13)
        self.actionAdd_Vector.setObjectName("actionAdd_Vector")
        self.actionAdd_Raster = QtWidgets.QAction(frmMain)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/map_add_r.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Raster.setIcon(icon14)
        self.actionAdd_Raster.setObjectName("actionAdd_Raster")
        self.actionPan = QtWidgets.QAction(frmMain)
        self.actionPan.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/map_qgis_pan.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPan.setIcon(icon15)
        self.actionPan.setObjectName("actionPan")
        self.actionShow_coordinates = QtWidgets.QAction(frmMain)
        self.actionShow_coordinates.setObjectName("actionShow_coordinates")
        self.actionZoom_in = QtWidgets.QAction(frmMain)
        self.actionZoom_in.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/map_qgis_zoomin.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_in.setIcon(icon16)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(frmMain)
        self.actionZoom_out.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/map_qgis_zoomout.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_out.setIcon(icon17)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionZoom_full = QtWidgets.QAction(frmMain)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/map_qgis_zoomfull.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_full.setIcon(icon18)
        self.actionZoom_full.setObjectName("actionZoom_full")
        self.actionStdOpenProjMenu = QtWidgets.QAction(frmMain)
        self.actionStdOpenProjMenu.setObjectName("actionStdOpenProjMenu")
        self.actionStdOpenProj = QtWidgets.QAction(frmMain)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/std_project_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdOpenProj.setIcon(icon19)
        self.actionStdOpenProj.setObjectName("actionStdOpenProj")
        self.actionStdNewProjectMenu = QtWidgets.QAction(frmMain)
        self.actionStdNewProjectMenu.setObjectName("actionStdNewProjectMenu")
        self.actionAdd_Feature = QtWidgets.QAction(frmMain)
        self.actionAdd_Feature.setCheckable(True)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/map_qgis_edit_addfeature0.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon20.addPixmap(QtGui.QPixmap(":/icons/map_qgis_edit_addfeature.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.actionAdd_Feature.setIcon(icon20)
        self.actionAdd_Feature.setObjectName("actionAdd_Feature")
        self.actionStdSaveMenu = QtWidgets.QAction(frmMain)
        self.actionStdSaveMenu.setObjectName("actionStdSaveMenu")
        self.actionStdSave = QtWidgets.QAction(frmMain)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/std_project_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdSave.setIcon(icon21)
        self.actionStdSave.setObjectName("actionStdSave")
        self.actionStdSave_As = QtWidgets.QAction(frmMain)
        self.actionStdSave_As.setObjectName("actionStdSave_As")
        self.actionStdImportMap = QtWidgets.QAction(frmMain)
        self.actionStdImportMap.setObjectName("actionStdImportMap")
        self.actionStdImportScenario = QtWidgets.QAction(frmMain)
        self.actionStdImportScenario.setObjectName("actionStdImportScenario")
        self.actionStdImportNetwork = QtWidgets.QAction(frmMain)
        self.actionStdImportNetwork.setObjectName("actionStdImportNetwork")
        self.actionStdExportMap = QtWidgets.QAction(frmMain)
        self.actionStdExportMap.setObjectName("actionStdExportMap")
        self.actionStdPage_Setup = QtWidgets.QAction(frmMain)
        self.actionStdPage_Setup.setObjectName("actionStdPage_Setup")
        self.actionStdPrint_Preview = QtWidgets.QAction(frmMain)
        self.actionStdPrint_Preview.setObjectName("actionStdPrint_Preview")
        self.actionStdPrint = QtWidgets.QAction(frmMain)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/std_project_printwindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdPrint.setIcon(icon22)
        self.actionStdPrint.setObjectName("actionStdPrint")
        self.actionStdExit = QtWidgets.QAction(frmMain)
        self.actionStdExit.setObjectName("actionStdExit")
        self.actionStdCopy_To = QtWidgets.QAction(frmMain)
        self.actionStdCopy_To.setObjectName("actionStdCopy_To")
        self.actionStdSelect_Object = QtWidgets.QAction(frmMain)
        self.actionStdSelect_Object.setObjectName("actionStdSelect_Object")
        self.actionStdSelect_Vertex = QtWidgets.QAction(frmMain)
        self.actionStdSelect_Vertex.setObjectName("actionStdSelect_Vertex")
        self.actionStdSelect_Region = QtWidgets.QAction(frmMain)
        self.actionStdSelect_Region.setObjectName("actionStdSelect_Region")
        self.actionStdSelect_All = QtWidgets.QAction(frmMain)
        self.actionStdSelect_All.setObjectName("actionStdSelect_All")
        self.actionStdGroup_Edit = QtWidgets.QAction(frmMain)
        self.actionStdGroup_Edit.setObjectName("actionStdGroup_Edit")
        self.actionStdProjSummary = QtWidgets.QAction(frmMain)
        self.actionStdProjSummary.setObjectName("actionStdProjSummary")
        self.actionStdProjDefault = QtWidgets.QAction(frmMain)
        self.actionStdProjDefault.setObjectName("actionStdProjDefault")
        self.actionStdProjCalibration_Data = QtWidgets.QAction(frmMain)
        self.actionStdProjCalibration_Data.setObjectName("actionStdProjCalibration_Data")
        self.actionStdProjSimulation_Options = QtWidgets.QAction(frmMain)
        self.actionStdProjSimulation_Options.setObjectName("actionStdProjSimulation_Options")
        self.actionRun_SimulationMenu = QtWidgets.QAction(frmMain)
        self.actionRun_SimulationMenu.setObjectName("actionRun_SimulationMenu")
        self.actionStdRun_Simulation = QtWidgets.QAction(frmMain)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/std_project_runswmm.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdRun_Simulation.setIcon(icon23)
        self.actionStdRun_Simulation.setObjectName("actionStdRun_Simulation")
        self.actionStdProjDetails = QtWidgets.QAction(frmMain)
        self.actionStdProjDetails.setObjectName("actionStdProjDetails")
        self.actionSave_Map_As_Image = QtWidgets.QAction(frmMain)
        self.actionSave_Map_As_Image.setObjectName("actionSave_Map_As_Image")
        self.actionObjAddSub = QtWidgets.QAction(frmMain)
        self.actionObjAddSub.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/obj_subcatchment.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddSub.setIcon(icon24)
        self.actionObjAddSub.setObjectName("actionObjAddSub")
        self.actionObjAddJunc = QtWidgets.QAction(frmMain)
        self.actionObjAddJunc.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/icons/obj_node_junction.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddJunc.setIcon(icon25)
        self.actionObjAddJunc.setObjectName("actionObjAddJunc")
        self.actionObjAddOutfall = QtWidgets.QAction(frmMain)
        self.actionObjAddOutfall.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/icons/obj_node_outfall.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOutfall.setIcon(icon26)
        self.actionObjAddOutfall.setObjectName("actionObjAddOutfall")
        self.actionObjAddDivider = QtWidgets.QAction(frmMain)
        self.actionObjAddDivider.setCheckable(True)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/obj_node_divider.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddDivider.setIcon(icon27)
        self.actionObjAddDivider.setObjectName("actionObjAddDivider")
        self.actionObjAddStorage = QtWidgets.QAction(frmMain)
        self.actionObjAddStorage.setCheckable(True)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/obj_node_storage.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddStorage.setIcon(icon28)
        self.actionObjAddStorage.setObjectName("actionObjAddStorage")
        self.actionObjAddConduit = QtWidgets.QAction(frmMain)
        self.actionObjAddConduit.setCheckable(True)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/obj_link_conduit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddConduit.setIcon(icon29)
        self.actionObjAddConduit.setObjectName("actionObjAddConduit")
        self.actionObjAddPump = QtWidgets.QAction(frmMain)
        self.actionObjAddPump.setCheckable(True)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/obj_link_pump.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddPump.setIcon(icon30)
        self.actionObjAddPump.setObjectName("actionObjAddPump")
        self.actionObjAddOrifice = QtWidgets.QAction(frmMain)
        self.actionObjAddOrifice.setCheckable(True)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/obj_link_orifice.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOrifice.setIcon(icon31)
        self.actionObjAddOrifice.setObjectName("actionObjAddOrifice")
        self.actionObjAddWeir = QtWidgets.QAction(frmMain)
        self.actionObjAddWeir.setCheckable(True)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/obj_link_weir.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddWeir.setIcon(icon32)
        self.actionObjAddWeir.setObjectName("actionObjAddWeir")
        self.actionObjAddOutlet = QtWidgets.QAction(frmMain)
        self.actionObjAddOutlet.setCheckable(True)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/obj_link_outlet.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddOutlet.setIcon(icon33)
        self.actionObjAddOutlet.setObjectName("actionObjAddOutlet")
        self.actionObjAddLabel = QtWidgets.QAction(frmMain)
        self.actionObjAddLabel.setCheckable(True)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/obj_maplabel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddLabel.setIcon(icon34)
        self.actionObjAddLabel.setObjectName("actionObjAddLabel")
        self.actionObjAddTank = QtWidgets.QAction(frmMain)
        self.actionObjAddTank.setCheckable(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/icons/obj_node_tank.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddTank.setIcon(icon35)
        self.actionObjAddTank.setObjectName("actionObjAddTank")
        self.actionObjAddValve = QtWidgets.QAction(frmMain)
        self.actionObjAddValve.setCheckable(True)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/icons/obj_link_valve.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddValve.setIcon(icon36)
        self.actionObjAddValve.setObjectName("actionObjAddValve")
        self.actionMapSelectRegion = QtWidgets.QAction(frmMain)
        self.actionMapSelectRegion.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/icons/map_selectregion.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectRegion.setIcon(icon37)
        self.actionMapSelectRegion.setObjectName("actionMapSelectRegion")
        self.actionMapFindObj = QtWidgets.QAction(frmMain)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/icons/std_project_findobjectinmap.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapFindObj.setIcon(icon38)
        self.actionMapFindObj.setObjectName("actionMapFindObj")
        self.actionMapQuery = QtWidgets.QAction(frmMain)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/icons/std_project_findobjectbyrules.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapQuery.setIcon(icon39)
        self.actionMapQuery.setObjectName("actionMapQuery")
        self.actionProjPlotProfile = QtWidgets.QAction(frmMain)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/icons/std_project_profileplot.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotProfile.setIcon(icon40)
        self.actionProjPlotProfile.setObjectName("actionProjPlotProfile")
        self.actionProjPlotTimeseries = QtWidgets.QAction(frmMain)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/icons/std_project_tsplot.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotTimeseries.setIcon(icon41)
        self.actionProjPlotTimeseries.setObjectName("actionProjPlotTimeseries")
        self.actionProjPlotScatter = QtWidgets.QAction(frmMain)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/icons/std_project_scatterplot.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjPlotScatter.setIcon(icon42)
        self.actionProjPlotScatter.setObjectName("actionProjPlotScatter")
        self.actionProjTableTimeseries = QtWidgets.QAction(frmMain)
        icon43 = QtGui.QIcon()
        icon43.addPixmap(QtGui.QPixmap(":/icons/std_project_tstable.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjTableTimeseries.setIcon(icon43)
        self.actionProjTableTimeseries.setObjectName("actionProjTableTimeseries")
        self.actionProjTableStatistics = QtWidgets.QAction(frmMain)
        icon44 = QtGui.QIcon()
        icon44.addPixmap(QtGui.QPixmap(":/icons/std_project_statisticreport.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjTableStatistics.setIcon(icon44)
        self.actionProjTableStatistics.setObjectName("actionProjTableStatistics")
        self.actionMapOption = QtWidgets.QAction(frmMain)
        icon45 = QtGui.QIcon()
        icon45.addPixmap(QtGui.QPixmap(":/icons/std_project_viewoption.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapOption.setIcon(icon45)
        self.actionMapOption.setObjectName("actionMapOption")
        self.actionProjStatus = QtWidgets.QAction(frmMain)
        icon46 = QtGui.QIcon()
        icon46.addPixmap(QtGui.QPixmap(":/icons/std_project_statusreport.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionProjStatus.setIcon(icon46)
        self.actionProjStatus.setObjectName("actionProjStatus")
        self.actionMapMeasure = QtWidgets.QAction(frmMain)
        self.actionMapMeasure.setCheckable(True)
        icon47 = QtGui.QIcon()
        icon47.addPixmap(QtGui.QPixmap(":/icons/map_measure.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapMeasure.setIcon(icon47)
        self.actionMapMeasure.setObjectName("actionMapMeasure")
        self.actionMapSelectVertices = QtWidgets.QAction(frmMain)
        self.actionMapSelectVertices.setCheckable(True)
        icon48 = QtGui.QIcon()
        icon48.addPixmap(QtGui.QPixmap(":/icons/map_selectvertices.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectVertices.setIcon(icon48)
        self.actionMapSelectVertices.setObjectName("actionMapSelectVertices")
        self.actionStdEditObject = QtWidgets.QAction(frmMain)
        self.actionStdEditObject.setObjectName("actionStdEditObject")
        self.actionStdDeleteObject = QtWidgets.QAction(frmMain)
        self.actionStdDeleteObject.setObjectName("actionStdDeleteObject")
        self.actionStdMapDimensions = QtWidgets.QAction(frmMain)
        self.actionStdMapDimensions.setObjectName("actionStdMapDimensions")
        self.actionLoad = QtWidgets.QAction(frmMain)
        self.actionLoad.setObjectName("actionLoad")
        self.actionStdMapBackLoad = QtWidgets.QAction(frmMain)
        self.actionStdMapBackLoad.setObjectName("actionStdMapBackLoad")
        self.actionStdMapBackUnload = QtWidgets.QAction(frmMain)
        self.actionStdMapBackUnload.setObjectName("actionStdMapBackUnload")
        self.actionStdMapBackAlign = QtWidgets.QAction(frmMain)
        self.actionStdMapBackAlign.setObjectName("actionStdMapBackAlign")
        self.actionStdMapBackResize = QtWidgets.QAction(frmMain)
        self.actionStdMapBackResize.setObjectName("actionStdMapBackResize")
        self.actionStdMapBackWatermark = QtWidgets.QAction(frmMain)
        self.actionStdMapBackWatermark.setObjectName("actionStdMapBackWatermark")
        self.actionStdMapPan = QtWidgets.QAction(frmMain)
        self.actionStdMapPan.setObjectName("actionStdMapPan")
        self.actionStdMapZoomIn = QtWidgets.QAction(frmMain)
        self.actionStdMapZoomIn.setObjectName("actionStdMapZoomIn")
        self.actionStdMapZoomOut = QtWidgets.QAction(frmMain)
        self.actionStdMapZoomOut.setObjectName("actionStdMapZoomOut")
        self.actionStdMapFullExtent = QtWidgets.QAction(frmMain)
        self.actionStdMapFullExtent.setObjectName("actionStdMapFullExtent")
        self.actionStdMapQuery = QtWidgets.QAction(frmMain)
        self.actionStdMapQuery.setObjectName("actionStdMapQuery")
        self.actionStdMapOverview = QtWidgets.QAction(frmMain)
        self.actionStdMapOverview.setObjectName("actionStdMapOverview")
        self.actionStdMapOptions = QtWidgets.QAction(frmMain)
        self.actionStdMapOptions.setObjectName("actionStdMapOptions")
        self.actionStdProgPrefer = QtWidgets.QAction(frmMain)
        self.actionStdProgPrefer.setObjectName("actionStdProgPrefer")
        self.actionStdConfigTools = QtWidgets.QAction(frmMain)
        self.actionStdConfigTools.setObjectName("actionStdConfigTools")
        self.actionStdWinCascade = QtWidgets.QAction(frmMain)
        self.actionStdWinCascade.setObjectName("actionStdWinCascade")
        self.actionStdWinTile = QtWidgets.QAction(frmMain)
        self.actionStdWinTile.setObjectName("actionStdWinTile")
        self.actionStdWinCloseAll = QtWidgets.QAction(frmMain)
        self.actionStdWinCloseAll.setObjectName("actionStdWinCloseAll")
        self.actionStdMapToggle = QtWidgets.QAction(frmMain)
        self.actionStdMapToggle.setCheckable(True)
        self.actionStdMapToggle.setChecked(True)
        self.actionStdMapToggle.setObjectName("actionStdMapToggle")
        self.actionStdMapShowRainGages = QtWidgets.QAction(frmMain)
        self.actionStdMapShowRainGages.setCheckable(True)
        self.actionStdMapShowRainGages.setObjectName("actionStdMapShowRainGages")
        self.actionStdMapShowSubcatchments = QtWidgets.QAction(frmMain)
        self.actionStdMapShowSubcatchments.setCheckable(True)
        self.actionStdMapShowSubcatchments.setObjectName("actionStdMapShowSubcatchments")
        self.actionStdMapShowNodes = QtWidgets.QAction(frmMain)
        self.actionStdMapShowNodes.setCheckable(True)
        self.actionStdMapShowNodes.setObjectName("actionStdMapShowNodes")
        self.actionStdMapShowLinks = QtWidgets.QAction(frmMain)
        self.actionStdMapShowLinks.setCheckable(True)
        self.actionStdMapShowLinks.setObjectName("actionStdMapShowLinks")
        self.actionStdMapShowLabels = QtWidgets.QAction(frmMain)
        self.actionStdMapShowLabels.setCheckable(True)
        self.actionStdMapShowLabels.setObjectName("actionStdMapShowLabels")
        self.actionStdMapShowBackdrop = QtWidgets.QAction(frmMain)
        self.actionStdMapShowBackdrop.setCheckable(True)
        self.actionStdMapShowBackdrop.setObjectName("actionStdMapShowBackdrop")
        self.actionStdLegSubcatchment = QtWidgets.QAction(frmMain)
        self.actionStdLegSubcatchment.setCheckable(True)
        self.actionStdLegSubcatchment.setObjectName("actionStdLegSubcatchment")
        self.actionStdLegNode = QtWidgets.QAction(frmMain)
        self.actionStdLegNode.setCheckable(True)
        self.actionStdLegNode.setObjectName("actionStdLegNode")
        self.actionStdLegLink = QtWidgets.QAction(frmMain)
        self.actionStdLegLink.setCheckable(True)
        self.actionStdLegLink.setObjectName("actionStdLegLink")
        self.actionStdLegTime = QtWidgets.QAction(frmMain)
        self.actionStdLegTime.setCheckable(True)
        self.actionStdLegTime.setObjectName("actionStdLegTime")
        self.actionStdLegModSubcatchment = QtWidgets.QAction(frmMain)
        self.actionStdLegModSubcatchment.setObjectName("actionStdLegModSubcatchment")
        self.actionStdLegModNode = QtWidgets.QAction(frmMain)
        self.actionStdLegModNode.setObjectName("actionStdLegModNode")
        self.actionStdLegModLink = QtWidgets.QAction(frmMain)
        self.actionStdLegModLink.setObjectName("actionStdLegModLink")
        self.actionToolbarShowStandard = QtWidgets.QAction(frmMain)
        self.actionToolbarShowStandard.setCheckable(True)
        self.actionToolbarShowStandard.setChecked(True)
        self.actionToolbarShowStandard.setObjectName("actionToolbarShowStandard")
        self.actionToolbarShowMap = QtWidgets.QAction(frmMain)
        self.actionToolbarShowMap.setCheckable(True)
        self.actionToolbarShowMap.setChecked(True)
        self.actionToolbarShowMap.setObjectName("actionToolbarShowMap")
        self.actionToolbarShowObject = QtWidgets.QAction(frmMain)
        self.actionToolbarShowObject.setCheckable(True)
        self.actionToolbarShowObject.setChecked(True)
        self.actionToolbarShowObject.setObjectName("actionToolbarShowObject")
        self.actionEditScript = QtWidgets.QAction(frmMain)
        self.actionEditScript.setObjectName("actionEditScript")
        self.actionRun_Script = QtWidgets.QAction(frmMain)
        self.actionRun_Script.setObjectName("actionRun_Script")
        self.actionOpen = QtWidgets.QAction(frmMain)
        self.actionOpen.setObjectName("actionOpen")
        self.actionStdMapFind = QtWidgets.QAction(frmMain)
        self.actionStdMapFind.setObjectName("actionStdMapFind")
        self.actionStdLegends = QtWidgets.QAction(frmMain)
        self.actionStdLegends.setObjectName("actionStdLegends")
        self.actionStdMapPanSelection = QtWidgets.QAction(frmMain)
        self.actionStdMapPanSelection.setObjectName("actionStdMapPanSelection")
        self.menuImport.addAction(self.actionStdImportMap)
        self.menuImport.addAction(self.actionStdImportScenario)
        self.menuImport.addAction(self.actionStdImportNetwork)
        self.menuExport.addAction(self.actionStdExportMap)
        self.menuFile.addAction(self.actionStdNewProjectMenu)
        self.menuFile.addAction(self.actionStdOpenProjMenu)
        self.menuFile.addAction(self.actionStdSaveMenu)
        self.menuFile.addAction(self.actionStdSave_As)
        self.menuFile.addAction(self.actionSave_Map_As_Image)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuImport.menuAction())
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStdPage_Setup)
        self.menuFile.addAction(self.actionStdPrint_Preview)
        self.menuFile.addAction(self.actionStdPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStdExit)
        self.menuEdit.addAction(self.actionStdCopy_To)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdSelect_Object)
        self.menuEdit.addAction(self.actionStdSelect_Vertex)
        self.menuEdit.addAction(self.actionStdSelect_Region)
        self.menuEdit.addAction(self.actionStdSelect_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdEditObject)
        self.menuEdit.addAction(self.actionStdDeleteObject)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionStdGroup_Edit)
        self.menuEdit.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackLoad)
        self.menuBackdrop.addAction(self.actionStdMapBackUnload)
        self.menuBackdrop.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackAlign)
        self.menuBackdrop.addAction(self.actionStdMapBackResize)
        self.menuBackdrop.addSeparator()
        self.menuBackdrop.addAction(self.actionStdMapBackWatermark)
        self.menuObjects.addAction(self.actionStdMapShowRainGages)
        self.menuObjects.addAction(self.actionStdMapShowSubcatchments)
        self.menuObjects.addAction(self.actionStdMapShowNodes)
        self.menuObjects.addAction(self.actionStdMapShowLinks)
        self.menuObjects.addAction(self.actionStdMapShowLabels)
        self.menuObjects.addAction(self.actionStdMapShowBackdrop)
        self.menuToolbars.addAction(self.actionToolbarShowStandard)
        self.menuToolbars.addAction(self.actionToolbarShowMap)
        self.menuToolbars.addAction(self.actionToolbarShowObject)
        self.menuView.addAction(self.actionStdMapDimensions)
        self.menuView.addAction(self.menuBackdrop.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapPan)
        self.menuView.addAction(self.actionStdMapZoomIn)
        self.menuView.addAction(self.actionStdMapZoomOut)
        self.menuView.addAction(self.actionStdMapFullExtent)
        self.menuView.addAction(self.actionStdMapPanSelection)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapFind)
        self.menuView.addAction(self.actionStdMapQuery)
        self.menuView.addAction(self.actionStdMapOverview)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuObjects.menuAction())
        self.menuView.addAction(self.actionStdLegends)
        self.menuView.addAction(self.menuToolbars.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStdMapOptions)
        self.menuProject.addAction(self.actionStdProjSummary)
        self.menuProject.addAction(self.actionStdProjDetails)
        self.menuProject.addAction(self.actionStdProjDefault)
        self.menuProject.addAction(self.actionStdProjCalibration_Data)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionStdProjSimulation_Options)
        self.menuProject.addAction(self.actionRun_SimulationMenu)
        self.menuTools.addAction(self.actionStdProgPrefer)
        self.menuTools.addAction(self.actionStdConfigTools)
        self.menuWindow.addAction(self.actionStdWinCascade)
        self.menuWindow.addAction(self.actionStdWinTile)
        self.menuWindow.addAction(self.actionStdWinCloseAll)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionStdMapToggle)
        self.menuPlugins.addSeparator()
        self.menuScripting.addAction(self.actionEditScript)
        self.menuScripting.addAction(self.actionRun_Script)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuScripting.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_Standard.addAction(self.actionStdNewProject)
        self.toolBar_Standard.addAction(self.actionStdOpenProj)
        self.toolBar_Standard.addAction(self.actionStdSave)
        self.toolBar_Standard.addAction(self.actionStdPrint)
        self.toolBar_Standard.addSeparator()
        self.toolBar_Standard.addAction(self.actionStdRun_Simulation)
        self.toolBar_Standard.addSeparator()
        self.toolBar_Standard.addAction(self.actionProjStatus)
        self.toolBar_Standard.addAction(self.actionProjPlotProfile)
        self.toolBar_Standard.addAction(self.actionProjPlotTimeseries)
        self.toolBar_Standard.addAction(self.actionProjPlotScatter)
        self.toolBar_Standard.addAction(self.actionProjTableTimeseries)
        self.toolBar_Standard.addAction(self.actionProjTableStatistics)
        self.toolBar_Map.addAction(self.actionAdd_Vector)
        self.toolBar_Map.addAction(self.actionAdd_Raster)
        self.toolBar_Map.addAction(self.actionZoom_in)
        self.toolBar_Map.addAction(self.actionZoom_out)
        self.toolBar_Map.addAction(self.actionZoom_full)
        self.toolBar_Map.addAction(self.actionPan)
        self.toolBar_Map.addAction(self.actionAdd_Feature)
        self.toolBar_Map.addAction(self.actionMapSelectObj)
        self.toolBar_Map.addAction(self.actionMapSelectVertices)
        self.toolBar_Map.addAction(self.actionMapSelectRegion)
        self.toolBar_Map.addAction(self.actionMapMeasure)
        self.toolBar_Map.addAction(self.actionMapFindObj)
        self.toolBar_Map.addAction(self.actionMapQuery)
        self.toolBar_Map.addSeparator()
        self.toolBar_Map.addAction(self.actionMapOption)
        self.toolBar_Object.addAction(self.actionObjAddGage)
        self.toolBar_Object.addAction(self.actionObjAddSub)
        self.toolBar_Object.addAction(self.actionObjAddJunc)
        self.toolBar_Object.addAction(self.actionObjAddOutfall)
        self.toolBar_Object.addAction(self.actionObjAddDivider)
        self.toolBar_Object.addAction(self.actionObjAddStorage)
        self.toolBar_Object.addAction(self.actionObjAddTank)
        self.toolBar_Object.addAction(self.actionObjAddConduit)
        self.toolBar_Object.addAction(self.actionObjAddPump)
        self.toolBar_Object.addAction(self.actionObjAddOrifice)
        self.toolBar_Object.addAction(self.actionObjAddWeir)
        self.toolBar_Object.addAction(self.actionObjAddOutlet)
        self.toolBar_Object.addAction(self.actionObjAddValve)
        self.toolBar_Object.addAction(self.actionObjAddLabel)

        self.retranslateUi(frmMain)
        self.tabProjMap.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "SWMM 5.1"))
        self.cbAutoLength.setItemText(0, _translate("frmMain", "Auto-Length: Off"))
        self.cbAutoLength.setItemText(1, _translate("frmMain", "Auto-Length: On"))
        self.cbOffset.setItemText(0, _translate("frmMain", "Offsets: Elevation"))
        self.cbOffset.setItemText(1, _translate("frmMain", "Offsets: Depth"))
        self.cbFlowUnits.setItemText(0, _translate("frmMain", "Flow Units: CFS"))
        self.cbFlowUnits.setItemText(1, _translate("frmMain", "Flow Units: GPM"))
        self.cbFlowUnits.setItemText(2, _translate("frmMain", "Flow Units: MGD"))
        self.cbFlowUnits.setItemText(3, _translate("frmMain", "Flow Units: CMS"))
        self.cbFlowUnits.setItemText(4, _translate("frmMain", "Flow Units: LPS"))
        self.cbFlowUnits.setItemText(5, _translate("frmMain", "Flow Units: MLD"))
        self.btnCoord.setText(_translate("frmMain", "x,y"))
        self.menuFile.setTitle(_translate("frmMain", "File"))
        self.menuImport.setTitle(_translate("frmMain", "Import"))
        self.menuExport.setTitle(_translate("frmMain", "Export"))
        self.menuEdit.setTitle(_translate("frmMain", "Edit"))
        self.menuView.setTitle(_translate("frmMain", "View"))
        self.menuBackdrop.setTitle(_translate("frmMain", "Backdrop"))
        self.menuObjects.setTitle(_translate("frmMain", "Objects"))
        self.menuToolbars.setTitle(_translate("frmMain", "Toolbars"))
        self.menuProject.setTitle(_translate("frmMain", "Project"))
        self.menuReport.setTitle(_translate("frmMain", "Report"))
        self.menuTools.setTitle(_translate("frmMain", "Tools"))
        self.menuWindow.setTitle(_translate("frmMain", "Window"))
        self.menuPlugins.setTitle(_translate("frmMain", "Plugins"))
        self.menuHelp.setTitle(_translate("frmMain", "Help"))
        self.menuScripting.setTitle(_translate("frmMain", "Scripting"))
        self.toolBar_Standard.setWindowTitle(_translate("frmMain", "Standard"))
        self.toolBar_Map.setWindowTitle(_translate("frmMain", "Map"))
        self.toolBar_Object.setWindowTitle(_translate("frmMain", "Object"))
        self.dockw_tab.setWindowTitle(_translate("frmMain", "Project Explorer"))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabProject), _translate("frmMain", "Project"))
        self.lblMapSubcatchments.setText(_translate("frmMain", "Subcatchments"))
        self.lblMapNodes.setText(_translate("frmMain", "Nodes"))
        self.lblMapLinks.setText(_translate("frmMain", "Links"))
        self.chkDisplayFlowDir.setText(_translate("frmMain", "Show Flow Direction"))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabMap), _translate("frmMain", "Map"))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabGIS), _translate("frmMain", "Layers"))
        self.dockw_more.setWindowTitle(_translate("frmMain", "Object Explorer"))
        self.time_widget.setWindowTitle(_translate("frmMain", "Time"))
        self.labelStartTime.setText(_translate("frmMain", "not set"))
        self.labelEndTime.setText(_translate("frmMain", "not set"))
        self.lblDate.setText(_translate("frmMain", "Date"))
        self.lblAnimateTime.setText(_translate("frmMain", "Time"))
        self.lblETime.setText(_translate("frmMain", "Elapsed"))
        self.actionStdNewProject.setText(_translate("frmMain", "New"))
        self.actionStdNewProject.setToolTip(_translate("frmMain", "Start a new project"))
        self.actionMapSelectObj.setText(_translate("frmMain", "Select an object"))
        self.actionMapSelectObj.setToolTip(_translate("frmMain", "Select an object from a map"))
        self.actionObjAddGage.setText(_translate("frmMain", "Add Gage"))
        self.actionObjAddGage.setToolTip(_translate("frmMain", "Add a rain gage"))
        self.actionScriptEditor.setText(_translate("frmMain", "Script Editor"))
        self.actionScriptEditor.setToolTip(_translate("frmMain", "ScriptEditor"))
        self.actionExec.setText(_translate("frmMain", "exec"))
        self.actionAdd_Vector.setText(_translate("frmMain", "Add Vector"))
        self.actionAdd_Vector.setToolTip(_translate("frmMain", "Add a vector layer"))
        self.actionAdd_Raster.setText(_translate("frmMain", "Add Raster"))
        self.actionAdd_Raster.setToolTip(_translate("frmMain", "Add a raster layer"))
        self.actionPan.setText(_translate("frmMain", "Pan"))
        self.actionPan.setToolTip(_translate("frmMain", "Pan"))
        self.actionShow_coordinates.setText(_translate("frmMain", "show coordinates"))
        self.actionZoom_in.setText(_translate("frmMain", "zoom in"))
        self.actionZoom_in.setToolTip(_translate("frmMain", "zoom in"))
        self.actionZoom_out.setText(_translate("frmMain", "zoom out"))
        self.actionZoom_out.setToolTip(_translate("frmMain", "zoom out"))
        self.actionZoom_full.setText(_translate("frmMain", "zoom full"))
        self.actionZoom_full.setToolTip(_translate("frmMain", "zoom full extent"))
        self.actionStdOpenProjMenu.setText(_translate("frmMain", "Open..."))
        self.actionStdOpenProjMenu.setToolTip(_translate("frmMain", "Open existing project"))
        self.actionStdOpenProj.setText(_translate("frmMain", "Open..."))
        self.actionStdOpenProj.setToolTip(_translate("frmMain", "Open existing project"))
        self.actionStdNewProjectMenu.setText(_translate("frmMain", "New"))
        self.actionStdNewProjectMenu.setToolTip(_translate("frmMain", "Create a new project"))
        self.actionAdd_Feature.setText(_translate("frmMain", "Add Feature"))
        self.actionAdd_Feature.setToolTip(_translate("frmMain", "Add Feature"))
        self.actionStdSaveMenu.setText(_translate("frmMain", "Save"))
        self.actionStdSaveMenu.setToolTip(_translate("frmMain", "Save Project"))
        self.actionStdSave.setText(_translate("frmMain", "Save"))
        self.actionStdSave.setToolTip(_translate("frmMain", "Save project"))
        self.actionStdSave_As.setText(_translate("frmMain", "Save As..."))
        self.actionStdSave_As.setToolTip(_translate("frmMain", "Save project as"))
        self.actionStdImportMap.setText(_translate("frmMain", "Map..."))
        self.actionStdImportMap.setToolTip(_translate("frmMain", "Import a map"))
        self.actionStdImportScenario.setText(_translate("frmMain", "Scenario..."))
        self.actionStdImportScenario.setToolTip(_translate("frmMain", "Import a scenario file"))
        self.actionStdImportNetwork.setText(_translate("frmMain", "Network..."))
        self.actionStdImportNetwork.setToolTip(_translate("frmMain", "Import an existing input file"))
        self.actionStdExportMap.setText(_translate("frmMain", "Map..."))
        self.actionStdExportMap.setToolTip(_translate("frmMain", "Export current schematic"))
        self.actionStdPage_Setup.setText(_translate("frmMain", "Page Setup..."))
        self.actionStdPage_Setup.setToolTip(_translate("frmMain", "Page setup"))
        self.actionStdPrint_Preview.setText(_translate("frmMain", "Print Preview"))
        self.actionStdPrint_Preview.setToolTip(_translate("frmMain", "Print preview"))
        self.actionStdPrint.setText(_translate("frmMain", "Print"))
        self.actionStdPrint.setToolTip(_translate("frmMain", "Print"))
        self.actionStdExit.setText(_translate("frmMain", "Exit"))
        self.actionStdExit.setToolTip(_translate("frmMain", "Quit program"))
        self.actionStdCopy_To.setText(_translate("frmMain", "Copy To..."))
        self.actionStdCopy_To.setToolTip(_translate("frmMain", "Copy map at current extent"))
        self.actionStdSelect_Object.setText(_translate("frmMain", "Select Object"))
        self.actionStdSelect_Object.setToolTip(_translate("frmMain", "Select object"))
        self.actionStdSelect_Vertex.setText(_translate("frmMain", "Select Vertex"))
        self.actionStdSelect_Vertex.setToolTip(_translate("frmMain", "Select vertex of object geometry"))
        self.actionStdSelect_Region.setText(_translate("frmMain", "Select Region"))
        self.actionStdSelect_Region.setToolTip(_translate("frmMain", "Select a region on the map"))
        self.actionStdSelect_All.setText(_translate("frmMain", "Select All"))
        self.actionStdSelect_All.setToolTip(_translate("frmMain", "Select all objects on the map"))
        self.actionStdGroup_Edit.setText(_translate("frmMain", "Group Edit..."))
        self.actionStdGroup_Edit.setToolTip(_translate("frmMain", "Edit a selected group of objects"))
        self.actionStdProjSummary.setText(_translate("frmMain", "Summary..."))
        self.actionStdProjSummary.setToolTip(_translate("frmMain", "Project summary"))
        self.actionStdProjDefault.setText(_translate("frmMain", "Defaults..."))
        self.actionStdProjDefault.setToolTip(_translate("frmMain", "Project defaults"))
        self.actionStdProjCalibration_Data.setText(_translate("frmMain", "Calibration Data..."))
        self.actionStdProjCalibration_Data.setToolTip(_translate("frmMain", "Set project calibration data"))
        self.actionStdProjSimulation_Options.setText(_translate("frmMain", "Simulation Options..."))
        self.actionStdProjSimulation_Options.setToolTip(_translate("frmMain", "Set Simulation Options"))
        self.actionRun_SimulationMenu.setText(_translate("frmMain", "Run Simulation"))
        self.actionRun_SimulationMenu.setToolTip(_translate("frmMain", "Start running simulation"))
        self.actionStdRun_Simulation.setText(_translate("frmMain", "Run Simulation"))
        self.actionStdRun_Simulation.setToolTip(_translate("frmMain", "Run Simulation"))
        self.actionStdProjDetails.setText(_translate("frmMain", "Details..."))
        self.actionStdProjDetails.setToolTip(_translate("frmMain", "Show properties"))
        self.actionSave_Map_As_Image.setText(_translate("frmMain", "Save Map As Image..."))
        self.actionObjAddSub.setText(_translate("frmMain", "ObjAddSub"))
        self.actionObjAddSub.setToolTip(_translate("frmMain", "Add a subcatchment"))
        self.actionObjAddJunc.setText(_translate("frmMain", "ObjAddJunc"))
        self.actionObjAddJunc.setToolTip(_translate("frmMain", "Add a junction node"))
        self.actionObjAddOutfall.setText(_translate("frmMain", "ObjAddOutfall"))
        self.actionObjAddOutfall.setToolTip(_translate("frmMain", "Add an outfall node"))
        self.actionObjAddDivider.setText(_translate("frmMain", "ObjAddDivider"))
        self.actionObjAddDivider.setToolTip(_translate("frmMain", "Add a flow divider node"))
        self.actionObjAddStorage.setText(_translate("frmMain", "ObjAddStorage"))
        self.actionObjAddStorage.setToolTip(_translate("frmMain", "Add a storage node"))
        self.actionObjAddConduit.setText(_translate("frmMain", "ObjAddConduit"))
        self.actionObjAddConduit.setToolTip(_translate("frmMain", "Add a conduit link"))
        self.actionObjAddPump.setText(_translate("frmMain", "ObjAddPump"))
        self.actionObjAddPump.setToolTip(_translate("frmMain", "Add a pump link"))
        self.actionObjAddOrifice.setText(_translate("frmMain", "ObjAddOrifice"))
        self.actionObjAddOrifice.setToolTip(_translate("frmMain", "Add an orifice link"))
        self.actionObjAddWeir.setText(_translate("frmMain", "ObjAddWeir"))
        self.actionObjAddWeir.setToolTip(_translate("frmMain", "Add a weir link"))
        self.actionObjAddOutlet.setText(_translate("frmMain", "ObjAddOutlet"))
        self.actionObjAddOutlet.setToolTip(_translate("frmMain", "Add an outlet link"))
        self.actionObjAddLabel.setText(_translate("frmMain", "ObjAddLabel"))
        self.actionObjAddLabel.setToolTip(_translate("frmMain", "Add a map label"))
        self.actionObjAddTank.setText(_translate("frmMain", "ObjAddTank"))
        self.actionObjAddTank.setToolTip(_translate("frmMain", "Add a tank node"))
        self.actionObjAddValve.setText(_translate("frmMain", "ObjAddValve"))
        self.actionObjAddValve.setToolTip(_translate("frmMain", "Add a valve link"))
        self.actionMapSelectRegion.setText(_translate("frmMain", "MapSelectRegion"))
        self.actionMapSelectRegion.setToolTip(_translate("frmMain", "Select region"))
        self.actionMapFindObj.setText(_translate("frmMain", "MapFindObj"))
        self.actionMapFindObj.setToolTip(_translate("frmMain", "Find an object on map"))
        self.actionMapQuery.setText(_translate("frmMain", "MapQuery"))
        self.actionMapQuery.setToolTip(_translate("frmMain", "Find object via query"))
        self.actionProjPlotProfile.setText(_translate("frmMain", "ProjPlotProfile"))
        self.actionProjPlotProfile.setToolTip(_translate("frmMain", "Plot profile"))
        self.actionProjPlotTimeseries.setText(_translate("frmMain", "ProjPlotTimeseries"))
        self.actionProjPlotTimeseries.setToolTip(_translate("frmMain", "Plot time series"))
        self.actionProjPlotScatter.setText(_translate("frmMain", "ProjPlotScatter"))
        self.actionProjPlotScatter.setToolTip(_translate("frmMain", "Scatter plot"))
        self.actionProjTableTimeseries.setText(_translate("frmMain", "ProjTableTimeseries"))
        self.actionProjTableTimeseries.setToolTip(_translate("frmMain", "Create time series table"))
        self.actionProjTableStatistics.setText(_translate("frmMain", "ProjTableStatistics"))
        self.actionProjTableStatistics.setToolTip(_translate("frmMain", "Create statistic report"))
        self.actionMapOption.setText(_translate("frmMain", "MapOption"))
        self.actionMapOption.setToolTip(_translate("frmMain", "Map options"))
        self.actionProjStatus.setText(_translate("frmMain", "ProjStatus"))
        self.actionProjStatus.setToolTip(_translate("frmMain", "Project status report"))
        self.actionMapMeasure.setText(_translate("frmMain", "MapMeasure"))
        self.actionMapMeasure.setToolTip(_translate("frmMain", "Measure distance or area"))
        self.actionMapSelectVertices.setText(_translate("frmMain", "MapSelectVertices"))
        self.actionMapSelectVertices.setToolTip(_translate("frmMain", "Edit vertex"))
        self.actionStdEditObject.setText(_translate("frmMain", "Edit Object..."))
        self.actionStdDeleteObject.setText(_translate("frmMain", "Delete Object"))
        self.actionStdMapDimensions.setText(_translate("frmMain", "Dimensions..."))
        self.actionLoad.setText(_translate("frmMain", "Load"))
        self.actionStdMapBackLoad.setText(_translate("frmMain", "Load..."))
        self.actionStdMapBackUnload.setText(_translate("frmMain", "Unload"))
        self.actionStdMapBackAlign.setText(_translate("frmMain", "Align"))
        self.actionStdMapBackResize.setText(_translate("frmMain", "Resize..."))
        self.actionStdMapBackWatermark.setText(_translate("frmMain", "Watermark"))
        self.actionStdMapPan.setText(_translate("frmMain", "Pan"))
        self.actionStdMapZoomIn.setText(_translate("frmMain", "Zoom In"))
        self.actionStdMapZoomOut.setText(_translate("frmMain", "Zoom Out"))
        self.actionStdMapFullExtent.setText(_translate("frmMain", "Full Extent"))
        self.actionStdMapQuery.setText(_translate("frmMain", "Query..."))
        self.actionStdMapOverview.setText(_translate("frmMain", "Overview"))
        self.actionStdMapOptions.setText(_translate("frmMain", "Map Options..."))
        self.actionStdProgPrefer.setText(_translate("frmMain", "Program Preferences..."))
        self.actionStdConfigTools.setText(_translate("frmMain", "Configure Tools"))
        self.actionStdWinCascade.setText(_translate("frmMain", "Cascade"))
        self.actionStdWinTile.setText(_translate("frmMain", "Tile"))
        self.actionStdWinCloseAll.setText(_translate("frmMain", "Close All"))
        self.actionStdMapToggle.setText(_translate("frmMain", "Study Area Map"))
        self.actionStdMapShowRainGages.setText(_translate("frmMain", "Rain Gages"))
        self.actionStdMapShowSubcatchments.setText(_translate("frmMain", "Subcatchments"))
        self.actionStdMapShowNodes.setText(_translate("frmMain", "Nodes"))
        self.actionStdMapShowLinks.setText(_translate("frmMain", "Links"))
        self.actionStdMapShowLabels.setText(_translate("frmMain", "Labels"))
        self.actionStdMapShowBackdrop.setText(_translate("frmMain", "Backdrop"))
        self.actionStdLegSubcatchment.setText(_translate("frmMain", "Subcatchment"))
        self.actionStdLegNode.setText(_translate("frmMain", "Node"))
        self.actionStdLegLink.setText(_translate("frmMain", "Link"))
        self.actionStdLegTime.setText(_translate("frmMain", "Time"))
        self.actionStdLegModSubcatchment.setText(_translate("frmMain", "Subcatchment"))
        self.actionStdLegModNode.setText(_translate("frmMain", "Node"))
        self.actionStdLegModLink.setText(_translate("frmMain", "Link"))
        self.actionToolbarShowStandard.setText(_translate("frmMain", "Standard"))
        self.actionToolbarShowMap.setText(_translate("frmMain", "Map"))
        self.actionToolbarShowObject.setText(_translate("frmMain", "Object"))
        self.actionEditScript.setText(_translate("frmMain", "Script Editor"))
        self.actionRun_Script.setText(_translate("frmMain", "Run Script"))
        self.actionOpen.setText(_translate("frmMain", "File0"))
        self.actionStdMapFind.setText(_translate("frmMain", "Find..."))
        self.actionStdLegends.setText(_translate("frmMain", "Legends"))
        self.actionStdMapPanSelection.setText(_translate("frmMain", "Pan to Selection"))
        self.actionStdMapPanSelection.setToolTip(_translate("frmMain", "Pan Map to Selected Object"))

import ui.swmm_rc
