# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMainSWMMDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMainSWMM(object):
    def setupUi(self, frmMainSWMM):
        frmMainSWMM.setObjectName(_fromUtf8("frmMainSWMM"))
        frmMainSWMM.resize(792, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/epa_swmm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMainSWMM.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(frmMainSWMM)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.map = QtGui.QMdiArea(self.centralwidget)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName(_fromUtf8("map"))
        self.verticalLayout.addWidget(self.map)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbAutoLength = QtGui.QComboBox(self.centralwidget)
        self.cbAutoLength.setObjectName(_fromUtf8("cbAutoLength"))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbAutoLength)
        self.cbOffset = QtGui.QComboBox(self.centralwidget)
        self.cbOffset.setObjectName(_fromUtf8("cbOffset"))
        self.cbOffset.addItem(_fromUtf8(""))
        self.cbOffset.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbOffset)
        self.cbFlowUnits = QtGui.QComboBox(self.centralwidget)
        self.cbFlowUnits.setObjectName(_fromUtf8("cbFlowUnits"))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbFlowUnits)
        self.btnZoom100 = QtGui.QPushButton(self.centralwidget)
        self.btnZoom100.setObjectName(_fromUtf8("btnZoom100"))
        self.horizontalLayout.addWidget(self.btnZoom100)
        self.btnCoord = QtGui.QPushButton(self.centralwidget)
        self.btnCoord.setObjectName(_fromUtf8("btnCoord"))
        self.horizontalLayout.addWidget(self.btnCoord)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        frmMainSWMM.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(frmMainSWMM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuScripting = QtGui.QMenu(self.menuPlugins)
        self.menuScripting.setObjectName(_fromUtf8("menuScripting"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        frmMainSWMM.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmMainSWMM)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frmMainSWMM.setStatusBar(self.statusbar)
        self.toolBar_Object = QtGui.QToolBar(frmMainSWMM)
        self.toolBar_Object.setObjectName(_fromUtf8("toolBar_Object"))
        frmMainSWMM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Object)
        self.toolBar_Map = QtGui.QToolBar(frmMainSWMM)
        self.toolBar_Map.setObjectName(_fromUtf8("toolBar_Map"))
        frmMainSWMM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Map)
        frmMainSWMM.insertToolBarBreak(self.toolBar_Map)
        self.toolBar_Standard = QtGui.QToolBar(frmMainSWMM)
        self.toolBar_Standard.setIconSize(QtCore.QSize(23, 22))
        self.toolBar_Standard.setObjectName(_fromUtf8("toolBar_Standard"))
        frmMainSWMM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Standard)
        frmMainSWMM.insertToolBarBreak(self.toolBar_Standard)
        self.dockw_tab = QtGui.QDockWidget(frmMainSWMM)
        self.dockw_tab.setObjectName(_fromUtf8("dockw_tab"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabProjMap = QtGui.QTabWidget(self.dockWidgetContents_6)
        self.tabProjMap.setObjectName(_fromUtf8("tabProjMap"))
        self.tabProject = QtGui.QWidget()
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.tabProjMap.addTab(self.tabProject, _fromUtf8(""))
        self.tabMap = QtGui.QWidget()
        self.tabMap.setObjectName(_fromUtf8("tabMap"))
        self.tabProjMap.addTab(self.tabMap, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabProjMap, 0, 0, 1, 1)
        self.dockw_tab.setWidget(self.dockWidgetContents_6)
        frmMainSWMM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_tab)
        self.dockw_more = QtGui.QDockWidget(frmMainSWMM)
        self.dockw_more.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dockw_more.setObjectName(_fromUtf8("dockw_more"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.dockw_more.setWidget(self.dockWidgetContents_7)
        frmMainSWMM.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_more)
        self.actionStdNewProject = QtGui.QAction(frmMainSWMM)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_new.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdNewProject.setIcon(icon1)
        self.actionStdNewProject.setObjectName(_fromUtf8("actionStdNewProject"))
        self.actionMapSelectObj = QtGui.QAction(frmMainSWMM)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_pointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectObj.setIcon(icon2)
        self.actionMapSelectObj.setObjectName(_fromUtf8("actionMapSelectObj"))
        self.actionObjAddGage = QtGui.QAction(frmMainSWMM)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_gage.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddGage.setIcon(icon3)
        self.actionObjAddGage.setObjectName(_fromUtf8("actionObjAddGage"))
        self.actionIPython = QtGui.QAction(frmMainSWMM)
        self.actionIPython.setObjectName(_fromUtf8("actionIPython"))
        self.actionExec = QtGui.QAction(frmMainSWMM)
        self.actionExec.setObjectName(_fromUtf8("actionExec"))
        self.menuScripting.addAction(self.actionIPython)
        self.menuScripting.addAction(self.actionExec)
        self.menuPlugins.addAction(self.menuScripting.menuAction())
        self.menuPlugins.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_Object.addAction(self.actionObjAddGage)
        self.toolBar_Map.addAction(self.actionMapSelectObj)
        self.toolBar_Standard.addAction(self.actionStdNewProject)

        self.retranslateUi(frmMainSWMM)
        self.tabProjMap.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(frmMainSWMM)

    def retranslateUi(self, frmMainSWMM):
        frmMainSWMM.setWindowTitle(_translate("frmMainSWMM", "SWMM 5.1", None))
        self.cbAutoLength.setItemText(0, _translate("frmMainSWMM", "Auto-Length: Off", None))
        self.cbAutoLength.setItemText(1, _translate("frmMainSWMM", "Auto-Length: On", None))
        self.cbOffset.setItemText(0, _translate("frmMainSWMM", "Offsets: Elevation", None))
        self.cbOffset.setItemText(1, _translate("frmMainSWMM", "Offsets: Depth", None))
        self.cbFlowUnits.setItemText(0, _translate("frmMainSWMM", "Flow Units: CFS", None))
        self.cbFlowUnits.setItemText(1, _translate("frmMainSWMM", "Flow Units: GPM", None))
        self.cbFlowUnits.setItemText(2, _translate("frmMainSWMM", "Flow Units: MGD", None))
        self.cbFlowUnits.setItemText(3, _translate("frmMainSWMM", "Flow Units: CMS", None))
        self.cbFlowUnits.setItemText(4, _translate("frmMainSWMM", "Flow Units:  LPS", None))
        self.cbFlowUnits.setItemText(5, _translate("frmMainSWMM", "Flow Units: MLD", None))
        self.btnZoom100.setText(_translate("frmMainSWMM", "Zoom Level: 100%", None))
        self.btnCoord.setText(_translate("frmMainSWMM", "x,y", None))
        self.menuFile.setTitle(_translate("frmMainSWMM", "File", None))
        self.menuEdit.setTitle(_translate("frmMainSWMM", "Edit", None))
        self.menuView.setTitle(_translate("frmMainSWMM", "View", None))
        self.menuProject.setTitle(_translate("frmMainSWMM", "Project", None))
        self.menuReport.setTitle(_translate("frmMainSWMM", "Report", None))
        self.menuTools.setTitle(_translate("frmMainSWMM", "Tools", None))
        self.menuWindow.setTitle(_translate("frmMainSWMM", "Window", None))
        self.menuPlugins.setTitle(_translate("frmMainSWMM", "Plugins", None))
        self.menuScripting.setTitle(_translate("frmMainSWMM", "Scripting", None))
        self.menuHelp.setTitle(_translate("frmMainSWMM", "Help", None))
        self.toolBar_Object.setWindowTitle(_translate("frmMainSWMM", "toolBar", None))
        self.toolBar_Map.setWindowTitle(_translate("frmMainSWMM", "toolBar_2", None))
        self.toolBar_Standard.setWindowTitle(_translate("frmMainSWMM", "toolBar_3", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabProject), _translate("frmMainSWMM", "Project", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabMap), _translate("frmMainSWMM", "Map", None))
        self.dockw_more.setWindowTitle(_translate("frmMainSWMM", "Titles/Notes", None))
        self.actionStdNewProject.setText(_translate("frmMainSWMM", "New Project", None))
        self.actionStdNewProject.setToolTip(_translate("frmMainSWMM", "Start a new project", None))
        self.actionMapSelectObj.setText(_translate("frmMainSWMM", "Select an object", None))
        self.actionMapSelectObj.setToolTip(_translate("frmMainSWMM", "Select an object from a map", None))
        self.actionObjAddGage.setText(_translate("frmMainSWMM", "Add Gage", None))
        self.actionObjAddGage.setToolTip(_translate("frmMainSWMM", "Add a rain gage", None))
        self.actionIPython.setText(_translate("frmMainSWMM", "IPython", None))
        self.actionExec.setText(_translate("frmMainSWMM", "exec", None))

import swmm_rc
