# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMainDesigner.ui'
#
# Created: Mon Feb 01 16:49:06 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName(_fromUtf8("frmMain"))
        frmMain.resize(792, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../icons/epa_swmm.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmMain.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(frmMain)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.map = QtGui.QMdiArea(self.centralwidget)
        self.map.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.map.setObjectName(_fromUtf8("map"))
        self.verticalLayout.addWidget(self.map)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbAutoLength = QtGui.QComboBox(self.centralwidget)
        self.cbAutoLength.setObjectName(_fromUtf8("cbAutoLength"))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.cbAutoLength.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbAutoLength)
        self.cbOffset = QtGui.QComboBox(self.centralwidget)
        self.cbOffset.setObjectName(_fromUtf8("cbOffset"))
        self.cbOffset.addItem(_fromUtf8(""))
        self.cbOffset.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbOffset)
        self.cbFlowUnits = QtGui.QComboBox(self.centralwidget)
        self.cbFlowUnits.setObjectName(_fromUtf8("cbFlowUnits"))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.cbFlowUnits.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.cbFlowUnits)
        self.btnZoom100 = QtGui.QPushButton(self.centralwidget)
        self.btnZoom100.setObjectName(_fromUtf8("btnZoom100"))
        self.horizontalLayout.addWidget(self.btnZoom100)
        self.btnCoord = QtGui.QPushButton(self.centralwidget)
        self.btnCoord.setObjectName(_fromUtf8("btnCoord"))
        self.horizontalLayout.addWidget(self.btnCoord)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        frmMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(frmMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuProject = QtGui.QMenu(self.menubar)
        self.menuProject.setObjectName(_fromUtf8("menuProject"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        self.menuPlugins = QtGui.QMenu(self.menubar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuScripting = QtGui.QMenu(self.menuPlugins)
        self.menuScripting.setObjectName(_fromUtf8("menuScripting"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        frmMain.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmMain)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frmMain.setStatusBar(self.statusbar)
        self.toolBar_Object = QtGui.QToolBar(frmMain)
        self.toolBar_Object.setObjectName(_fromUtf8("toolBar_Object"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Object)
        self.toolBar_Map = QtGui.QToolBar(frmMain)
        self.toolBar_Map.setObjectName(_fromUtf8("toolBar_Map"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Map)
        frmMain.insertToolBarBreak(self.toolBar_Map)
        self.toolBar_Standard = QtGui.QToolBar(frmMain)
        self.toolBar_Standard.setIconSize(QtCore.QSize(23, 22))
        self.toolBar_Standard.setObjectName(_fromUtf8("toolBar_Standard"))
        frmMain.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_Standard)
        frmMain.insertToolBarBreak(self.toolBar_Standard)
        self.dockw_tab = QtGui.QDockWidget(frmMain)
        self.dockw_tab.setObjectName(_fromUtf8("dockw_tab"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabProjMap = QtGui.QTabWidget(self.dockWidgetContents_6)
        self.tabProjMap.setObjectName(_fromUtf8("tabProjMap"))
        self.tabProject = QtGui.QWidget()
        self.tabProject.setObjectName(_fromUtf8("tabProject"))
        self.tabProjMap.addTab(self.tabProject, _fromUtf8(""))
        self.tabMap = QtGui.QWidget()
        self.tabMap.setObjectName(_fromUtf8("tabMap"))
        self.tabProjMap.addTab(self.tabMap, _fromUtf8(""))
        self.tabGIS = QtGui.QWidget()
        self.tabGIS.setObjectName(_fromUtf8("tabGIS"))
        self.tabProjMap.addTab(self.tabGIS, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabProjMap, 0, 0, 1, 1)
        self.dockw_tab.setWidget(self.dockWidgetContents_6)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_tab)
        self.dockw_more = QtGui.QDockWidget(frmMain)
        self.dockw_more.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dockw_more.setObjectName(_fromUtf8("dockw_more"))
        self.dockWidgetContents_7 = QtGui.QWidget()
        self.dockWidgetContents_7.setObjectName(_fromUtf8("dockWidgetContents_7"))
        self.dockw_more.setWidget(self.dockWidgetContents_7)
        frmMain.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockw_more)
        self.actionStdNewProject = QtGui.QAction(frmMain)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_new.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdNewProject.setIcon(icon1)
        self.actionStdNewProject.setObjectName(_fromUtf8("actionStdNewProject"))
        self.actionMapSelectObj = QtGui.QAction(frmMain)
        self.actionMapSelectObj.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_pointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionMapSelectObj.setIcon(icon2)
        self.actionMapSelectObj.setObjectName(_fromUtf8("actionMapSelectObj"))
        self.actionObjAddGage = QtGui.QAction(frmMain)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/obj_gage.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionObjAddGage.setIcon(icon3)
        self.actionObjAddGage.setObjectName(_fromUtf8("actionObjAddGage"))
        self.actionIPython = QtGui.QAction(frmMain)
        self.actionIPython.setObjectName(_fromUtf8("actionIPython"))
        self.actionExec = QtGui.QAction(frmMain)
        self.actionExec.setObjectName(_fromUtf8("actionExec"))
        self.actionAdd_Vector = QtGui.QAction(frmMain)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_add_v.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Vector.setIcon(icon4)
        self.actionAdd_Vector.setObjectName(_fromUtf8("actionAdd_Vector"))
        self.actionAdd_Raster = QtGui.QAction(frmMain)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_add_r.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAdd_Raster.setIcon(icon5)
        self.actionAdd_Raster.setObjectName(_fromUtf8("actionAdd_Raster"))
        self.actionPan = QtGui.QAction(frmMain)
        self.actionPan.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_pan.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPan.setIcon(icon6)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionShow_coordinates = QtGui.QAction(frmMain)
        self.actionShow_coordinates.setObjectName(_fromUtf8("actionShow_coordinates"))
        self.actionZoom_in = QtGui.QAction(frmMain)
        self.actionZoom_in.setCheckable(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomin.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_in.setIcon(icon7)
        self.actionZoom_in.setObjectName(_fromUtf8("actionZoom_in"))
        self.actionZoom_out = QtGui.QAction(frmMain)
        self.actionZoom_out.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomout.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_out.setIcon(icon8)
        self.actionZoom_out.setObjectName(_fromUtf8("actionZoom_out"))
        self.actionZoom_full = QtGui.QAction(frmMain)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_zoomfull.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionZoom_full.setIcon(icon9)
        self.actionZoom_full.setObjectName(_fromUtf8("actionZoom_full"))
        self.actionStdOpenProjMenu = QtGui.QAction(frmMain)
        self.actionStdOpenProjMenu.setObjectName(_fromUtf8("actionStdOpenProjMenu"))
        self.actionStdOpenProj = QtGui.QAction(frmMain)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/std_project_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionStdOpenProj.setIcon(icon10)
        self.actionStdOpenProj.setObjectName(_fromUtf8("actionStdOpenProj"))
        self.actionStdNewProjectMenu = QtGui.QAction(frmMain)
        self.actionStdNewProjectMenu.setObjectName(_fromUtf8("actionStdNewProjectMenu"))
        self.actionAdd_Feature = QtGui.QAction(frmMain)
        self.actionAdd_Feature.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_edit_addfeature.png")), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/map_qgis_edit_addfeature0.png")), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.actionAdd_Feature.setIcon(icon11)
        self.actionAdd_Feature.setObjectName(_fromUtf8("actionAdd_Feature"))
        self.menuFile.addAction(self.actionStdNewProjectMenu)
        self.menuFile.addAction(self.actionStdOpenProjMenu)
        self.menuScripting.addAction(self.actionIPython)
        self.menuScripting.addAction(self.actionExec)
        self.menuPlugins.addAction(self.menuScripting.menuAction())
        self.menuPlugins.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuPlugins.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar_Object.addAction(self.actionObjAddGage)
        self.toolBar_Map.addAction(self.actionAdd_Vector)
        self.toolBar_Map.addAction(self.actionAdd_Raster)
        self.toolBar_Map.addAction(self.actionZoom_in)
        self.toolBar_Map.addAction(self.actionZoom_out)
        self.toolBar_Map.addAction(self.actionZoom_full)
        self.toolBar_Map.addAction(self.actionPan)
        self.toolBar_Map.addAction(self.actionAdd_Feature)
        self.toolBar_Map.addAction(self.actionMapSelectObj)
        self.toolBar_Standard.addAction(self.actionStdNewProject)
        self.toolBar_Standard.addAction(self.actionStdOpenProj)

        self.retranslateUi(frmMain)
        self.tabProjMap.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        frmMain.setWindowTitle(_translate("frmMain", "SWMM 5.1", None))
        self.cbAutoLength.setItemText(0, _translate("frmMain", "Auto-Length: Off", None))
        self.cbAutoLength.setItemText(1, _translate("frmMain", "Auto-Length: On", None))
        self.cbOffset.setItemText(0, _translate("frmMain", "Offsets: Elevation", None))
        self.cbOffset.setItemText(1, _translate("frmMain", "Offsets: Depth", None))
        self.cbFlowUnits.setItemText(0, _translate("frmMain", "Flow Units: CFS", None))
        self.cbFlowUnits.setItemText(1, _translate("frmMain", "Flow Units: GPM", None))
        self.cbFlowUnits.setItemText(2, _translate("frmMain", "Flow Units: MGD", None))
        self.cbFlowUnits.setItemText(3, _translate("frmMain", "Flow Units: CMS", None))
        self.cbFlowUnits.setItemText(4, _translate("frmMain", "Flow Units:  LPS", None))
        self.cbFlowUnits.setItemText(5, _translate("frmMain", "Flow Units: MLD", None))
        self.btnZoom100.setText(_translate("frmMain", "Zoom Level: 100%", None))
        self.btnCoord.setText(_translate("frmMain", "x,y", None))
        self.menuFile.setTitle(_translate("frmMain", "File", None))
        self.menuEdit.setTitle(_translate("frmMain", "Edit", None))
        self.menuView.setTitle(_translate("frmMain", "View", None))
        self.menuProject.setTitle(_translate("frmMain", "Project", None))
        self.menuReport.setTitle(_translate("frmMain", "Report", None))
        self.menuTools.setTitle(_translate("frmMain", "Tools", None))
        self.menuWindow.setTitle(_translate("frmMain", "Window", None))
        self.menuPlugins.setTitle(_translate("frmMain", "Plugins", None))
        self.menuScripting.setTitle(_translate("frmMain", "Scripting", None))
        self.menuHelp.setTitle(_translate("frmMain", "Help", None))
        self.toolBar_Object.setWindowTitle(_translate("frmMain", "toolBar", None))
        self.toolBar_Map.setWindowTitle(_translate("frmMain", "toolBar_2", None))
        self.toolBar_Standard.setWindowTitle(_translate("frmMain", "toolBar_3", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabProject), _translate("frmMain", "Project", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabMap), _translate("frmMain", "Map", None))
        self.tabProjMap.setTabText(self.tabProjMap.indexOf(self.tabGIS), _translate("frmMain", "GIS", None))
        self.dockw_more.setWindowTitle(_translate("frmMain", "Titles/Notes", None))
        self.actionStdNewProject.setText(_translate("frmMain", "New Project", None))
        self.actionStdNewProject.setToolTip(_translate("frmMain", "Start a new project", None))
        self.actionMapSelectObj.setText(_translate("frmMain", "Select an object", None))
        self.actionMapSelectObj.setToolTip(_translate("frmMain", "Select an object from a map", None))
        self.actionObjAddGage.setText(_translate("frmMain", "Add Gage", None))
        self.actionObjAddGage.setToolTip(_translate("frmMain", "Add a rain gage", None))
        self.actionIPython.setText(_translate("frmMain", "IPython", None))
        self.actionExec.setText(_translate("frmMain", "exec", None))
        self.actionAdd_Vector.setText(_translate("frmMain", "Add Vector", None))
        self.actionAdd_Vector.setToolTip(_translate("frmMain", "Add a vector layer", None))
        self.actionAdd_Raster.setText(_translate("frmMain", "Add Raster", None))
        self.actionAdd_Raster.setToolTip(_translate("frmMain", "Add a raster layer", None))
        self.actionPan.setText(_translate("frmMain", "Pan", None))
        self.actionPan.setToolTip(_translate("frmMain", "Pan", None))
        self.actionShow_coordinates.setText(_translate("frmMain", "show coordinates", None))
        self.actionZoom_in.setText(_translate("frmMain", "zoom in", None))
        self.actionZoom_in.setToolTip(_translate("frmMain", "zoom in", None))
        self.actionZoom_out.setText(_translate("frmMain", "zoom out", None))
        self.actionZoom_out.setToolTip(_translate("frmMain", "zoom out", None))
        self.actionZoom_full.setText(_translate("frmMain", "zoom full", None))
        self.actionZoom_full.setToolTip(_translate("frmMain", "zoom full extent", None))
        self.actionStdOpenProjMenu.setText(_translate("frmMain", "Open...", None))
        self.actionStdOpenProjMenu.setToolTip(_translate("frmMain", "Open existing project", None))
        self.actionStdOpenProj.setText(_translate("frmMain", "Open...", None))
        self.actionStdOpenProj.setToolTip(_translate("frmMain", "Open existing project", None))
        self.actionStdNewProjectMenu.setText(_translate("frmMain", "New Project", None))
        self.actionStdNewProjectMenu.setToolTip(_translate("frmMain", "Create a new project", None))
        self.actionAdd_Feature.setText(_translate("frmMain", "Add Feature", None))
        self.actionAdd_Feature.setToolTip(_translate("frmMain", "Add Feature", None))

import swmm_rc
