# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\frmPreferencesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPreferences(object):
    def setupUi(self, frmPreferences):
        frmPreferences.setObjectName("frmPreferences")
        frmPreferences.resize(359, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmPreferences.sizePolicy().hasHeightForWidth())
        frmPreferences.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmPreferences.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmPreferences)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraTop)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabPrecision = QtWidgets.QTabWidget(self.fraTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabPrecision.sizePolicy().hasHeightForWidth())
        self.tabPrecision.setSizePolicy(sizePolicy)
        self.tabPrecision.setObjectName("tabPrecision")
        self.General = QtWidgets.QWidget()
        self.General.setObjectName("General")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.General)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbxGeneral1 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral1.sizePolicy().hasHeightForWidth())
        self.cbxGeneral1.setSizePolicy(sizePolicy)
        self.cbxGeneral1.setObjectName("cbxGeneral1")
        self.verticalLayout_2.addWidget(self.cbxGeneral1)
        self.cbxGeneral2 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral2.sizePolicy().hasHeightForWidth())
        self.cbxGeneral2.setSizePolicy(sizePolicy)
        self.cbxGeneral2.setObjectName("cbxGeneral2")
        self.verticalLayout_2.addWidget(self.cbxGeneral2)
        self.cbxGeneral3 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral3.sizePolicy().hasHeightForWidth())
        self.cbxGeneral3.setSizePolicy(sizePolicy)
        self.cbxGeneral3.setObjectName("cbxGeneral3")
        self.verticalLayout_2.addWidget(self.cbxGeneral3)
        self.cbxGeneral4 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral4.sizePolicy().hasHeightForWidth())
        self.cbxGeneral4.setSizePolicy(sizePolicy)
        self.cbxGeneral4.setObjectName("cbxGeneral4")
        self.verticalLayout_2.addWidget(self.cbxGeneral4)
        self.cbxGeneral5 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral5.sizePolicy().hasHeightForWidth())
        self.cbxGeneral5.setSizePolicy(sizePolicy)
        self.cbxGeneral5.setObjectName("cbxGeneral5")
        self.verticalLayout_2.addWidget(self.cbxGeneral5)
        self.cbxGeneral6 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral6.sizePolicy().hasHeightForWidth())
        self.cbxGeneral6.setSizePolicy(sizePolicy)
        self.cbxGeneral6.setObjectName("cbxGeneral6")
        self.verticalLayout_2.addWidget(self.cbxGeneral6)
        self.cbxGeneral7 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral7.sizePolicy().hasHeightForWidth())
        self.cbxGeneral7.setSizePolicy(sizePolicy)
        self.cbxGeneral7.setObjectName("cbxGeneral7")
        self.verticalLayout_2.addWidget(self.cbxGeneral7)
        self.cbxGeneral8 = QtWidgets.QCheckBox(self.General)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGeneral8.sizePolicy().hasHeightForWidth())
        self.cbxGeneral8.setSizePolicy(sizePolicy)
        self.cbxGeneral8.setObjectName("cbxGeneral8")
        self.verticalLayout_2.addWidget(self.cbxGeneral8)
        self.tabPrecision.addTab(self.General, "")
        self.Numerical = QtWidgets.QWidget()
        self.Numerical.setObjectName("Numerical")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Numerical)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblLink = QtWidgets.QLabel(self.Numerical)
        self.lblLink.setObjectName("lblLink")
        self.gridLayout_3.addWidget(self.lblLink, 5, 0, 1, 1)
        self.cboLink = QtWidgets.QComboBox(self.Numerical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLink.sizePolicy().hasHeightForWidth())
        self.cboLink.setSizePolicy(sizePolicy)
        self.cboLink.setObjectName("cboLink")
        self.gridLayout_3.addWidget(self.cboLink, 6, 0, 1, 1)
        self.cboNode = QtWidgets.QComboBox(self.Numerical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboNode.sizePolicy().hasHeightForWidth())
        self.cboNode.setSizePolicy(sizePolicy)
        self.cboNode.setObjectName("cboNode")
        self.gridLayout_3.addWidget(self.cboNode, 4, 0, 1, 1)
        self.lblNode = QtWidgets.QLabel(self.Numerical)
        self.lblNode.setWordWrap(True)
        self.lblNode.setObjectName("lblNode")
        self.gridLayout_3.addWidget(self.lblNode, 3, 0, 1, 1)
        self.lblSubcatchment = QtWidgets.QLabel(self.Numerical)
        self.lblSubcatchment.setObjectName("lblSubcatchment")
        self.gridLayout_3.addWidget(self.lblSubcatchment, 1, 0, 1, 1)
        self.cboSubcatchment = QtWidgets.QComboBox(self.Numerical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSubcatchment.sizePolicy().hasHeightForWidth())
        self.cboSubcatchment.setSizePolicy(sizePolicy)
        self.cboSubcatchment.setObjectName("cboSubcatchment")
        self.gridLayout_3.addWidget(self.cboSubcatchment, 2, 0, 1, 1)
        self.lblNumber = QtWidgets.QLabel(self.Numerical)
        self.lblNumber.setWordWrap(True)
        self.lblNumber.setObjectName("lblNumber")
        self.gridLayout_3.addWidget(self.lblNumber, 0, 0, 1, 1)
        self.spnSubcatchment = QtWidgets.QSpinBox(self.Numerical)
        self.spnSubcatchment.setMaximum(6)
        self.spnSubcatchment.setProperty("value", 2)
        self.spnSubcatchment.setObjectName("spnSubcatchment")
        self.gridLayout_3.addWidget(self.spnSubcatchment, 2, 1, 1, 1)
        self.spnNode = QtWidgets.QSpinBox(self.Numerical)
        self.spnNode.setMaximum(6)
        self.spnNode.setProperty("value", 2)
        self.spnNode.setObjectName("spnNode")
        self.gridLayout_3.addWidget(self.spnNode, 4, 1, 1, 1)
        self.spnLink = QtWidgets.QSpinBox(self.Numerical)
        self.spnLink.setMaximum(6)
        self.spnLink.setProperty("value", 2)
        self.spnLink.setObjectName("spnLink")
        self.gridLayout_3.addWidget(self.spnLink, 6, 1, 1, 1)
        self.lblDecimal2 = QtWidgets.QLabel(self.Numerical)
        self.lblDecimal2.setObjectName("lblDecimal2")
        self.gridLayout_3.addWidget(self.lblDecimal2, 3, 1, 1, 1)
        self.lblDecimal3 = QtWidgets.QLabel(self.Numerical)
        self.lblDecimal3.setObjectName("lblDecimal3")
        self.gridLayout_3.addWidget(self.lblDecimal3, 5, 1, 1, 1)
        self.lblDecimal1 = QtWidgets.QLabel(self.Numerical)
        self.lblDecimal1.setObjectName("lblDecimal1")
        self.gridLayout_3.addWidget(self.lblDecimal1, 1, 1, 1, 1)
        self.tabPrecision.addTab(self.Numerical, "")
        self.verticalLayout.addWidget(self.tabPrecision)
        self.verticalLayout_3.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmPreferences.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmPreferences)
        self.tabPrecision.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmPreferences)

    def retranslateUi(self, frmPreferences):
        _translate = QtCore.QCoreApplication.translate
        frmPreferences.setWindowTitle(_translate("frmPreferences", "Preferences"))
        self.cbxGeneral1.setText(_translate("frmPreferences", "Blinking Map Highlighter"))
        self.cbxGeneral2.setText(_translate("frmPreferences", "Flyover Map Labeling"))
        self.cbxGeneral3.setText(_translate("frmPreferences", "Confirm Deletions"))
        self.cbxGeneral4.setText(_translate("frmPreferences", "Automatic Backup File"))
        self.cbxGeneral5.setText(_translate("frmPreferences", "Tab Delimited Project File"))
        self.cbxGeneral6.setText(_translate("frmPreferences", "Report Elapsed Time by Default"))
        self.cbxGeneral7.setText(_translate("frmPreferences", "Prompt to Save Results"))
        self.cbxGeneral8.setText(_translate("frmPreferences", "Clear File List"))
        self.tabPrecision.setTabText(self.tabPrecision.indexOf(self.General), _translate("frmPreferences", "General Options"))
        self.lblLink.setText(_translate("frmPreferences", "Link Parameter"))
        self.lblNode.setText(_translate("frmPreferences", "Node Parameter"))
        self.lblSubcatchment.setText(_translate("frmPreferences", "Subcatchment Parameter"))
        self.lblNumber.setText(_translate("frmPreferences", "Select number of decimal places for computed results:"))
        self.lblDecimal2.setText(_translate("frmPreferences", "Decimals"))
        self.lblDecimal3.setText(_translate("frmPreferences", "Decimals"))
        self.lblDecimal1.setText(_translate("frmPreferences", "Decimals"))
        self.tabPrecision.setTabText(self.tabPrecision.indexOf(self.Numerical), _translate("frmPreferences", "Numerical Precision"))
        self.cmdOK.setText(_translate("frmPreferences", "OK"))
        self.cmdCancel.setText(_translate("frmPreferences", "Cancel"))

