# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmRunSimulationDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmRunSimulation(object):
    def setupUi(self, frmRunSimulation):
        frmRunSimulation.setObjectName(_fromUtf8("frmRunSimulation"))
        frmRunSimulation.resize(558, 274)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmRunSimulation.setFont(font)
        self.centralWidget = QtGui.QWidget(frmRunSimulation)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.fraEntire = QtGui.QFrame(self.centralWidget)
        self.fraEntire.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraEntire.setFrameShadow(QtGui.QFrame.Raised)
        self.fraEntire.setObjectName(_fromUtf8("fraEntire"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.fraEntire)
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.fraRunning = QtGui.QFrame(self.fraEntire)
        self.fraRunning.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraRunning.setFrameShadow(QtGui.QFrame.Raised)
        self.fraRunning.setObjectName(_fromUtf8("fraRunning"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fraRunning)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fraComputing = QtGui.QFrame(self.fraRunning)
        self.fraComputing.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraComputing.setFrameShadow(QtGui.QFrame.Raised)
        self.fraComputing.setObjectName(_fromUtf8("fraComputing"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraComputing)
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblIconComputing = QtGui.QLabel(self.fraComputing)
        self.lblIconComputing.setText(_fromUtf8(""))
        self.lblIconComputing.setPixmap(QtGui.QPixmap(_fromUtf8("swmmimages/rain.png")))
        self.lblIconComputing.setObjectName(_fromUtf8("lblIconComputing"))
        self.horizontalLayout_3.addWidget(self.lblIconComputing)
        self.StatusLabel = QtGui.QLabel(self.fraComputing)
        self.StatusLabel.setObjectName(_fromUtf8("StatusLabel"))
        self.horizontalLayout_3.addWidget(self.StatusLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fraComputing)
        self.progressBar = QtGui.QProgressBar(self.fraRunning)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.lblTime = QtGui.QLabel(self.fraRunning)
        self.lblTime.setObjectName(_fromUtf8("lblTime"))
        self.verticalLayout.addWidget(self.lblTime)
        self.fraTime = QtGui.QFrame(self.fraRunning)
        self.fraTime.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraTime.setFrameShadow(QtGui.QFrame.Raised)
        self.fraTime.setObjectName(_fromUtf8("fraTime"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraTime)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblDays = QtGui.QLabel(self.fraTime)
        self.lblDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblDays.setObjectName(_fromUtf8("lblDays"))
        self.horizontalLayout_2.addWidget(self.lblDays)
        self.txtDays = QtGui.QLabel(self.fraTime)
        self.txtDays.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtDays.setObjectName(_fromUtf8("txtDays"))
        self.horizontalLayout_2.addWidget(self.txtDays)
        self.lblHrsMin = QtGui.QLabel(self.fraTime)
        self.lblHrsMin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lblHrsMin.setObjectName(_fromUtf8("lblHrsMin"))
        self.horizontalLayout_2.addWidget(self.lblHrsMin)
        self.txtHrsMin = QtGui.QLabel(self.fraTime)
        self.txtHrsMin.setFrameShape(QtGui.QFrame.StyledPanel)
        self.txtHrsMin.setObjectName(_fromUtf8("txtHrsMin"))
        self.horizontalLayout_2.addWidget(self.txtHrsMin)
        self.verticalLayout.addWidget(self.fraTime)
        self.horizontalLayout_5.addWidget(self.fraRunning)
        self.fraFinished = QtGui.QFrame(self.fraEntire)
        self.fraFinished.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraFinished.setFrameShadow(QtGui.QFrame.Raised)
        self.fraFinished.setObjectName(_fromUtf8("fraFinished"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fraFinished)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraSuccessful = QtGui.QFrame(self.fraFinished)
        self.fraSuccessful.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraSuccessful.setFrameShadow(QtGui.QFrame.Raised)
        self.fraSuccessful.setObjectName(_fromUtf8("fraSuccessful"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fraSuccessful)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblIconSuccessful = QtGui.QLabel(self.fraSuccessful)
        self.lblIconSuccessful.setText(_fromUtf8(""))
        self.lblIconSuccessful.setPixmap(QtGui.QPixmap(_fromUtf8("swmmimages/info.png")))
        self.lblIconSuccessful.setObjectName(_fromUtf8("lblIconSuccessful"))
        self.horizontalLayout_4.addWidget(self.lblIconSuccessful)
        self.lblSuccessful = QtGui.QLabel(self.fraSuccessful)
        self.lblSuccessful.setObjectName(_fromUtf8("lblSuccessful"))
        self.horizontalLayout_4.addWidget(self.lblSuccessful)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.fraSuccessful)
        self.gbxContinuity = QtGui.QGroupBox(self.fraFinished)
        self.gbxContinuity.setObjectName(_fromUtf8("gbxContinuity"))
        self.gridLayout = QtGui.QGridLayout(self.gbxContinuity)
        self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSurface = QtGui.QLabel(self.gbxContinuity)
        self.lblSurface.setObjectName(_fromUtf8("lblSurface"))
        self.gridLayout.addWidget(self.lblSurface, 0, 0, 1, 1)
        self.txtSurface = QtGui.QLabel(self.gbxContinuity)
        self.txtSurface.setObjectName(_fromUtf8("txtSurface"))
        self.gridLayout.addWidget(self.txtSurface, 0, 1, 1, 1)
        self.lblFlow = QtGui.QLabel(self.gbxContinuity)
        self.lblFlow.setObjectName(_fromUtf8("lblFlow"))
        self.gridLayout.addWidget(self.lblFlow, 1, 0, 1, 1)
        self.txtFlow = QtGui.QLabel(self.gbxContinuity)
        self.txtFlow.setObjectName(_fromUtf8("txtFlow"))
        self.gridLayout.addWidget(self.txtFlow, 1, 1, 1, 1)
        self.lblQuality = QtGui.QLabel(self.gbxContinuity)
        self.lblQuality.setObjectName(_fromUtf8("lblQuality"))
        self.gridLayout.addWidget(self.lblQuality, 2, 0, 1, 1)
        self.txtQuality = QtGui.QLabel(self.gbxContinuity)
        self.txtQuality.setObjectName(_fromUtf8("txtQuality"))
        self.gridLayout.addWidget(self.txtQuality, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbxContinuity)
        self.horizontalLayout_5.addWidget(self.fraFinished)
        self.verticalLayout_3.addWidget(self.fraEntire)
        self.fraBottom = QtGui.QFrame(self.centralWidget)
        self.fraBottom.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QtGui.QFrame.Raised)
        self.fraBottom.setObjectName(_fromUtf8("fraBottom"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraBottom)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cmdStop = QtGui.QPushButton(self.fraBottom)
        self.cmdStop.setObjectName(_fromUtf8("cmdStop"))
        self.horizontalLayout.addWidget(self.cmdStop)
        self.cmdMinimize = QtGui.QPushButton(self.fraBottom)
        self.cmdMinimize.setObjectName(_fromUtf8("cmdMinimize"))
        self.horizontalLayout.addWidget(self.cmdMinimize)
        self.cmdOK = QtGui.QPushButton(self.fraBottom)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.fraBottom)
        frmRunSimulation.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmRunSimulation)
        QtCore.QMetaObject.connectSlotsByName(frmRunSimulation)

    def retranslateUi(self, frmRunSimulation):
        frmRunSimulation.setWindowTitle(_translate("frmRunSimulation", "Run Status", None))
        self.StatusLabel.setText(_translate("frmRunSimulation", "Computing ...", None))
        self.lblTime.setText(_translate("frmRunSimulation", "Simulated Time:", None))
        self.lblDays.setText(_translate("frmRunSimulation", "Days", None))
        self.txtDays.setText(_translate("frmRunSimulation", "0", None))
        self.lblHrsMin.setText(_translate("frmRunSimulation", "Hrs:Min", None))
        self.txtHrsMin.setText(_translate("frmRunSimulation", "0", None))
        self.lblSuccessful.setText(_translate("frmRunSimulation", "<html><head/><body><p>Run was Successful.</p></body></html>", None))
        self.gbxContinuity.setTitle(_translate("frmRunSimulation", "Continuity Error", None))
        self.lblSurface.setText(_translate("frmRunSimulation", "Surface Runoff:", None))
        self.txtSurface.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.lblFlow.setText(_translate("frmRunSimulation", "Flow Routing:", None))
        self.txtFlow.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.lblQuality.setText(_translate("frmRunSimulation", "Quality Routing:", None))
        self.txtQuality.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.cmdStop.setText(_translate("frmRunSimulation", "Stop", None))
        self.cmdMinimize.setText(_translate("frmRunSimulation", "Minimize", None))
        self.cmdOK.setText(_translate("frmRunSimulation", "OK", None))

