# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmRunSimulationDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmRunSimulation(object):
    def setupUi(self, frmRunSimulation):
        frmRunSimulation.setObjectName(_fromUtf8("frmRunSimulation"))
        frmRunSimulation.resize(558, 274)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmRunSimulation.setFont(font)
        self.centralWidget = QWidget(frmRunSimulation)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QVBoxLayout(self.centralWidget)
        # self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.fraEntire = QFrame(self.centralWidget)
        self.fraEntire.setFrameShape(QFrame.StyledPanel)
        self.fraEntire.setFrameShadow(QFrame.Raised)
        self.fraEntire.setObjectName(_fromUtf8("fraEntire"))
        self.horizontalLayout_5 = QHBoxLayout(self.fraEntire)
        # self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.fraRunning = QFrame(self.fraEntire)
        self.fraRunning.setFrameShape(QFrame.StyledPanel)
        self.fraRunning.setFrameShadow(QFrame.Raised)
        self.fraRunning.setObjectName(_fromUtf8("fraRunning"))
        self.verticalLayout = QVBoxLayout(self.fraRunning)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fraComputing = QFrame(self.fraRunning)
        self.fraComputing.setFrameShape(QFrame.StyledPanel)
        self.fraComputing.setFrameShadow(QFrame.Raised)
        self.fraComputing.setObjectName(_fromUtf8("fraComputing"))
        self.horizontalLayout_3 = QHBoxLayout(self.fraComputing)
        # self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblIconComputing = QLabel(self.fraComputing)
        self.lblIconComputing.setText(_fromUtf8(""))
        self.lblIconComputing.setPixmap(QPixmap(_fromUtf8("swmmimages/rain.png")))
        self.lblIconComputing.setObjectName(_fromUtf8("lblIconComputing"))
        self.horizontalLayout_3.addWidget(self.lblIconComputing)
        self.StatusLabel = QLabel(self.fraComputing)
        self.StatusLabel.setObjectName(_fromUtf8("StatusLabel"))
        self.horizontalLayout_3.addWidget(self.StatusLabel)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fraComputing)
        self.progressBar = QProgressBar(self.fraRunning)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout.addWidget(self.progressBar)
        self.lblTime = QLabel(self.fraRunning)
        self.lblTime.setObjectName(_fromUtf8("lblTime"))
        self.verticalLayout.addWidget(self.lblTime)
        self.fraTime = QFrame(self.fraRunning)
        self.fraTime.setFrameShape(QFrame.StyledPanel)
        self.fraTime.setFrameShadow(QFrame.Raised)
        self.fraTime.setObjectName(_fromUtf8("fraTime"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraTime)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblDays = QLabel(self.fraTime)
        self.lblDays.setFrameShape(QFrame.StyledPanel)
        self.lblDays.setObjectName(_fromUtf8("lblDays"))
        self.horizontalLayout_2.addWidget(self.lblDays)
        self.txtDays = QLabel(self.fraTime)
        self.txtDays.setFrameShape(QFrame.StyledPanel)
        self.txtDays.setObjectName(_fromUtf8("txtDays"))
        self.horizontalLayout_2.addWidget(self.txtDays)
        self.lblHrsMin = QLabel(self.fraTime)
        self.lblHrsMin.setFrameShape(QFrame.StyledPanel)
        self.lblHrsMin.setObjectName(_fromUtf8("lblHrsMin"))
        self.horizontalLayout_2.addWidget(self.lblHrsMin)
        self.txtHrsMin = QLabel(self.fraTime)
        self.txtHrsMin.setFrameShape(QFrame.StyledPanel)
        self.txtHrsMin.setObjectName(_fromUtf8("txtHrsMin"))
        self.horizontalLayout_2.addWidget(self.txtHrsMin)
        self.verticalLayout.addWidget(self.fraTime)
        self.horizontalLayout_5.addWidget(self.fraRunning)
        self.fraFinished = QFrame(self.fraEntire)
        self.fraFinished.setFrameShape(QFrame.StyledPanel)
        self.fraFinished.setFrameShadow(QFrame.Raised)
        self.fraFinished.setObjectName(_fromUtf8("fraFinished"))
        self.verticalLayout_2 = QVBoxLayout(self.fraFinished)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraSuccessful = QFrame(self.fraFinished)
        self.fraSuccessful.setFrameShape(QFrame.StyledPanel)
        self.fraSuccessful.setFrameShadow(QFrame.Raised)
        self.fraSuccessful.setObjectName(_fromUtf8("fraSuccessful"))
        self.horizontalLayout_4 = QHBoxLayout(self.fraSuccessful)
        # self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblIconSuccessful = QLabel(self.fraSuccessful)
        self.lblIconSuccessful.setText(_fromUtf8(""))
        self.lblIconSuccessful.setPixmap(QPixmap(_fromUtf8("swmmimages/info.png")))
        self.lblIconSuccessful.setObjectName(_fromUtf8("lblIconSuccessful"))
        self.horizontalLayout_4.addWidget(self.lblIconSuccessful)
        self.lblSuccessful = QLabel(self.fraSuccessful)
        self.lblSuccessful.setObjectName(_fromUtf8("lblSuccessful"))
        self.horizontalLayout_4.addWidget(self.lblSuccessful)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.fraSuccessful)
        self.gbxContinuity = QGroupBox(self.fraFinished)
        self.gbxContinuity.setObjectName(_fromUtf8("gbxContinuity"))
        self.gridLayout = QGridLayout(self.gbxContinuity)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblSurface = QLabel(self.gbxContinuity)
        self.lblSurface.setObjectName(_fromUtf8("lblSurface"))
        self.gridLayout.addWidget(self.lblSurface, 0, 0, 1, 1)
        self.txtSurface = QLabel(self.gbxContinuity)
        self.txtSurface.setObjectName(_fromUtf8("txtSurface"))
        self.gridLayout.addWidget(self.txtSurface, 0, 1, 1, 1)
        self.lblFlow = QLabel(self.gbxContinuity)
        self.lblFlow.setObjectName(_fromUtf8("lblFlow"))
        self.gridLayout.addWidget(self.lblFlow, 1, 0, 1, 1)
        self.txtFlow = QLabel(self.gbxContinuity)
        self.txtFlow.setObjectName(_fromUtf8("txtFlow"))
        self.gridLayout.addWidget(self.txtFlow, 1, 1, 1, 1)
        self.lblQuality = QLabel(self.gbxContinuity)
        self.lblQuality.setObjectName(_fromUtf8("lblQuality"))
        self.gridLayout.addWidget(self.lblQuality, 2, 0, 1, 1)
        self.txtQuality = QLabel(self.gbxContinuity)
        self.txtQuality.setObjectName(_fromUtf8("txtQuality"))
        self.gridLayout.addWidget(self.txtQuality, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbxContinuity)
        self.horizontalLayout_5.addWidget(self.fraFinished)
        self.verticalLayout_3.addWidget(self.fraEntire)
        self.fraBottom = QFrame(self.centralWidget)
        self.fraBottom.setFrameShape(QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QFrame.Raised)
        self.fraBottom.setObjectName(_fromUtf8("fraBottom"))
        self.horizontalLayout = QHBoxLayout(self.fraBottom)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cmdStop = QPushButton(self.fraBottom)
        self.cmdStop.setObjectName(_fromUtf8("cmdStop"))
        self.horizontalLayout.addWidget(self.cmdStop)
        self.cmdMinimize = QPushButton(self.fraBottom)
        self.cmdMinimize.setObjectName(_fromUtf8("cmdMinimize"))
        self.horizontalLayout.addWidget(self.cmdMinimize)
        self.cmdOK = QPushButton(self.fraBottom)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.fraBottom)
        frmRunSimulation.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmRunSimulation)
        QtCore.QMetaObject.connectSlotsByName(frmRunSimulation)

    def retranslateUi(self, frmRunSimulation):
        frmRunSimulation.setWindowTitle(_translate("frmRunSimulation", "Run Status", None))
        self.StatusLabel.setText(_translate("frmRunSimulation", "Computing ...", None))
        self.lblTime.setText(_translate("frmRunSimulation", "Simulated Time:", None))
        self.lblDays.setText(_translate("frmRunSimulation", "Days", None))
        self.txtDays.setText(_translate("frmRunSimulation", "0", None))
        self.lblHrsMin.setText(_translate("frmRunSimulation", "Hrs:Min", None))
        self.txtHrsMin.setText(_translate("frmRunSimulation", "0", None))
        self.lblSuccessful.setText(_translate("frmRunSimulation", "<html><head/><body><p>Run was Successful.</p></body></html>", None))
        self.gbxContinuity.setTitle(_translate("frmRunSimulation", "Continuity Error", None))
        self.lblSurface.setText(_translate("frmRunSimulation", "Surface Runoff:", None))
        self.txtSurface.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.lblFlow.setText(_translate("frmRunSimulation", "Flow Routing:", None))
        self.txtFlow.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.lblQuality.setText(_translate("frmRunSimulation", "Quality Routing:", None))
        self.txtQuality.setText(_translate("frmRunSimulation", "0.0 %", None))
        self.cmdStop.setText(_translate("frmRunSimulation", "Stop", None))
        self.cmdMinimize.setText(_translate("frmRunSimulation", "Minimize", None))
        self.cmdOK.setText(_translate("frmRunSimulation", "OK", None))

