# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmScatterPlotDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmScatterPlot(object):
    def setupUi(self, frmScatterPlot):
        frmScatterPlot.setObjectName(_fromUtf8("frmScatterPlot"))
        frmScatterPlot.resize(379, 478)
        font = QFont()
        font.setPointSize(10)
        frmScatterPlot.setFont(font)
        self.centralWidget = QWidget(frmScatterPlot)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QVBoxLayout(self.centralWidget)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbxTimePeriods = QGroupBox(self.centralWidget)
        self.gbxTimePeriods.setTitle(_fromUtf8(""))
        self.gbxTimePeriods.setObjectName(_fromUtf8("gbxTimePeriods"))
        self.gridLayout = QGridLayout(self.gbxTimePeriods)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cboStart = QComboBox(self.gbxTimePeriods)
        self.cboStart.setObjectName(_fromUtf8("cboStart"))
        self.gridLayout.addWidget(self.cboStart, 1, 0, 1, 1)
        self.lblStart = QLabel(self.gbxTimePeriods)
        self.lblStart.setObjectName(_fromUtf8("lblStart"))
        self.gridLayout.addWidget(self.lblStart, 0, 0, 1, 1)
        self.lblEnd = QLabel(self.gbxTimePeriods)
        self.lblEnd.setObjectName(_fromUtf8("lblEnd"))
        self.gridLayout.addWidget(self.lblEnd, 0, 1, 1, 1)
        self.cboEnd = QComboBox(self.gbxTimePeriods)
        self.cboEnd.setObjectName(_fromUtf8("cboEnd"))
        self.gridLayout.addWidget(self.cboEnd, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbxTimePeriods)
        self.fraMid = QFrame(self.centralWidget)
        self.fraMid.setFrameShape(QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QFrame.Raised)
        self.fraMid.setObjectName(_fromUtf8("fraMid"))
        self.horizontalLayout_3 = QHBoxLayout(self.fraMid)
        # self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gbxX = QGroupBox(self.fraMid)
        self.gbxX.setObjectName(_fromUtf8("gbxX"))
        self.verticalLayout_2 = QVBoxLayout(self.gbxX)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblXCat = QLabel(self.gbxX)
        self.lblXCat.setObjectName(_fromUtf8("lblXCat"))
        self.verticalLayout_2.addWidget(self.lblXCat)
        self.cboXCat = QComboBox(self.gbxX)
        self.cboXCat.setObjectName(_fromUtf8("cboXCat"))
        self.verticalLayout_2.addWidget(self.cboXCat)
        self.lblObjectX = QLabel(self.gbxX)
        self.lblObjectX.setObjectName(_fromUtf8("lblObjectX"))
        self.verticalLayout_2.addWidget(self.lblObjectX)
        self.lstX = QListWidget(self.gbxX)
        self.lstX.setObjectName(_fromUtf8("lstX"))
        self.verticalLayout_2.addWidget(self.lstX)
        self.lblVarX = QLabel(self.gbxX)
        self.lblVarX.setObjectName(_fromUtf8("lblVarX"))
        self.verticalLayout_2.addWidget(self.lblVarX)
        self.cboVarX = QComboBox(self.gbxX)
        self.cboVarX.setObjectName(_fromUtf8("cboVarX"))
        self.verticalLayout_2.addWidget(self.cboVarX)
        self.horizontalLayout_3.addWidget(self.gbxX)
        self.gbxY = QGroupBox(self.fraMid)
        self.gbxY.setObjectName(_fromUtf8("gbxY"))
        self.verticalLayout_3 = QVBoxLayout(self.gbxY)
        # self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblYCat = QLabel(self.gbxY)
        self.lblYCat.setObjectName(_fromUtf8("lblYCat"))
        self.verticalLayout_3.addWidget(self.lblYCat)
        self.cboYCat = QComboBox(self.gbxY)
        self.cboYCat.setObjectName(_fromUtf8("cboYCat"))
        self.verticalLayout_3.addWidget(self.cboYCat)
        self.lblObjectY = QLabel(self.gbxY)
        self.lblObjectY.setObjectName(_fromUtf8("lblObjectY"))
        self.verticalLayout_3.addWidget(self.lblObjectY)
        self.lstY = QListWidget(self.gbxY)
        self.lstY.setObjectName(_fromUtf8("lstY"))
        self.verticalLayout_3.addWidget(self.lstY)
        self.lblVarY = QLabel(self.gbxY)
        self.lblVarY.setObjectName(_fromUtf8("lblVarY"))
        self.verticalLayout_3.addWidget(self.lblVarY)
        self.cboVarY = QComboBox(self.gbxY)
        self.cboVarY.setObjectName(_fromUtf8("cboVarY"))
        self.verticalLayout_3.addWidget(self.cboVarY)
        self.horizontalLayout_3.addWidget(self.gbxY)
        self.verticalLayout.addWidget(self.fraMid)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmScatterPlot.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmScatterPlot)
        QtCore.QMetaObject.connectSlotsByName(frmScatterPlot)

    def retranslateUi(self, frmScatterPlot):
        frmScatterPlot.setWindowTitle(_translate("frmScatterPlot", "SWMM Scatter Plot Selection", None))
        self.lblStart.setText(_translate("frmScatterPlot", "Start Date", None))
        self.lblEnd.setText(_translate("frmScatterPlot", "End Date", None))
        self.gbxX.setTitle(_translate("frmScatterPlot", "X-Variable", None))
        self.lblXCat.setText(_translate("frmScatterPlot", "Object Category", None))
        self.lblObjectX.setText(_translate("frmScatterPlot", "Object", None))
        self.lblVarX.setText(_translate("frmScatterPlot", "Variable", None))
        self.gbxY.setTitle(_translate("frmScatterPlot", "Y-Variable", None))
        self.lblYCat.setText(_translate("frmScatterPlot", "Object Category", None))
        self.lblObjectY.setText(_translate("frmScatterPlot", "Object", None))
        self.lblVarY.setText(_translate("frmScatterPlot", "Variable", None))
        self.cmdOK.setText(_translate("frmScatterPlot", "OK", None))
        self.cmdCancel.setText(_translate("frmScatterPlot", "Cancel", None))

