# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\SWMM\frmCurveEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmCurveEditor(object):
    def setupUi(self, frmCurveEditor):
        frmCurveEditor.setObjectName("frmCurveEditor")
        frmCurveEditor.resize(587, 448)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmCurveEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmCurveEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setMaximumSize(QtCore.QSize(16777215, 250))
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.gridLayout = QtWidgets.QGridLayout(self.fraParms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblCurveID = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveID.setFont(font)
        self.lblCurveID.setObjectName("lblCurveID")
        self.gridLayout.addWidget(self.lblCurveID, 0, 0, 1, 1)
        self.lblCurveType = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveType.setFont(font)
        self.lblCurveType.setObjectName("lblCurveType")
        self.gridLayout.addWidget(self.lblCurveType, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(231, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.txtCurveName = QtWidgets.QLineEdit(self.fraParms)
        self.txtCurveName.setObjectName("txtCurveName")
        self.gridLayout.addWidget(self.txtCurveName, 1, 0, 1, 1)
        self.cboCurveType = QtWidgets.QComboBox(self.fraParms)
        self.cboCurveType.setObjectName("cboCurveType")
        self.gridLayout.addWidget(self.cboCurveType, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(231, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.fraParms)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 2, 0, 1, 1)
        self.txtDescription = QtWidgets.QLineEdit(self.fraParms)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 3, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.fraParms)
        self.fraBottom = QtWidgets.QFrame(self.centralWidget)
        self.fraBottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBottom.setObjectName("fraBottom")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fraBottom)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnSave = QtWidgets.QPushButton(self.fraBottom)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout_2.addWidget(self.btnSave, 1, 1, 1, 1)
        self.btnHelp = QtWidgets.QPushButton(self.fraBottom)
        self.btnHelp.setObjectName("btnHelp")
        self.gridLayout_2.addWidget(self.btnHelp, 1, 4, 1, 1)
        self.cmdOK = QtWidgets.QPushButton(self.fraBottom)
        self.cmdOK.setObjectName("cmdOK")
        self.gridLayout_2.addWidget(self.cmdOK, 1, 2, 1, 1)
        self.btnLoad = QtWidgets.QPushButton(self.fraBottom)
        self.btnLoad.setObjectName("btnLoad")
        self.gridLayout_2.addWidget(self.btnLoad, 1, 0, 1, 1)
        self.cmdCancel = QtWidgets.QPushButton(self.fraBottom)
        self.cmdCancel.setObjectName("cmdCancel")
        self.gridLayout_2.addWidget(self.cmdCancel, 1, 3, 1, 1)
        self.tblMult = QtWidgets.QTableWidget(self.fraBottom)
        self.tblMult.setCornerButtonEnabled(False)
        self.tblMult.setRowCount(100)
        self.tblMult.setColumnCount(2)
        self.tblMult.setObjectName("tblMult")
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(1, item)
        self.tblMult.horizontalHeader().setVisible(True)
        self.tblMult.verticalHeader().setVisible(True)
        self.gridLayout_2.addWidget(self.tblMult, 0, 0, 1, 2)
        self.fraRight = QtWidgets.QFrame(self.fraBottom)
        self.fraRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRight.setObjectName("fraRight")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraRight)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnView = QtWidgets.QPushButton(self.fraRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnView.sizePolicy().hasHeightForWidth())
        self.btnView.setSizePolicy(sizePolicy)
        self.btnView.setObjectName("btnView")
        self.verticalLayout.addWidget(self.btnView)
        self.gridLayout_2.addWidget(self.fraRight, 0, 2, 1, 3)
        self.verticalLayout_2.addWidget(self.fraBottom)
        frmCurveEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmCurveEditor)
        QtCore.QMetaObject.connectSlotsByName(frmCurveEditor)

    def retranslateUi(self, frmCurveEditor):
        _translate = QtCore.QCoreApplication.translate
        frmCurveEditor.setWindowTitle(_translate("frmCurveEditor", "SWMM Curves"))
        self.lblCurveID.setText(_translate("frmCurveEditor", "Curve Name"))
        self.lblCurveType.setText(_translate("frmCurveEditor", "Pump Type"))
        self.lblDescription.setText(_translate("frmCurveEditor", "<html><head/><body><p>Description</p></body></html>"))
        self.btnSave.setText(_translate("frmCurveEditor", "Save..."))
        self.btnHelp.setText(_translate("frmCurveEditor", "Help"))
        self.cmdOK.setText(_translate("frmCurveEditor", "OK"))
        self.btnLoad.setText(_translate("frmCurveEditor", "Load..."))
        self.cmdCancel.setText(_translate("frmCurveEditor", "Cancel"))
        item = self.tblMult.horizontalHeaderItem(0)
        item.setText(_translate("frmCurveEditor", "Flow"))
        item = self.tblMult.horizontalHeaderItem(1)
        item.setText(_translate("frmCurveEditor", "Head"))
        self.btnView.setText(_translate("frmCurveEditor", "View"))

