# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmCrossSectionDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmCrossSection(object):
    def setupUi(self, frmCrossSection):
        frmCrossSection.setObjectName(_fromUtf8("frmCrossSection"))
        frmCrossSection.resize(739, 524)
        font = QFont()
        font.setPointSize(10)
        frmCrossSection.setFont(font)
        self.centralWidget = QWidget(frmCrossSection)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QVBoxLayout(self.centralWidget)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraTop = QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraTop)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.listWidget = QListWidget(self.fraTop)
        self.listWidget.setIconSize(QtCore.QSize(150, 100))
        self.listWidget.setResizeMode(QListView.Adjust)
        self.listWidget.setGridSize(QtCore.QSize(100, 100))
        self.listWidget.setViewMode(QListView.IconMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(True)
        self.listWidget.setWordWrap(True)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.frame = QFrame(self.fraTop)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QGridLayout(self.frame)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txt3 = QLineEdit(self.frame)
        self.txt3.setObjectName(_fromUtf8("txt3"))
        self.gridLayout.addWidget(self.txt3, 3, 1, 1, 1)
        self.lblText3 = QLabel(self.frame)
        self.lblText3.setObjectName(_fromUtf8("lblText3"))
        self.gridLayout.addWidget(self.lblText3, 3, 0, 1, 1)
        self.txt2 = QLineEdit(self.frame)
        self.txt2.setObjectName(_fromUtf8("txt2"))
        self.gridLayout.addWidget(self.txt2, 2, 1, 1, 1)
        self.lblSpin = QLabel(self.frame)
        self.lblSpin.setObjectName(_fromUtf8("lblSpin"))
        self.gridLayout.addWidget(self.lblSpin, 0, 0, 1, 1)
        self.sbxNumber = QSpinBox(self.frame)
        self.sbxNumber.setObjectName(_fromUtf8("sbxNumber"))
        self.gridLayout.addWidget(self.sbxNumber, 0, 1, 1, 1)
        self.lblText1 = QLabel(self.frame)
        self.lblText1.setObjectName(_fromUtf8("lblText1"))
        self.gridLayout.addWidget(self.lblText1, 1, 0, 1, 1)
        self.txt1 = QLineEdit(self.frame)
        self.txt1.setObjectName(_fromUtf8("txt1"))
        self.gridLayout.addWidget(self.txt1, 1, 1, 1, 1)
        self.lblText4 = QLabel(self.frame)
        self.lblText4.setObjectName(_fromUtf8("lblText4"))
        self.gridLayout.addWidget(self.lblText4, 4, 0, 1, 1)
        self.txt4 = QLineEdit(self.frame)
        self.txt4.setObjectName(_fromUtf8("txt4"))
        self.gridLayout.addWidget(self.txt4, 4, 1, 1, 1)
        self.lblCombo = QLabel(self.frame)
        self.lblCombo.setObjectName(_fromUtf8("lblCombo"))
        self.gridLayout.addWidget(self.lblCombo, 5, 0, 1, 1)
        self.cboCombo = QComboBox(self.frame)
        self.cboCombo.setObjectName(_fromUtf8("cboCombo"))
        self.gridLayout.addWidget(self.cboCombo, 5, 1, 1, 1)
        self.lblText2 = QLabel(self.frame)
        self.lblText2.setObjectName(_fromUtf8("lblText2"))
        self.gridLayout.addWidget(self.lblText2, 2, 0, 1, 1)
        self.btnDialog = QToolButton(self.frame)
        self.btnDialog.setObjectName(_fromUtf8("btnDialog"))
        self.gridLayout.addWidget(self.btnDialog, 5, 2, 1, 1)
        self.lblFootnote = QLabel(self.frame)
        self.lblFootnote.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lblFootnote.setObjectName(_fromUtf8("lblFootnote"))
        self.gridLayout.addWidget(self.lblFootnote, 6, 0, 1, 2)
        self.lblDimensions = QLabel(self.frame)
        self.lblDimensions.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.lblDimensions.setFont(font)
        self.lblDimensions.setObjectName(_fromUtf8("lblDimensions"))
        self.gridLayout.addWidget(self.lblDimensions, 7, 0, 1, 3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.fraBottom = QFrame(self.centralWidget)
        self.fraBottom.setFrameShape(QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QFrame.Raised)
        self.fraBottom.setObjectName(_fromUtf8("fraBottom"))
        self.verticalLayout = QVBoxLayout(self.fraBottom)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblBottom = QLabel(self.fraBottom)
        self.lblBottom.setObjectName(_fromUtf8("lblBottom"))
        self.verticalLayout.addWidget(self.lblBottom)
        self.verticalLayout_2.addWidget(self.fraBottom)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmCrossSection.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmCrossSection)
        QtCore.QMetaObject.connectSlotsByName(frmCrossSection)

    def retranslateUi(self, frmCrossSection):
        frmCrossSection.setWindowTitle(_translate("frmCrossSection", "SWMM Cross-Section Editor", None))
        self.lblText3.setText(_translate("frmCrossSection", "Left Slope", None))
        self.lblSpin.setText(_translate("frmCrossSection", "Number of Barrels", None))
        self.lblText1.setText(_translate("frmCrossSection", "Maximum Height", None))
        self.lblText4.setText(_translate("frmCrossSection", "Right Slope", None))
        self.lblCombo.setText(_translate("frmCrossSection", "Sidewalls Removed", None))
        self.lblText2.setText(_translate("frmCrossSection", "Bottom Width", None))
        self.btnDialog.setText(_translate("frmCrossSection", "...", None))
        self.lblFootnote.setText(_translate("frmCrossSection", "*Hazen-Williams C-factor", None))
        self.lblDimensions.setText(_translate("frmCrossSection", "Dimensions are feet unless otherwise stated.", None))
        self.lblBottom.setText(_translate("frmCrossSection", "Open rectangular channel.  Sidewalls can be removed for 2-D modeling.", None))
        self.cmdOK.setText(_translate("frmCrossSection", "OK", None))
        self.cmdCancel.setText(_translate("frmCrossSection", "Cancel", None))

