# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmDatesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmDates(object):
    def setupUi(self, frmDates):
        frmDates.setObjectName("frmDates")
        frmDates.resize(445, 368)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmDates.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmDates)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraHeader = QtWidgets.QFrame(self.centralWidget)
        self.fraHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraHeader.setObjectName("fraHeader")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fraHeader)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.fraHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.lblDays = QtWidgets.QLabel(self.fraHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDays.sizePolicy().hasHeightForWidth())
        self.lblDays.setSizePolicy(sizePolicy)
        self.lblDays.setMinimumSize(QtCore.QSize(50, 0))
        self.lblDays.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblDays.setObjectName("lblDays")
        self.horizontalLayout_5.addWidget(self.lblDays)
        self.lblTimes = QtWidgets.QLabel(self.fraHeader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTimes.sizePolicy().hasHeightForWidth())
        self.lblTimes.setSizePolicy(sizePolicy)
        self.lblTimes.setMinimumSize(QtCore.QSize(50, 0))
        self.lblTimes.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblTimes.setObjectName("lblTimes")
        self.horizontalLayout_5.addWidget(self.lblTimes)
        self.verticalLayout.addWidget(self.fraHeader)
        self.fraAnalysisStart = QtWidgets.QFrame(self.centralWidget)
        self.fraAnalysisStart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraAnalysisStart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraAnalysisStart.setObjectName("fraAnalysisStart")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraAnalysisStart)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblStart = QtWidgets.QLabel(self.fraAnalysisStart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStart.sizePolicy().hasHeightForWidth())
        self.lblStart.setSizePolicy(sizePolicy)
        self.lblStart.setMinimumSize(QtCore.QSize(100, 0))
        self.lblStart.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblStart.setObjectName("lblStart")
        self.horizontalLayout_2.addWidget(self.lblStart)
        self.dedStart = QtWidgets.QDateEdit(self.fraAnalysisStart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dedStart.sizePolicy().hasHeightForWidth())
        self.dedStart.setSizePolicy(sizePolicy)
        self.dedStart.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.dedStart.setDate(QtCore.QDate(2002, 1, 1))
        self.dedStart.setObjectName("dedStart")
        self.horizontalLayout_2.addWidget(self.dedStart)
        self.tmeStart = QtWidgets.QTimeEdit(self.fraAnalysisStart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmeStart.sizePolicy().hasHeightForWidth())
        self.tmeStart.setSizePolicy(sizePolicy)
        self.tmeStart.setMinimumSize(QtCore.QSize(50, 0))
        self.tmeStart.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.tmeStart.setBaseSize(QtCore.QSize(0, 0))
        self.tmeStart.setProperty("showGroupSeparator", False)
        self.tmeStart.setObjectName("tmeStart")
        self.horizontalLayout_2.addWidget(self.tmeStart)
        self.verticalLayout.addWidget(self.fraAnalysisStart)
        self.fraReport = QtWidgets.QFrame(self.centralWidget)
        self.fraReport.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraReport.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraReport.setObjectName("fraReport")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraReport)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblStartReporting = QtWidgets.QLabel(self.fraReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStartReporting.sizePolicy().hasHeightForWidth())
        self.lblStartReporting.setSizePolicy(sizePolicy)
        self.lblStartReporting.setMinimumSize(QtCore.QSize(100, 0))
        self.lblStartReporting.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblStartReporting.setObjectName("lblStartReporting")
        self.horizontalLayout_3.addWidget(self.lblStartReporting)
        self.dedStartReport = QtWidgets.QDateEdit(self.fraReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dedStartReport.sizePolicy().hasHeightForWidth())
        self.dedStartReport.setSizePolicy(sizePolicy)
        self.dedStartReport.setMaximumSize(QtCore.QSize(20000, 16777215))
        self.dedStartReport.setDate(QtCore.QDate(2002, 1, 1))
        self.dedStartReport.setObjectName("dedStartReport")
        self.horizontalLayout_3.addWidget(self.dedStartReport)
        self.tmeReport = QtWidgets.QTimeEdit(self.fraReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmeReport.sizePolicy().hasHeightForWidth())
        self.tmeReport.setSizePolicy(sizePolicy)
        self.tmeReport.setMinimumSize(QtCore.QSize(50, 0))
        self.tmeReport.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.tmeReport.setProperty("showGroupSeparator", False)
        self.tmeReport.setObjectName("tmeReport")
        self.horizontalLayout_3.addWidget(self.tmeReport)
        self.verticalLayout.addWidget(self.fraReport)
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblEnd = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEnd.sizePolicy().hasHeightForWidth())
        self.lblEnd.setSizePolicy(sizePolicy)
        self.lblEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.lblEnd.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblEnd.setObjectName("lblEnd")
        self.horizontalLayout_4.addWidget(self.lblEnd)
        self.dedEnd = QtWidgets.QDateEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dedEnd.sizePolicy().hasHeightForWidth())
        self.dedEnd.setSizePolicy(sizePolicy)
        self.dedEnd.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.dedEnd.setDate(QtCore.QDate(2002, 1, 1))
        self.dedEnd.setObjectName("dedEnd")
        self.horizontalLayout_4.addWidget(self.dedEnd)
        self.tmeEnd = QtWidgets.QTimeEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmeEnd.sizePolicy().hasHeightForWidth())
        self.tmeEnd.setSizePolicy(sizePolicy)
        self.tmeEnd.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.tmeEnd.setProperty("showGroupSeparator", False)
        self.tmeEnd.setObjectName("tmeEnd")
        self.horizontalLayout_4.addWidget(self.tmeEnd)
        self.verticalLayout.addWidget(self.frame_4)
        self.fraOther = QtWidgets.QFrame(self.centralWidget)
        self.fraOther.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOther.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOther.setObjectName("fraOther")
        self.gridLayout = QtWidgets.QGridLayout(self.fraOther)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblStartSweeping = QtWidgets.QLabel(self.fraOther)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStartSweeping.sizePolicy().hasHeightForWidth())
        self.lblStartSweeping.setSizePolicy(sizePolicy)
        self.lblStartSweeping.setMinimumSize(QtCore.QSize(150, 0))
        self.lblStartSweeping.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblStartSweeping.setObjectName("lblStartSweeping")
        self.gridLayout.addWidget(self.lblStartSweeping, 0, 0, 1, 1)
        self.dedSweepStart = QtWidgets.QDateEdit(self.fraOther)
        self.dedSweepStart.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.dedSweepStart.setObjectName("dedSweepStart")
        self.gridLayout.addWidget(self.dedSweepStart, 0, 1, 1, 1)
        self.lblEndSweeping = QtWidgets.QLabel(self.fraOther)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblEndSweeping.sizePolicy().hasHeightForWidth())
        self.lblEndSweeping.setSizePolicy(sizePolicy)
        self.lblEndSweeping.setMinimumSize(QtCore.QSize(150, 0))
        self.lblEndSweeping.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblEndSweeping.setObjectName("lblEndSweeping")
        self.gridLayout.addWidget(self.lblEndSweeping, 1, 0, 1, 1)
        self.dedSweepEnd = QtWidgets.QDateEdit(self.fraOther)
        self.dedSweepEnd.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.dedSweepEnd.setObjectName("dedSweepEnd")
        self.gridLayout.addWidget(self.dedSweepEnd, 1, 1, 1, 1)
        self.lblAntecedent = QtWidgets.QLabel(self.fraOther)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblAntecedent.sizePolicy().hasHeightForWidth())
        self.lblAntecedent.setSizePolicy(sizePolicy)
        self.lblAntecedent.setMinimumSize(QtCore.QSize(150, 0))
        self.lblAntecedent.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.lblAntecedent.setObjectName("lblAntecedent")
        self.gridLayout.addWidget(self.lblAntecedent, 2, 0, 1, 1)
        self.txtAntecedent = QtWidgets.QLineEdit(self.fraOther)
        self.txtAntecedent.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.txtAntecedent.setObjectName("txtAntecedent")
        self.gridLayout.addWidget(self.txtAntecedent, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.fraOther)
        self.fraButtons = QtWidgets.QFrame(self.centralWidget)
        self.fraButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraButtons.setObjectName("fraButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraButtons)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(164, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraButtons)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraButtons)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraButtons)
        frmDates.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmDates)
        QtCore.QMetaObject.connectSlotsByName(frmDates)

    def retranslateUi(self, frmDates):
        _translate = QtCore.QCoreApplication.translate
        frmDates.setWindowTitle(_translate("frmDates", "SWMM Dates Options"))
        self.lblDays.setText(_translate("frmDates", "Date (M/D/Y)"))
        self.lblTimes.setText(_translate("frmDates", "Time (H:M)"))
        self.lblStart.setText(_translate("frmDates", "Start Analysis on"))
        self.dedStart.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy"))
        self.tmeStart.setDisplayFormat(_translate("frmDates", "hh:mm"))
        self.lblStartReporting.setText(_translate("frmDates", "Start Reporting on"))
        self.dedStartReport.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy"))
        self.tmeReport.setDisplayFormat(_translate("frmDates", "hh:mm"))
        self.lblEnd.setText(_translate("frmDates", "End Analysis on"))
        self.dedEnd.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy"))
        self.tmeEnd.setDisplayFormat(_translate("frmDates", "hh:mm"))
        self.lblStartSweeping.setText(_translate("frmDates", "Start Sweeping on"))
        self.dedSweepStart.setDisplayFormat(_translate("frmDates", "MM/dd"))
        self.lblEndSweeping.setText(_translate("frmDates", "End Sweeping on"))
        self.dedSweepEnd.setDisplayFormat(_translate("frmDates", "MM/dd"))
        self.lblAntecedent.setText(_translate("frmDates", "Antecedent Dry Days"))
        self.cmdOK.setText(_translate("frmDates", "OK"))
        self.cmdCancel.setText(_translate("frmDates", "Cancel"))

