# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmDatesDesigner.ui'
#
# Created: Tue Mar 08 16:50:05 2016
#      by: PyQt5 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmDates(object):
    def setupUi(self, frmDates):
        frmDates.setObjectName(_fromUtf8("frmDates"))
        frmDates.resize(367, 352)
        font = QFont()
        font.setPointSize(10)
        frmDates.setFont(font)
        self.centralWidget = QWidget(frmDates)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fraHeader = QFrame(self.centralWidget)
        self.fraHeader.setFrameShape(QFrame.StyledPanel)
        self.fraHeader.setFrameShadow(QFrame.Raised)
        self.fraHeader.setObjectName(_fromUtf8("fraHeader"))
        self.horizontalLayout_5 = QHBoxLayout(self.fraHeader)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QLabel(self.fraHeader)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.lblTimes = QLabel(self.fraHeader)
        self.lblTimes.setMinimumSize(QtCore.QSize(50, 0))
        self.lblTimes.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTimes.setObjectName(_fromUtf8("lblTimes"))
        self.horizontalLayout_5.addWidget(self.lblTimes)
        self.lblDays = QLabel(self.fraHeader)
        self.lblDays.setMinimumSize(QtCore.QSize(50, 0))
        self.lblDays.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblDays.setObjectName(_fromUtf8("lblDays"))
        self.horizontalLayout_5.addWidget(self.lblDays)
        self.verticalLayout.addWidget(self.fraHeader)
        self.fraAnalysisStart = QFrame(self.centralWidget)
        self.fraAnalysisStart.setFrameShape(QFrame.StyledPanel)
        self.fraAnalysisStart.setFrameShadow(QFrame.Raised)
        self.fraAnalysisStart.setObjectName(_fromUtf8("fraAnalysisStart"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraAnalysisStart)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblStart = QLabel(self.fraAnalysisStart)
        self.lblStart.setMinimumSize(QtCore.QSize(100, 0))
        self.lblStart.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblStart.setObjectName(_fromUtf8("lblStart"))
        self.horizontalLayout_2.addWidget(self.lblStart)
        self.dedStart = QDateEdit(self.fraAnalysisStart)
        self.dedStart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dedStart.setDate(QtCore.QDate(2002, 1, 1))
        self.dedStart.setObjectName(_fromUtf8("dedStart"))
        self.horizontalLayout_2.addWidget(self.dedStart)
        self.tmeStart = QTimeEdit(self.fraAnalysisStart)
        self.tmeStart.setMinimumSize(QtCore.QSize(50, 0))
        self.tmeStart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tmeStart.setBaseSize(QtCore.QSize(0, 0))
        self.tmeStart.setProperty("showGroupSeparator", False)
        self.tmeStart.setObjectName(_fromUtf8("tmeStart"))
        self.horizontalLayout_2.addWidget(self.tmeStart)
        self.verticalLayout.addWidget(self.fraAnalysisStart)
        self.fraReport = QFrame(self.centralWidget)
        self.fraReport.setFrameShape(QFrame.StyledPanel)
        self.fraReport.setFrameShadow(QFrame.Raised)
        self.fraReport.setObjectName(_fromUtf8("fraReport"))
        self.horizontalLayout_3 = QHBoxLayout(self.fraReport)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblStartReporting = QLabel(self.fraReport)
        self.lblStartReporting.setMinimumSize(QtCore.QSize(100, 0))
        self.lblStartReporting.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblStartReporting.setObjectName(_fromUtf8("lblStartReporting"))
        self.horizontalLayout_3.addWidget(self.lblStartReporting)
        self.dedStartReport = QDateEdit(self.fraReport)
        self.dedStartReport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dedStartReport.setDate(QtCore.QDate(2002, 1, 1))
        self.dedStartReport.setObjectName(_fromUtf8("dedStartReport"))
        self.horizontalLayout_3.addWidget(self.dedStartReport)
        self.tmeReport = QTimeEdit(self.fraReport)
        self.tmeReport.setMinimumSize(QtCore.QSize(50, 0))
        self.tmeReport.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tmeReport.setProperty("showGroupSeparator", False)
        self.tmeReport.setObjectName(_fromUtf8("tmeReport"))
        self.horizontalLayout_3.addWidget(self.tmeReport)
        self.verticalLayout.addWidget(self.fraReport)
        self.frame_4 = QFrame(self.centralWidget)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_4 = QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblEnd = QLabel(self.frame_4)
        self.lblEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.lblEnd.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblEnd.setObjectName(_fromUtf8("lblEnd"))
        self.horizontalLayout_4.addWidget(self.lblEnd)
        self.dedEnd = QDateEdit(self.frame_4)
        self.dedEnd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dedEnd.setDate(QtCore.QDate(2002, 1, 1))
        self.dedEnd.setObjectName(_fromUtf8("dedEnd"))
        self.horizontalLayout_4.addWidget(self.dedEnd)
        self.tmeEnd = QTimeEdit(self.frame_4)
        self.tmeEnd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.tmeEnd.setProperty("showGroupSeparator", False)
        self.tmeEnd.setObjectName(_fromUtf8("tmeEnd"))
        self.horizontalLayout_4.addWidget(self.tmeEnd)
        self.verticalLayout.addWidget(self.frame_4)
        self.fraOther = QFrame(self.centralWidget)
        self.fraOther.setFrameShape(QFrame.StyledPanel)
        self.fraOther.setFrameShadow(QFrame.Raised)
        self.fraOther.setObjectName(_fromUtf8("fraOther"))
        self.formLayout = QFormLayout(self.fraOther)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblStartSweeping = QLabel(self.fraOther)
        self.lblStartSweeping.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblStartSweeping.setObjectName(_fromUtf8("lblStartSweeping"))
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.lblStartSweeping)
        self.dedSweepStart = QDateEdit(self.fraOther)
        self.dedSweepStart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dedSweepStart.setObjectName(_fromUtf8("dedSweepStart"))
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.dedSweepStart)
        self.lblEndSweeping = QLabel(self.fraOther)
        self.lblEndSweeping.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lblEndSweeping.setObjectName(_fromUtf8("lblEndSweeping"))
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.lblEndSweeping)
        self.dedSweepEnd = QDateEdit(self.fraOther)
        self.dedSweepEnd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dedSweepEnd.setObjectName(_fromUtf8("dedSweepEnd"))
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.dedSweepEnd)
        self.lblAntecedent = QLabel(self.fraOther)
        self.lblAntecedent.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lblAntecedent.setObjectName(_fromUtf8("lblAntecedent"))
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.lblAntecedent)
        self.txtAntecedent = QLineEdit(self.fraOther)
        self.txtAntecedent.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtAntecedent.setObjectName(_fromUtf8("txtAntecedent"))
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.txtAntecedent)
        self.verticalLayout.addWidget(self.fraOther)
        self.fraButtons = QFrame(self.centralWidget)
        self.fraButtons.setFrameShape(QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QFrame.Raised)
        self.fraButtons.setObjectName(_fromUtf8("fraButtons"))
        self.horizontalLayout = QHBoxLayout(self.fraButtons)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(164, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraButtons)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraButtons)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraButtons)
        frmDates.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmDates)
        QtCore.QMetaObject.connectSlotsByName(frmDates)

    def retranslateUi(self, frmDates):
        frmDates.setWindowTitle(_translate("frmDates", "SWMM Dates Options", None))
        self.lblTimes.setText(_translate("frmDates", "Time (H:M)", None))
        self.lblDays.setText(_translate("frmDates", "Date (M/D/Y)", None))
        self.lblStart.setText(_translate("frmDates", "Start Analysis on", None))
        self.dedStart.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy", None))
        self.tmeStart.setDisplayFormat(_translate("frmDates", "hh:mm", None))
        self.lblStartReporting.setText(_translate("frmDates", "Start Reporting on", None))
        self.dedStartReport.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy", None))
        self.tmeReport.setDisplayFormat(_translate("frmDates", "hh:mm", None))
        self.lblEnd.setText(_translate("frmDates", "End Analysis on", None))
        self.dedEnd.setDisplayFormat(_translate("frmDates", "MM/dd/yyyy", None))
        self.tmeEnd.setDisplayFormat(_translate("frmDates", "hh:mm", None))
        self.lblStartSweeping.setText(_translate("frmDates", "Start Sweeping on", None))
        self.dedSweepStart.setDisplayFormat(_translate("frmDates", "MM/dd", None))
        self.lblEndSweeping.setText(_translate("frmDates", "End Sweeping on", None))
        self.dedSweepEnd.setDisplayFormat(_translate("frmDates", "MM/dd", None))
        self.lblAntecedent.setText(_translate("frmDates", "Antecedent Dry Days", None))
        self.cmdOK.setText(_translate("frmDates", "OK", None))
        self.cmdCancel.setText(_translate("frmDates", "Cancel", None))

