# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmGeneralOptionsDesigner.ui'
#
# Created: Tue Mar 08 16:50:25 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmGeneralOptions(object):
    def setupUi(self, frmGeneralOptions):
        frmGeneralOptions.setObjectName(_fromUtf8("frmGeneralOptions"))
        frmGeneralOptions.resize(364, 438)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGeneralOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmGeneralOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbxProcess = QtGui.QGroupBox(self.centralWidget)
        self.gbxProcess.setObjectName(_fromUtf8("gbxProcess"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbxProcess)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.cbxRainfallRunoff = QtGui.QCheckBox(self.gbxProcess)
        self.cbxRainfallRunoff.setObjectName(_fromUtf8("cbxRainfallRunoff"))
        self.verticalLayout.addWidget(self.cbxRainfallRunoff)
        self.cbxRainfallII = QtGui.QCheckBox(self.gbxProcess)
        self.cbxRainfallII.setObjectName(_fromUtf8("cbxRainfallII"))
        self.verticalLayout.addWidget(self.cbxRainfallII)
        self.cbxSnowmelt = QtGui.QCheckBox(self.gbxProcess)
        self.cbxSnowmelt.setObjectName(_fromUtf8("cbxSnowmelt"))
        self.verticalLayout.addWidget(self.cbxSnowmelt)
        self.cbxGroundwater = QtGui.QCheckBox(self.gbxProcess)
        self.cbxGroundwater.setObjectName(_fromUtf8("cbxGroundwater"))
        self.verticalLayout.addWidget(self.cbxGroundwater)
        self.cbxFlowRouting = QtGui.QCheckBox(self.gbxProcess)
        self.cbxFlowRouting.setObjectName(_fromUtf8("cbxFlowRouting"))
        self.verticalLayout.addWidget(self.cbxFlowRouting)
        self.cbxWaterQuality = QtGui.QCheckBox(self.gbxProcess)
        self.cbxWaterQuality.setObjectName(_fromUtf8("cbxWaterQuality"))
        self.verticalLayout.addWidget(self.cbxWaterQuality)
        self.gridLayout.addWidget(self.gbxProcess, 0, 0, 1, 1)
        self.gbxInfiltration = QtGui.QGroupBox(self.centralWidget)
        self.gbxInfiltration.setObjectName(_fromUtf8("gbxInfiltration"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbxInfiltration)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.rbnHorton = QtGui.QRadioButton(self.gbxInfiltration)
        self.rbnHorton.setObjectName(_fromUtf8("rbnHorton"))
        self.verticalLayout_2.addWidget(self.rbnHorton)
        self.rbnModifiedHorton = QtGui.QRadioButton(self.gbxInfiltration)
        self.rbnModifiedHorton.setObjectName(_fromUtf8("rbnModifiedHorton"))
        self.verticalLayout_2.addWidget(self.rbnModifiedHorton)
        self.rbnGreenAmpt = QtGui.QRadioButton(self.gbxInfiltration)
        self.rbnGreenAmpt.setObjectName(_fromUtf8("rbnGreenAmpt"))
        self.verticalLayout_2.addWidget(self.rbnGreenAmpt)
        self.rbnModifiedGreenAmpt = QtGui.QRadioButton(self.gbxInfiltration)
        self.rbnModifiedGreenAmpt.setObjectName(_fromUtf8("rbnModifiedGreenAmpt"))
        self.verticalLayout_2.addWidget(self.rbnModifiedGreenAmpt)
        self.rbnCurveNumber = QtGui.QRadioButton(self.gbxInfiltration)
        self.rbnCurveNumber.setObjectName(_fromUtf8("rbnCurveNumber"))
        self.verticalLayout_2.addWidget(self.rbnCurveNumber)
        self.gridLayout.addWidget(self.gbxInfiltration, 0, 1, 1, 1)
        self.gbxRouting = QtGui.QGroupBox(self.centralWidget)
        self.gbxRouting.setObjectName(_fromUtf8("gbxRouting"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxRouting)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.rbnSteady = QtGui.QRadioButton(self.gbxRouting)
        self.rbnSteady.setObjectName(_fromUtf8("rbnSteady"))
        self.verticalLayout_3.addWidget(self.rbnSteady)
        self.rbnKinematic = QtGui.QRadioButton(self.gbxRouting)
        self.rbnKinematic.setObjectName(_fromUtf8("rbnKinematic"))
        self.verticalLayout_3.addWidget(self.rbnKinematic)
        self.rbnDynamic = QtGui.QRadioButton(self.gbxRouting)
        self.rbnDynamic.setObjectName(_fromUtf8("rbnDynamic"))
        self.verticalLayout_3.addWidget(self.rbnDynamic)
        self.gridLayout.addWidget(self.gbxRouting, 1, 0, 1, 1)
        self.gbxMiscellaneous = QtGui.QGroupBox(self.centralWidget)
        self.gbxMiscellaneous.setObjectName(_fromUtf8("gbxMiscellaneous"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbxMiscellaneous)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cbxAllowPonding = QtGui.QCheckBox(self.gbxMiscellaneous)
        self.cbxAllowPonding.setObjectName(_fromUtf8("cbxAllowPonding"))
        self.verticalLayout_4.addWidget(self.cbxAllowPonding)
        self.cbxReportControl = QtGui.QCheckBox(self.gbxMiscellaneous)
        self.cbxReportControl.setObjectName(_fromUtf8("cbxReportControl"))
        self.verticalLayout_4.addWidget(self.cbxReportControl)
        self.cbxReportInput = QtGui.QCheckBox(self.gbxMiscellaneous)
        self.cbxReportInput.setObjectName(_fromUtf8("cbxReportInput"))
        self.verticalLayout_4.addWidget(self.cbxReportInput)
        self.lblMinimum = QtGui.QLabel(self.gbxMiscellaneous)
        self.lblMinimum.setObjectName(_fromUtf8("lblMinimum"))
        self.verticalLayout_4.addWidget(self.lblMinimum)
        self.frame_2 = QtGui.QFrame(self.gbxMiscellaneous)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtMinimum = QtGui.QLineEdit(self.frame_2)
        self.txtMinimum.setMinimumSize(QtCore.QSize(50, 0))
        self.txtMinimum.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txtMinimum.setObjectName(_fromUtf8("txtMinimum"))
        self.horizontalLayout_2.addWidget(self.txtMinimum)
        self.lblPercent = QtGui.QLabel(self.frame_2)
        self.lblPercent.setObjectName(_fromUtf8("lblPercent"))
        self.horizontalLayout_2.addWidget(self.lblPercent)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.gbxMiscellaneous, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(161, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.frame)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.frame)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 2)
        frmGeneralOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGeneralOptions)
        QtCore.QMetaObject.connectSlotsByName(frmGeneralOptions)
        frmGeneralOptions.setTabOrder(self.cbxRainfallRunoff, self.cbxRainfallII)
        frmGeneralOptions.setTabOrder(self.cbxRainfallII, self.cbxSnowmelt)
        frmGeneralOptions.setTabOrder(self.cbxSnowmelt, self.cbxGroundwater)
        frmGeneralOptions.setTabOrder(self.cbxGroundwater, self.cbxFlowRouting)
        frmGeneralOptions.setTabOrder(self.cbxFlowRouting, self.cbxWaterQuality)
        frmGeneralOptions.setTabOrder(self.cbxWaterQuality, self.rbnSteady)
        frmGeneralOptions.setTabOrder(self.rbnSteady, self.rbnKinematic)
        frmGeneralOptions.setTabOrder(self.rbnKinematic, self.rbnDynamic)
        frmGeneralOptions.setTabOrder(self.rbnDynamic, self.rbnHorton)
        frmGeneralOptions.setTabOrder(self.rbnHorton, self.rbnModifiedHorton)
        frmGeneralOptions.setTabOrder(self.rbnModifiedHorton, self.rbnGreenAmpt)
        frmGeneralOptions.setTabOrder(self.rbnGreenAmpt, self.rbnModifiedGreenAmpt)
        frmGeneralOptions.setTabOrder(self.rbnModifiedGreenAmpt, self.rbnCurveNumber)
        frmGeneralOptions.setTabOrder(self.rbnCurveNumber, self.cbxAllowPonding)
        frmGeneralOptions.setTabOrder(self.cbxAllowPonding, self.cbxReportControl)
        frmGeneralOptions.setTabOrder(self.cbxReportControl, self.cbxReportInput)
        frmGeneralOptions.setTabOrder(self.cbxReportInput, self.txtMinimum)
        frmGeneralOptions.setTabOrder(self.txtMinimum, self.cmdOK)
        frmGeneralOptions.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmGeneralOptions):
        frmGeneralOptions.setWindowTitle(_translate("frmGeneralOptions", "SWMM General Options", None))
        self.gbxProcess.setTitle(_translate("frmGeneralOptions", "Process Models", None))
        self.cbxRainfallRunoff.setText(_translate("frmGeneralOptions", "Rainfall/Runoff", None))
        self.cbxRainfallII.setText(_translate("frmGeneralOptions", "Rainfall Dependent I/I", None))
        self.cbxSnowmelt.setText(_translate("frmGeneralOptions", "Snow Melt", None))
        self.cbxGroundwater.setText(_translate("frmGeneralOptions", "Groundwater", None))
        self.cbxFlowRouting.setText(_translate("frmGeneralOptions", "Flow Routing", None))
        self.cbxWaterQuality.setText(_translate("frmGeneralOptions", "Water Quality", None))
        self.gbxInfiltration.setTitle(_translate("frmGeneralOptions", "Infiltration Model", None))
        self.rbnHorton.setText(_translate("frmGeneralOptions", "Horton", None))
        self.rbnModifiedHorton.setText(_translate("frmGeneralOptions", "Modified Horton", None))
        self.rbnGreenAmpt.setText(_translate("frmGeneralOptions", "Green-Ampt", None))
        self.rbnModifiedGreenAmpt.setText(_translate("frmGeneralOptions", "Modified Green-Ampt", None))
        self.rbnCurveNumber.setText(_translate("frmGeneralOptions", "Curve Number", None))
        self.gbxRouting.setTitle(_translate("frmGeneralOptions", "Routing Model", None))
        self.rbnSteady.setText(_translate("frmGeneralOptions", "Steady Flow", None))
        self.rbnKinematic.setText(_translate("frmGeneralOptions", "Kinematic Wave", None))
        self.rbnDynamic.setText(_translate("frmGeneralOptions", "Dynamic Wave", None))
        self.gbxMiscellaneous.setTitle(_translate("frmGeneralOptions", "Miscellaneous", None))
        self.cbxAllowPonding.setText(_translate("frmGeneralOptions", "Allow Ponding", None))
        self.cbxReportControl.setText(_translate("frmGeneralOptions", "Report Control Actions", None))
        self.cbxReportInput.setText(_translate("frmGeneralOptions", "Report Input Summary", None))
        self.lblMinimum.setText(_translate("frmGeneralOptions", "Minimum Conduit Slope", None))
        self.lblPercent.setText(_translate("frmGeneralOptions", "(%)", None))
        self.cmdOK.setText(_translate("frmGeneralOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmGeneralOptions", "Cancel", None))

