# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\SWMM\frmInterfaceFilesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmInterfaceFiles(object):
    def setupUi(self, frmInterfaceFiles):
        frmInterfaceFiles.setObjectName("frmInterfaceFiles")
        frmInterfaceFiles.resize(503, 562)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmInterfaceFiles.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmInterfaceFiles)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblUseRainfall = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUseRainfall.sizePolicy().hasHeightForWidth())
        self.lblUseRainfall.setSizePolicy(sizePolicy)
        self.lblUseRainfall.setObjectName("lblUseRainfall")
        self.horizontalLayout_10.addWidget(self.lblUseRainfall)
        self.txtUseRainfall = QtWidgets.QLineEdit(self.frame_2)
        self.txtUseRainfall.setObjectName("txtUseRainfall")
        self.horizontalLayout_10.addWidget(self.txtUseRainfall)
        self.cmdUseRainfall = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUseRainfall.sizePolicy().hasHeightForWidth())
        self.cmdUseRainfall.setSizePolicy(sizePolicy)
        self.cmdUseRainfall.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdUseRainfall.setObjectName("cmdUseRainfall")
        self.horizontalLayout_10.addWidget(self.cmdUseRainfall)
        self.txtUseRainfall.raise_()
        self.cmdUseRainfall.raise_()
        self.lblUseRainfall.raise_()
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lblSaveRainfall = QtWidgets.QLabel(self.frame_3)
        self.lblSaveRainfall.setObjectName("lblSaveRainfall")
        self.horizontalLayout_11.addWidget(self.lblSaveRainfall)
        self.txtSaveRainfall = QtWidgets.QLineEdit(self.frame_3)
        self.txtSaveRainfall.setObjectName("txtSaveRainfall")
        self.horizontalLayout_11.addWidget(self.txtSaveRainfall)
        self.cmdSaveRainfall = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdSaveRainfall.sizePolicy().hasHeightForWidth())
        self.cmdSaveRainfall.setSizePolicy(sizePolicy)
        self.cmdSaveRainfall.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdSaveRainfall.setObjectName("cmdSaveRainfall")
        self.horizontalLayout_11.addWidget(self.cmdSaveRainfall)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lblUseRunoff = QtWidgets.QLabel(self.frame_4)
        self.lblUseRunoff.setObjectName("lblUseRunoff")
        self.horizontalLayout_9.addWidget(self.lblUseRunoff)
        self.txtUseRunoff = QtWidgets.QLineEdit(self.frame_4)
        self.txtUseRunoff.setObjectName("txtUseRunoff")
        self.horizontalLayout_9.addWidget(self.txtUseRunoff)
        self.cmdUseRunoff = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUseRunoff.sizePolicy().hasHeightForWidth())
        self.cmdUseRunoff.setSizePolicy(sizePolicy)
        self.cmdUseRunoff.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdUseRunoff.setObjectName("cmdUseRunoff")
        self.horizontalLayout_9.addWidget(self.cmdUseRunoff)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblSaveRunoff = QtWidgets.QLabel(self.frame_5)
        self.lblSaveRunoff.setObjectName("lblSaveRunoff")
        self.horizontalLayout_8.addWidget(self.lblSaveRunoff)
        self.txtSaveRunoff = QtWidgets.QLineEdit(self.frame_5)
        self.txtSaveRunoff.setObjectName("txtSaveRunoff")
        self.horizontalLayout_8.addWidget(self.txtSaveRunoff)
        self.cmdSaveRunoff = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdSaveRunoff.sizePolicy().hasHeightForWidth())
        self.cmdSaveRunoff.setSizePolicy(sizePolicy)
        self.cmdSaveRunoff.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdSaveRunoff.setObjectName("cmdSaveRunoff")
        self.horizontalLayout_8.addWidget(self.cmdSaveRunoff)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblUseHotstart = QtWidgets.QLabel(self.frame_6)
        self.lblUseHotstart.setObjectName("lblUseHotstart")
        self.horizontalLayout_7.addWidget(self.lblUseHotstart)
        self.txtUseHotstart = QtWidgets.QLineEdit(self.frame_6)
        self.txtUseHotstart.setObjectName("txtUseHotstart")
        self.horizontalLayout_7.addWidget(self.txtUseHotstart)
        self.cmdUseHotstart = QtWidgets.QPushButton(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUseHotstart.sizePolicy().hasHeightForWidth())
        self.cmdUseHotstart.setSizePolicy(sizePolicy)
        self.cmdUseHotstart.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdUseHotstart.setObjectName("cmdUseHotstart")
        self.horizontalLayout_7.addWidget(self.cmdUseHotstart)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblSaveHotstart = QtWidgets.QLabel(self.frame_7)
        self.lblSaveHotstart.setObjectName("lblSaveHotstart")
        self.horizontalLayout_6.addWidget(self.lblSaveHotstart)
        self.txtSaveHotstart = QtWidgets.QLineEdit(self.frame_7)
        self.txtSaveHotstart.setObjectName("txtSaveHotstart")
        self.horizontalLayout_6.addWidget(self.txtSaveHotstart)
        self.cmdSaveHotstart = QtWidgets.QPushButton(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdSaveHotstart.sizePolicy().hasHeightForWidth())
        self.cmdSaveHotstart.setSizePolicy(sizePolicy)
        self.cmdSaveHotstart.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdSaveHotstart.setObjectName("cmdSaveHotstart")
        self.horizontalLayout_6.addWidget(self.cmdSaveHotstart)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblUseRDII = QtWidgets.QLabel(self.frame_8)
        self.lblUseRDII.setObjectName("lblUseRDII")
        self.horizontalLayout_5.addWidget(self.lblUseRDII)
        self.txtUseRDII = QtWidgets.QLineEdit(self.frame_8)
        self.txtUseRDII.setObjectName("txtUseRDII")
        self.horizontalLayout_5.addWidget(self.txtUseRDII)
        self.cmdUseRDII = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUseRDII.sizePolicy().hasHeightForWidth())
        self.cmdUseRDII.setSizePolicy(sizePolicy)
        self.cmdUseRDII.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdUseRDII.setObjectName("cmdUseRDII")
        self.horizontalLayout_5.addWidget(self.cmdUseRDII)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblSaveRDII = QtWidgets.QLabel(self.frame_9)
        self.lblSaveRDII.setObjectName("lblSaveRDII")
        self.horizontalLayout_4.addWidget(self.lblSaveRDII)
        self.txtSaveRDII = QtWidgets.QLineEdit(self.frame_9)
        self.txtSaveRDII.setObjectName("txtSaveRDII")
        self.horizontalLayout_4.addWidget(self.txtSaveRDII)
        self.cmdSaveRDII = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdSaveRDII.sizePolicy().hasHeightForWidth())
        self.cmdSaveRDII.setSizePolicy(sizePolicy)
        self.cmdSaveRDII.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdSaveRDII.setObjectName("cmdSaveRDII")
        self.horizontalLayout_4.addWidget(self.cmdSaveRDII)
        self.verticalLayout.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblUseInflows = QtWidgets.QLabel(self.frame_10)
        self.lblUseInflows.setObjectName("lblUseInflows")
        self.horizontalLayout_3.addWidget(self.lblUseInflows)
        self.txtUseInflows = QtWidgets.QLineEdit(self.frame_10)
        self.txtUseInflows.setObjectName("txtUseInflows")
        self.horizontalLayout_3.addWidget(self.txtUseInflows)
        self.cmdUseInflows = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdUseInflows.sizePolicy().hasHeightForWidth())
        self.cmdUseInflows.setSizePolicy(sizePolicy)
        self.cmdUseInflows.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdUseInflows.setObjectName("cmdUseInflows")
        self.horizontalLayout_3.addWidget(self.cmdUseInflows)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.centralWidget)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblSaveOutflows = QtWidgets.QLabel(self.frame_11)
        self.lblSaveOutflows.setObjectName("lblSaveOutflows")
        self.horizontalLayout_2.addWidget(self.lblSaveOutflows)
        self.txtSaveOutflows = QtWidgets.QLineEdit(self.frame_11)
        self.txtSaveOutflows.setObjectName("txtSaveOutflows")
        self.horizontalLayout_2.addWidget(self.txtSaveOutflows)
        self.cmdSaveInflows = QtWidgets.QPushButton(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmdSaveInflows.sizePolicy().hasHeightForWidth())
        self.cmdSaveInflows.setSizePolicy(sizePolicy)
        self.cmdSaveInflows.setMaximumSize(QtCore.QSize(31, 16777215))
        self.cmdSaveInflows.setObjectName("cmdSaveInflows")
        self.horizontalLayout_2.addWidget(self.cmdSaveInflows)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(249, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.frame)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.frame)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.frame)
        frmInterfaceFiles.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmInterfaceFiles)
        QtCore.QMetaObject.connectSlotsByName(frmInterfaceFiles)
        frmInterfaceFiles.setTabOrder(self.txtSaveRainfall, self.txtUseRunoff)
        frmInterfaceFiles.setTabOrder(self.txtUseRunoff, self.txtUseHotstart)
        frmInterfaceFiles.setTabOrder(self.txtUseHotstart, self.txtSaveHotstart)
        frmInterfaceFiles.setTabOrder(self.txtSaveHotstart, self.txtUseRDII)
        frmInterfaceFiles.setTabOrder(self.txtUseRDII, self.txtSaveRDII)
        frmInterfaceFiles.setTabOrder(self.txtSaveRDII, self.txtUseInflows)
        frmInterfaceFiles.setTabOrder(self.txtUseInflows, self.txtSaveOutflows)
        frmInterfaceFiles.setTabOrder(self.txtSaveOutflows, self.cmdOK)
        frmInterfaceFiles.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmInterfaceFiles):
        _translate = QtCore.QCoreApplication.translate
        frmInterfaceFiles.setWindowTitle(_translate("frmInterfaceFiles", "SWMM Interface File Options"))
        self.lblUseRainfall.setText(_translate("frmInterfaceFiles", "<html><head/><body><p>Use Rainfall</p></body></html>"))
        self.cmdUseRainfall.setText(_translate("frmInterfaceFiles", "..."))
        self.lblSaveRainfall.setText(_translate("frmInterfaceFiles", "Save Rainfall"))
        self.cmdSaveRainfall.setText(_translate("frmInterfaceFiles", "..."))
        self.lblUseRunoff.setText(_translate("frmInterfaceFiles", "Use Runoff"))
        self.cmdUseRunoff.setText(_translate("frmInterfaceFiles", "..."))
        self.lblSaveRunoff.setText(_translate("frmInterfaceFiles", "Save Runoff"))
        self.cmdSaveRunoff.setText(_translate("frmInterfaceFiles", "..."))
        self.lblUseHotstart.setText(_translate("frmInterfaceFiles", "Use Hotstart"))
        self.cmdUseHotstart.setText(_translate("frmInterfaceFiles", "..."))
        self.lblSaveHotstart.setText(_translate("frmInterfaceFiles", "Save Hotstart"))
        self.cmdSaveHotstart.setText(_translate("frmInterfaceFiles", "..."))
        self.lblUseRDII.setText(_translate("frmInterfaceFiles", "Use RDII"))
        self.cmdUseRDII.setText(_translate("frmInterfaceFiles", "..."))
        self.lblSaveRDII.setText(_translate("frmInterfaceFiles", "Save RDII"))
        self.cmdSaveRDII.setText(_translate("frmInterfaceFiles", "..."))
        self.lblUseInflows.setText(_translate("frmInterfaceFiles", "Use Inflows"))
        self.cmdUseInflows.setText(_translate("frmInterfaceFiles", "..."))
        self.lblSaveOutflows.setText(_translate("frmInterfaceFiles", "Save Outflows"))
        self.cmdSaveInflows.setText(_translate("frmInterfaceFiles", "..."))
        self.cmdOK.setText(_translate("frmInterfaceFiles", "OK"))
        self.cmdCancel.setText(_translate("frmInterfaceFiles", "Cancel"))

