# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\SWMM\frmLIDControlsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmLIDControls(object):
    def setupUi(self, frmLIDControls):
        frmLIDControls.setObjectName("frmLIDControls")
        frmLIDControls.resize(644, 245)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmLIDControls.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmLIDControls)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tblControls = QtWidgets.QTableWidget(self.fraTop)
        self.tblControls.setColumnCount(6)
        self.tblControls.setObjectName("tblControls")
        self.tblControls.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblControls.setHorizontalHeaderItem(5, item)
        self.horizontalLayout_2.addWidget(self.tblControls)
        self.fraButtons = QtWidgets.QFrame(self.fraTop)
        self.fraButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraButtons.setObjectName("fraButtons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraButtons)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.fraButtons)
        self.btnAdd.setObjectName("btnAdd")
        self.verticalLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(self.fraButtons)
        self.btnEdit.setObjectName("btnEdit")
        self.verticalLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(self.fraButtons)
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout.addWidget(self.btnDelete)
        self.horizontalLayout_2.addWidget(self.fraButtons)
        self.verticalLayout_2.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_2.addWidget(self.fraOKCancel)
        frmLIDControls.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmLIDControls)
        QtCore.QMetaObject.connectSlotsByName(frmLIDControls)

    def retranslateUi(self, frmLIDControls):
        _translate = QtCore.QCoreApplication.translate
        frmLIDControls.setWindowTitle(_translate("frmLIDControls", "SWMM LID Controls"))
        item = self.tblControls.horizontalHeaderItem(0)
        item.setText(_translate("frmLIDControls", "Control Name"))
        item = self.tblControls.horizontalHeaderItem(1)
        item.setText(_translate("frmLIDControls", "LID Type"))
        item = self.tblControls.horizontalHeaderItem(2)
        item.setText(_translate("frmLIDControls", "% of Area"))
        item = self.tblControls.horizontalHeaderItem(3)
        item.setText(_translate("frmLIDControls", "% From Imperv"))
        item = self.tblControls.horizontalHeaderItem(4)
        item.setText(_translate("frmLIDControls", "% From Perv"))
        item = self.tblControls.horizontalHeaderItem(5)
        item.setText(_translate("frmLIDControls", "Report File"))
        self.btnAdd.setText(_translate("frmLIDControls", "Add"))
        self.btnEdit.setText(_translate("frmLIDControls", "Edit"))
        self.btnDelete.setText(_translate("frmLIDControls", "Delete"))
        self.cmdOK.setText(_translate("frmLIDControls", "OK"))
        self.cmdCancel.setText(_translate("frmLIDControls", "Cancel"))

