# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmLIDUsageDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmLIDUsage(object):
    def setupUi(self, frmLIDUsage):
        frmLIDUsage.setObjectName(_fromUtf8("frmLIDUsage"))
        frmLIDUsage.resize(691, 382)
        font = QFont()
        font.setPointSize(10)
        frmLIDUsage.setFont(font)
        self.centralWidget = QWidget(frmLIDUsage)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QVBoxLayout(self.centralWidget)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fraTop = QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraTop)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fraLeft = QFrame(self.fraTop)
        self.fraLeft.setFrameShape(QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QFrame.Raised)
        self.fraLeft.setObjectName(_fromUtf8("fraLeft"))
        self.verticalLayout_2 = QVBoxLayout(self.fraLeft)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraTopLeft = QFrame(self.fraLeft)
        self.fraTopLeft.setFrameShape(QFrame.StyledPanel)
        self.fraTopLeft.setFrameShadow(QFrame.Raised)
        self.fraTopLeft.setObjectName(_fromUtf8("fraTopLeft"))
        self.gridLayout_12 = QGridLayout(self.fraTopLeft)
        # self.gridLayout_12.setMargin(11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.lblLIDControlName = QLabel(self.fraTopLeft)
        self.lblLIDControlName.setObjectName(_fromUtf8("lblLIDControlName"))
        self.gridLayout_12.addWidget(self.lblLIDControlName, 0, 0, 1, 1)
        self.cboLIDControl = QComboBox(self.fraTopLeft)
        self.cboLIDControl.setObjectName(_fromUtf8("cboLIDControl"))
        self.gridLayout_12.addWidget(self.cboLIDControl, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.fraTopLeft)
        self.lblImage = QLabel(self.fraLeft)
        self.lblImage.setText(_fromUtf8(""))
        self.lblImage.setObjectName(_fromUtf8("lblImage"))
        self.verticalLayout_2.addWidget(self.lblImage)
        self.fraBotLeft = QFrame(self.fraLeft)
        self.fraBotLeft.setFrameShape(QFrame.StyledPanel)
        self.fraBotLeft.setFrameShadow(QFrame.Raised)
        self.fraBotLeft.setObjectName(_fromUtf8("fraBotLeft"))
        self.gridLayout_13 = QGridLayout(self.fraBotLeft)
        # self.gridLayout_13.setMargin(11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lblFile = QLabel(self.fraBotLeft)
        self.lblFile.setObjectName(_fromUtf8("lblFile"))
        self.gridLayout_13.addWidget(self.lblFile, 0, 0, 1, 1)
        self.btnFile = QToolButton(self.fraBotLeft)
        self.btnFile.setObjectName(_fromUtf8("btnFile"))
        self.gridLayout_13.addWidget(self.btnFile, 0, 1, 1, 1)
        self.btnClear = QToolButton(self.fraBotLeft)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.gridLayout_13.addWidget(self.btnClear, 0, 2, 1, 1)
        self.txtFile = QLineEdit(self.fraBotLeft)
        self.txtFile.setObjectName(_fromUtf8("txtFile"))
        self.gridLayout_13.addWidget(self.txtFile, 1, 0, 1, 3)
        self.verticalLayout_2.addWidget(self.fraBotLeft)
        self.horizontalLayout_2.addWidget(self.fraLeft)
        self.line = QFrame(self.fraTop)
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.fraRight = QFrame(self.fraTop)
        self.fraRight.setFrameShape(QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QFrame.Raised)
        self.fraRight.setObjectName(_fromUtf8("fraRight"))
        self.gridLayout_2 = QGridLayout(self.fraRight)
        # self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbxFull = QCheckBox(self.fraRight)
        self.cbxFull.setObjectName(_fromUtf8("cbxFull"))
        self.gridLayout_2.addWidget(self.cbxFull, 0, 0, 1, 2)
        self.lblArea = QLabel(self.fraRight)
        self.lblArea.setObjectName(_fromUtf8("lblArea"))
        self.gridLayout_2.addWidget(self.lblArea, 1, 0, 1, 1)
        self.txtArea = QLineEdit(self.fraRight)
        self.txtArea.setObjectName(_fromUtf8("txtArea"))
        self.gridLayout_2.addWidget(self.txtArea, 1, 1, 1, 1)
        self.lblUnits = QLabel(self.fraRight)
        self.lblUnits.setObjectName(_fromUtf8("lblUnits"))
        self.gridLayout_2.addWidget(self.lblUnits, 2, 0, 1, 1)
        self.spxUnits = QSpinBox(self.fraRight)
        self.spxUnits.setObjectName(_fromUtf8("spxUnits"))
        self.gridLayout_2.addWidget(self.spxUnits, 2, 1, 1, 1)
        self.lblOccupied = QLabel(self.fraRight)
        self.lblOccupied.setObjectName(_fromUtf8("lblOccupied"))
        self.gridLayout_2.addWidget(self.lblOccupied, 3, 0, 1, 1)
        self.lblPercent = QLabel(self.fraRight)
        self.lblPercent.setObjectName(_fromUtf8("lblPercent"))
        self.gridLayout_2.addWidget(self.lblPercent, 3, 1, 1, 1)
        self.lblWidth = QLabel(self.fraRight)
        self.lblWidth.setObjectName(_fromUtf8("lblWidth"))
        self.gridLayout_2.addWidget(self.lblWidth, 4, 0, 1, 1)
        self.txtWidth = QLineEdit(self.fraRight)
        self.txtWidth.setObjectName(_fromUtf8("txtWidth"))
        self.gridLayout_2.addWidget(self.txtWidth, 4, 1, 1, 1)
        self.lblSat = QLabel(self.fraRight)
        self.lblSat.setObjectName(_fromUtf8("lblSat"))
        self.gridLayout_2.addWidget(self.lblSat, 5, 0, 1, 1)
        self.txtSat = QLineEdit(self.fraRight)
        self.txtSat.setObjectName(_fromUtf8("txtSat"))
        self.gridLayout_2.addWidget(self.txtSat, 5, 1, 1, 1)
        self.lblTreated = QLabel(self.fraRight)
        self.lblTreated.setObjectName(_fromUtf8("lblTreated"))
        self.gridLayout_2.addWidget(self.lblTreated, 6, 0, 1, 1)
        self.txtTreated = QLineEdit(self.fraRight)
        self.txtTreated.setObjectName(_fromUtf8("txtTreated"))
        self.gridLayout_2.addWidget(self.txtTreated, 6, 1, 1, 1)
        self.lblDrain = QLabel(self.fraRight)
        self.lblDrain.setWordWrap(True)
        self.lblDrain.setObjectName(_fromUtf8("lblDrain"))
        self.gridLayout_2.addWidget(self.lblDrain, 7, 0, 1, 2)
        self.txtDrain = QLineEdit(self.fraRight)
        self.txtDrain.setObjectName(_fromUtf8("txtDrain"))
        self.gridLayout_2.addWidget(self.txtDrain, 8, 0, 1, 1)
        self.cbkReturn = QCheckBox(self.fraRight)
        self.cbkReturn.setObjectName(_fromUtf8("cbkReturn"))
        self.gridLayout_2.addWidget(self.cbkReturn, 9, 0, 1, 2)
        self.horizontalLayout_2.addWidget(self.fraRight)
        self.verticalLayout.addWidget(self.fraTop)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmLIDUsage.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmLIDUsage)
        QtCore.QMetaObject.connectSlotsByName(frmLIDUsage)

    def retranslateUi(self, frmLIDUsage):
        frmLIDUsage.setWindowTitle(_translate("frmLIDUsage", "SWMM LID Usage Editor", None))
        self.lblLIDControlName.setText(_translate("frmLIDUsage", "LID Control Name", None))
        self.lblFile.setText(_translate("frmLIDUsage", "Detailed Report File (Optional)", None))
        self.btnFile.setText(_translate("frmLIDUsage", "...", None))
        self.btnClear.setText(_translate("frmLIDUsage", "X", None))
        self.cbxFull.setText(_translate("frmLIDUsage", "LID Occupies Full Subcatchment", None))
        self.lblArea.setText(_translate("frmLIDUsage", "Area of Each Unit (sq ft or sq m)", None))
        self.lblUnits.setText(_translate("frmLIDUsage", "Number of Units", None))
        self.lblOccupied.setText(_translate("frmLIDUsage", "% of Subcatchment Occupied", None))
        self.lblPercent.setText(_translate("frmLIDUsage", "100.0", None))
        self.lblWidth.setText(_translate("frmLIDUsage", "Surface Width per Unit (ft or m)", None))
        self.lblSat.setText(_translate("frmLIDUsage", "% Initially Saturated", None))
        self.lblTreated.setText(_translate("frmLIDUsage", "% of Impervious Area Treated", None))
        self.lblDrain.setText(_translate("frmLIDUsage", "Set Drain Flow To: \n"
"Leave Blank to use outlet of current subcatchment", None))
        self.cbkReturn.setText(_translate("frmLIDUsage", "Return all Outflow to Pervious Area", None))
        self.cmdOK.setText(_translate("frmLIDUsage", "OK", None))
        self.cmdCancel.setText(_translate("frmLIDUsage", "Cancel", None))

