# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmLandUsesDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmLandUsesEditor(object):
    def setupUi(self, frmLandUsesEditor):
        frmLandUsesEditor.setObjectName(_fromUtf8("frmLandUsesEditor"))
        frmLandUsesEditor.resize(401, 383)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmLandUsesEditor.setFont(font)
        self.centralWidget = QtGui.QWidget(frmLandUsesEditor)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabLanduse = QtGui.QTabWidget(self.centralWidget)
        self.tabLanduse.setObjectName(_fromUtf8("tabLanduse"))
        self.General = QtGui.QWidget()
        self.General.setObjectName(_fromUtf8("General"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.General)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraGeneral = QtGui.QFrame(self.General)
        self.fraGeneral.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraGeneral.setFrameShadow(QtGui.QFrame.Raised)
        self.fraGeneral.setObjectName(_fromUtf8("fraGeneral"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraGeneral)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tblGeneral = QtGui.QTableWidget(self.fraGeneral)
        self.tblGeneral.setObjectName(_fromUtf8("tblGeneral"))
        self.tblGeneral.setColumnCount(1)
        self.tblGeneral.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblGeneral.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_2.addWidget(self.tblGeneral)
        self.verticalLayout_2.addWidget(self.fraGeneral)
        self.fraNotesGeneral = QtGui.QFrame(self.General)
        self.fraNotesGeneral.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraNotesGeneral.setFrameShadow(QtGui.QFrame.Raised)
        self.fraNotesGeneral.setObjectName(_fromUtf8("fraNotesGeneral"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fraNotesGeneral)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblNotesGeneral = QtGui.QLabel(self.fraNotesGeneral)
        self.lblNotesGeneral.setWordWrap(True)
        self.lblNotesGeneral.setObjectName(_fromUtf8("lblNotesGeneral"))
        self.verticalLayout.addWidget(self.lblNotesGeneral)
        self.verticalLayout_2.addWidget(self.fraNotesGeneral)
        self.tabLanduse.addTab(self.General, _fromUtf8(""))
        self.Buildup = QtGui.QWidget()
        self.Buildup.setObjectName(_fromUtf8("Buildup"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Buildup)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.fraBuildup = QtGui.QFrame(self.Buildup)
        self.fraBuildup.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraBuildup.setFrameShadow(QtGui.QFrame.Raised)
        self.fraBuildup.setObjectName(_fromUtf8("fraBuildup"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraBuildup)
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tblBuildup = QtGui.QTableWidget(self.fraBuildup)
        self.tblBuildup.setObjectName(_fromUtf8("tblBuildup"))
        self.tblBuildup.setColumnCount(1)
        self.tblBuildup.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblBuildup.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_3.addWidget(self.tblBuildup)
        self.verticalLayout_6.addWidget(self.fraBuildup)
        self.fraNotesBuildup = QtGui.QFrame(self.Buildup)
        self.fraNotesBuildup.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraNotesBuildup.setFrameShadow(QtGui.QFrame.Raised)
        self.fraNotesBuildup.setObjectName(_fromUtf8("fraNotesBuildup"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.fraNotesBuildup)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblNotesBuildup = QtGui.QLabel(self.fraNotesBuildup)
        self.lblNotesBuildup.setWordWrap(True)
        self.lblNotesBuildup.setObjectName(_fromUtf8("lblNotesBuildup"))
        self.verticalLayout_4.addWidget(self.lblNotesBuildup)
        self.verticalLayout_6.addWidget(self.fraNotesBuildup)
        self.tabLanduse.addTab(self.Buildup, _fromUtf8(""))
        self.Washoff = QtGui.QWidget()
        self.Washoff.setObjectName(_fromUtf8("Washoff"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Washoff)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.fraWashoff = QtGui.QFrame(self.Washoff)
        self.fraWashoff.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraWashoff.setFrameShadow(QtGui.QFrame.Raised)
        self.fraWashoff.setObjectName(_fromUtf8("fraWashoff"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fraWashoff)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tblWashoff = QtGui.QTableWidget(self.fraWashoff)
        self.tblWashoff.setObjectName(_fromUtf8("tblWashoff"))
        self.tblWashoff.setColumnCount(1)
        self.tblWashoff.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblWashoff.setHorizontalHeaderItem(0, item)
        self.horizontalLayout_4.addWidget(self.tblWashoff)
        self.verticalLayout_7.addWidget(self.fraWashoff)
        self.fraNotesWashoff = QtGui.QFrame(self.Washoff)
        self.fraNotesWashoff.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraNotesWashoff.setFrameShadow(QtGui.QFrame.Raised)
        self.fraNotesWashoff.setObjectName(_fromUtf8("fraNotesWashoff"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.fraNotesWashoff)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblNotesWashoff = QtGui.QLabel(self.fraNotesWashoff)
        self.lblNotesWashoff.setWordWrap(True)
        self.lblNotesWashoff.setObjectName(_fromUtf8("lblNotesWashoff"))
        self.verticalLayout_5.addWidget(self.lblNotesWashoff)
        self.verticalLayout_7.addWidget(self.fraNotesWashoff)
        self.tabLanduse.addTab(self.Washoff, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabLanduse)
        self.fraOKCancel = QtGui.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtGui.QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmLandUsesEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmLandUsesEditor)
        self.tabLanduse.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmLandUsesEditor)

    def retranslateUi(self, frmLandUsesEditor):
        frmLandUsesEditor.setWindowTitle(_translate("frmLandUsesEditor", "SWMM Land Use Editor", None))
        item = self.tblGeneral.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value", None))
        self.lblNotesGeneral.setText(_translate("frmLandUsesEditor", "Explanatory notes", None))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.General), _translate("frmLandUsesEditor", "General", None))
        item = self.tblBuildup.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value", None))
        self.lblNotesBuildup.setText(_translate("frmLandUsesEditor", "Explanatory notes", None))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.Buildup), _translate("frmLandUsesEditor", "Buildup", None))
        item = self.tblWashoff.horizontalHeaderItem(0)
        item.setText(_translate("frmLandUsesEditor", "Value", None))
        self.lblNotesWashoff.setText(_translate("frmLandUsesEditor", "Explanatory notes", None))
        self.tabLanduse.setTabText(self.tabLanduse.indexOf(self.Washoff), _translate("frmLandUsesEditor", "Washoff", None))
        self.cmdOK.setText(_translate("frmLandUsesEditor", "OK", None))
        self.cmdCancel.setText(_translate("frmLandUsesEditor", "Cancel", None))

