# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmReportOptionsDesigner.ui'
#
# Created: Tue Mar 08 16:50:57 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmReportOptions(object):
    def setupUi(self, frmReportOptions):
        frmReportOptions.setObjectName(_fromUtf8("frmReportOptions"))
        frmReportOptions.resize(578, 364)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmReportOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmReportOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gbxReport = QtGui.QGroupBox(self.centralWidget)
        self.gbxReport.setObjectName(_fromUtf8("gbxReport"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbxReport)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cbxInput = QtGui.QCheckBox(self.gbxReport)
        self.cbxInput.setObjectName(_fromUtf8("cbxInput"))
        self.horizontalLayout.addWidget(self.cbxInput)
        self.cbxContinuity = QtGui.QCheckBox(self.gbxReport)
        self.cbxContinuity.setObjectName(_fromUtf8("cbxContinuity"))
        self.horizontalLayout.addWidget(self.cbxContinuity)
        self.cbxFlow = QtGui.QCheckBox(self.gbxReport)
        self.cbxFlow.setObjectName(_fromUtf8("cbxFlow"))
        self.horizontalLayout.addWidget(self.cbxFlow)
        self.cbxControls = QtGui.QCheckBox(self.gbxReport)
        self.cbxControls.setObjectName(_fromUtf8("cbxControls"))
        self.horizontalLayout.addWidget(self.cbxControls)
        self.verticalLayout.addWidget(self.gbxReport)
        self.fraObjects = QtGui.QFrame(self.centralWidget)
        self.fraObjects.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraObjects.setFrameShadow(QtGui.QFrame.Raised)
        self.fraObjects.setObjectName(_fromUtf8("fraObjects"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraObjects)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gbxNode = QtGui.QGroupBox(self.fraObjects)
        self.gbxNode.setObjectName(_fromUtf8("gbxNode"))
        self.gridLayout = QtGui.QGridLayout(self.gbxNode)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidget = QtGui.QListWidget(self.gbxNode)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 2)
        self.cmdNodeAll = QtGui.QPushButton(self.gbxNode)
        self.cmdNodeAll.setObjectName(_fromUtf8("cmdNodeAll"))
        self.gridLayout.addWidget(self.cmdNodeAll, 1, 0, 1, 1)
        self.cmdNodeNone = QtGui.QPushButton(self.gbxNode)
        self.cmdNodeNone.setObjectName(_fromUtf8("cmdNodeNone"))
        self.gridLayout.addWidget(self.cmdNodeNone, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.gbxNode)
        self.gbxLinks = QtGui.QGroupBox(self.fraObjects)
        self.gbxLinks.setObjectName(_fromUtf8("gbxLinks"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbxLinks)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.listWidget_2 = QtGui.QListWidget(self.gbxLinks)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_2.addWidget(self.listWidget_2, 0, 0, 1, 2)
        self.cmdLinksAll = QtGui.QPushButton(self.gbxLinks)
        self.cmdLinksAll.setObjectName(_fromUtf8("cmdLinksAll"))
        self.gridLayout_2.addWidget(self.cmdLinksAll, 1, 0, 1, 1)
        self.cmdLinksNone = QtGui.QPushButton(self.gbxLinks)
        self.cmdLinksNone.setObjectName(_fromUtf8("cmdLinksNone"))
        self.gridLayout_2.addWidget(self.cmdLinksNone, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.gbxLinks)
        self.gbxSubcatchments = QtGui.QGroupBox(self.fraObjects)
        self.gbxSubcatchments.setObjectName(_fromUtf8("gbxSubcatchments"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbxSubcatchments)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.listWidget_3 = QtGui.QListWidget(self.gbxSubcatchments)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.gridLayout_3.addWidget(self.listWidget_3, 0, 0, 1, 2)
        self.cmdSubcatchmentsAll = QtGui.QPushButton(self.gbxSubcatchments)
        self.cmdSubcatchmentsAll.setObjectName(_fromUtf8("cmdSubcatchmentsAll"))
        self.gridLayout_3.addWidget(self.cmdSubcatchmentsAll, 1, 0, 1, 1)
        self.cmdSubcatchmentsNone = QtGui.QPushButton(self.gbxSubcatchments)
        self.cmdSubcatchmentsNone.setObjectName(_fromUtf8("cmdSubcatchmentsNone"))
        self.gridLayout_3.addWidget(self.cmdSubcatchmentsNone, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.gbxSubcatchments)
        self.verticalLayout.addWidget(self.fraObjects)
        self.fraButtons = QtGui.QFrame(self.centralWidget)
        self.fraButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.fraButtons.setObjectName(_fromUtf8("fraButtons"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraButtons)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(375, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.fraButtons)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout_2.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.fraButtons)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout_2.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraButtons)
        frmReportOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmReportOptions)
        QtCore.QMetaObject.connectSlotsByName(frmReportOptions)
        frmReportOptions.setTabOrder(self.cbxInput, self.cbxContinuity)
        frmReportOptions.setTabOrder(self.cbxContinuity, self.cbxFlow)
        frmReportOptions.setTabOrder(self.cbxFlow, self.cbxControls)
        frmReportOptions.setTabOrder(self.cbxControls, self.listWidget)
        frmReportOptions.setTabOrder(self.listWidget, self.cmdNodeAll)
        frmReportOptions.setTabOrder(self.cmdNodeAll, self.cmdNodeNone)
        frmReportOptions.setTabOrder(self.cmdNodeNone, self.listWidget_2)
        frmReportOptions.setTabOrder(self.listWidget_2, self.cmdLinksAll)
        frmReportOptions.setTabOrder(self.cmdLinksAll, self.cmdLinksNone)
        frmReportOptions.setTabOrder(self.cmdLinksNone, self.listWidget_3)
        frmReportOptions.setTabOrder(self.listWidget_3, self.cmdSubcatchmentsAll)
        frmReportOptions.setTabOrder(self.cmdSubcatchmentsAll, self.cmdSubcatchmentsNone)
        frmReportOptions.setTabOrder(self.cmdSubcatchmentsNone, self.cmdOK)
        frmReportOptions.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmReportOptions):
        frmReportOptions.setWindowTitle(_translate("frmReportOptions", "SWMM Report Options", None))
        self.gbxReport.setTitle(_translate("frmReportOptions", "Report Options", None))
        self.cbxInput.setText(_translate("frmReportOptions", "Input Summary", None))
        self.cbxContinuity.setText(_translate("frmReportOptions", "Continuity Checks", None))
        self.cbxFlow.setText(_translate("frmReportOptions", "Flow Stats", None))
        self.cbxControls.setText(_translate("frmReportOptions", "Controls", None))
        self.gbxNode.setTitle(_translate("frmReportOptions", "Nodes", None))
        self.cmdNodeAll.setText(_translate("frmReportOptions", "All", None))
        self.cmdNodeNone.setText(_translate("frmReportOptions", "None", None))
        self.gbxLinks.setTitle(_translate("frmReportOptions", "Links", None))
        self.cmdLinksAll.setText(_translate("frmReportOptions", "All", None))
        self.cmdLinksNone.setText(_translate("frmReportOptions", "None", None))
        self.gbxSubcatchments.setTitle(_translate("frmReportOptions", "Subcatchments", None))
        self.cmdSubcatchmentsAll.setText(_translate("frmReportOptions", "All", None))
        self.cmdSubcatchmentsNone.setText(_translate("frmReportOptions", "None", None))
        self.cmdOK.setText(_translate("frmReportOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmReportOptions", "Cancel", None))

