# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmSnowPackDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmSnowPack(object):
    def setupUi(self, frmSnowPack):
        frmSnowPack.setObjectName(_fromUtf8("frmSnowPack"))
        frmSnowPack.resize(562, 496)
        font = QFont()
        font.setPointSize(10)
        frmSnowPack.setFont(font)
        self.centralWidget = QWidget(frmSnowPack)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_3 = QVBoxLayout(self.centralWidget)
        # self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.fraTop = QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraTop)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblSnow = QLabel(self.fraTop)
        self.lblSnow.setObjectName(_fromUtf8("lblSnow"))
        self.horizontalLayout_2.addWidget(self.lblSnow)
        self.txtSnow = QLineEdit(self.fraTop)
        self.txtSnow.setObjectName(_fromUtf8("txtSnow"))
        self.horizontalLayout_2.addWidget(self.txtSnow)
        self.verticalLayout_3.addWidget(self.fraTop)
        self.fraMiddle = QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QFrame.Raised)
        self.fraMiddle.setObjectName(_fromUtf8("fraMiddle"))
        self.verticalLayout_2 = QVBoxLayout(self.fraMiddle)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabSnow = QTabWidget(self.fraMiddle)
        self.tabSnow.setObjectName(_fromUtf8("tabSnow"))
        self.tabPack = QWidget()
        self.tabPack.setObjectName(_fromUtf8("tabPack"))
        self.verticalLayout = QVBoxLayout(self.tabPack)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tblPack = QTableWidget(self.tabPack)
        self.tblPack.setRowCount(7)
        self.tblPack.setObjectName(_fromUtf8("tblPack"))
        self.tblPack.setColumnCount(3)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(6, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(2, item)
        self.tblPack.horizontalHeader().setCascadingSectionResizes(False)
        self.tblPack.horizontalHeader().setDefaultSectionSize(113)
        self.tblPack.horizontalHeader().setStretchLastSection(True)
        self.tblPack.verticalHeader().setDefaultSectionSize(30)
        self.tblPack.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tblPack)
        self.frame = QFrame(self.tabPack)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QHBoxLayout(self.frame)
        # self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblFraction = QLabel(self.frame)
        self.lblFraction.setObjectName(_fromUtf8("lblFraction"))
        self.horizontalLayout_3.addWidget(self.lblFraction)
        self.txtFraction = QLineEdit(self.frame)
        self.txtFraction.setObjectName(_fromUtf8("txtFraction"))
        self.horizontalLayout_3.addWidget(self.txtFraction)
        self.verticalLayout.addWidget(self.frame)
        self.tabSnow.addTab(self.tabPack, _fromUtf8(""))
        self.tabRemoval = QWidget()
        self.tabRemoval.setObjectName(_fromUtf8("tabRemoval"))
        self.gridLayout = QGridLayout(self.tabRemoval)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblRemoval1 = QLabel(self.tabRemoval)
        self.lblRemoval1.setObjectName(_fromUtf8("lblRemoval1"))
        self.gridLayout.addWidget(self.lblRemoval1, 0, 0, 1, 1)
        self.txtRemoval1 = QLineEdit(self.tabRemoval)
        self.txtRemoval1.setObjectName(_fromUtf8("txtRemoval1"))
        self.gridLayout.addWidget(self.txtRemoval1, 0, 1, 1, 1)
        self.lblRemoval2 = QLabel(self.tabRemoval)
        self.lblRemoval2.setObjectName(_fromUtf8("lblRemoval2"))
        self.gridLayout.addWidget(self.lblRemoval2, 1, 0, 1, 1)
        self.txtRemoval2 = QLineEdit(self.tabRemoval)
        self.txtRemoval2.setObjectName(_fromUtf8("txtRemoval2"))
        self.gridLayout.addWidget(self.txtRemoval2, 1, 1, 1, 1)
        self.lblRemoval3 = QLabel(self.tabRemoval)
        self.lblRemoval3.setObjectName(_fromUtf8("lblRemoval3"))
        self.gridLayout.addWidget(self.lblRemoval3, 2, 0, 1, 1)
        self.txtRemoval3 = QLineEdit(self.tabRemoval)
        self.txtRemoval3.setObjectName(_fromUtf8("txtRemoval3"))
        self.gridLayout.addWidget(self.txtRemoval3, 2, 1, 1, 1)
        self.lblRemoval4 = QLabel(self.tabRemoval)
        self.lblRemoval4.setObjectName(_fromUtf8("lblRemoval4"))
        self.gridLayout.addWidget(self.lblRemoval4, 3, 0, 1, 1)
        self.txtRemoval4 = QLineEdit(self.tabRemoval)
        self.txtRemoval4.setObjectName(_fromUtf8("txtRemoval4"))
        self.gridLayout.addWidget(self.txtRemoval4, 3, 1, 1, 1)
        self.lblRemoval5 = QLabel(self.tabRemoval)
        self.lblRemoval5.setObjectName(_fromUtf8("lblRemoval5"))
        self.gridLayout.addWidget(self.lblRemoval5, 4, 0, 1, 1)
        self.txtRemoval5 = QLineEdit(self.tabRemoval)
        self.txtRemoval5.setObjectName(_fromUtf8("txtRemoval5"))
        self.gridLayout.addWidget(self.txtRemoval5, 4, 1, 1, 1)
        self.lblRemoval6 = QLabel(self.tabRemoval)
        self.lblRemoval6.setObjectName(_fromUtf8("lblRemoval6"))
        self.gridLayout.addWidget(self.lblRemoval6, 5, 0, 1, 1)
        self.txtRemoval6 = QLineEdit(self.tabRemoval)
        self.txtRemoval6.setObjectName(_fromUtf8("txtRemoval6"))
        self.gridLayout.addWidget(self.txtRemoval6, 5, 1, 1, 1)
        self.lblRemoval7 = QLabel(self.tabRemoval)
        self.lblRemoval7.setObjectName(_fromUtf8("lblRemoval7"))
        self.gridLayout.addWidget(self.lblRemoval7, 6, 0, 1, 1)
        self.txtRemoval7 = QLineEdit(self.tabRemoval)
        self.txtRemoval7.setObjectName(_fromUtf8("txtRemoval7"))
        self.gridLayout.addWidget(self.txtRemoval7, 6, 1, 1, 1)
        self.lblRemoval8 = QLabel(self.tabRemoval)
        self.lblRemoval8.setObjectName(_fromUtf8("lblRemoval8"))
        self.gridLayout.addWidget(self.lblRemoval8, 7, 0, 1, 2)
        self.tabSnow.addTab(self.tabRemoval, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabSnow)
        self.verticalLayout_3.addWidget(self.fraMiddle)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_3.addWidget(self.fraOKCancel)
        frmSnowPack.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmSnowPack)
        self.tabSnow.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmSnowPack)

    def retranslateUi(self, frmSnowPack):
        frmSnowPack.setWindowTitle(_translate("frmSnowPack", "SWMM Snow Pack Editor", None))
        self.lblSnow.setText(_translate("frmSnowPack", "Snow Pack Name", None))
        item = self.tblPack.verticalHeaderItem(0)
        item.setText(_translate("frmSnowPack", "Min. Melt Coeff. (in/hr/deg F)", None))
        item = self.tblPack.verticalHeaderItem(1)
        item.setText(_translate("frmSnowPack", "Max. Melt Coeff. (in/hr/deg F)", None))
        item = self.tblPack.verticalHeaderItem(2)
        item.setText(_translate("frmSnowPack", "Base Temperature (deg F)", None))
        item = self.tblPack.verticalHeaderItem(3)
        item.setText(_translate("frmSnowPack", "Fraction Free Water Capacity", None))
        item = self.tblPack.verticalHeaderItem(4)
        item.setText(_translate("frmSnowPack", "Initial Snow Depth (in)", None))
        item = self.tblPack.verticalHeaderItem(5)
        item.setText(_translate("frmSnowPack", "Initial Free Water (in)", None))
        item = self.tblPack.verticalHeaderItem(6)
        item.setText(_translate("frmSnowPack", "Depth at 100% Cover (in)", None))
        item = self.tblPack.horizontalHeaderItem(0)
        item.setText(_translate("frmSnowPack", "Plowable", None))
        item = self.tblPack.horizontalHeaderItem(1)
        item.setText(_translate("frmSnowPack", "Impervious", None))
        item = self.tblPack.horizontalHeaderItem(2)
        item.setText(_translate("frmSnowPack", "Pervious", None))
        self.lblFraction.setText(_translate("frmSnowPack", "Fraction of Impervious Area that is Plowable:", None))
        self.tabSnow.setTabText(self.tabSnow.indexOf(self.tabPack), _translate("frmSnowPack", "Snow Pack Parameters", None))
        self.lblRemoval1.setText(_translate("frmSnowPack", "Depth at which snow removal begins (in)", None))
        self.lblRemoval2.setText(_translate("frmSnowPack", "Fraction transferred out of the watershed", None))
        self.lblRemoval3.setText(_translate("frmSnowPack", "Fraction transferred to the impervious area", None))
        self.lblRemoval4.setText(_translate("frmSnowPack", "Fraction transferred to the pervious area", None))
        self.lblRemoval5.setText(_translate("frmSnowPack", "Fraction converted into immediate melt", None))
        self.lblRemoval6.setText(_translate("frmSnowPack", "Fraction moved to another subcatchment", None))
        self.lblRemoval7.setText(_translate("frmSnowPack", "(Subcatchment name)", None))
        self.lblRemoval8.setText(_translate("frmSnowPack", "Note: sum of all fractions must be <= 1.0.", None))
        self.tabSnow.setTabText(self.tabSnow.indexOf(self.tabRemoval), _translate("frmSnowPack", "Snow Removal Parameters", None))
        self.cmdOK.setText(_translate("frmSnowPack", "OK", None))
        self.cmdCancel.setText(_translate("frmSnowPack", "Cancel", None))

