# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui-py3qt5\src\ui\SWMM\frmTimeStepsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmTimeSteps(object):
    def setupUi(self, frmTimeSteps):
        frmTimeSteps.setObjectName("frmTimeSteps")
        frmTimeSteps.resize(307, 397)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTimeSteps.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmTimeSteps)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblDays = QtWidgets.QLabel(self.frame_2)
        self.lblDays.setMaximumSize(QtCore.QSize(70, 16777215))
        self.lblDays.setObjectName("lblDays")
        self.gridLayout.addWidget(self.lblDays, 0, 1, 1, 1)
        self.lblHr = QtWidgets.QLabel(self.frame_2)
        self.lblHr.setObjectName("lblHr")
        self.gridLayout.addWidget(self.lblHr, 0, 2, 1, 1)
        self.lblReporting = QtWidgets.QLabel(self.frame_2)
        self.lblReporting.setObjectName("lblReporting")
        self.gridLayout.addWidget(self.lblReporting, 1, 0, 1, 1)
        self.sbxReportDay = QtWidgets.QSpinBox(self.frame_2)
        self.sbxReportDay.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sbxReportDay.setObjectName("sbxReportDay")
        self.gridLayout.addWidget(self.sbxReportDay, 1, 1, 1, 1)
        self.tmeReport = QtWidgets.QTimeEdit(self.frame_2)
        self.tmeReport.setMinimumSize(QtCore.QSize(70, 0))
        self.tmeReport.setProperty("showGroupSeparator", False)
        self.tmeReport.setObjectName("tmeReport")
        self.gridLayout.addWidget(self.tmeReport, 1, 2, 1, 1)
        self.lblRunoffDry = QtWidgets.QLabel(self.frame_2)
        self.lblRunoffDry.setTextFormat(QtCore.Qt.AutoText)
        self.lblRunoffDry.setObjectName("lblRunoffDry")
        self.gridLayout.addWidget(self.lblRunoffDry, 2, 0, 1, 1)
        self.sbxDry = QtWidgets.QSpinBox(self.frame_2)
        self.sbxDry.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sbxDry.setObjectName("sbxDry")
        self.gridLayout.addWidget(self.sbxDry, 2, 1, 1, 1)
        self.tmeDry = QtWidgets.QTimeEdit(self.frame_2)
        self.tmeDry.setMinimumSize(QtCore.QSize(70, 0))
        self.tmeDry.setProperty("showGroupSeparator", False)
        self.tmeDry.setObjectName("tmeDry")
        self.gridLayout.addWidget(self.tmeDry, 2, 2, 1, 1)
        self.lblRunoffWet = QtWidgets.QLabel(self.frame_2)
        self.lblRunoffWet.setObjectName("lblRunoffWet")
        self.gridLayout.addWidget(self.lblRunoffWet, 3, 0, 1, 1)
        self.sbxWet = QtWidgets.QSpinBox(self.frame_2)
        self.sbxWet.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sbxWet.setObjectName("sbxWet")
        self.gridLayout.addWidget(self.sbxWet, 3, 1, 1, 1)
        self.tmeWet = QtWidgets.QTimeEdit(self.frame_2)
        self.tmeWet.setMinimumSize(QtCore.QSize(70, 0))
        self.tmeWet.setProperty("showGroupSeparator", False)
        self.tmeWet.setObjectName("tmeWet")
        self.gridLayout.addWidget(self.tmeWet, 3, 2, 1, 1)
        self.lblControl = QtWidgets.QLabel(self.frame_2)
        self.lblControl.setObjectName("lblControl")
        self.gridLayout.addWidget(self.lblControl, 4, 0, 1, 1)
        self.tmeControl = QtWidgets.QTimeEdit(self.frame_2)
        self.tmeControl.setObjectName("tmeControl")
        self.gridLayout.addWidget(self.tmeControl, 4, 2, 1, 1)
        self.lblRouting = QtWidgets.QLabel(self.frame_2)
        self.lblRouting.setObjectName("lblRouting")
        self.gridLayout.addWidget(self.lblRouting, 5, 0, 1, 1)
        self.txtRouting = QtWidgets.QLineEdit(self.frame_2)
        self.txtRouting.setMaximumSize(QtCore.QSize(70, 16777215))
        self.txtRouting.setObjectName("txtRouting")
        self.gridLayout.addWidget(self.txtRouting, 5, 1, 1, 1)
        self.lblSeconds = QtWidgets.QLabel(self.frame_2)
        self.lblSeconds.setObjectName("lblSeconds")
        self.gridLayout.addWidget(self.lblSeconds, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.gbxSteady = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxSteady.setObjectName("gbxSteady")
        self.cbxSkip = QtWidgets.QCheckBox(self.gbxSteady)
        self.cbxSkip.setGeometry(QtCore.QRect(10, 26, 167, 20))
        self.cbxSkip.setObjectName("cbxSkip")
        self.lblSystem = QtWidgets.QLabel(self.gbxSteady)
        self.lblSystem.setGeometry(QtCore.QRect(10, 52, 160, 16))
        self.lblSystem.setObjectName("lblSystem")
        self.sbxSystem = QtWidgets.QSpinBox(self.gbxSteady)
        self.sbxSystem.setGeometry(QtCore.QRect(183, 52, 40, 22))
        self.sbxSystem.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sbxSystem.setObjectName("sbxSystem")
        self.lblLateral = QtWidgets.QLabel(self.gbxSteady)
        self.lblLateral.setGeometry(QtCore.QRect(10, 80, 157, 16))
        self.lblLateral.setObjectName("lblLateral")
        self.sbxLateral = QtWidgets.QSpinBox(self.gbxSteady)
        self.sbxLateral.setGeometry(QtCore.QRect(183, 80, 40, 22))
        self.sbxLateral.setMaximumSize(QtCore.QSize(150, 16777215))
        self.sbxLateral.setObjectName("sbxLateral")
        self.verticalLayout.addWidget(self.gbxSteady)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.frame)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.frame)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.frame)
        frmTimeSteps.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTimeSteps)
        QtCore.QMetaObject.connectSlotsByName(frmTimeSteps)
        frmTimeSteps.setTabOrder(self.sbxReportDay, self.tmeReport)
        frmTimeSteps.setTabOrder(self.tmeReport, self.sbxDry)
        frmTimeSteps.setTabOrder(self.sbxDry, self.tmeDry)
        frmTimeSteps.setTabOrder(self.tmeDry, self.sbxWet)
        frmTimeSteps.setTabOrder(self.sbxWet, self.tmeWet)
        frmTimeSteps.setTabOrder(self.tmeWet, self.txtRouting)
        frmTimeSteps.setTabOrder(self.txtRouting, self.cbxSkip)
        frmTimeSteps.setTabOrder(self.cbxSkip, self.sbxSystem)
        frmTimeSteps.setTabOrder(self.sbxSystem, self.sbxLateral)
        frmTimeSteps.setTabOrder(self.sbxLateral, self.cmdOK)
        frmTimeSteps.setTabOrder(self.cmdOK, self.cmdCancel)

    def retranslateUi(self, frmTimeSteps):
        _translate = QtCore.QCoreApplication.translate
        frmTimeSteps.setWindowTitle(_translate("frmTimeSteps", "SWMM Time Steps Options"))
        self.lblDays.setText(_translate("frmTimeSteps", "Days"))
        self.lblHr.setText(_translate("frmTimeSteps", "Hr:Min:Sec"))
        self.lblReporting.setText(_translate("frmTimeSteps", "Reporting"))
        self.tmeReport.setDisplayFormat(_translate("frmTimeSteps", "h:mm:ss"))
        self.lblRunoffDry.setText(_translate("frmTimeSteps", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Runoff:</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Dry weather</p></body></html>"))
        self.tmeDry.setDisplayFormat(_translate("frmTimeSteps", "h:mm:ss"))
        self.lblRunoffWet.setText(_translate("frmTimeSteps", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Runoff:</p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Wet weather</p></body></html>"))
        self.tmeWet.setDisplayFormat(_translate("frmTimeSteps", "h:mm:ss"))
        self.lblControl.setText(_translate("frmTimeSteps", "Control Rule Step"))
        self.tmeControl.setDisplayFormat(_translate("frmTimeSteps", "h:mm:ss"))
        self.lblRouting.setText(_translate("frmTimeSteps", "Routing"))
        self.lblSeconds.setText(_translate("frmTimeSteps", "Seconds"))
        self.gbxSteady.setTitle(_translate("frmTimeSteps", "Steady Flow Periods"))
        self.cbxSkip.setText(_translate("frmTimeSteps", "Skip Steady Flow Periods"))
        self.lblSystem.setText(_translate("frmTimeSteps", "System Flow Tolerance (%)"))
        self.lblLateral.setText(_translate("frmTimeSteps", "Lateral Flow Tolerance (%)"))
        self.cmdOK.setText(_translate("frmTimeSteps", "OK"))
        self.cmdCancel.setText(_translate("frmTimeSteps", "Cancel"))

