# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmTimeseriesDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmTimeseries(object):
    def setupUi(self, frmTimeseries):
        frmTimeseries.setObjectName(_fromUtf8("frmTimeseries"))
        frmTimeseries.resize(648, 456)
        font = QFont()
        font.setPointSize(10)
        frmTimeseries.setFont(font)
        self.centralWidget = QWidget(frmTimeseries)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QVBoxLayout(self.centralWidget)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.fraParms = QFrame(self.centralWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QFrame.Raised)
        self.fraParms.setObjectName(_fromUtf8("fraParms"))
        self.gridLayout = QGridLayout(self.fraParms)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblTimeseriesName = QLabel(self.fraParms)
        font = QFont()
        font.setPointSize(10)
        self.lblTimeseriesName.setFont(font)
        self.lblTimeseriesName.setObjectName(_fromUtf8("lblTimeseriesName"))
        self.gridLayout.addWidget(self.lblTimeseriesName, 0, 0, 1, 1)
        self.lblDescription = QLabel(self.fraParms)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.gridLayout.addWidget(self.lblDescription, 1, 0, 1, 1)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.txtTimeseriesName = QLineEdit(self.fraParms)
        self.txtTimeseriesName.setObjectName(_fromUtf8("txtTimeseriesName"))
        self.gridLayout.addWidget(self.txtTimeseriesName, 0, 1, 1, 1)
        self.txtDescription = QLineEdit(self.fraParms)
        self.txtDescription.setObjectName(_fromUtf8("txtDescription"))
        self.gridLayout.addWidget(self.txtDescription, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.fraParms)
        self.fraMid = QFrame(self.centralWidget)
        self.fraMid.setFrameShape(QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QFrame.Raised)
        self.fraMid.setObjectName(_fromUtf8("fraMid"))
        self.gridLayout_3 = QGridLayout(self.fraMid)
        # self.gridLayout_3.setMargin(11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.txtExternalFile = QLineEdit(self.fraMid)
        self.txtExternalFile.setObjectName(_fromUtf8("txtExternalFile"))
        self.gridLayout_3.addWidget(self.txtExternalFile, 2, 0, 1, 1)
        self.btnFile = QToolButton(self.fraMid)
        self.btnFile.setObjectName(_fromUtf8("btnFile"))
        self.gridLayout_3.addWidget(self.btnFile, 2, 3, 1, 1)
        self.rbnExternal = QRadioButton(self.fraMid)
        self.rbnExternal.setObjectName(_fromUtf8("rbnExternal"))
        self.gridLayout_3.addWidget(self.rbnExternal, 0, 0, 1, 1)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 5, 3, 1, 1)
        self.btnView = QPushButton(self.fraMid)
        self.btnView.setObjectName(_fromUtf8("btnView"))
        self.gridLayout_3.addWidget(self.btnView, 5, 4, 1, 1)
        self.lblNote = QLabel(self.fraMid)
        font = QFont()
        font.setPointSize(10)
        self.lblNote.setFont(font)
        self.lblNote.setObjectName(_fromUtf8("lblNote"))
        self.gridLayout_3.addWidget(self.lblNote, 5, 0, 1, 1)
        self.rbnTable = QRadioButton(self.fraMid)
        self.rbnTable.setObjectName(_fromUtf8("rbnTable"))
        self.gridLayout_3.addWidget(self.rbnTable, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.fraMid)
        self.fraBottom = QFrame(self.centralWidget)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraBottom.sizePolicy().hasHeightForWidth())
        self.fraBottom.setSizePolicy(sizePolicy)
        self.fraBottom.setFrameShape(QFrame.StyledPanel)
        self.fraBottom.setFrameShadow(QFrame.Raised)
        self.fraBottom.setObjectName(_fromUtf8("fraBottom"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraBottom)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fraLeft = QFrame(self.fraBottom)
        self.fraLeft.setFrameShape(QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QFrame.Raised)
        self.fraLeft.setObjectName(_fromUtf8("fraLeft"))
        self.verticalLayout_3 = QVBoxLayout(self.fraLeft)
        # self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tblTime = QTableWidget(self.fraLeft)
        self.tblTime.setRowCount(24)
        self.tblTime.setColumnCount(3)
        self.tblTime.setObjectName(_fromUtf8("tblTime"))
        item = QTableWidgetItem()
        self.tblTime.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblTime.setHorizontalHeaderItem(2, item)
        self.tblTime.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tblTime)
        self.horizontalLayout_2.addWidget(self.fraLeft)
        self.fraRight = QFrame(self.fraBottom)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraRight.sizePolicy().hasHeightForWidth())
        self.fraRight.setSizePolicy(sizePolicy)
        self.fraRight.setMaximumSize(QtCore.QSize(200, 16777215))
        self.fraRight.setFrameShape(QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QFrame.Raised)
        self.fraRight.setObjectName(_fromUtf8("fraRight"))
        self.verticalLayout = QVBoxLayout(self.fraRight)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem2 = QSpacerItem(20, 128, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.fraOKCancel = QFrame(self.fraRight)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraOKCancel.sizePolicy().hasHeightForWidth())
        self.fraOKCancel.setSizePolicy(sizePolicy)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        self.horizontalLayout_2.addWidget(self.fraRight)
        self.verticalLayout_2.addWidget(self.fraBottom)
        frmTimeseries.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTimeseries)
        QtCore.QMetaObject.connectSlotsByName(frmTimeseries)

    def retranslateUi(self, frmTimeseries):
        frmTimeseries.setWindowTitle(_translate("frmTimeseries", "SWMM Time Series Editor", None))
        self.lblTimeseriesName.setText(_translate("frmTimeseries", "Time Series Name", None))
        self.lblDescription.setText(_translate("frmTimeseries", "<html><head/><body><p>Description</p></body></html>", None))
        self.btnFile.setText(_translate("frmTimeseries", "...", None))
        self.rbnExternal.setText(_translate("frmTimeseries", "Use external data file named below", None))
        self.btnView.setText(_translate("frmTimeseries", "View", None))
        self.lblNote.setText(_translate("frmTimeseries", "No dates means times are relative to start of simulation.", None))
        self.rbnTable.setText(_translate("frmTimeseries", "Enter time series data in the table below", None))
        item = self.tblTime.verticalHeaderItem(0)
        item.setText(_translate("frmTimeseries", "1", None))
        item = self.tblTime.horizontalHeaderItem(0)
        item.setText(_translate("frmTimeseries", "Date (M/D/Y)", None))
        item = self.tblTime.horizontalHeaderItem(1)
        item.setText(_translate("frmTimeseries", "Time (H:M)", None))
        item = self.tblTime.horizontalHeaderItem(2)
        item.setText(_translate("frmTimeseries", "Value", None))
        self.cmdOK.setText(_translate("frmTimeseries", "OK", None))
        self.cmdCancel.setText(_translate("frmTimeseries", "Cancel", None))

