# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\QtForms\frmHydraulicsOptions\frmHydraulicsOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmHydraulicsOptions(object):
    def setupUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setObjectName(_fromUtf8("frmHydraulicsOptions"))
        frmHydraulicsOptions.resize(304, 501)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmHydraulicsOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmHydraulicsOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.lbl1 = QtGui.QLabel(self.centralWidget)
        self.lbl1.setGeometry(QtCore.QRect(30, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl1.setFont(font)
        self.lbl1.setObjectName(_fromUtf8("lbl1"))
        self.lbl2 = QtGui.QLabel(self.centralWidget)
        self.lbl2.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.lbl2.setObjectName(_fromUtf8("lbl2"))
        self.lbl3 = QtGui.QLabel(self.centralWidget)
        self.lbl3.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.lbl3.setObjectName(_fromUtf8("lbl3"))
        self.cmdOK = QtGui.QPushButton(self.centralWidget)
        self.cmdOK.setGeometry(QtCore.QRect(60, 440, 75, 23))
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.cmdCancel = QtGui.QPushButton(self.centralWidget)
        self.cmdCancel.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.cboFlow = QtGui.QComboBox(self.centralWidget)
        self.cboFlow.setGeometry(QtCore.QRect(160, 20, 111, 22))
        self.cboFlow.setObjectName(_fromUtf8("cboFlow"))
        self.cboHeadloss = QtGui.QComboBox(self.centralWidget)
        self.cboHeadloss.setGeometry(QtCore.QRect(160, 50, 111, 22))
        self.cboHeadloss.setObjectName(_fromUtf8("cboHeadloss"))
        self.txtVal1 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal1.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.txtVal1.setObjectName(_fromUtf8("txtVal1"))
        self.lbl4 = QtGui.QLabel(self.centralWidget)
        self.lbl4.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.lbl4.setObjectName(_fromUtf8("lbl4"))
        self.txtVal2 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal2.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.txtVal2.setObjectName(_fromUtf8("txtVal2"))
        self.lbl5 = QtGui.QLabel(self.centralWidget)
        self.lbl5.setGeometry(QtCore.QRect(30, 140, 111, 16))
        self.lbl5.setObjectName(_fromUtf8("lbl5"))
        self.txtVal3 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal3.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.txtVal3.setObjectName(_fromUtf8("txtVal3"))
        self.lbl6 = QtGui.QLabel(self.centralWidget)
        self.lbl6.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.lbl6.setObjectName(_fromUtf8("lbl6"))
        self.lbl7 = QtGui.QLabel(self.centralWidget)
        self.lbl7.setGeometry(QtCore.QRect(30, 200, 111, 16))
        self.lbl7.setObjectName(_fromUtf8("lbl7"))
        self.cboUnbalanced = QtGui.QComboBox(self.centralWidget)
        self.cboUnbalanced.setGeometry(QtCore.QRect(160, 200, 111, 22))
        self.cboUnbalanced.setObjectName(_fromUtf8("cboUnbalanced"))
        self.txtVal4 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal4.setGeometry(QtCore.QRect(160, 170, 113, 20))
        self.txtVal4.setObjectName(_fromUtf8("txtVal4"))
        self.lbl8 = QtGui.QLabel(self.centralWidget)
        self.lbl8.setGeometry(QtCore.QRect(30, 230, 111, 16))
        self.lbl8.setObjectName(_fromUtf8("lbl8"))
        self.lbl9 = QtGui.QLabel(self.centralWidget)
        self.lbl9.setGeometry(QtCore.QRect(30, 260, 111, 16))
        self.lbl9.setObjectName(_fromUtf8("lbl9"))
        self.lbl10 = QtGui.QLabel(self.centralWidget)
        self.lbl10.setGeometry(QtCore.QRect(30, 290, 111, 16))
        self.lbl10.setObjectName(_fromUtf8("lbl10"))
        self.lbl11 = QtGui.QLabel(self.centralWidget)
        self.lbl11.setGeometry(QtCore.QRect(30, 320, 111, 16))
        self.lbl11.setObjectName(_fromUtf8("lbl11"))
        self.cboStatus = QtGui.QComboBox(self.centralWidget)
        self.cboStatus.setGeometry(QtCore.QRect(160, 320, 111, 22))
        self.cboStatus.setObjectName(_fromUtf8("cboStatus"))
        self.txtVal5 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal5.setGeometry(QtCore.QRect(160, 230, 113, 20))
        self.txtVal5.setObjectName(_fromUtf8("txtVal5"))
        self.txtVal6 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal6.setGeometry(QtCore.QRect(160, 260, 113, 20))
        self.txtVal6.setObjectName(_fromUtf8("txtVal6"))
        self.txtVal7 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal7.setGeometry(QtCore.QRect(160, 290, 113, 20))
        self.txtVal7.setObjectName(_fromUtf8("txtVal7"))
        self.lbl12 = QtGui.QLabel(self.centralWidget)
        self.lbl12.setGeometry(QtCore.QRect(30, 350, 111, 16))
        self.lbl12.setObjectName(_fromUtf8("lbl12"))
        self.lbl13 = QtGui.QLabel(self.centralWidget)
        self.lbl13.setGeometry(QtCore.QRect(30, 380, 111, 16))
        self.lbl13.setObjectName(_fromUtf8("lbl13"))
        self.lbl14 = QtGui.QLabel(self.centralWidget)
        self.lbl14.setGeometry(QtCore.QRect(30, 410, 111, 16))
        self.lbl14.setObjectName(_fromUtf8("lbl14"))
        self.txtVal8 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal8.setGeometry(QtCore.QRect(160, 350, 113, 20))
        self.txtVal8.setObjectName(_fromUtf8("txtVal8"))
        self.txtVal9 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal9.setGeometry(QtCore.QRect(160, 380, 113, 20))
        self.txtVal9.setObjectName(_fromUtf8("txtVal9"))
        self.txtVal10 = QtGui.QLineEdit(self.centralWidget)
        self.txtVal10.setGeometry(QtCore.QRect(160, 410, 113, 20))
        self.txtVal10.setObjectName(_fromUtf8("txtVal10"))
        frmHydraulicsOptions.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(frmHydraulicsOptions)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        frmHydraulicsOptions.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(frmHydraulicsOptions)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        frmHydraulicsOptions.setStatusBar(self.statusBar)

        self.retranslateUi(frmHydraulicsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmHydraulicsOptions)

    def retranslateUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setWindowTitle(_translate("frmHydraulicsOptions", "EPANET Hydraulics Options", None))
        self.lbl1.setText(_translate("frmHydraulicsOptions", "Flow Units", None))
        self.lbl2.setText(_translate("frmHydraulicsOptions", "<html><head/><body><p>Headloss Formula</p></body></html>", None))
        self.lbl3.setText(_translate("frmHydraulicsOptions", "Specific Gravity", None))
        self.cmdOK.setText(_translate("frmHydraulicsOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmHydraulicsOptions", "Cancel", None))
        self.lbl4.setText(_translate("frmHydraulicsOptions", "Relative Viscosity", None))
        self.lbl5.setText(_translate("frmHydraulicsOptions", "Maximum Trials", None))
        self.lbl6.setText(_translate("frmHydraulicsOptions", "Accuracy", None))
        self.lbl7.setText(_translate("frmHydraulicsOptions", "If Unbalanced", None))
        self.lbl8.setText(_translate("frmHydraulicsOptions", "Default Pattern", None))
        self.lbl9.setText(_translate("frmHydraulicsOptions", "Demand Multiplier", None))
        self.lbl10.setText(_translate("frmHydraulicsOptions", "Emitter Exponent", None))
        self.lbl11.setText(_translate("frmHydraulicsOptions", "Status Report", None))
        self.lbl12.setText(_translate("frmHydraulicsOptions", "Check Frequency", None))
        self.lbl13.setText(_translate("frmHydraulicsOptions", "Max Check", None))
        self.lbl14.setText(_translate("frmHydraulicsOptions", "Damp Limit", None))

