# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\SWMM\frmUnitHydrographDesigner.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmUnitHydrograph(object):
    def setupUi(self, frmUnitHydrograph):
        frmUnitHydrograph.setObjectName(_fromUtf8("frmUnitHydrograph"))
        frmUnitHydrograph.resize(460, 543)
        font = QFont()
        font.setPointSize(10)
        frmUnitHydrograph.setFont(font)
        self.centralWidget = QWidget(frmUnitHydrograph)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_6 = QVBoxLayout(self.centralWidget)
        # self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.fraTop = QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.gridLayout_2 = QGridLayout(self.fraTop)
        # self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblGroup = QLabel(self.fraTop)
        self.lblGroup.setObjectName(_fromUtf8("lblGroup"))
        self.gridLayout_2.addWidget(self.lblGroup, 0, 0, 1, 1)
        self.txtGroup = QLineEdit(self.fraTop)
        self.txtGroup.setObjectName(_fromUtf8("txtGroup"))
        self.gridLayout_2.addWidget(self.txtGroup, 0, 1, 1, 1)
        self.lblRain = QLabel(self.fraTop)
        self.lblRain.setObjectName(_fromUtf8("lblRain"))
        self.gridLayout_2.addWidget(self.lblRain, 1, 0, 1, 1)
        self.cboRain = QComboBox(self.fraTop)
        self.cboRain.setObjectName(_fromUtf8("cboRain"))
        self.gridLayout_2.addWidget(self.cboRain, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.fraTop)
        self.line = QFrame(self.centralWidget)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_6.addWidget(self.line)
        self.fraUpperMiddle = QFrame(self.centralWidget)
        self.fraUpperMiddle.setFrameShape(QFrame.StyledPanel)
        self.fraUpperMiddle.setFrameShadow(QFrame.Raised)
        self.fraUpperMiddle.setObjectName(_fromUtf8("fraUpperMiddle"))
        self.horizontalLayout_2 = QHBoxLayout(self.fraUpperMiddle)
        # self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblHydrograph = QLabel(self.fraUpperMiddle)
        self.lblHydrograph.setObjectName(_fromUtf8("lblHydrograph"))
        self.horizontalLayout_2.addWidget(self.lblHydrograph)
        self.cboHydrograph = QComboBox(self.fraUpperMiddle)
        self.cboHydrograph.setObjectName(_fromUtf8("cboHydrograph"))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.cboHydrograph.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.cboHydrograph)
        self.verticalLayout_6.addWidget(self.fraUpperMiddle)
        self.fraMiddle = QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QFrame.Raised)
        self.fraMiddle.setObjectName(_fromUtf8("fraMiddle"))
        self.verticalLayout_5 = QVBoxLayout(self.fraMiddle)
        # self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabHydrograph = QTabWidget(self.fraMiddle)
        self.tabHydrograph.setObjectName(_fromUtf8("tabHydrograph"))
        self.tabUnit = QWidget()
        self.tabUnit.setObjectName(_fromUtf8("tabUnit"))
        self.verticalLayout_4 = QVBoxLayout(self.tabUnit)
        # self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tblPack = QTableWidget(self.tabUnit)
        self.tblPack.setRowCount(3)
        self.tblPack.setObjectName(_fromUtf8("tblPack"))
        self.tblPack.setColumnCount(3)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblPack.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblPack.setHorizontalHeaderItem(2, item)
        self.tblPack.horizontalHeader().setCascadingSectionResizes(False)
        self.tblPack.horizontalHeader().setDefaultSectionSize(100)
        self.tblPack.horizontalHeader().setStretchLastSection(True)
        self.tblPack.verticalHeader().setDefaultSectionSize(30)
        self.tblPack.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tblPack)
        self.fraNote1 = QFrame(self.tabUnit)
        self.fraNote1.setFrameShape(QFrame.StyledPanel)
        self.fraNote1.setFrameShadow(QFrame.Raised)
        self.fraNote1.setObjectName(_fromUtf8("fraNote1"))
        self.verticalLayout = QVBoxLayout(self.fraNote1)
        # self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblNote1 = QLabel(self.fraNote1)
        self.lblNote1.setObjectName(_fromUtf8("lblNote1"))
        self.verticalLayout.addWidget(self.lblNote1)
        self.lblNote2 = QLabel(self.fraNote1)
        self.lblNote2.setObjectName(_fromUtf8("lblNote2"))
        self.verticalLayout.addWidget(self.lblNote2)
        self.lblNote3 = QLabel(self.fraNote1)
        self.lblNote3.setObjectName(_fromUtf8("lblNote3"))
        self.verticalLayout.addWidget(self.lblNote3)
        self.verticalLayout_4.addWidget(self.fraNote1)
        self.tabHydrograph.addTab(self.tabUnit, _fromUtf8(""))
        self.tabAbstraction = QWidget()
        self.tabAbstraction.setObjectName(_fromUtf8("tabAbstraction"))
        self.gridLayout = QGridLayout(self.tabAbstraction)
        # self.gridLayout.setMargin(11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fraNote2 = QFrame(self.tabAbstraction)
        self.fraNote2.setFrameShape(QFrame.StyledPanel)
        self.fraNote2.setFrameShadow(QFrame.Raised)
        self.fraNote2.setObjectName(_fromUtf8("fraNote2"))
        self.verticalLayout_2 = QVBoxLayout(self.fraNote2)
        # self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblNote4 = QLabel(self.fraNote2)
        self.lblNote4.setObjectName(_fromUtf8("lblNote4"))
        self.verticalLayout_2.addWidget(self.lblNote4)
        self.lblNote5 = QLabel(self.fraNote2)
        self.lblNote5.setObjectName(_fromUtf8("lblNote5"))
        self.verticalLayout_2.addWidget(self.lblNote5)
        self.lblNote6 = QLabel(self.fraNote2)
        self.lblNote6.setObjectName(_fromUtf8("lblNote6"))
        self.verticalLayout_2.addWidget(self.lblNote6)
        self.gridLayout.addWidget(self.fraNote2, 1, 0, 1, 1)
        self.tblAbstraction = QTableWidget(self.tabAbstraction)
        self.tblAbstraction.setRowCount(3)
        self.tblAbstraction.setObjectName(_fromUtf8("tblAbstraction"))
        self.tblAbstraction.setColumnCount(3)
        item = QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblAbstraction.setVerticalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.tblAbstraction.setHorizontalHeaderItem(2, item)
        self.tblAbstraction.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAbstraction.horizontalHeader().setDefaultSectionSize(100)
        self.tblAbstraction.horizontalHeader().setStretchLastSection(True)
        self.tblAbstraction.verticalHeader().setDefaultSectionSize(30)
        self.tblAbstraction.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAbstraction, 0, 0, 1, 1)
        self.tabHydrograph.addTab(self.tabAbstraction, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabHydrograph)
        self.lblGeneral = QLabel(self.fraMiddle)
        self.lblGeneral.setObjectName(_fromUtf8("lblGeneral"))
        self.verticalLayout_5.addWidget(self.lblGeneral)
        self.verticalLayout_6.addWidget(self.fraMiddle)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        # self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QSpacerItem(338, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_6.addWidget(self.fraOKCancel)
        frmUnitHydrograph.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmUnitHydrograph)
        self.tabHydrograph.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmUnitHydrograph)

    def retranslateUi(self, frmUnitHydrograph):
        frmUnitHydrograph.setWindowTitle(_translate("frmUnitHydrograph", "SWMM Unit Hydrograph Editor", None))
        self.lblGroup.setText(_translate("frmUnitHydrograph", "Name of UH Group", None))
        self.lblRain.setText(_translate("frmUnitHydrograph", "Rain Gage Used", None))
        self.lblHydrograph.setText(_translate("frmUnitHydrograph", "Hydrographs For:", None))
        self.cboHydrograph.setItemText(0, _translate("frmUnitHydrograph", "All Months", None))
        self.cboHydrograph.setItemText(1, _translate("frmUnitHydrograph", "January", None))
        self.cboHydrograph.setItemText(2, _translate("frmUnitHydrograph", "February", None))
        self.cboHydrograph.setItemText(3, _translate("frmUnitHydrograph", "March", None))
        self.cboHydrograph.setItemText(4, _translate("frmUnitHydrograph", "April", None))
        self.cboHydrograph.setItemText(5, _translate("frmUnitHydrograph", "May", None))
        self.cboHydrograph.setItemText(6, _translate("frmUnitHydrograph", "June", None))
        self.cboHydrograph.setItemText(7, _translate("frmUnitHydrograph", "July", None))
        self.cboHydrograph.setItemText(8, _translate("frmUnitHydrograph", "August", None))
        self.cboHydrograph.setItemText(9, _translate("frmUnitHydrograph", "September", None))
        self.cboHydrograph.setItemText(10, _translate("frmUnitHydrograph", "October", None))
        self.cboHydrograph.setItemText(11, _translate("frmUnitHydrograph", "November", None))
        self.cboHydrograph.setItemText(12, _translate("frmUnitHydrograph", "December", None))
        item = self.tblPack.verticalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Short-Term", None))
        item = self.tblPack.verticalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Medium-Term", None))
        item = self.tblPack.verticalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Long-Term", None))
        item = self.tblPack.horizontalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "R", None))
        item = self.tblPack.horizontalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "T", None))
        item = self.tblPack.horizontalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "K", None))
        self.lblNote1.setText(_translate("frmUnitHydrograph", "R = fraction of rainfall that becomes I&I", None))
        self.lblNote2.setText(_translate("frmUnitHydrograph", "T = time to hydrograph peak (hours)", None))
        self.lblNote3.setText(_translate("frmUnitHydrograph", "K = falling limb duration / rising limb duration", None))
        self.tabHydrograph.setTabText(self.tabHydrograph.indexOf(self.tabUnit), _translate("frmUnitHydrograph", "Unit Hydrographs", None))
        self.lblNote4.setText(_translate("frmUnitHydrograph", "Dmax = maximum depth (inches)", None))
        self.lblNote5.setText(_translate("frmUnitHydrograph", "Drec = recovery rate (in/day)", None))
        self.lblNote6.setText(_translate("frmUnitHydrograph", "Do = starting depth (inches)", None))
        item = self.tblAbstraction.verticalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Short-Term", None))
        item = self.tblAbstraction.verticalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Medium-Term", None))
        item = self.tblAbstraction.verticalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Long-Term", None))
        item = self.tblAbstraction.horizontalHeaderItem(0)
        item.setText(_translate("frmUnitHydrograph", "Dmax", None))
        item = self.tblAbstraction.horizontalHeaderItem(1)
        item.setText(_translate("frmUnitHydrograph", "Drec", None))
        item = self.tblAbstraction.horizontalHeaderItem(2)
        item.setText(_translate("frmUnitHydrograph", "Do", None))
        self.tabHydrograph.setTabText(self.tabHydrograph.indexOf(self.tabAbstraction), _translate("frmUnitHydrograph", "Initial Abstraction Depth", None))
        self.lblGeneral.setText(_translate("frmUnitHydrograph", "Months with UH data have a (*) next to them.", None))
        self.cmdOK.setText(_translate("frmUnitHydrograph", "OK", None))
        self.cmdCancel.setText(_translate("frmUnitHydrograph", "Cancel", None))

