# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmCurveEditorDesigner.ui'
#
# Created: Fri Dec 09 13:09:44 2016
#      by: PyQt5 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QApplication.translate(context, text, disambig)

class Ui_frmCurveEditor(object):
    def setupUi(self, frmCurveEditor):
        frmCurveEditor.setObjectName(_fromUtf8("frmCurveEditor"))
        frmCurveEditor.resize(588, 383)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmCurveEditor.setFont(font)
        self.centralWidget = QWidget(frmCurveEditor)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.formLayout_2 = QFormLayout(self.centralWidget)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.fraParms = QFrame(self.centralWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QFrame.Raised)
        self.fraParms.setObjectName(_fromUtf8("fraParms"))
        self.formLayout = QFormLayout(self.fraParms)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblCurveID = QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveID.setFont(font)
        self.lblCurveID.setObjectName(_fromUtf8("lblCurveID"))
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.lblCurveID)
        self.lblDescription = QLabel(self.fraParms)
        self.lblDescription.setObjectName(_fromUtf8("lblDescription"))
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.lblDescription)
        self.txtCurveName = QLineEdit(self.fraParms)
        self.txtCurveName.setObjectName(_fromUtf8("txtCurveName"))
        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.txtCurveName)
        self.txtDescription = QLineEdit(self.fraParms)
        self.txtDescription.setObjectName(_fromUtf8("txtDescription"))
        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.txtDescription)
        self.lblCurveType = QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveType.setFont(font)
        self.lblCurveType.setObjectName(_fromUtf8("lblCurveType"))
        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.lblCurveType)
        self.lblEquation = QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblEquation.setFont(font)
        self.lblEquation.setObjectName(_fromUtf8("lblEquation"))
        self.formLayout.setWidget(2, QFormLayout.FieldRole, self.lblEquation)
        self.cboCurveType = QComboBox(self.fraParms)
        self.cboCurveType.setObjectName(_fromUtf8("cboCurveType"))
        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.cboCurveType)
        self.txtEquation = QLineEdit(self.fraParms)
        self.txtEquation.setObjectName(_fromUtf8("txtEquation"))
        self.formLayout.setWidget(3, QFormLayout.FieldRole, self.txtEquation)
        self.formLayout_2.setWidget(0, QFormLayout.SpanningRole, self.fraParms)
        self.tblMult = QTableWidget(self.centralWidget)
        self.tblMult.setCornerButtonEnabled(False)
        self.tblMult.setRowCount(50)
        self.tblMult.setColumnCount(2)
        self.tblMult.setObjectName(_fromUtf8("tblMult"))
        item = QTableWidgetItem()
        self.tblMult.setVerticalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(1, item)
        self.tblMult.horizontalHeader().setVisible(True)
        self.tblMult.verticalHeader().setVisible(False)
        self.formLayout_2.setWidget(1, QFormLayout.LabelRole, self.tblMult)
        self.fraPlot = QFrame(self.centralWidget)
        self.fraPlot.setFrameShape(QFrame.StyledPanel)
        self.fraPlot.setFrameShadow(QFrame.Raised)
        self.fraPlot.setObjectName(_fromUtf8("fraPlot"))
        self.formLayout_2.setWidget(1, QFormLayout.FieldRole, self.fraPlot)
        self.fraOKCancel = QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnLoad = QPushButton(self.fraOKCancel)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.horizontalLayout.addWidget(self.btnLoad)
        self.btnSave = QPushButton(self.fraOKCancel)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        spacerItem = QSpacerItem(99, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.btnHelp = QPushButton(self.fraOKCancel)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.horizontalLayout.addWidget(self.btnHelp)
        self.formLayout_2.setWidget(2, QFormLayout.SpanningRole, self.fraOKCancel)
        frmCurveEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmCurveEditor)
        QtCore.QMetaObject.connectSlotsByName(frmCurveEditor)
        frmCurveEditor.setTabOrder(self.txtCurveName, self.txtDescription)
        frmCurveEditor.setTabOrder(self.txtDescription, self.cboCurveType)
        frmCurveEditor.setTabOrder(self.cboCurveType, self.txtEquation)
        frmCurveEditor.setTabOrder(self.txtEquation, self.tblMult)
        frmCurveEditor.setTabOrder(self.tblMult, self.cmdCancel)
        frmCurveEditor.setTabOrder(self.cmdCancel, self.cmdOK)
        frmCurveEditor.setTabOrder(self.cmdOK, self.btnLoad)
        frmCurveEditor.setTabOrder(self.btnLoad, self.btnSave)
        frmCurveEditor.setTabOrder(self.btnSave, self.btnHelp)

    def retranslateUi(self, frmCurveEditor):
        frmCurveEditor.setWindowTitle(_translate("frmCurveEditor", "EPANET Curve Editor", None))
        self.lblCurveID.setText(_translate("frmCurveEditor", "Curve ID", None))
        self.lblDescription.setText(_translate("frmCurveEditor", "<html><head/><body><p>Description</p></body></html>", None))
        self.lblCurveType.setText(_translate("frmCurveEditor", "Curve Type", None))
        self.lblEquation.setText(_translate("frmCurveEditor", "Equation", None))
        item = self.tblMult.verticalHeaderItem(0)
        item.setText(_translate("frmCurveEditor", "Flow", None))
        item = self.tblMult.horizontalHeaderItem(0)
        item.setText(_translate("frmCurveEditor", "Flow", None))
        item = self.tblMult.horizontalHeaderItem(1)
        item.setText(_translate("frmCurveEditor", "Head", None))
        self.btnLoad.setText(_translate("frmCurveEditor", "Load...", None))
        self.btnSave.setText(_translate("frmCurveEditor", "Save...", None))
        self.cmdOK.setText(_translate("frmCurveEditor", "OK", None))
        self.cmdCancel.setText(_translate("frmCurveEditor", "Cancel", None))
        self.btnHelp.setText(_translate("frmCurveEditor", "Help", None))

