# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmCurveEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmCurveEditor(object):
    def setupUi(self, frmCurveEditor):
        frmCurveEditor.setObjectName("frmCurveEditor")
        frmCurveEditor.resize(589, 383)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmCurveEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmCurveEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralWidget)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.formLayout = QtWidgets.QFormLayout(self.fraParms)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblCurveID = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveID.setFont(font)
        self.lblCurveID.setObjectName("lblCurveID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblCurveID)
        self.lblDescription = QtWidgets.QLabel(self.fraParms)
        self.lblDescription.setObjectName("lblDescription")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblDescription)
        self.txtCurveName = QtWidgets.QLineEdit(self.fraParms)
        self.txtCurveName.setObjectName("txtCurveName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.txtCurveName)
        self.txtDescription = QtWidgets.QLineEdit(self.fraParms)
        self.txtDescription.setObjectName("txtDescription")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtDescription)
        self.lblCurveType = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblCurveType.setFont(font)
        self.lblCurveType.setObjectName("lblCurveType")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblCurveType)
        self.lblEquation = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblEquation.setFont(font)
        self.lblEquation.setObjectName("lblEquation")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblEquation)
        self.cboCurveType = QtWidgets.QComboBox(self.fraParms)
        self.cboCurveType.setObjectName("cboCurveType")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cboCurveType)
        self.txtEquation = QtWidgets.QLineEdit(self.fraParms)
        self.txtEquation.setObjectName("txtEquation")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtEquation)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.fraParms)
        self.tblMult = QtWidgets.QTableWidget(self.centralWidget)
        self.tblMult.setCornerButtonEnabled(False)
        self.tblMult.setRowCount(50)
        self.tblMult.setColumnCount(2)
        self.tblMult.setObjectName("tblMult")
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setHorizontalHeaderItem(1, item)
        self.tblMult.horizontalHeader().setVisible(True)
        self.tblMult.verticalHeader().setVisible(False)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tblMult)
        self.fraPlot = QtWidgets.QFrame(self.centralWidget)
        self.fraPlot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraPlot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraPlot.setObjectName("fraPlot")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fraPlot)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLoad = QtWidgets.QPushButton(self.fraOKCancel)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.fraOKCancel)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        spacerItem = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.btnHelp = QtWidgets.QPushButton(self.fraOKCancel)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout.addWidget(self.btnHelp)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.fraOKCancel)
        frmCurveEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmCurveEditor)
        QtCore.QMetaObject.connectSlotsByName(frmCurveEditor)
        frmCurveEditor.setTabOrder(self.txtCurveName, self.txtDescription)
        frmCurveEditor.setTabOrder(self.txtDescription, self.cboCurveType)
        frmCurveEditor.setTabOrder(self.cboCurveType, self.txtEquation)
        frmCurveEditor.setTabOrder(self.txtEquation, self.tblMult)
        frmCurveEditor.setTabOrder(self.tblMult, self.cmdCancel)
        frmCurveEditor.setTabOrder(self.cmdCancel, self.cmdOK)
        frmCurveEditor.setTabOrder(self.cmdOK, self.btnLoad)
        frmCurveEditor.setTabOrder(self.btnLoad, self.btnSave)
        frmCurveEditor.setTabOrder(self.btnSave, self.btnHelp)

    def retranslateUi(self, frmCurveEditor):
        _translate = QtCore.QCoreApplication.translate
        frmCurveEditor.setWindowTitle(_translate("frmCurveEditor", "EPANET Curve Editor"))
        self.lblCurveID.setText(_translate("frmCurveEditor", "Curve ID"))
        self.lblDescription.setText(_translate("frmCurveEditor", "<html><head/><body><p>Description</p></body></html>"))
        self.lblCurveType.setText(_translate("frmCurveEditor", "Curve Type"))
        self.lblEquation.setText(_translate("frmCurveEditor", "Equation"))
        item = self.tblMult.verticalHeaderItem(0)
        item.setText(_translate("frmCurveEditor", "Flow"))
        item = self.tblMult.horizontalHeaderItem(0)
        item.setText(_translate("frmCurveEditor", "Flow"))
        item = self.tblMult.horizontalHeaderItem(1)
        item.setText(_translate("frmCurveEditor", "Head"))
        self.btnLoad.setText(_translate("frmCurveEditor", "Load..."))
        self.btnSave.setText(_translate("frmCurveEditor", "Save..."))
        self.cmdOK.setText(_translate("frmCurveEditor", "OK"))
        self.cmdCancel.setText(_translate("frmCurveEditor", "Cancel"))
        self.btnHelp.setText(_translate("frmCurveEditor", "Help"))

