# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmEnergyOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmEnergyOptions(object):
    def setupUi(self, frmEnergyOptions):
        frmEnergyOptions.setObjectName("frmEnergyOptions")
        frmEnergyOptions.resize(302, 236)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmEnergyOptions.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmEnergyOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.gridLayout = QtWidgets.QGridLayout(self.fraParms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblGlobalEfficiency = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGlobalEfficiency.setFont(font)
        self.lblGlobalEfficiency.setObjectName("lblGlobalEfficiency")
        self.gridLayout.addWidget(self.lblGlobalEfficiency, 0, 0, 1, 1)
        self.txtGlobalEfficiency = QtWidgets.QLineEdit(self.fraParms)
        self.txtGlobalEfficiency.setObjectName("txtGlobalEfficiency")
        self.gridLayout.addWidget(self.txtGlobalEfficiency, 0, 1, 1, 1)
        self.lblGlobalPrice = QtWidgets.QLabel(self.fraParms)
        self.lblGlobalPrice.setObjectName("lblGlobalPrice")
        self.gridLayout.addWidget(self.lblGlobalPrice, 1, 0, 1, 1)
        self.txtGlobalPrice = QtWidgets.QLineEdit(self.fraParms)
        self.txtGlobalPrice.setObjectName("txtGlobalPrice")
        self.gridLayout.addWidget(self.txtGlobalPrice, 1, 1, 1, 1)
        self.lblGlobalPattern = QtWidgets.QLabel(self.fraParms)
        self.lblGlobalPattern.setObjectName("lblGlobalPattern")
        self.gridLayout.addWidget(self.lblGlobalPattern, 2, 0, 1, 1)
        self.txtGlobalPattern = QtWidgets.QLineEdit(self.fraParms)
        self.txtGlobalPattern.setObjectName("txtGlobalPattern")
        self.gridLayout.addWidget(self.txtGlobalPattern, 2, 1, 1, 1)
        self.lblDemandCharge = QtWidgets.QLabel(self.fraParms)
        self.lblDemandCharge.setObjectName("lblDemandCharge")
        self.gridLayout.addWidget(self.lblDemandCharge, 3, 0, 1, 1)
        self.txtDemandCharge = QtWidgets.QLineEdit(self.fraParms)
        self.txtDemandCharge.setObjectName("txtDemandCharge")
        self.gridLayout.addWidget(self.txtDemandCharge, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.fraParms)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmEnergyOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmEnergyOptions)
        QtCore.QMetaObject.connectSlotsByName(frmEnergyOptions)

    def retranslateUi(self, frmEnergyOptions):
        _translate = QtCore.QCoreApplication.translate
        frmEnergyOptions.setWindowTitle(_translate("frmEnergyOptions", "EPANET Energy Options"))
        self.lblGlobalEfficiency.setText(_translate("frmEnergyOptions", "Pump Efficiency (%)"))
        self.lblGlobalPrice.setText(_translate("frmEnergyOptions", "<html><head/><body><p>Energy Price/kwh</p></body></html>"))
        self.lblGlobalPattern.setText(_translate("frmEnergyOptions", "Price Pattern"))
        self.lblDemandCharge.setText(_translate("frmEnergyOptions", "Demand Charge"))
        self.cmdOK.setText(_translate("frmEnergyOptions", "OK"))
        self.cmdCancel.setText(_translate("frmEnergyOptions", "Cancel"))

