# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\EPANET\frmEnergyReportDesigner.ui'
#
# Created: Mon Aug 22 17:45:58 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmEnergyReport(object):
    def setupUi(self, frmEnergyReport):
        frmEnergyReport.setObjectName(_fromUtf8("frmEnergyReport"))
        frmEnergyReport.resize(685, 396)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmEnergyReport.setFont(font)
        self.centralWidget = QtGui.QWidget(frmEnergyReport)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.fraTop = QtGui.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtGui.QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraTop)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.fraTop)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabTable = QtGui.QWidget()
        self.tabTable.setObjectName(_fromUtf8("tabTable"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabTable)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidget = QtGui.QTableWidget(self.tabTable)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tabTable, _fromUtf8(""))
        self.tabChart = QtGui.QWidget()
        self.tabChart.setObjectName(_fromUtf8("tabChart"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabChart)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fraColumn = QtGui.QFrame(self.tabChart)
        self.fraColumn.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fraColumn.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraColumn.setFrameShadow(QtGui.QFrame.Raised)
        self.fraColumn.setObjectName(_fromUtf8("fraColumn"))
        self.verticalLayout = QtGui.QVBoxLayout(self.fraColumn)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbnUtilization = QtGui.QRadioButton(self.fraColumn)
        self.rbnUtilization.setObjectName(_fromUtf8("rbnUtilization"))
        self.verticalLayout.addWidget(self.rbnUtilization)
        self.rbnEfficiency = QtGui.QRadioButton(self.fraColumn)
        self.rbnEfficiency.setObjectName(_fromUtf8("rbnEfficiency"))
        self.verticalLayout.addWidget(self.rbnEfficiency)
        self.rbnKwHr = QtGui.QRadioButton(self.fraColumn)
        self.rbnKwHr.setObjectName(_fromUtf8("rbnKwHr"))
        self.verticalLayout.addWidget(self.rbnKwHr)
        self.rbnAverageKw = QtGui.QRadioButton(self.fraColumn)
        self.rbnAverageKw.setObjectName(_fromUtf8("rbnAverageKw"))
        self.verticalLayout.addWidget(self.rbnAverageKw)
        self.rbnPeakKw = QtGui.QRadioButton(self.fraColumn)
        self.rbnPeakKw.setObjectName(_fromUtf8("rbnPeakKw"))
        self.verticalLayout.addWidget(self.rbnPeakKw)
        self.rbnCost = QtGui.QRadioButton(self.fraColumn)
        self.rbnCost.setObjectName(_fromUtf8("rbnCost"))
        self.verticalLayout.addWidget(self.rbnCost)
        self.horizontalLayout_2.addWidget(self.fraColumn)
        self.frameChart = QtGui.QFrame(self.tabChart)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameChart.sizePolicy().hasHeightForWidth())
        self.frameChart.setSizePolicy(sizePolicy)
        self.frameChart.setObjectName(_fromUtf8("frameChart"))
        self.horizontalLayout_2.addWidget(self.frameChart)
        self.tabWidget.addTab(self.tabChart, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_8.addWidget(self.fraTop)
        self.fraOKCancel = QtGui.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtGui.QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdCancel = QtGui.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_8.addWidget(self.fraOKCancel)
        frmEnergyReport.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmEnergyReport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmEnergyReport)

    def retranslateUi(self, frmEnergyReport):
        frmEnergyReport.setWindowTitle(_translate("frmEnergyReport", "EPANET Energy Report", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("frmEnergyReport", "Pump 9", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("frmEnergyReport", "Total Cost", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("frmEnergyReport", "Demand Charge", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("frmEnergyReport", "Percent Utilization", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("frmEnergyReport", "Average Efficiency", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("frmEnergyReport", "Kw-hr/Mgal", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("frmEnergyReport", "Average Kwatts", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("frmEnergyReport", "Peak Kwatts", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("frmEnergyReport", "Cost / day", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTable), _translate("frmEnergyReport", "Table", None))
        self.rbnUtilization.setText(_translate("frmEnergyReport", "Utilization", None))
        self.rbnEfficiency.setText(_translate("frmEnergyReport", "Efficiency", None))
        self.rbnKwHr.setText(_translate("frmEnergyReport", "Kw-hr/Mgal", None))
        self.rbnAverageKw.setText(_translate("frmEnergyReport", "Average Kw", None))
        self.rbnPeakKw.setText(_translate("frmEnergyReport", "Peak Kw", None))
        self.rbnCost.setText(_translate("frmEnergyReport", "Cost / day", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabChart), _translate("frmEnergyReport", "Chart", None))
        self.cmdCancel.setText(_translate("frmEnergyReport", "Close", None))

