# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmEnergyReportDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmEnergyReport(object):
    def setupUi(self, frmEnergyReport):
        frmEnergyReport.setObjectName("frmEnergyReport")
        frmEnergyReport.resize(685, 396)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmEnergyReport.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmEnergyReport)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.fraTop)
        self.tabWidget.setObjectName("tabWidget")
        self.tabTable = QtWidgets.QWidget()
        self.tabTable.setObjectName("tabTable")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabTable)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget = QtWidgets.QTableWidget(self.tabTable)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tabTable, "")
        self.tabChart = QtWidgets.QWidget()
        self.tabChart.setObjectName("tabChart")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabChart)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fraColumn = QtWidgets.QFrame(self.tabChart)
        self.fraColumn.setMaximumSize(QtCore.QSize(400, 16777215))
        self.fraColumn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraColumn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraColumn.setObjectName("fraColumn")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fraColumn)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbnUtilization = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnUtilization.setObjectName("rbnUtilization")
        self.verticalLayout.addWidget(self.rbnUtilization)
        self.rbnEfficiency = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnEfficiency.setObjectName("rbnEfficiency")
        self.verticalLayout.addWidget(self.rbnEfficiency)
        self.rbnKwHr = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnKwHr.setObjectName("rbnKwHr")
        self.verticalLayout.addWidget(self.rbnKwHr)
        self.rbnAverageKw = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnAverageKw.setObjectName("rbnAverageKw")
        self.verticalLayout.addWidget(self.rbnAverageKw)
        self.rbnPeakKw = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnPeakKw.setObjectName("rbnPeakKw")
        self.verticalLayout.addWidget(self.rbnPeakKw)
        self.rbnCost = QtWidgets.QRadioButton(self.fraColumn)
        self.rbnCost.setObjectName("rbnCost")
        self.verticalLayout.addWidget(self.rbnCost)
        self.horizontalLayout_2.addWidget(self.fraColumn)
        self.frameChart = QtWidgets.QFrame(self.tabChart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameChart.sizePolicy().hasHeightForWidth())
        self.frameChart.setSizePolicy(sizePolicy)
        self.frameChart.setObjectName("frameChart")
        self.horizontalLayout_2.addWidget(self.frameChart)
        self.tabWidget.addTab(self.tabChart, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_8.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_8.addWidget(self.fraOKCancel)
        frmEnergyReport.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmEnergyReport)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmEnergyReport)

    def retranslateUi(self, frmEnergyReport):
        _translate = QtCore.QCoreApplication.translate
        frmEnergyReport.setWindowTitle(_translate("frmEnergyReport", "EPANET Energy Report"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("frmEnergyReport", "Pump 9"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("frmEnergyReport", "Total Cost"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("frmEnergyReport", "Demand Charge"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("frmEnergyReport", "Percent Utilization"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("frmEnergyReport", "Average Efficiency"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("frmEnergyReport", "Kw-hr/Mgal"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("frmEnergyReport", "Average Kwatts"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("frmEnergyReport", "Peak Kwatts"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("frmEnergyReport", "Cost / day"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTable), _translate("frmEnergyReport", "Table"))
        self.rbnUtilization.setText(_translate("frmEnergyReport", "Utilization"))
        self.rbnEfficiency.setText(_translate("frmEnergyReport", "Efficiency"))
        self.rbnKwHr.setText(_translate("frmEnergyReport", "Kw-hr/Mgal"))
        self.rbnAverageKw.setText(_translate("frmEnergyReport", "Average Kw"))
        self.rbnPeakKw.setText(_translate("frmEnergyReport", "Peak Kw"))
        self.rbnCost.setText(_translate("frmEnergyReport", "Cost / day"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabChart), _translate("frmEnergyReport", "Chart"))
        self.cmdCancel.setText(_translate("frmEnergyReport", "Close"))

