# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\EPANET\frmGraphDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmGraph(object):
    def setupUi(self, frmGraph):
        frmGraph.setObjectName(_fromUtf8("frmGraph"))
        frmGraph.resize(465, 396)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGraph.setFont(font)
        self.centralWidget = QtGui.QWidget(frmGraph)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.fraTop = QtGui.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtGui.QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraTop)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.fraLeft = QtGui.QFrame(self.fraTop)
        self.fraLeft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QtGui.QFrame.Raised)
        self.fraLeft.setObjectName(_fromUtf8("fraLeft"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.fraLeft)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbxType = QtGui.QGroupBox(self.fraLeft)
        self.gbxType.setObjectName(_fromUtf8("gbxType"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbxType)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbnTime = QtGui.QRadioButton(self.gbxType)
        self.rbnTime.setObjectName(_fromUtf8("rbnTime"))
        self.verticalLayout.addWidget(self.rbnTime)
        self.rbnProfile = QtGui.QRadioButton(self.gbxType)
        self.rbnProfile.setObjectName(_fromUtf8("rbnProfile"))
        self.verticalLayout.addWidget(self.rbnProfile)
        self.rbnContour = QtGui.QRadioButton(self.gbxType)
        self.rbnContour.setObjectName(_fromUtf8("rbnContour"))
        self.verticalLayout.addWidget(self.rbnContour)
        self.rbnFrequency = QtGui.QRadioButton(self.gbxType)
        self.rbnFrequency.setObjectName(_fromUtf8("rbnFrequency"))
        self.verticalLayout.addWidget(self.rbnFrequency)
        self.rbnSystem = QtGui.QRadioButton(self.gbxType)
        self.rbnSystem.setObjectName(_fromUtf8("rbnSystem"))
        self.verticalLayout.addWidget(self.rbnSystem)
        self.verticalLayout_2.addWidget(self.gbxType)
        self.gbxParameter = QtGui.QGroupBox(self.fraLeft)
        self.gbxParameter.setObjectName(_fromUtf8("gbxParameter"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxParameter)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cboParameter = QtGui.QComboBox(self.gbxParameter)
        self.cboParameter.setObjectName(_fromUtf8("cboParameter"))
        self.verticalLayout_3.addWidget(self.cboParameter)
        self.verticalLayout_2.addWidget(self.gbxParameter)
        self.gbxTime = QtGui.QGroupBox(self.fraLeft)
        self.gbxTime.setObjectName(_fromUtf8("gbxTime"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbxTime)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cboTime = QtGui.QComboBox(self.gbxTime)
        self.cboTime.setObjectName(_fromUtf8("cboTime"))
        self.verticalLayout_4.addWidget(self.cboTime)
        self.verticalLayout_2.addWidget(self.gbxTime)
        self.horizontalLayout_3.addWidget(self.fraLeft)
        self.fraRight = QtGui.QFrame(self.fraTop)
        self.fraRight.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtGui.QFrame.Raised)
        self.fraRight.setObjectName(_fromUtf8("fraRight"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fraRight)
        self.verticalLayout_6.setMargin(11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gbxObject = QtGui.QGroupBox(self.fraRight)
        self.gbxObject.setObjectName(_fromUtf8("gbxObject"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.gbxObject)
        self.verticalLayout_7.setMargin(11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.rbnNodes = QtGui.QRadioButton(self.gbxObject)
        self.rbnNodes.setObjectName(_fromUtf8("rbnNodes"))
        self.verticalLayout_7.addWidget(self.rbnNodes)
        self.rbnLinks = QtGui.QRadioButton(self.gbxObject)
        self.rbnLinks.setObjectName(_fromUtf8("rbnLinks"))
        self.verticalLayout_7.addWidget(self.rbnLinks)
        self.verticalLayout_6.addWidget(self.gbxObject)
        self.fraMid = QtGui.QFrame(self.fraRight)
        self.fraMid.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QtGui.QFrame.Raised)
        self.fraMid.setObjectName(_fromUtf8("fraMid"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraMid)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbxToGraph = QtGui.QGroupBox(self.fraMid)
        self.gbxToGraph.setObjectName(_fromUtf8("gbxToGraph"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbxToGraph)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lstToGraph = QtGui.QListWidget(self.gbxToGraph)
        self.lstToGraph.setObjectName(_fromUtf8("lstToGraph"))
        self.horizontalLayout_4.addWidget(self.lstToGraph)
        self.horizontalLayout_2.addWidget(self.gbxToGraph)
        self.fraButtons = QtGui.QFrame(self.fraMid)
        self.fraButtons.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtGui.QFrame.Raised)
        self.fraButtons.setObjectName(_fromUtf8("fraButtons"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.fraButtons)
        self.verticalLayout_5.setMargin(11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.cmdAdd = QtGui.QPushButton(self.fraButtons)
        self.cmdAdd.setObjectName(_fromUtf8("cmdAdd"))
        self.verticalLayout_5.addWidget(self.cmdAdd)
        self.cmdDelete = QtGui.QPushButton(self.fraButtons)
        self.cmdDelete.setObjectName(_fromUtf8("cmdDelete"))
        self.verticalLayout_5.addWidget(self.cmdDelete)
        self.cmdUp = QtGui.QPushButton(self.fraButtons)
        self.cmdUp.setObjectName(_fromUtf8("cmdUp"))
        self.verticalLayout_5.addWidget(self.cmdUp)
        self.cmdDown = QtGui.QPushButton(self.fraButtons)
        self.cmdDown.setObjectName(_fromUtf8("cmdDown"))
        self.verticalLayout_5.addWidget(self.cmdDown)
        self.horizontalLayout_2.addWidget(self.fraButtons)
        self.verticalLayout_6.addWidget(self.fraMid)
        self.horizontalLayout_3.addWidget(self.fraRight)
        self.verticalLayout_8.addWidget(self.fraTop)
        self.fraOKCancel = QtGui.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtGui.QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_8.addWidget(self.fraOKCancel)
        frmGraph.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGraph)
        QtCore.QMetaObject.connectSlotsByName(frmGraph)

    def retranslateUi(self, frmGraph):
        frmGraph.setWindowTitle(_translate("frmGraph", "EPANET Graph Selection", None))
        self.gbxType.setTitle(_translate("frmGraph", "Graph Type", None))
        self.rbnTime.setText(_translate("frmGraph", "Time Series", None))
        self.rbnProfile.setText(_translate("frmGraph", "Profile Plot", None))
        self.rbnContour.setText(_translate("frmGraph", "Contour Plot", None))
        self.rbnFrequency.setText(_translate("frmGraph", "Frequency Plot", None))
        self.rbnSystem.setText(_translate("frmGraph", "System Flow", None))
        self.gbxParameter.setTitle(_translate("frmGraph", "Parameter", None))
        self.gbxTime.setTitle(_translate("frmGraph", "Time Period", None))
        self.gbxObject.setTitle(_translate("frmGraph", "Object Type", None))
        self.rbnNodes.setText(_translate("frmGraph", "Nodes", None))
        self.rbnLinks.setText(_translate("frmGraph", "Links", None))
        self.gbxToGraph.setTitle(_translate("frmGraph", "Nodes to Graph", None))
        self.cmdAdd.setText(_translate("frmGraph", "Add", None))
        self.cmdDelete.setText(_translate("frmGraph", "Delete", None))
        self.cmdUp.setText(_translate("frmGraph", "Move Up", None))
        self.cmdDown.setText(_translate("frmGraph", "Move Down", None))
        self.cmdOK.setText(_translate("frmGraph", "OK", None))
        self.cmdCancel.setText(_translate("frmGraph", "Cancel", None))

