# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmGraphDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmGraph(object):
    def setupUi(self, frmGraph):
        frmGraph.setObjectName("frmGraph")
        frmGraph.resize(490, 465)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmGraph.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmGraph)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.fraTop)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fraLeft = QtWidgets.QFrame(self.fraTop)
        self.fraLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraLeft.setObjectName("fraLeft")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fraLeft)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxType = QtWidgets.QGroupBox(self.fraLeft)
        self.gbxType.setObjectName("gbxType")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxType)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbnTime = QtWidgets.QRadioButton(self.gbxType)
        self.rbnTime.setObjectName("rbnTime")
        self.verticalLayout.addWidget(self.rbnTime)
        self.rbnProfile = QtWidgets.QRadioButton(self.gbxType)
        self.rbnProfile.setObjectName("rbnProfile")
        self.verticalLayout.addWidget(self.rbnProfile)
        self.rbnContour = QtWidgets.QRadioButton(self.gbxType)
        self.rbnContour.setObjectName("rbnContour")
        self.verticalLayout.addWidget(self.rbnContour)
        self.rbnFrequency = QtWidgets.QRadioButton(self.gbxType)
        self.rbnFrequency.setObjectName("rbnFrequency")
        self.verticalLayout.addWidget(self.rbnFrequency)
        self.rbnSystem = QtWidgets.QRadioButton(self.gbxType)
        self.rbnSystem.setObjectName("rbnSystem")
        self.verticalLayout.addWidget(self.rbnSystem)
        self.verticalLayout_2.addWidget(self.gbxType)
        self.gbxParameter = QtWidgets.QGroupBox(self.fraLeft)
        self.gbxParameter.setObjectName("gbxParameter")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbxParameter)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cboParameter = QtWidgets.QComboBox(self.gbxParameter)
        self.cboParameter.setObjectName("cboParameter")
        self.verticalLayout_3.addWidget(self.cboParameter)
        self.verticalLayout_2.addWidget(self.gbxParameter)
        self.gbxTime = QtWidgets.QGroupBox(self.fraLeft)
        self.gbxTime.setObjectName("gbxTime")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbxTime)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cboTime = QtWidgets.QComboBox(self.gbxTime)
        self.cboTime.setObjectName("cboTime")
        self.verticalLayout_4.addWidget(self.cboTime)
        self.verticalLayout_2.addWidget(self.gbxTime)
        self.horizontalLayout_3.addWidget(self.fraLeft)
        self.fraRight = QtWidgets.QFrame(self.fraTop)
        self.fraRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraRight.setObjectName("fraRight")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fraRight)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gbxObject = QtWidgets.QGroupBox(self.fraRight)
        self.gbxObject.setObjectName("gbxObject")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gbxObject)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rbnNodes = QtWidgets.QRadioButton(self.gbxObject)
        self.rbnNodes.setObjectName("rbnNodes")
        self.verticalLayout_7.addWidget(self.rbnNodes)
        self.rbnLinks = QtWidgets.QRadioButton(self.gbxObject)
        self.rbnLinks.setObjectName("rbnLinks")
        self.verticalLayout_7.addWidget(self.rbnLinks)
        self.verticalLayout_6.addWidget(self.gbxObject)
        self.fraMid = QtWidgets.QFrame(self.fraRight)
        self.fraMid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMid.setObjectName("fraMid")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraMid)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gbxToGraph = QtWidgets.QGroupBox(self.fraMid)
        self.gbxToGraph.setObjectName("gbxToGraph")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbxToGraph)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lstToGraph = QtWidgets.QListWidget(self.gbxToGraph)
        self.lstToGraph.setObjectName("lstToGraph")
        self.horizontalLayout_4.addWidget(self.lstToGraph)
        self.horizontalLayout_2.addWidget(self.gbxToGraph)
        self.fraButtons = QtWidgets.QFrame(self.fraMid)
        self.fraButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraButtons.setObjectName("fraButtons")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fraButtons)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cmdAdd = QtWidgets.QPushButton(self.fraButtons)
        self.cmdAdd.setObjectName("cmdAdd")
        self.verticalLayout_5.addWidget(self.cmdAdd)
        self.cmdDelete = QtWidgets.QPushButton(self.fraButtons)
        self.cmdDelete.setObjectName("cmdDelete")
        self.verticalLayout_5.addWidget(self.cmdDelete)
        self.cmdUp = QtWidgets.QPushButton(self.fraButtons)
        self.cmdUp.setObjectName("cmdUp")
        self.verticalLayout_5.addWidget(self.cmdUp)
        self.cmdDown = QtWidgets.QPushButton(self.fraButtons)
        self.cmdDown.setObjectName("cmdDown")
        self.verticalLayout_5.addWidget(self.cmdDown)
        self.horizontalLayout_2.addWidget(self.fraButtons)
        self.verticalLayout_6.addWidget(self.fraMid)
        self.horizontalLayout_3.addWidget(self.fraRight)
        self.verticalLayout_8.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(338, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_8.addWidget(self.fraOKCancel)
        frmGraph.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmGraph)
        QtCore.QMetaObject.connectSlotsByName(frmGraph)

    def retranslateUi(self, frmGraph):
        _translate = QtCore.QCoreApplication.translate
        frmGraph.setWindowTitle(_translate("frmGraph", "EPANET Graph Selection"))
        self.gbxType.setTitle(_translate("frmGraph", "Graph Type"))
        self.rbnTime.setText(_translate("frmGraph", "Time Series"))
        self.rbnProfile.setText(_translate("frmGraph", "Profile Plot"))
        self.rbnContour.setText(_translate("frmGraph", "Contour Plot"))
        self.rbnFrequency.setText(_translate("frmGraph", "Frequency Plot"))
        self.rbnSystem.setText(_translate("frmGraph", "System Flow"))
        self.gbxParameter.setTitle(_translate("frmGraph", "Parameter"))
        self.gbxTime.setTitle(_translate("frmGraph", "Time Period"))
        self.gbxObject.setTitle(_translate("frmGraph", "Object Type"))
        self.rbnNodes.setText(_translate("frmGraph", "Nodes"))
        self.rbnLinks.setText(_translate("frmGraph", "Links"))
        self.gbxToGraph.setTitle(_translate("frmGraph", "Nodes to Graph"))
        self.cmdAdd.setText(_translate("frmGraph", "Add"))
        self.cmdDelete.setText(_translate("frmGraph", "Delete"))
        self.cmdUp.setText(_translate("frmGraph", "Move Up"))
        self.cmdDown.setText(_translate("frmGraph", "Move Down"))
        self.cmdOK.setText(_translate("frmGraph", "OK"))
        self.cmdCancel.setText(_translate("frmGraph", "Cancel"))

