# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\EPANET\frmHydraulicsOptionsDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmHydraulicsOptions(object):
    def setupUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setObjectName(_fromUtf8("frmHydraulicsOptions"))
        frmHydraulicsOptions.resize(589, 332)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmHydraulicsOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmHydraulicsOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.fraTop = QtGui.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtGui.QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraTop)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.fraLeft = QtGui.QFrame(self.fraTop)
        self.fraLeft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraLeft.setFrameShadow(QtGui.QFrame.Raised)
        self.fraLeft.setObjectName(_fromUtf8("fraLeft"))
        self.formLayout_2 = QtGui.QFormLayout(self.fraLeft)
        self.formLayout_2.setMargin(11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblFlowUnits = QtGui.QLabel(self.fraLeft)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblFlowUnits.setFont(font)
        self.lblFlowUnits.setObjectName(_fromUtf8("lblFlowUnits"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblFlowUnits)
        self.cboFlow = QtGui.QComboBox(self.fraLeft)
        self.cboFlow.setObjectName(_fromUtf8("cboFlow"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cboFlow)
        self.lblHeadloss = QtGui.QLabel(self.fraLeft)
        self.lblHeadloss.setObjectName(_fromUtf8("lblHeadloss"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblHeadloss)
        self.cboHeadloss = QtGui.QComboBox(self.fraLeft)
        self.cboHeadloss.setObjectName(_fromUtf8("cboHeadloss"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cboHeadloss)
        self.lblSpecificGravity = QtGui.QLabel(self.fraLeft)
        self.lblSpecificGravity.setObjectName(_fromUtf8("lblSpecificGravity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblSpecificGravity)
        self.txtSpecificGravity = QtGui.QLineEdit(self.fraLeft)
        self.txtSpecificGravity.setObjectName(_fromUtf8("txtSpecificGravity"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtSpecificGravity)
        self.lblRelativeViscosity = QtGui.QLabel(self.fraLeft)
        self.lblRelativeViscosity.setObjectName(_fromUtf8("lblRelativeViscosity"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblRelativeViscosity)
        self.txtRelativeViscosity = QtGui.QLineEdit(self.fraLeft)
        self.txtRelativeViscosity.setObjectName(_fromUtf8("txtRelativeViscosity"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtRelativeViscosity)
        self.gbxUnbalanced = QtGui.QGroupBox(self.fraLeft)
        self.gbxUnbalanced.setObjectName(_fromUtf8("gbxUnbalanced"))
        self.formLayout = QtGui.QFormLayout(self.gbxUnbalanced)
        self.formLayout.setMargin(11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.rbnStop = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnStop.setObjectName(_fromUtf8("rbnStop"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.rbnStop)
        self.rbnContinue = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnContinue.setObjectName(_fromUtf8("rbnContinue"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.rbnContinue)
        self.rbnContinueN = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnContinueN.setObjectName(_fromUtf8("rbnContinueN"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.rbnContinueN)
        self.txtContinueN = QtGui.QLineEdit(self.gbxUnbalanced)
        self.txtContinueN.setObjectName(_fromUtf8("txtContinueN"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtContinueN)
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.gbxUnbalanced)
        self.horizontalLayout_2.addWidget(self.fraLeft)
        self.frame = QtGui.QFrame(self.fraTop)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame)
        self.formLayout_3.setMargin(11)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lblMaximumTrials = QtGui.QLabel(self.frame)
        self.lblMaximumTrials.setObjectName(_fromUtf8("lblMaximumTrials"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblMaximumTrials)
        self.txtMaximumTrials = QtGui.QLineEdit(self.frame)
        self.txtMaximumTrials.setObjectName(_fromUtf8("txtMaximumTrials"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtMaximumTrials)
        self.lblAccuracy = QtGui.QLabel(self.frame)
        self.lblAccuracy.setObjectName(_fromUtf8("lblAccuracy"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblAccuracy)
        self.txtAccuracy = QtGui.QLineEdit(self.frame)
        self.txtAccuracy.setObjectName(_fromUtf8("txtAccuracy"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtAccuracy)
        self.lblDefaultPattern = QtGui.QLabel(self.frame)
        self.lblDefaultPattern.setObjectName(_fromUtf8("lblDefaultPattern"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblDefaultPattern)
        self.txtDefaultPattern = QtGui.QLineEdit(self.frame)
        self.txtDefaultPattern.setObjectName(_fromUtf8("txtDefaultPattern"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtDefaultPattern)
        self.lblDemandMultiplier = QtGui.QLabel(self.frame)
        self.lblDemandMultiplier.setObjectName(_fromUtf8("lblDemandMultiplier"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblDemandMultiplier)
        self.txtDemandMultiplier = QtGui.QLineEdit(self.frame)
        self.txtDemandMultiplier.setObjectName(_fromUtf8("txtDemandMultiplier"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtDemandMultiplier)
        self.lblEmitterExponent = QtGui.QLabel(self.frame)
        self.lblEmitterExponent.setObjectName(_fromUtf8("lblEmitterExponent"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblEmitterExponent)
        self.txtEmitterExponent = QtGui.QLineEdit(self.frame)
        self.txtEmitterExponent.setObjectName(_fromUtf8("txtEmitterExponent"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtEmitterExponent)
        self.lblCheckFrequency = QtGui.QLabel(self.frame)
        self.lblCheckFrequency.setObjectName(_fromUtf8("lblCheckFrequency"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblCheckFrequency)
        self.txtCheckFrequency = QtGui.QLineEdit(self.frame)
        self.txtCheckFrequency.setObjectName(_fromUtf8("txtCheckFrequency"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.txtCheckFrequency)
        self.lblMaxCheck = QtGui.QLabel(self.frame)
        self.lblMaxCheck.setObjectName(_fromUtf8("lblMaxCheck"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.lblMaxCheck)
        self.txtMaxCheck = QtGui.QLineEdit(self.frame)
        self.txtMaxCheck.setObjectName(_fromUtf8("txtMaxCheck"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.txtMaxCheck)
        self.lblDampLimit = QtGui.QLabel(self.frame)
        self.lblDampLimit.setObjectName(_fromUtf8("lblDampLimit"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.lblDampLimit)
        self.txtDampLimit = QtGui.QLineEdit(self.frame)
        self.txtDampLimit.setObjectName(_fromUtf8("txtDampLimit"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.txtDampLimit)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.fraTop)
        self.fraOKCancel = QtGui.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtGui.QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(386, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmHydraulicsOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmHydraulicsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmHydraulicsOptions)

    def retranslateUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setWindowTitle(_translate("frmHydraulicsOptions", "EPANET Hydraulics Options", None))
        self.lblFlowUnits.setText(_translate("frmHydraulicsOptions", "Flow Units", None))
        self.lblHeadloss.setText(_translate("frmHydraulicsOptions", "<html><head/><body><p>Headloss Formula</p></body></html>", None))
        self.lblSpecificGravity.setText(_translate("frmHydraulicsOptions", "Specific Gravity", None))
        self.lblRelativeViscosity.setText(_translate("frmHydraulicsOptions", "Relative Viscosity", None))
        self.gbxUnbalanced.setTitle(_translate("frmHydraulicsOptions", "If Unbalanced", None))
        self.rbnStop.setText(_translate("frmHydraulicsOptions", "Stop", None))
        self.rbnContinue.setText(_translate("frmHydraulicsOptions", "Continue", None))
        self.rbnContinueN.setText(_translate("frmHydraulicsOptions", "Continue N", None))
        self.lblMaximumTrials.setText(_translate("frmHydraulicsOptions", "Maximum Trials", None))
        self.lblAccuracy.setText(_translate("frmHydraulicsOptions", "Accuracy", None))
        self.lblDefaultPattern.setText(_translate("frmHydraulicsOptions", "Default Pattern", None))
        self.lblDemandMultiplier.setText(_translate("frmHydraulicsOptions", "Demand Multiplier", None))
        self.lblEmitterExponent.setText(_translate("frmHydraulicsOptions", "Emitter Exponent", None))
        self.lblCheckFrequency.setText(_translate("frmHydraulicsOptions", "Check Frequency", None))
        self.lblMaxCheck.setText(_translate("frmHydraulicsOptions", "Max Check", None))
        self.lblDampLimit.setText(_translate("frmHydraulicsOptions", "Damp Limit", None))
        self.cmdOK.setText(_translate("frmHydraulicsOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmHydraulicsOptions", "Cancel", None))

