# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\EPANET\frmHydraulicsOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmHydraulicsOptions(object):
    def setupUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setObjectName(_fromUtf8("frmHydraulicsOptions"))
        frmHydraulicsOptions.resize(576, 358)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmHydraulicsOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmHydraulicsOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.lblFlowUnits = QtGui.QLabel(self.centralWidget)
        self.lblFlowUnits.setGeometry(QtCore.QRect(30, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblFlowUnits.setFont(font)
        self.lblFlowUnits.setObjectName(_fromUtf8("lblFlowUnits"))
        self.lblHeadloss = QtGui.QLabel(self.centralWidget)
        self.lblHeadloss.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.lblHeadloss.setObjectName(_fromUtf8("lblHeadloss"))
        self.lblSpecificGravity = QtGui.QLabel(self.centralWidget)
        self.lblSpecificGravity.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.lblSpecificGravity.setObjectName(_fromUtf8("lblSpecificGravity"))
        self.cmdOK = QtGui.QPushButton(self.centralWidget)
        self.cmdOK.setGeometry(QtCore.QRect(200, 320, 75, 23))
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.cmdCancel = QtGui.QPushButton(self.centralWidget)
        self.cmdCancel.setGeometry(QtCore.QRect(300, 320, 75, 23))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.cboFlow = QtGui.QComboBox(self.centralWidget)
        self.cboFlow.setGeometry(QtCore.QRect(160, 20, 111, 22))
        self.cboFlow.setObjectName(_fromUtf8("cboFlow"))
        self.cboHeadloss = QtGui.QComboBox(self.centralWidget)
        self.cboHeadloss.setGeometry(QtCore.QRect(160, 50, 111, 22))
        self.cboHeadloss.setObjectName(_fromUtf8("cboHeadloss"))
        self.txtSpecificGravity = QtGui.QLineEdit(self.centralWidget)
        self.txtSpecificGravity.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.txtSpecificGravity.setObjectName(_fromUtf8("txtSpecificGravity"))
        self.lblRelativeViscosity = QtGui.QLabel(self.centralWidget)
        self.lblRelativeViscosity.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.lblRelativeViscosity.setObjectName(_fromUtf8("lblRelativeViscosity"))
        self.txtRelativeViscosity = QtGui.QLineEdit(self.centralWidget)
        self.txtRelativeViscosity.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.txtRelativeViscosity.setObjectName(_fromUtf8("txtRelativeViscosity"))
        self.lblMaximumTrials = QtGui.QLabel(self.centralWidget)
        self.lblMaximumTrials.setGeometry(QtCore.QRect(30, 140, 111, 16))
        self.lblMaximumTrials.setObjectName(_fromUtf8("lblMaximumTrials"))
        self.txtMaximumTrials = QtGui.QLineEdit(self.centralWidget)
        self.txtMaximumTrials.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.txtMaximumTrials.setObjectName(_fromUtf8("txtMaximumTrials"))
        self.lblAccuracy = QtGui.QLabel(self.centralWidget)
        self.lblAccuracy.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.lblAccuracy.setObjectName(_fromUtf8("lblAccuracy"))
        self.txtAccuracy = QtGui.QLineEdit(self.centralWidget)
        self.txtAccuracy.setGeometry(QtCore.QRect(160, 170, 113, 20))
        self.txtAccuracy.setObjectName(_fromUtf8("txtAccuracy"))
        self.lblDefaultPattern = QtGui.QLabel(self.centralWidget)
        self.lblDefaultPattern.setGeometry(QtCore.QRect(310, 20, 111, 16))
        self.lblDefaultPattern.setObjectName(_fromUtf8("lblDefaultPattern"))
        self.lblDemandMultiplier = QtGui.QLabel(self.centralWidget)
        self.lblDemandMultiplier.setGeometry(QtCore.QRect(310, 50, 111, 16))
        self.lblDemandMultiplier.setObjectName(_fromUtf8("lblDemandMultiplier"))
        self.lblEmitterExponent = QtGui.QLabel(self.centralWidget)
        self.lblEmitterExponent.setGeometry(QtCore.QRect(310, 80, 111, 16))
        self.lblEmitterExponent.setObjectName(_fromUtf8("lblEmitterExponent"))
        self.txtDefaultPattern = QtGui.QLineEdit(self.centralWidget)
        self.txtDefaultPattern.setGeometry(QtCore.QRect(440, 20, 113, 20))
        self.txtDefaultPattern.setObjectName(_fromUtf8("txtDefaultPattern"))
        self.txtDemandMultiplier = QtGui.QLineEdit(self.centralWidget)
        self.txtDemandMultiplier.setGeometry(QtCore.QRect(440, 50, 113, 20))
        self.txtDemandMultiplier.setObjectName(_fromUtf8("txtDemandMultiplier"))
        self.txtEmitterExponent = QtGui.QLineEdit(self.centralWidget)
        self.txtEmitterExponent.setGeometry(QtCore.QRect(440, 80, 113, 20))
        self.txtEmitterExponent.setObjectName(_fromUtf8("txtEmitterExponent"))
        self.lblCheckFrequency = QtGui.QLabel(self.centralWidget)
        self.lblCheckFrequency.setGeometry(QtCore.QRect(310, 110, 111, 16))
        self.lblCheckFrequency.setObjectName(_fromUtf8("lblCheckFrequency"))
        self.lblMaxCheck = QtGui.QLabel(self.centralWidget)
        self.lblMaxCheck.setGeometry(QtCore.QRect(310, 140, 111, 16))
        self.lblMaxCheck.setObjectName(_fromUtf8("lblMaxCheck"))
        self.lblDampLimit = QtGui.QLabel(self.centralWidget)
        self.lblDampLimit.setGeometry(QtCore.QRect(310, 170, 111, 16))
        self.lblDampLimit.setObjectName(_fromUtf8("lblDampLimit"))
        self.txtCheckFrequency = QtGui.QLineEdit(self.centralWidget)
        self.txtCheckFrequency.setGeometry(QtCore.QRect(440, 110, 113, 20))
        self.txtCheckFrequency.setObjectName(_fromUtf8("txtCheckFrequency"))
        self.txtMaxCheck = QtGui.QLineEdit(self.centralWidget)
        self.txtMaxCheck.setGeometry(QtCore.QRect(440, 140, 113, 20))
        self.txtMaxCheck.setObjectName(_fromUtf8("txtMaxCheck"))
        self.txtDampLimit = QtGui.QLineEdit(self.centralWidget)
        self.txtDampLimit.setGeometry(QtCore.QRect(440, 170, 113, 20))
        self.txtDampLimit.setObjectName(_fromUtf8("txtDampLimit"))
        self.gbxUnbalanced = QtGui.QGroupBox(self.centralWidget)
        self.gbxUnbalanced.setGeometry(QtCore.QRect(30, 210, 241, 91))
        self.gbxUnbalanced.setObjectName(_fromUtf8("gbxUnbalanced"))
        self.txtContinueN = QtGui.QLineEdit(self.gbxUnbalanced)
        self.txtContinueN.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.txtContinueN.setObjectName(_fromUtf8("txtContinueN"))
        self.rbnStop = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnStop.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.rbnStop.setObjectName(_fromUtf8("rbnStop"))
        self.rbnContinue = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnContinue.setGeometry(QtCore.QRect(30, 40, 82, 17))
        self.rbnContinue.setObjectName(_fromUtf8("rbnContinue"))
        self.rbnContinueN = QtGui.QRadioButton(self.gbxUnbalanced)
        self.rbnContinueN.setGeometry(QtCore.QRect(30, 60, 82, 17))
        self.rbnContinueN.setObjectName(_fromUtf8("rbnContinueN"))
        self.gbxHydraulics = QtGui.QGroupBox(self.centralWidget)
        self.gbxHydraulics.setGeometry(QtCore.QRect(300, 210, 251, 91))
        self.gbxHydraulics.setObjectName(_fromUtf8("gbxHydraulics"))
        self.txtHydraulicsFile = QtGui.QLineEdit(self.gbxHydraulics)
        self.txtHydraulicsFile.setGeometry(QtCore.QRect(20, 60, 211, 20))
        self.txtHydraulicsFile.setObjectName(_fromUtf8("txtHydraulicsFile"))
        self.rbnUse = QtGui.QRadioButton(self.gbxHydraulics)
        self.rbnUse.setGeometry(QtCore.QRect(20, 30, 82, 17))
        self.rbnUse.setObjectName(_fromUtf8("rbnUse"))
        self.rbnSave = QtGui.QRadioButton(self.gbxHydraulics)
        self.rbnSave.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.rbnSave.setObjectName(_fromUtf8("rbnSave"))
        frmHydraulicsOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmHydraulicsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmHydraulicsOptions)

    def retranslateUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setWindowTitle(_translate("frmHydraulicsOptions", "EPANET Hydraulics Options", None))
        self.lblFlowUnits.setText(_translate("frmHydraulicsOptions", "Flow Units", None))
        self.lblHeadloss.setText(_translate("frmHydraulicsOptions", "<html><head/><body><p>Headloss Formula</p></body></html>", None))
        self.lblSpecificGravity.setText(_translate("frmHydraulicsOptions", "Specific Gravity", None))
        self.cmdOK.setText(_translate("frmHydraulicsOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmHydraulicsOptions", "Cancel", None))
        self.lblRelativeViscosity.setText(_translate("frmHydraulicsOptions", "Relative Viscosity", None))
        self.lblMaximumTrials.setText(_translate("frmHydraulicsOptions", "Maximum Trials", None))
        self.lblAccuracy.setText(_translate("frmHydraulicsOptions", "Accuracy", None))
        self.lblDefaultPattern.setText(_translate("frmHydraulicsOptions", "Default Pattern", None))
        self.lblDemandMultiplier.setText(_translate("frmHydraulicsOptions", "Demand Multiplier", None))
        self.lblEmitterExponent.setText(_translate("frmHydraulicsOptions", "Emitter Exponent", None))
        self.lblCheckFrequency.setText(_translate("frmHydraulicsOptions", "Check Frequency", None))
        self.lblMaxCheck.setText(_translate("frmHydraulicsOptions", "Max Check", None))
        self.lblDampLimit.setText(_translate("frmHydraulicsOptions", "Damp Limit", None))
        self.gbxUnbalanced.setTitle(_translate("frmHydraulicsOptions", "If Unbalanced", None))
        self.rbnStop.setText(_translate("frmHydraulicsOptions", "Stop", None))
        self.rbnContinue.setText(_translate("frmHydraulicsOptions", "Continue", None))
        self.rbnContinueN.setText(_translate("frmHydraulicsOptions", "Continue N", None))
        self.gbxHydraulics.setTitle(_translate("frmHydraulicsOptions", "Hydraulics File", None))
        self.rbnUse.setText(_translate("frmHydraulicsOptions", "Use", None))
        self.rbnSave.setText(_translate("frmHydraulicsOptions", "Save", None))

