# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmMapBackdropOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmMapBackdropOptions(object):
    def setupUi(self, frmMapBackdropOptions):
        frmMapBackdropOptions.setObjectName("frmMapBackdropOptions")
        frmMapBackdropOptions.resize(662, 487)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmMapBackdropOptions.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmMapBackdropOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraMapFile = QtWidgets.QFrame(self.centralWidget)
        self.fraMapFile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMapFile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMapFile.setObjectName("fraMapFile")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fraMapFile)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblMapFile = QtWidgets.QLabel(self.fraMapFile)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMapFile.setFont(font)
        self.lblMapFile.setObjectName("lblMapFile")
        self.horizontalLayout_2.addWidget(self.lblMapFile)
        self.txtMapFile = QtWidgets.QLineEdit(self.fraMapFile)
        self.txtMapFile.setObjectName("txtMapFile")
        self.horizontalLayout_2.addWidget(self.txtMapFile)
        self.verticalLayout.addWidget(self.fraMapFile)
        self.gbxMap = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxMap.setObjectName("gbxMap")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbxMap)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gbxLL = QtWidgets.QGroupBox(self.gbxMap)
        self.gbxLL.setObjectName("gbxLL")
        self.formLayout = QtWidgets.QFormLayout(self.gbxLL)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lblLLX = QtWidgets.QLabel(self.gbxLL)
        self.lblLLX.setObjectName("lblLLX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblLLX)
        self.txtLLX = QtWidgets.QLineEdit(self.gbxLL)
        self.txtLLX.setObjectName("txtLLX")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtLLX)
        self.lblLLY = QtWidgets.QLabel(self.gbxLL)
        self.lblLLY.setObjectName("lblLLY")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblLLY)
        self.txtLLY = QtWidgets.QLineEdit(self.gbxLL)
        self.txtLLY.setObjectName("txtLLY")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtLLY)
        self.horizontalLayout_4.addWidget(self.gbxLL)
        self.gbxUR = QtWidgets.QGroupBox(self.gbxMap)
        self.gbxUR.setObjectName("gbxUR")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gbxUR)
        self.formLayout_2.setContentsMargins(11, 11, 11, 11)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lblURX = QtWidgets.QLabel(self.gbxUR)
        self.lblURX.setObjectName("lblURX")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblURX)
        self.txtURX = QtWidgets.QLineEdit(self.gbxUR)
        self.txtURX.setObjectName("txtURX")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtURX)
        self.lblURY = QtWidgets.QLabel(self.gbxUR)
        self.lblURY.setObjectName("lblURY")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblURY)
        self.txtURY = QtWidgets.QLineEdit(self.gbxUR)
        self.txtURY.setObjectName("txtURY")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtURY)
        self.horizontalLayout_4.addWidget(self.gbxUR)
        self.verticalLayout.addWidget(self.gbxMap)
        self.fraMapUnits = QtWidgets.QFrame(self.centralWidget)
        self.fraMapUnits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMapUnits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMapUnits.setObjectName("fraMapUnits")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.fraMapUnits)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblMapUnits = QtWidgets.QLabel(self.fraMapUnits)
        self.lblMapUnits.setObjectName("lblMapUnits")
        self.horizontalLayout_5.addWidget(self.lblMapUnits)
        self.cboMapUnits = QtWidgets.QComboBox(self.fraMapUnits)
        self.cboMapUnits.setObjectName("cboMapUnits")
        self.horizontalLayout_5.addWidget(self.cboMapUnits)
        spacerItem = QtWidgets.QSpacerItem(484, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addWidget(self.fraMapUnits)
        self.fraBackdrop = QtWidgets.QFrame(self.centralWidget)
        self.fraBackdrop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraBackdrop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraBackdrop.setObjectName("fraBackdrop")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fraBackdrop)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblBackdrop = QtWidgets.QLabel(self.fraBackdrop)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBackdrop.setFont(font)
        self.lblBackdrop.setObjectName("lblBackdrop")
        self.horizontalLayout_6.addWidget(self.lblBackdrop)
        self.txtBackdropFile = QtWidgets.QLineEdit(self.fraBackdrop)
        self.txtBackdropFile.setObjectName("txtBackdropFile")
        self.horizontalLayout_6.addWidget(self.txtBackdropFile)
        self.verticalLayout.addWidget(self.fraBackdrop)
        self.gbxBackdrop = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxBackdrop.setObjectName("gbxBackdrop")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxBackdrop)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.txtBackdropY = QtWidgets.QLineEdit(self.gbxBackdrop)
        self.txtBackdropY.setObjectName("txtBackdropY")
        self.gridLayout.addWidget(self.txtBackdropY, 1, 3, 1, 1)
        self.lblX = QtWidgets.QLabel(self.gbxBackdrop)
        self.lblX.setObjectName("lblX")
        self.gridLayout.addWidget(self.lblX, 1, 0, 1, 1)
        self.txtBackdropX = QtWidgets.QLineEdit(self.gbxBackdrop)
        self.txtBackdropX.setObjectName("txtBackdropX")
        self.gridLayout.addWidget(self.txtBackdropX, 1, 1, 1, 1)
        self.lblY = QtWidgets.QLabel(self.gbxBackdrop)
        self.lblY.setObjectName("lblY")
        self.gridLayout.addWidget(self.lblY, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout.addWidget(self.gbxBackdrop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmMapBackdropOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmMapBackdropOptions)
        QtCore.QMetaObject.connectSlotsByName(frmMapBackdropOptions)

    def retranslateUi(self, frmMapBackdropOptions):
        _translate = QtCore.QCoreApplication.translate
        frmMapBackdropOptions.setWindowTitle(_translate("frmMapBackdropOptions", "EPANET Map/Backdrop Options"))
        self.lblMapFile.setText(_translate("frmMapBackdropOptions", "Map File Name"))
        self.gbxMap.setTitle(_translate("frmMapBackdropOptions", "Map Dimensions"))
        self.gbxLL.setTitle(_translate("frmMapBackdropOptions", "Lower Left"))
        self.lblLLX.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblLLY.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.gbxUR.setTitle(_translate("frmMapBackdropOptions", "Upper Right"))
        self.lblURX.setText(_translate("frmMapBackdropOptions", "X-Coordinate"))
        self.lblURY.setText(_translate("frmMapBackdropOptions", "Y-Coordinate"))
        self.lblMapUnits.setText(_translate("frmMapBackdropOptions", "Map Units"))
        self.lblBackdrop.setText(_translate("frmMapBackdropOptions", "Backdrop File Name"))
        self.gbxBackdrop.setTitle(_translate("frmMapBackdropOptions", "Backdrop Offsets"))
        self.lblX.setText(_translate("frmMapBackdropOptions", "X"))
        self.lblY.setText(_translate("frmMapBackdropOptions", "Y"))
        self.cmdOK.setText(_translate("frmMapBackdropOptions", "OK"))
        self.cmdCancel.setText(_translate("frmMapBackdropOptions", "Cancel"))

