# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmPatternEditorDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmPatternEditor(object):
    def setupUi(self, frmPatternEditor):
        frmPatternEditor.setObjectName("frmPatternEditor")
        frmPatternEditor.resize(575, 262)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmPatternEditor.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmPatternEditor)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraParms = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraParms.sizePolicy().hasHeightForWidth())
        self.fraParms.setSizePolicy(sizePolicy)
        self.fraParms.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraParms.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraParms.setObjectName("fraParms")
        self.gridLayout = QtWidgets.QGridLayout(self.fraParms)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(325, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.lblDescription = QtWidgets.QLabel(self.fraParms)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.lblPatternID = QtWidgets.QLabel(self.fraParms)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPatternID.setFont(font)
        self.lblPatternID.setObjectName("lblPatternID")
        self.gridLayout.addWidget(self.lblPatternID, 0, 0, 1, 1)
        self.tblMult = QtWidgets.QTableWidget(self.fraParms)
        self.tblMult.setRowCount(1)
        self.tblMult.setColumnCount(24)
        self.tblMult.setObjectName("tblMult")
        item = QtWidgets.QTableWidgetItem()
        self.tblMult.setVerticalHeaderItem(0, item)
        self.gridLayout.addWidget(self.tblMult, 2, 0, 1, 3)
        self.txtPatternID = QtWidgets.QLineEdit(self.fraParms)
        self.txtPatternID.setObjectName("txtPatternID")
        self.gridLayout.addWidget(self.txtPatternID, 0, 1, 1, 1)
        self.txtDescription = QtWidgets.QLineEdit(self.fraParms)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 1, 1, 1, 2)
        self.verticalLayout.addWidget(self.fraParms)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(99, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmPatternEditor.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmPatternEditor)
        QtCore.QMetaObject.connectSlotsByName(frmPatternEditor)

    def retranslateUi(self, frmPatternEditor):
        _translate = QtCore.QCoreApplication.translate
        frmPatternEditor.setWindowTitle(_translate("frmPatternEditor", "EPANET Pattern Editor"))
        self.lblDescription.setText(_translate("frmPatternEditor", "<html><head/><body><p>Description</p></body></html>"))
        self.lblPatternID.setText(_translate("frmPatternEditor", "Pattern ID"))
        item = self.tblMult.verticalHeaderItem(0)
        item.setText(_translate("frmPatternEditor", "Multiplier"))
        self.cmdOK.setText(_translate("frmPatternEditor", "OK"))
        self.cmdCancel.setText(_translate("frmPatternEditor", "Cancel"))

