# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmQualityOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmQualityOptions(object):
    def setupUi(self, frmQualityOptions):
        frmQualityOptions.setObjectName("frmQualityOptions")
        frmQualityOptions.resize(287, 379)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmQualityOptions.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmQualityOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxQuality = QtWidgets.QGroupBox(self.centralWidget)
        self.gbxQuality.setObjectName("gbxQuality")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbxQuality)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbnTrace = QtWidgets.QRadioButton(self.gbxQuality)
        self.rbnTrace.setObjectName("rbnTrace")
        self.gridLayout_2.addWidget(self.rbnTrace, 1, 1, 1, 1)
        self.rbnNone = QtWidgets.QRadioButton(self.gbxQuality)
        self.rbnNone.setObjectName("rbnNone")
        self.gridLayout_2.addWidget(self.rbnNone, 0, 0, 1, 1)
        self.rbnAge = QtWidgets.QRadioButton(self.gbxQuality)
        self.rbnAge.setObjectName("rbnAge")
        self.gridLayout_2.addWidget(self.rbnAge, 0, 1, 1, 1)
        self.rbnChemical = QtWidgets.QRadioButton(self.gbxQuality)
        self.rbnChemical.setObjectName("rbnChemical")
        self.gridLayout_2.addWidget(self.rbnChemical, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.gbxQuality)
        self.fraMiddle = QtWidgets.QFrame(self.centralWidget)
        self.fraMiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraMiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraMiddle.setObjectName("fraMiddle")
        self.gridLayout = QtWidgets.QGridLayout(self.fraMiddle)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblTolerance = QtWidgets.QLabel(self.fraMiddle)
        self.lblTolerance.setObjectName("lblTolerance")
        self.gridLayout.addWidget(self.lblTolerance, 4, 0, 1, 1)
        self.txtTraceNode = QtWidgets.QLineEdit(self.fraMiddle)
        self.txtTraceNode.setObjectName("txtTraceNode")
        self.gridLayout.addWidget(self.txtTraceNode, 3, 1, 1, 1)
        self.txtTolerance = QtWidgets.QLineEdit(self.fraMiddle)
        self.txtTolerance.setObjectName("txtTolerance")
        self.gridLayout.addWidget(self.txtTolerance, 4, 1, 1, 1)
        self.lblTraceNode = QtWidgets.QLabel(self.fraMiddle)
        self.lblTraceNode.setObjectName("lblTraceNode")
        self.gridLayout.addWidget(self.lblTraceNode, 3, 0, 1, 1)
        self.txtChemicalName = QtWidgets.QLineEdit(self.fraMiddle)
        self.txtChemicalName.setObjectName("txtChemicalName")
        self.gridLayout.addWidget(self.txtChemicalName, 0, 1, 1, 1)
        self.lblChemicalName = QtWidgets.QLabel(self.fraMiddle)
        self.lblChemicalName.setObjectName("lblChemicalName")
        self.gridLayout.addWidget(self.lblChemicalName, 0, 0, 1, 1)
        self.lblDiffusivity = QtWidgets.QLabel(self.fraMiddle)
        self.lblDiffusivity.setObjectName("lblDiffusivity")
        self.gridLayout.addWidget(self.lblDiffusivity, 2, 0, 1, 1)
        self.lblMassUnits = QtWidgets.QLabel(self.fraMiddle)
        self.lblMassUnits.setObjectName("lblMassUnits")
        self.gridLayout.addWidget(self.lblMassUnits, 1, 0, 1, 1)
        self.txtMassUnits = QtWidgets.QLineEdit(self.fraMiddle)
        self.txtMassUnits.setObjectName("txtMassUnits")
        self.gridLayout.addWidget(self.txtMassUnits, 1, 1, 1, 1)
        self.txtDiffusivity = QtWidgets.QLineEdit(self.fraMiddle)
        self.txtDiffusivity.setObjectName("txtDiffusivity")
        self.gridLayout.addWidget(self.txtDiffusivity, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.fraMiddle)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(84, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.frame_2)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.frame_2)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.frame_2)
        frmQualityOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmQualityOptions)
        QtCore.QMetaObject.connectSlotsByName(frmQualityOptions)

    def retranslateUi(self, frmQualityOptions):
        _translate = QtCore.QCoreApplication.translate
        frmQualityOptions.setWindowTitle(_translate("frmQualityOptions", "EPANET Quality Options"))
        self.gbxQuality.setTitle(_translate("frmQualityOptions", "Analysis Type"))
        self.rbnTrace.setText(_translate("frmQualityOptions", "Trace"))
        self.rbnNone.setText(_translate("frmQualityOptions", "None"))
        self.rbnAge.setText(_translate("frmQualityOptions", "Age"))
        self.rbnChemical.setText(_translate("frmQualityOptions", "Chemical"))
        self.lblTolerance.setText(_translate("frmQualityOptions", "Quality Tolerance"))
        self.lblTraceNode.setText(_translate("frmQualityOptions", "Trace Node"))
        self.lblChemicalName.setText(_translate("frmQualityOptions", "<html><head/><body><p>Chemical Name</p></body></html>"))
        self.lblDiffusivity.setText(_translate("frmQualityOptions", "Relative Diffusivity"))
        self.lblMassUnits.setText(_translate("frmQualityOptions", "Mass Units"))
        self.cmdOK.setText(_translate("frmQualityOptions", "OK"))
        self.cmdCancel.setText(_translate("frmQualityOptions", "Cancel"))

