# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\SWMM-EPANET_User_Interface\src\ui\plugins\EPANET\frmReportOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmHydraulicsOptions(object):
    def setupUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setObjectName(_fromUtf8("frmHydraulicsOptions"))
        frmHydraulicsOptions.resize(414, 695)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmHydraulicsOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmHydraulicsOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.lblPageSize = QtGui.QLabel(self.centralWidget)
        self.lblPageSize.setGeometry(QtCore.QRect(30, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPageSize.setFont(font)
        self.lblPageSize.setObjectName(_fromUtf8("lblPageSize"))
        self.lblReportFileName = QtGui.QLabel(self.centralWidget)
        self.lblReportFileName.setGeometry(QtCore.QRect(30, 50, 121, 16))
        self.lblReportFileName.setObjectName(_fromUtf8("lblReportFileName"))
        self.lblStatus = QtGui.QLabel(self.centralWidget)
        self.lblStatus.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.lblStatus.setObjectName(_fromUtf8("lblStatus"))
        self.cmdOK = QtGui.QPushButton(self.centralWidget)
        self.cmdOK.setGeometry(QtCore.QRect(110, 640, 75, 23))
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.cmdCancel = QtGui.QPushButton(self.centralWidget)
        self.cmdCancel.setGeometry(QtCore.QRect(210, 640, 75, 23))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.cboSummary = QtGui.QComboBox(self.centralWidget)
        self.cboSummary.setGeometry(QtCore.QRect(160, 110, 111, 22))
        self.cboSummary.setObjectName(_fromUtf8("cboSummary"))
        self.cboEnergy = QtGui.QComboBox(self.centralWidget)
        self.cboEnergy.setGeometry(QtCore.QRect(160, 140, 111, 22))
        self.cboEnergy.setObjectName(_fromUtf8("cboEnergy"))
        self.lblSummary = QtGui.QLabel(self.centralWidget)
        self.lblSummary.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.lblSummary.setObjectName(_fromUtf8("lblSummary"))
        self.lblEnergy = QtGui.QLabel(self.centralWidget)
        self.lblEnergy.setGeometry(QtCore.QRect(30, 140, 111, 16))
        self.lblEnergy.setObjectName(_fromUtf8("lblEnergy"))
        self.cboStatus = QtGui.QComboBox(self.centralWidget)
        self.cboStatus.setGeometry(QtCore.QRect(160, 80, 111, 22))
        self.cboStatus.setObjectName(_fromUtf8("cboStatus"))
        self.txtReportFileName = QtGui.QLineEdit(self.centralWidget)
        self.txtReportFileName.setGeometry(QtCore.QRect(160, 50, 231, 20))
        self.txtReportFileName.setObjectName(_fromUtf8("txtReportFileName"))
        self.txtPageSize = QtGui.QLineEdit(self.centralWidget)
        self.txtPageSize.setGeometry(QtCore.QRect(160, 20, 113, 20))
        self.txtPageSize.setObjectName(_fromUtf8("txtPageSize"))
        self.gbxNode = QtGui.QGroupBox(self.centralWidget)
        self.gbxNode.setGeometry(QtCore.QRect(20, 180, 371, 171))
        self.gbxNode.setObjectName(_fromUtf8("gbxNode"))
        self.cbxNode1 = QtGui.QCheckBox(self.gbxNode)
        self.cbxNode1.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.cbxNode1.setObjectName(_fromUtf8("cbxNode1"))
        self.cbxNode3 = QtGui.QCheckBox(self.gbxNode)
        self.cbxNode3.setGeometry(QtCore.QRect(20, 90, 101, 17))
        self.cbxNode3.setObjectName(_fromUtf8("cbxNode3"))
        self.cbxNode2 = QtGui.QCheckBox(self.gbxNode)
        self.cbxNode2.setGeometry(QtCore.QRect(20, 70, 70, 17))
        self.cbxNode2.setObjectName(_fromUtf8("cbxNode2"))
        self.cbxNode4 = QtGui.QCheckBox(self.gbxNode)
        self.cbxNode4.setGeometry(QtCore.QRect(20, 110, 101, 17))
        self.cbxNode4.setObjectName(_fromUtf8("cbxNode4"))
        self.cbxNode5 = QtGui.QCheckBox(self.gbxNode)
        self.cbxNode5.setGeometry(QtCore.QRect(20, 130, 101, 17))
        self.cbxNode5.setObjectName(_fromUtf8("cbxNode5"))
        self.cboNode1 = QtGui.QComboBox(self.gbxNode)
        self.cboNode1.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.cboNode1.setObjectName(_fromUtf8("cboNode1"))
        self.cboNode2 = QtGui.QComboBox(self.gbxNode)
        self.cboNode2.setGeometry(QtCore.QRect(110, 70, 69, 22))
        self.cboNode2.setObjectName(_fromUtf8("cboNode2"))
        self.cboNode3 = QtGui.QComboBox(self.gbxNode)
        self.cboNode3.setGeometry(QtCore.QRect(110, 90, 69, 22))
        self.cboNode3.setObjectName(_fromUtf8("cboNode3"))
        self.cboNode4 = QtGui.QComboBox(self.gbxNode)
        self.cboNode4.setGeometry(QtCore.QRect(110, 110, 69, 22))
        self.cboNode4.setObjectName(_fromUtf8("cboNode4"))
        self.cboNode5 = QtGui.QComboBox(self.gbxNode)
        self.cboNode5.setGeometry(QtCore.QRect(110, 130, 69, 22))
        self.cboNode5.setObjectName(_fromUtf8("cboNode5"))
        self.lblLimit = QtGui.QLabel(self.gbxNode)
        self.lblLimit.setGeometry(QtCore.QRect(110, 30, 71, 16))
        self.lblLimit.setObjectName(_fromUtf8("lblLimit"))
        self.txtNode1 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode1.setGeometry(QtCore.QRect(180, 50, 81, 20))
        self.txtNode1.setObjectName(_fromUtf8("txtNode1"))
        self.txtNode2 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode2.setGeometry(QtCore.QRect(180, 70, 81, 20))
        self.txtNode2.setObjectName(_fromUtf8("txtNode2"))
        self.txtNode3 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode3.setGeometry(QtCore.QRect(180, 90, 81, 20))
        self.txtNode3.setObjectName(_fromUtf8("txtNode3"))
        self.txtNode4 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode4.setGeometry(QtCore.QRect(180, 110, 81, 20))
        self.txtNode4.setObjectName(_fromUtf8("txtNode4"))
        self.txtNode5 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode5.setGeometry(QtCore.QRect(180, 130, 81, 20))
        self.txtNode5.setObjectName(_fromUtf8("txtNode5"))
        self.lblPrecision = QtGui.QLabel(self.gbxNode)
        self.lblPrecision.setGeometry(QtCore.QRect(270, 30, 71, 16))
        self.lblPrecision.setObjectName(_fromUtf8("lblPrecision"))
        self.txtNode6 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode6.setGeometry(QtCore.QRect(270, 50, 81, 20))
        self.txtNode6.setObjectName(_fromUtf8("txtNode6"))
        self.txtNode8 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode8.setGeometry(QtCore.QRect(270, 90, 81, 20))
        self.txtNode8.setObjectName(_fromUtf8("txtNode8"))
        self.txtNode7 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode7.setGeometry(QtCore.QRect(270, 70, 81, 20))
        self.txtNode7.setObjectName(_fromUtf8("txtNode7"))
        self.txtNode10 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode10.setGeometry(QtCore.QRect(270, 130, 81, 20))
        self.txtNode10.setObjectName(_fromUtf8("txtNode10"))
        self.txtNode9 = QtGui.QLineEdit(self.gbxNode)
        self.txtNode9.setGeometry(QtCore.QRect(270, 110, 81, 20))
        self.txtNode9.setObjectName(_fromUtf8("txtNode9"))
        self.gbxLink = QtGui.QGroupBox(self.centralWidget)
        self.gbxLink.setGeometry(QtCore.QRect(20, 370, 371, 251))
        self.gbxLink.setObjectName(_fromUtf8("gbxLink"))
        self.cbxLink1 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink1.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.cbxLink1.setObjectName(_fromUtf8("cbxLink1"))
        self.cbxLink3 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink3.setGeometry(QtCore.QRect(20, 90, 101, 17))
        self.cbxLink3.setObjectName(_fromUtf8("cbxLink3"))
        self.cbxLink2 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink2.setGeometry(QtCore.QRect(20, 70, 70, 17))
        self.cbxLink2.setObjectName(_fromUtf8("cbxLink2"))
        self.cbxLink4 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink4.setGeometry(QtCore.QRect(20, 110, 101, 17))
        self.cbxLink4.setObjectName(_fromUtf8("cbxLink4"))
        self.cbxLink5 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink5.setGeometry(QtCore.QRect(20, 130, 101, 17))
        self.cbxLink5.setObjectName(_fromUtf8("cbxLink5"))
        self.cboLink1 = QtGui.QComboBox(self.gbxLink)
        self.cboLink1.setGeometry(QtCore.QRect(110, 50, 69, 22))
        self.cboLink1.setObjectName(_fromUtf8("cboLink1"))
        self.cboLink2 = QtGui.QComboBox(self.gbxLink)
        self.cboLink2.setGeometry(QtCore.QRect(110, 70, 69, 22))
        self.cboLink2.setObjectName(_fromUtf8("cboLink2"))
        self.cboLink3 = QtGui.QComboBox(self.gbxLink)
        self.cboLink3.setGeometry(QtCore.QRect(110, 90, 69, 22))
        self.cboLink3.setObjectName(_fromUtf8("cboLink3"))
        self.cboLink4 = QtGui.QComboBox(self.gbxLink)
        self.cboLink4.setGeometry(QtCore.QRect(110, 110, 69, 22))
        self.cboLink4.setObjectName(_fromUtf8("cboLink4"))
        self.cboLink5 = QtGui.QComboBox(self.gbxLink)
        self.cboLink5.setGeometry(QtCore.QRect(110, 130, 69, 22))
        self.cboLink5.setObjectName(_fromUtf8("cboLink5"))
        self.lblLimitLink = QtGui.QLabel(self.gbxLink)
        self.lblLimitLink.setGeometry(QtCore.QRect(110, 30, 71, 16))
        self.lblLimitLink.setObjectName(_fromUtf8("lblLimitLink"))
        self.txtLink1 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink1.setGeometry(QtCore.QRect(180, 50, 81, 20))
        self.txtLink1.setObjectName(_fromUtf8("txtLink1"))
        self.txtLink2 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink2.setGeometry(QtCore.QRect(180, 70, 81, 20))
        self.txtLink2.setObjectName(_fromUtf8("txtLink2"))
        self.txtLink3 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink3.setGeometry(QtCore.QRect(180, 90, 81, 20))
        self.txtLink3.setObjectName(_fromUtf8("txtLink3"))
        self.txtLink4 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink4.setGeometry(QtCore.QRect(180, 110, 81, 20))
        self.txtLink4.setObjectName(_fromUtf8("txtLink4"))
        self.txtLink5 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink5.setGeometry(QtCore.QRect(180, 130, 81, 20))
        self.txtLink5.setObjectName(_fromUtf8("txtLink5"))
        self.lblPrecisionLink = QtGui.QLabel(self.gbxLink)
        self.lblPrecisionLink.setGeometry(QtCore.QRect(270, 30, 71, 16))
        self.lblPrecisionLink.setObjectName(_fromUtf8("lblPrecisionLink"))
        self.txtLink10 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink10.setGeometry(QtCore.QRect(270, 50, 81, 20))
        self.txtLink10.setObjectName(_fromUtf8("txtLink10"))
        self.txtLink12 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink12.setGeometry(QtCore.QRect(270, 90, 81, 20))
        self.txtLink12.setObjectName(_fromUtf8("txtLink12"))
        self.txtLink11 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink11.setGeometry(QtCore.QRect(270, 70, 81, 20))
        self.txtLink11.setObjectName(_fromUtf8("txtLink11"))
        self.txtLink14 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink14.setGeometry(QtCore.QRect(270, 130, 81, 20))
        self.txtLink14.setObjectName(_fromUtf8("txtLink14"))
        self.txtLink13 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink13.setGeometry(QtCore.QRect(270, 110, 81, 20))
        self.txtLink13.setObjectName(_fromUtf8("txtLink13"))
        self.cboLink6 = QtGui.QComboBox(self.gbxLink)
        self.cboLink6.setGeometry(QtCore.QRect(110, 150, 69, 22))
        self.cboLink6.setObjectName(_fromUtf8("cboLink6"))
        self.txtLink15 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink15.setGeometry(QtCore.QRect(270, 150, 81, 20))
        self.txtLink15.setObjectName(_fromUtf8("txtLink15"))
        self.txtLink6 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink6.setGeometry(QtCore.QRect(180, 150, 81, 20))
        self.txtLink6.setObjectName(_fromUtf8("txtLink6"))
        self.cbxLink6 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink6.setGeometry(QtCore.QRect(20, 150, 101, 17))
        self.cbxLink6.setObjectName(_fromUtf8("cbxLink6"))
        self.cboLink7 = QtGui.QComboBox(self.gbxLink)
        self.cboLink7.setGeometry(QtCore.QRect(110, 170, 69, 22))
        self.cboLink7.setObjectName(_fromUtf8("cboLink7"))
        self.txtLink16 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink16.setGeometry(QtCore.QRect(270, 170, 81, 20))
        self.txtLink16.setObjectName(_fromUtf8("txtLink16"))
        self.txtLink7 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink7.setGeometry(QtCore.QRect(180, 170, 81, 20))
        self.txtLink7.setObjectName(_fromUtf8("txtLink7"))
        self.cbxLink7 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink7.setGeometry(QtCore.QRect(20, 170, 101, 17))
        self.cbxLink7.setObjectName(_fromUtf8("cbxLink7"))
        self.cboLink8 = QtGui.QComboBox(self.gbxLink)
        self.cboLink8.setGeometry(QtCore.QRect(110, 190, 69, 22))
        self.cboLink8.setObjectName(_fromUtf8("cboLink8"))
        self.txtLink17 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink17.setGeometry(QtCore.QRect(270, 190, 81, 20))
        self.txtLink17.setObjectName(_fromUtf8("txtLink17"))
        self.txtLink8 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink8.setGeometry(QtCore.QRect(180, 190, 81, 20))
        self.txtLink8.setObjectName(_fromUtf8("txtLink8"))
        self.cbxLink8 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink8.setGeometry(QtCore.QRect(20, 190, 101, 17))
        self.cbxLink8.setObjectName(_fromUtf8("cbxLink8"))
        self.cboLink9 = QtGui.QComboBox(self.gbxLink)
        self.cboLink9.setGeometry(QtCore.QRect(110, 210, 69, 22))
        self.cboLink9.setObjectName(_fromUtf8("cboLink9"))
        self.txtLink18 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink18.setGeometry(QtCore.QRect(270, 210, 81, 20))
        self.txtLink18.setObjectName(_fromUtf8("txtLink18"))
        self.txtLink9 = QtGui.QLineEdit(self.gbxLink)
        self.txtLink9.setGeometry(QtCore.QRect(180, 210, 81, 20))
        self.txtLink9.setObjectName(_fromUtf8("txtLink9"))
        self.cbxLink9 = QtGui.QCheckBox(self.gbxLink)
        self.cbxLink9.setGeometry(QtCore.QRect(20, 210, 101, 17))
        self.cbxLink9.setObjectName(_fromUtf8("cbxLink9"))
        frmHydraulicsOptions.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtGui.QToolBar(frmHydraulicsOptions)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        frmHydraulicsOptions.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(frmHydraulicsOptions)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        frmHydraulicsOptions.setStatusBar(self.statusBar)

        self.retranslateUi(frmHydraulicsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmHydraulicsOptions)

    def retranslateUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setWindowTitle(_translate("frmHydraulicsOptions", "EPANET Hydraulics Options", None))
        self.lblPageSize.setText(_translate("frmHydraulicsOptions", "Page Size", None))
        self.lblReportFileName.setText(_translate("frmHydraulicsOptions", "<html><head/><body><p>Report File Name</p></body></html>", None))
        self.lblStatus.setText(_translate("frmHydraulicsOptions", "Status", None))
        self.cmdOK.setText(_translate("frmHydraulicsOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmHydraulicsOptions", "Cancel", None))
        self.lblSummary.setText(_translate("frmHydraulicsOptions", "Summary", None))
        self.lblEnergy.setText(_translate("frmHydraulicsOptions", "Energy", None))
        self.gbxNode.setTitle(_translate("frmHydraulicsOptions", "Node Parameters:", None))
        self.cbxNode1.setText(_translate("frmHydraulicsOptions", "Elevation", None))
        self.cbxNode3.setText(_translate("frmHydraulicsOptions", "Head", None))
        self.cbxNode2.setText(_translate("frmHydraulicsOptions", "Demand", None))
        self.cbxNode4.setText(_translate("frmHydraulicsOptions", "Pressure", None))
        self.cbxNode5.setText(_translate("frmHydraulicsOptions", "Quality", None))
        self.lblLimit.setText(_translate("frmHydraulicsOptions", "Limit", None))
        self.lblPrecision.setText(_translate("frmHydraulicsOptions", "Precision", None))
        self.gbxLink.setTitle(_translate("frmHydraulicsOptions", "Link Parameters:", None))
        self.cbxLink1.setText(_translate("frmHydraulicsOptions", "Length", None))
        self.cbxLink3.setText(_translate("frmHydraulicsOptions", "Flow", None))
        self.cbxLink2.setText(_translate("frmHydraulicsOptions", "Diameter", None))
        self.cbxLink4.setText(_translate("frmHydraulicsOptions", "Velocity", None))
        self.cbxLink5.setText(_translate("frmHydraulicsOptions", "Headloss", None))
        self.lblLimitLink.setText(_translate("frmHydraulicsOptions", "Limit", None))
        self.lblPrecisionLink.setText(_translate("frmHydraulicsOptions", "Precision", None))
        self.cbxLink6.setText(_translate("frmHydraulicsOptions", "Position", None))
        self.cbxLink7.setText(_translate("frmHydraulicsOptions", "Setting", None))
        self.cbxLink8.setText(_translate("frmHydraulicsOptions", "Reaction", None))
        self.cbxLink9.setText(_translate("frmHydraulicsOptions", "F-Factor", None))

