# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EPANET\frmReactionsOptionsDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frmReactionsOptions(object):
    def setupUi(self, frmReactionsOptions):
        frmReactionsOptions.setObjectName("frmReactionsOptions")
        frmReactionsOptions.resize(339, 338)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmReactionsOptions.setFont(font)
        self.centralWidget = QtWidgets.QWidget(frmReactionsOptions)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fraTop = QtWidgets.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraTop.setObjectName("fraTop")
        self.gridLayout = QtWidgets.QGridLayout(self.fraTop)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lblBulkOrder = QtWidgets.QLabel(self.fraTop)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblBulkOrder.setFont(font)
        self.lblBulkOrder.setObjectName("lblBulkOrder")
        self.gridLayout.addWidget(self.lblBulkOrder, 0, 0, 1, 1)
        self.txtBulkOrder = QtWidgets.QLineEdit(self.fraTop)
        self.txtBulkOrder.setObjectName("txtBulkOrder")
        self.gridLayout.addWidget(self.txtBulkOrder, 0, 1, 1, 1)
        self.lblWallOrder = QtWidgets.QLabel(self.fraTop)
        self.lblWallOrder.setObjectName("lblWallOrder")
        self.gridLayout.addWidget(self.lblWallOrder, 1, 0, 1, 1)
        self.txtWallOrder = QtWidgets.QLineEdit(self.fraTop)
        self.txtWallOrder.setObjectName("txtWallOrder")
        self.gridLayout.addWidget(self.txtWallOrder, 1, 1, 1, 1)
        self.lblTankOrder = QtWidgets.QLabel(self.fraTop)
        self.lblTankOrder.setObjectName("lblTankOrder")
        self.gridLayout.addWidget(self.lblTankOrder, 2, 0, 1, 1)
        self.txtTankOrder = QtWidgets.QLineEdit(self.fraTop)
        self.txtTankOrder.setObjectName("txtTankOrder")
        self.gridLayout.addWidget(self.txtTankOrder, 2, 1, 1, 1)
        self.lblGlobalBulk = QtWidgets.QLabel(self.fraTop)
        self.lblGlobalBulk.setObjectName("lblGlobalBulk")
        self.gridLayout.addWidget(self.lblGlobalBulk, 3, 0, 1, 1)
        self.txtGlobalBulk = QtWidgets.QLineEdit(self.fraTop)
        self.txtGlobalBulk.setObjectName("txtGlobalBulk")
        self.gridLayout.addWidget(self.txtGlobalBulk, 3, 1, 1, 1)
        self.lblGlobalWall = QtWidgets.QLabel(self.fraTop)
        self.lblGlobalWall.setObjectName("lblGlobalWall")
        self.gridLayout.addWidget(self.lblGlobalWall, 4, 0, 1, 1)
        self.txtGlobalWall = QtWidgets.QLineEdit(self.fraTop)
        self.txtGlobalWall.setObjectName("txtGlobalWall")
        self.gridLayout.addWidget(self.txtGlobalWall, 4, 1, 1, 1)
        self.lblLimiting = QtWidgets.QLabel(self.fraTop)
        self.lblLimiting.setObjectName("lblLimiting")
        self.gridLayout.addWidget(self.lblLimiting, 5, 0, 1, 1)
        self.txtLimiting = QtWidgets.QLineEdit(self.fraTop)
        self.txtLimiting.setObjectName("txtLimiting")
        self.gridLayout.addWidget(self.txtLimiting, 5, 1, 1, 1)
        self.lblCorrelation = QtWidgets.QLabel(self.fraTop)
        self.lblCorrelation.setObjectName("lblCorrelation")
        self.gridLayout.addWidget(self.lblCorrelation, 6, 0, 1, 1)
        self.txtCorrelation = QtWidgets.QLineEdit(self.fraTop)
        self.txtCorrelation.setObjectName("txtCorrelation")
        self.gridLayout.addWidget(self.txtCorrelation, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.fraTop)
        self.fraOKCancel = QtWidgets.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fraOKCancel.setObjectName("fraOKCancel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(136, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName("cmdOK")
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtWidgets.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName("cmdCancel")
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout.addWidget(self.fraOKCancel)
        frmReactionsOptions.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmReactionsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmReactionsOptions)

    def retranslateUi(self, frmReactionsOptions):
        _translate = QtCore.QCoreApplication.translate
        frmReactionsOptions.setWindowTitle(_translate("frmReactionsOptions", "EPANET Reactions Options"))
        self.lblBulkOrder.setText(_translate("frmReactionsOptions", "Bulk Reaction Order"))
        self.lblWallOrder.setText(_translate("frmReactionsOptions", "<html><head/><body><p>Wall Reaction Order</p></body></html>"))
        self.lblTankOrder.setText(_translate("frmReactionsOptions", "Tank Reaction Order"))
        self.lblGlobalBulk.setText(_translate("frmReactionsOptions", "Global Bulk Coefficient"))
        self.lblGlobalWall.setText(_translate("frmReactionsOptions", "Global Wall Coefficient"))
        self.lblLimiting.setText(_translate("frmReactionsOptions", "Limiting Concentration"))
        self.lblCorrelation.setText(_translate("frmReactionsOptions", "Wall Roughness Correlation"))
        self.cmdOK.setText(_translate("frmReactionsOptions", "OK"))
        self.cmdCancel.setText(_translate("frmReactionsOptions", "Cancel"))

