# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\dev-ui\src\ui\EPANET\frmTableDesigner.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmTable(object):
    def setupUi(self, frmTable):
        frmTable.setObjectName(_fromUtf8("frmTable"))
        frmTable.resize(465, 396)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmTable.setFont(font)
        self.centralWidget = QtGui.QWidget(frmTable)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setMargin(11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.fraTop = QtGui.QFrame(self.centralWidget)
        self.fraTop.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraTop.setFrameShadow(QtGui.QFrame.Raised)
        self.fraTop.setObjectName(_fromUtf8("fraTop"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.fraTop)
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.fraTop)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabType = QtGui.QWidget()
        self.tabType.setObjectName(_fromUtf8("tabType"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabType)
        self.verticalLayout_4.setMargin(11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSelect = QtGui.QLabel(self.tabType)
        self.lblSelect.setObjectName(_fromUtf8("lblSelect"))
        self.verticalLayout_4.addWidget(self.lblSelect)
        self.fraType1 = QtGui.QFrame(self.tabType)
        self.fraType1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraType1.setFrameShadow(QtGui.QFrame.Raised)
        self.fraType1.setObjectName(_fromUtf8("fraType1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.fraType1)
        self.gridLayout_2.setMargin(11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rbnTimeseriesNode = QtGui.QRadioButton(self.fraType1)
        self.rbnTimeseriesNode.setObjectName(_fromUtf8("rbnTimeseriesNode"))
        self.gridLayout_2.addWidget(self.rbnTimeseriesNode, 4, 0, 1, 1)
        self.rbnTimeseriesLink = QtGui.QRadioButton(self.fraType1)
        self.rbnTimeseriesLink.setObjectName(_fromUtf8("rbnTimeseriesLink"))
        self.gridLayout_2.addWidget(self.rbnTimeseriesLink, 6, 0, 1, 1)
        self.txtNodeLink = QtGui.QLineEdit(self.fraType1)
        self.txtNodeLink.setObjectName(_fromUtf8("txtNodeLink"))
        self.gridLayout_2.addWidget(self.txtNodeLink, 5, 1, 1, 1)
        self.rbnNodes = QtGui.QRadioButton(self.fraType1)
        self.rbnNodes.setObjectName(_fromUtf8("rbnNodes"))
        self.gridLayout_2.addWidget(self.rbnNodes, 0, 0, 1, 1)
        self.cboTime = QtGui.QComboBox(self.fraType1)
        self.cboTime.setObjectName(_fromUtf8("cboTime"))
        self.gridLayout_2.addWidget(self.cboTime, 1, 1, 1, 1)
        self.rbnLinks = QtGui.QRadioButton(self.fraType1)
        self.rbnLinks.setObjectName(_fromUtf8("rbnLinks"))
        self.gridLayout_2.addWidget(self.rbnLinks, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.fraType1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.fraType1)
        self.tabWidget.addTab(self.tabType, _fromUtf8(""))
        self.tabColumns = QtGui.QWidget()
        self.tabColumns.setObjectName(_fromUtf8("tabColumns"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabColumns)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSelectColumn = QtGui.QLabel(self.tabColumns)
        self.lblSelectColumn.setObjectName(_fromUtf8("lblSelectColumn"))
        self.verticalLayout_3.addWidget(self.lblSelectColumn)
        self.lstColumns = QtGui.QListWidget(self.tabColumns)
        self.lstColumns.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lstColumns.setObjectName(_fromUtf8("lstColumns"))
        self.verticalLayout_3.addWidget(self.lstColumns)
        self.cbxSort = QtGui.QCheckBox(self.tabColumns)
        self.cbxSort.setObjectName(_fromUtf8("cbxSort"))
        self.verticalLayout_3.addWidget(self.cbxSort)
        self.tabWidget.addTab(self.tabColumns, _fromUtf8(""))
        self.tabFilters = QtGui.QWidget()
        self.tabFilters.setObjectName(_fromUtf8("tabFilters"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabFilters)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblDefine = QtGui.QLabel(self.tabFilters)
        self.lblDefine.setObjectName(_fromUtf8("lblDefine"))
        self.verticalLayout_2.addWidget(self.lblDefine)
        self.fraFilter1 = QtGui.QFrame(self.tabFilters)
        self.fraFilter1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraFilter1.setFrameShadow(QtGui.QFrame.Raised)
        self.fraFilter1.setObjectName(_fromUtf8("fraFilter1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.fraFilter1)
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cboFilter = QtGui.QComboBox(self.fraFilter1)
        self.cboFilter.setObjectName(_fromUtf8("cboFilter"))
        self.horizontalLayout_2.addWidget(self.cboFilter)
        self.cboCompare = QtGui.QComboBox(self.fraFilter1)
        self.cboCompare.setObjectName(_fromUtf8("cboCompare"))
        self.horizontalLayout_2.addWidget(self.cboCompare)
        self.txtValue = QtGui.QLineEdit(self.fraFilter1)
        self.txtValue.setObjectName(_fromUtf8("txtValue"))
        self.horizontalLayout_2.addWidget(self.txtValue)
        self.verticalLayout_2.addWidget(self.fraFilter1)
        self.lstFilter = QtGui.QListWidget(self.tabFilters)
        self.lstFilter.setObjectName(_fromUtf8("lstFilter"))
        self.verticalLayout_2.addWidget(self.lstFilter)
        self.fraFilter3 = QtGui.QFrame(self.tabFilters)
        self.fraFilter3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraFilter3.setFrameShadow(QtGui.QFrame.Raised)
        self.fraFilter3.setObjectName(_fromUtf8("fraFilter3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.fraFilter3)
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cmdAdd = QtGui.QPushButton(self.fraFilter3)
        self.cmdAdd.setObjectName(_fromUtf8("cmdAdd"))
        self.horizontalLayout_4.addWidget(self.cmdAdd)
        self.cmdDelete = QtGui.QPushButton(self.fraFilter3)
        self.cmdDelete.setObjectName(_fromUtf8("cmdDelete"))
        self.horizontalLayout_4.addWidget(self.cmdDelete)
        self.verticalLayout_2.addWidget(self.fraFilter3)
        self.tabWidget.addTab(self.tabFilters, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_8.addWidget(self.fraTop)
        self.fraOKCancel = QtGui.QFrame(self.centralWidget)
        self.fraOKCancel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fraOKCancel.setFrameShadow(QtGui.QFrame.Raised)
        self.fraOKCancel.setObjectName(_fromUtf8("fraOKCancel"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.fraOKCancel)
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(338, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cmdOK = QtGui.QPushButton(self.fraOKCancel)
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.horizontalLayout.addWidget(self.cmdOK)
        self.cmdCancel = QtGui.QPushButton(self.fraOKCancel)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.verticalLayout_8.addWidget(self.fraOKCancel)
        frmTable.setCentralWidget(self.centralWidget)

        self.retranslateUi(frmTable)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmTable)

    def retranslateUi(self, frmTable):
        frmTable.setWindowTitle(_translate("frmTable", "EPANET Table Selection", None))
        self.lblSelect.setText(_translate("frmTable", "Select the type of table to create:", None))
        self.rbnTimeseriesNode.setText(_translate("frmTable", "Time series for node", None))
        self.rbnTimeseriesLink.setText(_translate("frmTable", "Time series for link", None))
        self.rbnNodes.setText(_translate("frmTable", "Network Nodes at", None))
        self.rbnLinks.setText(_translate("frmTable", "Network Links at", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabType), _translate("frmTable", "Type", None))
        self.lblSelectColumn.setText(_translate("frmTable", "Select which columns to include in the table:", None))
        self.cbxSort.setText(_translate("frmTable", "Sort by", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabColumns), _translate("frmTable", "Columns", None))
        self.lblDefine.setText(_translate("frmTable", "Define conditions for selecting table entries: ", None))
        self.cmdAdd.setText(_translate("frmTable", "Add", None))
        self.cmdDelete.setText(_translate("frmTable", "Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilters), _translate("frmTable", "Filters", None))
        self.cmdOK.setText(_translate("frmTable", "OK", None))
        self.cmdCancel.setText(_translate("frmTable", "Cancel", None))

