# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\dev\Python\QtForms\frmHydraulicsOptions\frmHydraulicsOptions.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmHydraulicsOptions(object):
    def setupUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setObjectName(_fromUtf8("frmHydraulicsOptions"))
        frmHydraulicsOptions.resize(304, 501)
        font = QtGui.QFont()
        font.setPointSize(10)
        frmHydraulicsOptions.setFont(font)
        self.centralWidget = QtGui.QWidget(frmHydraulicsOptions)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.lblFlowUnits = QtGui.QLabel(self.centralWidget)
        self.lblFlowUnits.setGeometry(QtCore.QRect(30, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblFlowUnits.setFont(font)
        self.lblFlowUnits.setObjectName(_fromUtf8("lblFlowUnits"))
        self.lblHeadlossFormula = QtGui.QLabel(self.centralWidget)
        self.lblHeadlossFormula.setGeometry(QtCore.QRect(30, 50, 101, 16))
        self.lblHeadlossFormula.setObjectName(_fromUtf8("lblHeadlossFormula"))
        self.lblSpecificGravity = QtGui.QLabel(self.centralWidget)
        self.lblSpecificGravity.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.lblSpecificGravity.setObjectName(_fromUtf8("lblSpecificGravity"))
        self.txtSpecificGravity = QtGui.QLineEdit(self.centralWidget)
        self.txtSpecificGravity.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.txtSpecificGravity.setObjectName(_fromUtf8("txtSpecificGravity"))
        self.cboFlowUnits = QtGui.QComboBox(self.centralWidget)
        self.cboFlowUnits.setGeometry(QtCore.QRect(160, 20, 111, 22))
        self.cboFlowUnits.setObjectName(_fromUtf8("cboFlow"))
        self.cboHeadloss = QtGui.QComboBox(self.centralWidget)
        self.cboHeadloss.setGeometry(QtCore.QRect(160, 50, 111, 22))
        self.cboHeadloss.setObjectName(_fromUtf8("cboHeadloss"))
        self.lblRelativeViscosity = QtGui.QLabel(self.centralWidget)
        self.lblRelativeViscosity.setGeometry(QtCore.QRect(30, 110, 111, 16))
        self.lblRelativeViscosity.setObjectName(_fromUtf8("lblRelativeViscosity"))
        self.txtRelativeViscosity = QtGui.QLineEdit(self.centralWidget)
        self.txtRelativeViscosity.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.txtRelativeViscosity.setObjectName(_fromUtf8("txtRelativeViscosity"))
        self.lblMaximumTrials = QtGui.QLabel(self.centralWidget)
        self.lblMaximumTrials.setGeometry(QtCore.QRect(30, 140, 111, 16))
        self.lblMaximumTrials.setObjectName(_fromUtf8("lblMaximumTrials"))
        self.txtMaximumTrials = QtGui.QLineEdit(self.centralWidget)
        self.txtMaximumTrials.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.txtMaximumTrials.setObjectName(_fromUtf8("txtMaximumTrials"))
        self.lblAccuracy = QtGui.QLabel(self.centralWidget)
        self.lblAccuracy.setGeometry(QtCore.QRect(30, 170, 111, 16))
        self.lblAccuracy.setObjectName(_fromUtf8("lbl6"))
        self.txtAccuracy = QtGui.QLineEdit(self.centralWidget)
        self.txtAccuracy.setGeometry(QtCore.QRect(160, 170, 113, 20))
        self.txtAccuracy.setObjectName(_fromUtf8("txtAccuracy"))
        self.lblUnbalanced = QtGui.QLabel(self.centralWidget)
        self.lblUnbalanced.setGeometry(QtCore.QRect(30, 200, 111, 16))
        self.lblUnbalanced.setObjectName(_fromUtf8("lblUnbalanced"))
        self.cboUnbalanced = QtGui.QComboBox(self.centralWidget)
        self.cboUnbalanced.setGeometry(QtCore.QRect(160, 200, 111, 22))
        self.cboUnbalanced.setObjectName(_fromUtf8("cboUnbalanced"))
        self.lblDefaultPattern = QtGui.QLabel(self.centralWidget)
        self.lblDefaultPattern.setGeometry(QtCore.QRect(30, 230, 111, 16))
        self.lblDefaultPattern.setObjectName(_fromUtf8("lbl8"))
        self.txtDefaultPattern = QtGui.QLineEdit(self.centralWidget)
        self.txtDefaultPattern.setGeometry(QtCore.QRect(160, 230, 113, 20))
        self.txtDefaultPattern.setObjectName(_fromUtf8("txtDefaultPattern"))
        self.lblDemandMultiplier = QtGui.QLabel(self.centralWidget)
        self.lblDemandMultiplier.setGeometry(QtCore.QRect(30, 260, 111, 16))
        self.lblDemandMultiplier.setObjectName(_fromUtf8("lbl9"))
        self.txtDemandMultiplier = QtGui.QLineEdit(self.centralWidget)
        self.txtDemandMultiplier.setGeometry(QtCore.QRect(160, 260, 113, 20))
        self.txtDemandMultiplier.setObjectName(_fromUtf8("txtDemandMultiplier"))
        self.lbl1EmitterExponent = QtGui.QLabel(self.centralWidget)
        self.lbl1EmitterExponent.setGeometry(QtCore.QRect(30, 290, 111, 16))
        self.lbl1EmitterExponent.setObjectName(_fromUtf8("lbl10"))
        self.txtEmitterExponent = QtGui.QLineEdit(self.centralWidget)
        self.txtEmitterExponent.setGeometry(QtCore.QRect(160, 290, 113, 20))
        self.txtEmitterExponent.setObjectName(_fromUtf8("txtEmitterExponent"))
        self.lblStatusReport = QtGui.QLabel(self.centralWidget)
        self.lblStatusReport.setGeometry(QtCore.QRect(30, 320, 111, 16))
        self.lblStatusReport.setObjectName(_fromUtf8("lblStatusReport"))
        self.cboStatus = QtGui.QComboBox(self.centralWidget)
        self.cboStatus.setGeometry(QtCore.QRect(160, 320, 111, 22))
        self.cboStatus.setObjectName(_fromUtf8("cboStatus"))
        self.lblCheckFrequency = QtGui.QLabel(self.centralWidget)
        self.lblCheckFrequency.setGeometry(QtCore.QRect(30, 350, 111, 16))
        self.lblCheckFrequency.setObjectName(_fromUtf8("lblCheckFrequency"))
        self.txtCheckFrequency = QtGui.QLineEdit(self.centralWidget)
        self.txtCheckFrequency.setGeometry(QtCore.QRect(160, 350, 113, 20))
        self.txtCheckFrequency.setObjectName(_fromUtf8("txtCheckFrequency"))
        self.lblMaxCheck = QtGui.QLabel(self.centralWidget)
        self.lblMaxCheck.setGeometry(QtCore.QRect(30, 380, 111, 16))
        self.lblMaxCheck.setObjectName(_fromUtf8("lblMaxCheck"))
        self.txtMaxCheck = QtGui.QLineEdit(self.centralWidget)
        self.txtMaxCheck.setGeometry(QtCore.QRect(160, 380, 113, 20))
        self.txtMaxCheck.setObjectName(_fromUtf8("txtMaxCheck"))
        self.lblDampLimit = QtGui.QLabel(self.centralWidget)
        self.lblDampLimit.setGeometry(QtCore.QRect(30, 410, 111, 16))
        self.lblDampLimit.setObjectName(_fromUtf8("lbl14"))
        self.txtDampLimit = QtGui.QLineEdit(self.centralWidget)
        self.txtDampLimit.setGeometry(QtCore.QRect(160, 410, 113, 20))
        self.txtDampLimit.setObjectName(_fromUtf8("txtDampLimit"))
        self.cmdOK = QtGui.QPushButton(self.centralWidget)
        self.cmdOK.setGeometry(QtCore.QRect(60, 440, 75, 23))
        self.cmdOK.setObjectName(_fromUtf8("cmdOK"))
        self.cmdCancel = QtGui.QPushButton(self.centralWidget)
        self.cmdCancel.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        frmHydraulicsOptions.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(frmHydraulicsOptions)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        frmHydraulicsOptions.setStatusBar(self.statusBar)

        self.retranslateUi(frmHydraulicsOptions)
        QtCore.QMetaObject.connectSlotsByName(frmHydraulicsOptions)

    def retranslateUi(self, frmHydraulicsOptions):
        frmHydraulicsOptions.setWindowTitle(_translate("frmHydraulicsOptions", "EPANET Hydraulics Options", None))
        self.lblFlowUnits.setText(_translate("frmHydraulicsOptions", "Flow Units", None))
        self.lblHeadlossFormula.setText(_translate("frmHydraulicsOptions", "<html><head/><body><p>Headloss Formula</p></body></html>", None))
        self.lblSpecificGravity.setText(_translate("frmHydraulicsOptions", "Specific Gravity", None))
        self.cmdOK.setText(_translate("frmHydraulicsOptions", "OK", None))
        self.cmdCancel.setText(_translate("frmHydraulicsOptions", "Cancel", None))
        self.lblRelativeViscosity.setText(_translate("frmHydraulicsOptions", "Relative Viscosity", None))
        self.lblMaximumTrials.setText(_translate("frmHydraulicsOptions", "Maximum Trials", None))
        self.lblAccuracy.setText(_translate("frmHydraulicsOptions", "Accuracy", None))
        self.lblUnbalanced.setText(_translate("frmHydraulicsOptions", "Unbalanced", None))
        self.lblDefaultPattern.setText(_translate("frmHydraulicsOptions", "Default Pattern", None))
        self.lblDemandMultiplier.setText(_translate("frmHydraulicsOptions", "Demand Multiplier", None))
        self.lbl1EmitterExponent.setText(_translate("frmHydraulicsOptions", "Emitter Exponent", None))
        self.lblStatusReport.setText(_translate("frmHydraulicsOptions", "Status Report", None))
        self.lblCheckFrequency.setText(_translate("frmHydraulicsOptions", "Check Frequency", None))
        self.lblMaxCheck.setText(_translate("frmHydraulicsOptions", "Max Check", None))
        self.lblDampLimit.setText(_translate("frmHydraulicsOptions", "Damp Limit", None))

