# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_swmm_output')).lstrip('.')
        return importlib.import_module(mname)
    _swmm_output = swig_import_helper()
    del swig_import_helper
elif version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_swmm_output', [dirname(__file__)])
        except ImportError:
            import _swmm_output
            return _swmm_output
        if fp is not None:
            try:
                _mod = imp.load_module('_swmm_output', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _swmm_output = swig_import_helper()
    del swig_import_helper
else:
    import _swmm_output
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


SMO_flow_rate = _swmm_output.SMO_flow_rate
SMO_concentration = _swmm_output.SMO_concentration
SMO_subcatch = _swmm_output.SMO_subcatch
SMO_node = _swmm_output.SMO_node
SMO_link = _swmm_output.SMO_link
SMO_sys = _swmm_output.SMO_sys
SMO_reportStep = _swmm_output.SMO_reportStep
SMO_numPeriods = _swmm_output.SMO_numPeriods
SMO_rainfall_subcatch = _swmm_output.SMO_rainfall_subcatch
SMO_snow_depth_subcatch = _swmm_output.SMO_snow_depth_subcatch
SMO_evap_loss = _swmm_output.SMO_evap_loss
SMO_infil_loss = _swmm_output.SMO_infil_loss
SMO_runoff_rate = _swmm_output.SMO_runoff_rate
SMO_gwoutflow_rate = _swmm_output.SMO_gwoutflow_rate
SMO_gwtable_elev = _swmm_output.SMO_gwtable_elev
SMO_soil_moisture = _swmm_output.SMO_soil_moisture
SMO_pollutant_conc_subcatch = _swmm_output.SMO_pollutant_conc_subcatch
SMO_invert_depth = _swmm_output.SMO_invert_depth
SMO_hydraulic_head = _swmm_output.SMO_hydraulic_head
SMO_stored_ponded_volume = _swmm_output.SMO_stored_ponded_volume
SMO_lateral_inflow = _swmm_output.SMO_lateral_inflow
SMO_total_inflow = _swmm_output.SMO_total_inflow
SMO_flooding_losses = _swmm_output.SMO_flooding_losses
SMO_pollutant_conc_node = _swmm_output.SMO_pollutant_conc_node
SMO_flow_rate_link = _swmm_output.SMO_flow_rate_link
SMO_flow_depth = _swmm_output.SMO_flow_depth
SMO_flow_velocity = _swmm_output.SMO_flow_velocity
SMO_flow_volume = _swmm_output.SMO_flow_volume
SMO_capacity = _swmm_output.SMO_capacity
SMO_pollutant_conc_link = _swmm_output.SMO_pollutant_conc_link
SMO_air_temp = _swmm_output.SMO_air_temp
SMO_rainfall_system = _swmm_output.SMO_rainfall_system
SMO_snow_depth_system = _swmm_output.SMO_snow_depth_system
SMO_evap_infil_loss = _swmm_output.SMO_evap_infil_loss
SMO_runoff_flow = _swmm_output.SMO_runoff_flow
SMO_dry_weather_inflow = _swmm_output.SMO_dry_weather_inflow
SMO_groundwater_inflow = _swmm_output.SMO_groundwater_inflow
SMO_RDII_inflow = _swmm_output.SMO_RDII_inflow
SMO_direct_inflow = _swmm_output.SMO_direct_inflow
SMO_total_lateral_inflow = _swmm_output.SMO_total_lateral_inflow
SMO_flood_losses = _swmm_output.SMO_flood_losses
SMO_outfall_flows = _swmm_output.SMO_outfall_flows
SMO_volume_stored = _swmm_output.SMO_volume_stored
SMO_evap_rate = _swmm_output.SMO_evap_rate

def smo_open(p_handle, path):
    return _swmm_output.smo_open(p_handle, path)
smo_open = _swmm_output.smo_open

def smo_get_version(p_handle):
    return _swmm_output.smo_get_version(p_handle)
smo_get_version = _swmm_output.smo_get_version

def smo_get_project_size(p_handle):
    return _swmm_output.smo_get_project_size(p_handle)
smo_get_project_size = _swmm_output.smo_get_project_size

def smo_get_flow_units(p_handle):
    return _swmm_output.smo_get_flow_units(p_handle)
smo_get_flow_units = _swmm_output.smo_get_flow_units

def smo_get_pollutant_units(p_handle):
    return _swmm_output.smo_get_pollutant_units(p_handle)
smo_get_pollutant_units = _swmm_output.smo_get_pollutant_units

def smo_get_start_date(p_handle):
    return _swmm_output.smo_get_start_date(p_handle)
smo_get_start_date = _swmm_output.smo_get_start_date

def smo_get_times(p_handle, code):
    return _swmm_output.smo_get_times(p_handle, code)
smo_get_times = _swmm_output.smo_get_times

def smo_get_element_name(p_handle, type, elementIndex):
    return _swmm_output.smo_get_element_name(p_handle, type, elementIndex)
smo_get_element_name = _swmm_output.smo_get_element_name

def smo_get_subcatch_series(p_handle, subcatchIndex, attr, startPeriod, endPeriod):
    return _swmm_output.smo_get_subcatch_series(p_handle, subcatchIndex, attr, startPeriod, endPeriod)
smo_get_subcatch_series = _swmm_output.smo_get_subcatch_series

def smo_get_node_series(p_handle, nodeIndex, attr, startPeriod, endPeriod):
    return _swmm_output.smo_get_node_series(p_handle, nodeIndex, attr, startPeriod, endPeriod)
smo_get_node_series = _swmm_output.smo_get_node_series

def smo_get_link_series(p_handle, linkIndex, attr, startPeriod, endPeriod):
    return _swmm_output.smo_get_link_series(p_handle, linkIndex, attr, startPeriod, endPeriod)
smo_get_link_series = _swmm_output.smo_get_link_series

def smo_get_system_series(p_handle, attr, startPeriod, endPeriod):
    return _swmm_output.smo_get_system_series(p_handle, attr, startPeriod, endPeriod)
smo_get_system_series = _swmm_output.smo_get_system_series

def smo_get_subcatch_attribute(p_handle, timeIndex, attr):
    return _swmm_output.smo_get_subcatch_attribute(p_handle, timeIndex, attr)
smo_get_subcatch_attribute = _swmm_output.smo_get_subcatch_attribute

def smo_get_node_attribute(p_handle, timeIndex, attr):
    return _swmm_output.smo_get_node_attribute(p_handle, timeIndex, attr)
smo_get_node_attribute = _swmm_output.smo_get_node_attribute

def smo_get_link_attribute(p_handle, timeIndex, attr):
    return _swmm_output.smo_get_link_attribute(p_handle, timeIndex, attr)
smo_get_link_attribute = _swmm_output.smo_get_link_attribute

def smo_get_system_attribute(p_handle, timeIndex, attr):
    return _swmm_output.smo_get_system_attribute(p_handle, timeIndex, attr)
smo_get_system_attribute = _swmm_output.smo_get_system_attribute

def smo_get_subcatch_result(p_handle, timeIndex, subcatchIndex):
    return _swmm_output.smo_get_subcatch_result(p_handle, timeIndex, subcatchIndex)
smo_get_subcatch_result = _swmm_output.smo_get_subcatch_result

def smo_get_node_result(p_handle, timeIndex, nodeIndex):
    return _swmm_output.smo_get_node_result(p_handle, timeIndex, nodeIndex)
smo_get_node_result = _swmm_output.smo_get_node_result

def smo_get_link_result(p_handle, timeIndex, linkIndex):
    return _swmm_output.smo_get_link_result(p_handle, timeIndex, linkIndex)
smo_get_link_result = _swmm_output.smo_get_link_result

def smo_get_system_result(p_handle, timeIndex, dummyIndex):
    return _swmm_output.smo_get_system_result(p_handle, timeIndex, dummyIndex)
smo_get_system_result = _swmm_output.smo_get_system_result

def smo_init():
    return _swmm_output.smo_init()
smo_init = _swmm_output.smo_init

def smo_close():
    return _swmm_output.smo_close()
smo_close = _swmm_output.smo_close

def smo_free(array):
    return _swmm_output.smo_free(array)
smo_free = _swmm_output.smo_free

def smo_clear_error(p_handle):
    return _swmm_output.smo_clear_error(p_handle)
smo_clear_error = _swmm_output.smo_clear_error

def smo_check_error(p_handle, msg_buffer):
    return _swmm_output.smo_check_error(p_handle, msg_buffer)
smo_check_error = _swmm_output.smo_check_error

import enum

class Unit(enum.Enum):
    FLOW_UNIT = SMO_flow_rate
    CONC_UNIT = SMO_concentration

class ElementType(enum.Enum):
    SUBCATCH = SMO_subcatch
    NODE = SMO_node
    LINK = SMO_link
    SYSTEM = SMO_sys

class Time(enum.Enum):
    REPORT_STEP = SMO_reportStep
    NUM_PERIODS = SMO_numPeriods

class SubcatchAttribute(enum.Enum):
    RAINFALL = SMO_rainfall_subcatch
    SNOW_DEPTH = SMO_snow_depth_subcatch
    EVAP_LOSS = SMO_evap_loss
    INFIL_LOSS = SMO_infil_loss
    RUNOFF_RATE = SMO_runoff_rate
    GWOUTFLOW_RATE = SMO_gwoutflow_rate
    GETABLE_ELEV = SMO_gwtable_elev
    SOIL_MOISTURE = SMO_soil_moisture
    POLLUT_CONC = SMO_pollutant_conc_subcatch

class NodeAttribute(enum.Enum):
    INVERT_DEPTH = SMO_invert_depth
    HYDRAULIC_HEAD = SMO_hydraulic_head
    PONDED_VOLUME = SMO_stored_ponded_volume
    LATERAL_INFLOW = SMO_lateral_inflow
    TOTAL_INFLOW = SMO_total_inflow
    FLOODING_LOSSES = SMO_flooding_losses
    POLLUT_CONC = SMO_pollutant_conc_node

class LinkAttribute(enum.Enum):
    FLOW_RATE = SMO_flow_rate_link
    FLOW_DEPTH = SMO_flow_depth
    FLOW_VELOCITY = SMO_flow_velocity
    FLOW_VOLUME = SMO_flow_volume
    CAPACITY = SMO_capacity
    POLLUT_CONC = SMO_pollutant_conc_link

class SystemAttribute(enum.Enum):
    AIR_TEMP = SMO_air_temp
    RAINFALL = SMO_rainfall_system
    SNOW_DEPTH = SMO_snow_depth_system
    EVAP_INFIL_LOSS = SMO_evap_infil_loss
    RUNOFF_FLOW = SMO_runoff_flow
    DRY_WEATHER_INFLOW = SMO_dry_weather_inflow
    GW_INFLOW = SMO_groundwater_inflow
    RDII_INFLOW = SMO_RDII_inflow
    DIRECT_INFLOW = SMO_direct_inflow
    TOTAL_LATERAL_INFLOW = SMO_total_lateral_inflow
    FLOOD_LOSSES = SMO_flood_losses
    OUTFALL_FLOWS = SMO_outfall_flows
    VOLUME_STORED = SMO_volume_stored
    EVAP_RATE = SMO_evap_rate




